### ISSUE TITLE
работа со справочниками

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#100]
Добрый день!

Как получить список полей вакансии аналогично списку полей анкеты кандидата?
Как получить список всех справочников?
Как в справочнике изменить значение поля foreign «Внешний уникальный идентификатор значения справочника» и на что это повлияет?

**Comment by glibin** [comment]
Добрый день!

> Как получить список полей вакансии аналогично списку полей анкеты кандидата?

К сожалению, такого метода в API сейчас нет. Мы поставим задачу на доработку. Если вам нужна схема, мы можем ее прислать вам по запросу на hello@huntflow.ru с указанием информации о вашей организации в Хантфлоу и ссылкой на этот тикет.

> Как получить список всех справочников?

Такого метода также нет в API. Его добавление пока не планируется.

> Как в справочнике изменить значение поля foreign «Внешний уникальный идентификатор значения справочника» и на что это повлияет?

Изменить этот параметр невозможно.
