### ISSUE TITLE
Параметры постраничного вывода

### ISSUE THREAD

**Issue by MadPigeon** [huntflow/api#101]
Доброго времени суток,

Возникла проблема с постраничным выводом - порой элементов очень много и хочется делать меньше запросов. Однако, при попытке указать в параметре постраничного вывода `count` значение больше 30, в ответе получаю код ошибки 400, `Internal Server Error`.

**Comment by glibin** [comment]
Добрый день!

К сожалению, пока увеличение максимального количества данных в ответе не планируется.

Для получения обновлений в режиме реального времени рекомендуем воспользоваться вебхуками: https://github.com/huntflow/api/blob/master/ru/webhooks.md

**Comment by MadPigeon** [comment]
Спасибо за оперативный ответ.
Жаль, что в планах этого нет.
