### ISSUE TITLE
Получение всех заявок

### ISSUE THREAD

**Issue by MadPigeon** [huntflow/api#102]
Доброго времени суток,

В ответ на попытку получить список заявок на вакансии по адресу `vacancy_request` приходит далеко **не полный список вакансий**.
Текущая теория - приходят только те заявки, по которым ещё нет вакансий. Текущее решение - получать заявки по одной через id, получаемые из списка вакансий.
Буду рад убрать это костыльное решение из алгоритма получения данных по вашему API.
Если получение заявок без вакансий - важная функция, то было бы здорово задавать параметр при запросе, позволяющий отделить запрос заявок с привязкой от запроса заявок без привязки.

**Comment by glibin** [comment]
Добрый день!

Из вашего вопроса непонятно на какой адрес вы обращаетесь для получения списка заявок. Не могли бы вы его уточнить?

**Comment by MadPigeon** [comment]
`https://api.huntflow.ru/vacancy_request`

**Comment by glibin** [comment]
Да, верно, сейчас на этот запрос отдаются заявки без вакансий. 

Добавить возможность получения всех заявок мы планируем сделать в начале следующего года.
