### ISSUE TITLE
Заказчик и ответственный за вакансию

### ISSUE THREAD

**Issue by MadPigeon** [huntflow/api#103]
Доброго времени суток,

В web-версии huntflow есть возможность узнать две вещи касательно **вакансий**, а именно: кто заказчик и кто работает над вакансией (ответственен за неё).
В API об эти сущности не упоминаются, но для аналитиков это было бы очень ценно знать. В идеале, с историей изменений.

**Comment by glibin** [comment]
Добрый день!

Есть методы:

`/account/<account_id>/members`

который вернет всех работающих в организации рекрутеров, также возможен фильтр для вакансии (кто работает на вакансии):

`/account/<account_id>/members?vacancy=<vacancy_id>`

а также добавить в ответ заказчиков:

`/account/<account_id>/members?show_watchers=true`

Метода пока нет в документации, исправим эту оплошность в обозримом будущем.

**Comment by MadPigeon** [comment]
В какие сроки планируется ввести описание документации на эту тему?
И может ли один и тот же member с одним и тем же id участвовать в одних и тех же вакансиях в разных ролях?

**Comment by glibin** [comment]
> В какие сроки планируется ввести описание документации на эту тему?

до конца декабря

> И может ли один и тот же member с одним и тем же id участвовать в одних и тех же вакансиях в разных ролях?

Нет. Один пользователь может быть только в одной роли в организации
