### ISSUE TITLE
Проблема с загрузкой файла

### ISSUE THREAD

**Issue by bodagovsky** [huntflow/api#104]
Пытаюсь загрузить файл через API
получаю ответ 500
не могу понять, что я делаю не так
помогите разобраться, пожалуйста

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, более подробную информацию (заголовки запроса, заголовки ответа) о проблеме.

**Comment by bodagovsky** [comment]
заголовки ответа следующие:

{'Date': 'Wed, 11 Dec 2019 15:44:11 GMT',
'Content-Type': 'application/json; charset=UTF-8',
'Content-Length': '38',
'Connection': 'keep-alive',
'Server': 'TornadoServer/6.0.3',
'Access-Control-Allow-Origin': '*',
'Access-Control-Allow-Headers': 'x-requested-with, content-type',
'Access-Control-Allow-Methods': 'POST, GET, OPTIONS'}

заголовки запроса:

"Authorization": "Bearer {token}",
"Content-Type": "multipart/form-data",
"Host": "api.huntflow.ru",
"User-Agent": "App/1.0"

**Comment by bodagovsky** [comment]
Если нужна еще какая-нибудь информация, напишите, пожалуйста

**Comment by glibin** [comment]
Пришлите, пожалуйста, проблемный  файл на hello@huntflow.ru

**Comment by bodagovsky** [comment]
Отправил

**Comment by glibin** [comment]
Добрый день!

Файл успешно загружается, пример запроса на curl:

```
curl -i -X POST -H "User-Agent: App/1.0 (incaseoffire@example.com)" -H "Content-Type: multipart/form-data" -H "X-File-Parse: true" -H "Authorization: Bearer <token>" -F "file=@1572286174_gGt3CZPdEw.pdf" https://api.huntflow.ru/account/<account_id>/upload
```

**Comment by bodagovsky** [comment]
то есть, в поле file нужно передать ссылку?

**Comment by glibin** [comment]
Это пример запроса на curl, в который можно передать файл по ссылке (он преобразуется в multipart/form-data). 

Непосредственно API не принимает файлы по ссылке.

**Comment by bodagovsky** [comment]
правильно понимаю, в API нужно передавать файл в байтах?

**Comment by bodagovsky** [comment]
А есть возможность сгенерировать этот запрос на Python?  с помощью requests, например?
просто curl у нас тоже работает, и даже через insomnia. Но из кода запрос не проходит

**Comment by bodagovsky** [comment]
или этот метод работает исключительно по curl?

**Comment by nikepan** [comment]
Вот примерно такая функция выходит:
```
    def upload_file(name, content):
        mimetypes.init()
        ext_data = os.path.splitext(name)
        if len(ext_data) > 1:
            mime_type = mimetypes.types_map.get(ext_data[len(ext_data) - 1]) or 'application/zip'
        else:
            mime_type = 'application/zip'

        headers = {
            'Authorization': 'Bearer {}'.format(settings.HUNTFLOW_TOKEN),
            'User-Agent': 'App/1.0 (n.pavlovich@corp.mail.ru)',
        }
        r = requests.request(
            'POST',
            '{}/account/{}/upload'.format(settings.HUNTFLOW_URL, settings.HUNTFLOW_ACCOUNT),
            files={'file': (name, content, mime_type)},
            headers=headers,
        )
        return r.json()
```

**Comment by bodagovsky** [comment]
позвольте уточнить, какого типа должна быть переменная content?
потому что наш запрос выглядит примерно так же)

**Comment by bodagovsky** [comment]
все, спасибо, сработало)

**Comment by glibin** [comment]
@nikepan спасибо :)
