### ISSUE TITLE
Создание заявки на вакансию со списком выбора нескольких значений

### ISSUE THREAD

**Issue by Altlmn** [huntflow/api#106]
Здравствуйте.

Подскажите пожалуйста, как при создании заявки на вакансию через API отправить данные в поля, в которых нужно указывать несколько значений?

Из созданной заявки на вакансию через портал мы можем видеть, что в эти поля встали следующие значение:

```
"english": [
    2893,
    2894,
    2895,
    2896,
    2897,
    2898
],
"employment": [
    2890,
    2891,
    2892
],
```
В схеме они имеют такой вид:
```
"english": {
    "title": "Уровень английского языка",
    "id": 50027,
    "order": 18,
    "account": 33768,
    "value": null,
    "dictionary": "english",
    "key": null,
    "type": "dictionary",
    "multiple": true,
    "required": false,
    "delimiter": true
},
"employment": {
    "title": "Характер работы",
    "id": 50023,
    "order": 14,
    "account": 33768,
    "value": null,
    "dictionary": "employment",
    "key": "employment",
    "type": "dictionary",
    "multiple": true,
    "required": false
},
```

Но при отправке в любом виде мы создаём заявку со значениями null в этих полях.
Нигде в документации про это найти не удалось.
Как правильно указывать для таких полей значения при отправке?
Спасибо.

**Comment by Altlmn** [comment]
Прошу прощения.
Нашёл здесь же в другой заявке подобную информацию.
https://github.com/huntflow/api/issues/76
Помогло.

**Comment by Altlmn** [comment]
Понял, что можно получать справочники следующим образом
https://api.huntflow.ru/account/33768/dictionary/english
А подскажите пожалуйста, как правильно указать отправку данных из этого справочника? (Например в JSON)

Пример данного справочника:
```
{
    "name": "Уровень английского языка",
    "id": 15268,
    "foreign": null,
    "created": "2019-12-12T15:09:52+03:00",
    "code": "english",
    "fields": [
        {
            "deep": 0,
            "meta": null,
            "name": "A1",
            "id": 2893,
            "foreign": "A1",
            "active": true,
            "order": 0,
            "parent": null
        },
        {
            "deep": 0,
            "meta": null,
            "name": "A2",
            "id": 2894,
            "foreign": "A2",
            "active": true,
            "order": 1,
            "parent": null
        },
        {
            "deep": 0,
            "meta": null,
            "name": "B1",
            "id": 2895,
            "foreign": "B1",
            "active": true,
            "order": 2,
            "parent": null
        },
        {
            "deep": 0,
            "meta": null,
            "name": "B2",
            "id": 2896,
            "foreign": "B2",
            "active": true,
            "order": 3,
            "parent": null
        },
        {
            "deep": 0,
            "meta": null,
            "name": "C1",
            "id": 2897,
            "foreign": "C1",
            "active": true,
            "order": 4,
            "parent": null
        },
        {
            "deep": 0,
            "meta": null,
            "name": "C2",
            "id": 2898,
            "foreign": "C2",
            "active": true,
            "order": 5,
            "parent": null
        }
    ]
}
```

**Comment by glibin** [comment]
Добрый день!

Их можно передать списком идентификаторов:

```
{
"english": [2896, 2897],
...
}
```

Напишите, получилось ли?

**Comment by Altlmn** [comment]
Добрый день!
Мы пробовали отправлять таким образом, но всегда в эти поля устанавливается null.
Что может быть не так?

**Comment by glibin** [comment]
Мы выявили проблему, что на вход ожидается передача параметра в виде:

```
{
"english": "[2896, 2897]",
...
}
```

мы сейчас занимаемся исправлением проблемы, но как временное решение (на момент отладки/разработки) можно использовать это.

**Comment by Altlmn** [comment]
Проверил. Работает.
Но таким образом получается отправить лишь "english".
А вот "employment" не проходит, так же null.

Подскажите пожалуйста, а когда будет реализована отправка правильным способом?
И как сейчас отправить "employment"?

**Comment by glibin** [comment]
> Подскажите пожалуйста, а когда будет реализована отправка правильным способом?
до конца этой недели

**Comment by glibin** [comment]
Добрый день!

Исправление выпущено.
