### ISSUE TITLE
Получение анкеты кандидата

### ISSUE THREAD

**Issue by HappyVlad** [huntflow/api#107]
Добрый день!

Подскажите, пожалуйста, как через API получить Анкету кандидата, которая в интерфейсе заполняется через контрол "Заполнить анкету". И, соответственно, как получить список полей этой анкеты (вопросы и идентификаторы).

**Comment by glibin** [comment]
Добрый день!

Информация доступна здесь: https://github.com/huntflow/api/blob/master/ru/questionaries.md

**Comment by HappyVlad** [comment]
Спасибо!
