### ISSUE TITLE
Удаление заметок на странице кандидата.

### ISSUE THREAD

**Issue by CAMCOH1989** [huntflow/api#108]
У нас возникла проблема, на страницы кандидата проникли левые коменты через POST /account/{account_id}/applicants/{applicant_id}/log. И я хотел узнать, есть ли возможность их удалить через API. Я не нашёл, а метод DELETE не разрешён по этому url.

**Comment by glibin** [comment]
Добрый день!

К сожалению, такого метода сейчас нет в API. Можно только удалять вручную из интерфейса.

**Comment by CAMCOH1989** [comment]
Спасибо.
