### ISSUE TITLE
Дата закрытия вакансии

### ISSUE THREAD

**Issue by MadPigeon** [huntflow/api#109]
Доброго времени суток,

Пожалуйста, добавьте дату закрытия вакансии.

**Comment by glibin** [comment]
Добрый день!

Мы сейчас готовим документацию для метода https://api.huntflow.ru/account/<account_id>/vacancy/<vacancy_id>/logs

Можете начинать его использовать для получения истории работы по вакансии. 

```
"state": "CLOSED", <-- state, который говорит о факте закрытия вакансии
"created": "2020-01-11T23:59:59+03:00", <-- дата закрытия вакансии
```

Так как вакансия может переоткрываться несколько раз, то обратите внимание, что таких записей в ответе может быть несколько. Метод получения периодов открытия вакансии мы готовим к выпуску.
