### ISSUE TITLE
Как получить данные по кандидату?

### ISSUE THREAD

**Issue by infernov** [huntflow/api#11]
Почему в вебхуке по кандидату, так мало полей кандидата (интересуют контакты)?
Как получить все поля кандидата?

**Comment by glibin** [comment]
Спасибо за обращение, в данный момент возвращается базовая информация. 

Полную информацию о кандидате вы можете получить вызовом метода `/account/{account_id}/applicants/{applicant_id}`

**Comment by glibin** [comment]
Уточните, какие методы API вы вызываете?

**Comment by infernov** [comment]
Виталий, я так понял через апи нельзя изменять кандидата существующего, можно только нового создавать?

Я уже понял, выход из моей ситуации метод: POST /account/{account_id}/applicants/{applicant_id}/vacancy

**Comment by glibin** [comment]
В данный момент да, но в ближайшем времени функционал появится в API.

Также, судя по полям запроса выше, вы пытаетесь сохранить данные по анкете кандидата? Обработка этого функционала появится, ориентировочно, в начале следующей недели.

**Comment by infernov** [comment]
Посмотите, пожалуйста, почему выдается ошибка 400 Bad Request
POST /account/7115/applicants/2294073/vacancy 
{"vacancy": 2383389, "status": 40421, "comment": "", "files": [{"id": 2956117}], "rejection_reason": null}

**Comment by infernov** [comment]
Какое ограничение на заливаемые файлы?

**Comment by glibin** [comment]
> Какое ограничение на заливаемые файлы?

15 Мб

> Посмотите, пожалуйста, почему выдается ошибка 400 Bad Request
POST /account/7115/applicants/2294073/vacancy
{"vacancy": 2383389, "status": 40421, "comment": "", "files": [{"id": 2956117}], "rejection_reason": null}

проверим, сообщу как будут результаты

**Comment by infernov** [comment]
Посмотрели? Куда присылать возникшие ошибки (их много)?
