### ISSUE TITLE
Ошибка при создании/редактировании справочников

### ISSUE THREAD

**Issue by rogozhinsv** [huntflow/api#110]
Добрый день!
Возникает ошибка при создании/редактировании справочников:
**{
    "errors": [
        {
            "type": "server_error",
            "value": "internal_error"
        }
    ],
    "description": "Internal Server Error"
}**

1. Для создания справочника отправляю POST-запрос (https://api.huntflow.ru/account/*****/dictionary) с содержимым:
{
    "code": "12345678",
    "foreign": "test-dict-123"
    "name": "test dict",
    "items": [
    	{"name": "Информационные технологии", "foreign": "5" }
    ]
}
В headers указываю content-type: application/json

2. Для редактирования справочника отправляю PUT-запрос (https://api.huntflow.ru/account/*****/dictionary/professional) с содержимым:
{
    "name": "Профобласти",
    "code": "professional",
    "foreign": null,
    "id": 14811,
    "items": [
    	{"name": "Информационные технологии", "foreign": "5" }
    ]
}
В headers указываю content-type: application/json

Подскажите, пожалуйста, в чем проблема?

**Comment by mullakhmetov** [comment]
Причина аналогична с #116
