### ISSUE TITLE
division и dictionary

### ISSUE THREAD

**Issue by charararara** [huntflow/api#111]
С dictionary разобрался. Остался только тип division. В значение передаётся ID подразделения, но где брать этот ID? 

_Добрый день!
Не подскажете, какие значения мне необходимо передавать в типы division и dictionary?
Попытался запустить тестовую, но ошибка в ответе не совсем информативная. {"errors": [{"type": "server_error"}]}
Словари выгружал, но какие именно ключи использовать из их значений?
/account/{account_id}/vacancy_request
https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E
![test](https://user-images.githubusercontent.com/51745816/71408893-ec885280-2669-11ea-9919-99f732aab7d6.png)_

**Comment by glibin** [comment]
Добрый день!

Для получения подразделений нужно использовать следующий endpoint: `/account/<account_id>/divisions`
