### ISSUE TITLE
Не работает метод обновления резюме

### ISSUE THREAD

**Issue by ElchinMustafaev** [huntflow/api#112]
Пытаемся перевести резюме на другой этап, апи отдает нам такой ответ "{"status": 75191, "updated": "2019-12-24T14:05:42+03:00", "changed": "2019-12-24T14:05:42+03:00", "vacancy": 2439769, "rejection_reason": null, "id": 3937246}", но ничего не происходит, несколько дней назад это работало, подскажите что-то обновилось или это баг?

**Comment by glibin** [comment]
Добрый день!

Сохраняется ли проблема?

Если да, пришлите, пожалуйста, чуть больше вводных: URL запроса, тело запроса, тело и код ответа.
