### ISSUE TITLE
Связь с вакансией на HeadHunter 

### ISSUE THREAD

**Issue by Dumkaaa** [huntflow/api#113]
Через интерфейс хантфлоу создана вакансия, через этот же интерфейс она опубликована на хедхантере, там же настроен сбор откликов с хедхантера.

Как через API хантфлоу, при запросе информации о этой вакансии, получить идентификатор опубликованной вакансии на хедхантере?

**Comment by glibin** [comment]
Доброе утро!

Такой возможности в API пока нет.
