### ISSUE TITLE
 У вакансии не передаётся поле  teams

### ISSUE THREAD

**Issue by garyanikin** [huntflow/api#114]
Добрый день. Подскажите, почему у вакансии с этим id: 2412589 в api (/vacancies/2412589) не приходит поле "teams"? На сайте huntflow у этой вакансии выбрана команда
![2020-01-09_09 48 52](https://user-images.githubusercontent.com/8394041/72142742-67f63d80-33a6-11ea-8166-e0bad115a9dc.png)

Компания sweatcoin

**Comment by glibin** [comment]
Добрый день!

Дополнительные поля вакансии были внедрены позже создания данной вакансии, поэтому у нее выставлено значение в базе для этого поля. В интерфейсе отображается первый элемент из списка по умолчанию. Если вы нажмете "Сохранить", то параметр должен появиться в API.

**Comment by garyanikin** [comment]
Мы обновили вакансию, нажали Save. Но в ответе апи поле "teams" не появилось

**Comment by glibin** [comment]
Передадим в отдел тестирования проверить данную ситуацию.
