### ISSUE TITLE
не работает метод создания справочника

### ISSUE THREAD

**Issue by rogozhinsv** [huntflow/api#116]
Добрый день, пытаюсь создать справочник (использую пример из вашего описания), выдает ошибку:
![image](https://user-images.githubusercontent.com/40475135/72597629-2f62e080-391f-11ea-9445-ea3ade811f5a.png)

что не так?

**Comment by mullakhmetov** [comment]
Здравствуйте! Судя по логам, вы отправляете запрос на создание справочника с аккаунта, который не является управляющим в организации. Управление справочниками недоступно для рядовых рекрутеров.

Этот момент, к сожалению, не описан в документации, но скоро будет.
