### ISSUE TITLE
Получение списка подразделений и активов

### ISSUE THREAD

**Issue by nastya-klim** [huntflow/api#117]
Здравствуйте!

Сейчас мы используем запрос GET /account/23158/all_divisions для получения списка всех подразделений, но в выгружаемых данных нет информации о активе (отделе), к которому принадлежит подразделение.

Подскажите, пожалуйста, как можно получить информацию о активах (отделах)?

**Comment by glibin** [comment]
Добрый день!

Приведите, пожалуйста, пример? Из вашего рассказа не очень понятна проблема.

**Comment by nastya-klim** [comment]
При ручной выгрузке мы получаем подразделения в таком виде (Отдел, подразделение):
![image](https://user-images.githubusercontent.com/34706810/72733480-9d6a0a80-3ba0-11ea-84eb-1aa4872608e0.png)

Используя GET-запрос  .../account/23158/all_divisions получаем вот такой результат:
![image](https://user-images.githubusercontent.com/34706810/72733596-cee2d600-3ba0-11ea-927d-13f4d7dc5f8e.png)
Выгружается список всех подразделений, но без отделов.

Вопрос: можно ли получить список подразделений вместе с отделами к которым они принадлежат? Если да, то как?

**Comment by glibin** [comment]
Для построения дерева необходимо использовать ключ `parent`, который указывает на родительский узел. Элемент с `parent: null` указывает на корневое подразделение.

**Comment by nastya-klim** [comment]
Спасибо за ответ. Советую добавить описание этого метода в документацию :)
