### ISSUE TITLE
Добавление кандидата в базу

### ISSUE THREAD

**Issue by may-cat** [huntflow/api#118]
Загрузил pdf через метод upload, полученные результаты скормил в метод applicants. Получил 500-ую ошибку без каких-либо пояснений, которые помогли бы отладить проблему.
```
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}
```
Запросы бросал примерно в 2020-01-20 17:47:30. По необходимости могу помочь отладить (телеграм: @i_tsupko)

**Comment by may-cat** [comment]
Разобрался. В этих двух методах совершенно разный формат аттрибутов, что неожиданно и достаточно неудобно.

**Comment by glibin** [comment]
Доброе утро!

Да, формат данных из парсера отличается от формата данных для кандидата. Рад, что смогли разобраться самостоятельно.
