### ISSUE TITLE
Как получить загруженный файл снова?

### ISSUE THREAD

**Issue by maddoxdev** [huntflow/api#120]
Добрый день.
В API есть метод загрузки файлов с возможность парсинга структуры и получения какой-либо информации из файла. Это все работает спасибо. Но скажем я не могу сохранить эту информацию (та что спарсилась) на момент загрузки файла.

Я могу получить ту же самую структуру которая возвращается при загрузке файла, по Id загруженного файла?

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности нет, так как за обработку файлов отвечает отдельный сервис.

Единственный вариант загружать файл заново.
