### ISSUE TITLE
Как получить список справочников компании?

### ISSUE THREAD

**Issue by garry-m** [huntflow/api#121]
Пытаемся вытащить данные из кастомных полей, которые возвращаются в формате id из справочников.
Читали документацию по справочникам, на которую вы ссылаетесь: https://github.com/huntflow/api/blob/master/ru/dictionaries.md

Но эти справочники создавали не мы, поэтому мы не знаем их конкретных id, к которым можем обратиться.
Как можно вытащить весь список имеющихся справочников с их id по нашей компании, чтобы иметь возможность к ним в дальнейшем обращаться?

**Comment by glibin** [comment]
Добрый день!

На данный момент метода получения всех справочников нет. Он есть в плане доработок методов API.

Вы можете прислать название организации и account_id, мы передадим информацию о справочниках здесь или через почту (нужно написать письмо на hello@huntflow.ru со ссылкой на тикет)
