### ISSUE TITLE
Как принять комментарий к вакансии

### ISSUE THREAD

**Issue by chastoedov** [huntflow/api#123]
Здравтвуйте!
Внутри huntflow у нас есть поле "комментарий к вакансии, но в апи он не передается. Как нам его подключить?

![image](https://user-images.githubusercontent.com/56137952/73004823-022f9a00-3e19-11ea-85f2-dc08ee9b92ab.png)
"

**Comment by glibin** [comment]
Добрый день!

Необходимо получать данное поле или иметь возможность передавать его при создании вакансии?

**Comment by chastoedov** [comment]
Пока задача просто получить

**Comment by glibin** [comment]
Получить можно запросом на вакансию https://github.com/huntflow/api/blob/master/ru/vacancies.md#vacancy 

оно будет среди результатов запроса
