### ISSUE TITLE
Интеграция с сайтом

### ISSUE THREAD

**Issue by robeenpower** [huntflow/api#124]
На сайте есть раздел вакансий.

Заказчик хочет публиковать вакансии на сайт, собирать отклики кандидатов с сайта на эти вакансии в лк Huntflow.

Нужно:
* сохранить текущую категоризацию вакансий
* уведомлять пользователей о поступлении отклика на вакансию с сайта
* добавить id вакансии с данного сайта в json

Прошу связаться со мной по этому вопросу.

**Comment by Dumkaaa** [comment]
@glibin 

Как сейчас:
- На сайте есть вакансии, они разбиты по категориям.
- Отклики собираются в БД сайта.

Как хотим сделать:
- Хантфлоу публикует вакансию на сайте
- Хантфлоу собирает отклики

То есть, настройка согласно по этой инструкции:
https://github.com/huntflow/api/blob/master/ru/responses.md

Вопросы:
- Как отнести вакансию с Хантфлоу, после создания её на сайте, к нужной категории
(может ли Хантфлоу передавать какой-то признак категории - ид, код или еще что-то)?
- С какой периодичностью Хантфлоу будет забирать отклики?

**Comment by glibin** [comment]
> Как отнести вакансию с Хантфлоу, после создания её на сайте, к нужной категории
(может ли Хантфлоу передавать какой-то признак категории - ид, код или еще что-то)?

В форме публикации вакансии в Хантфлоу для вашего карьерного сайта можно предусмотреть справочник (категории?), из которого рекрутер будет выбирать значение. Оно будет передаваться при публикации.

> С какой периодичностью Хантфлоу будет забирать отклики?

В момент, когда рекрутер заходит в вакансию в Хантфлоу, мы собираем отклики со всех работных сайтов, где опубликована вакансия.
