### ISSUE TITLE
Запрос от Хантфлоу карьерному сайту

### ISSUE THREAD

**Issue by RA13** [huntflow/api#125]
1.	При публикации вакансии с Хантфлоу на карьерный сайт клиента (по средством вызовом API) для некоторых полей, которые хранят значения «да/нет», отправляются значения текстом:
 
![image](https://user-images.githubusercontent.com/14919148/73059855-ac560300-3ea7-11ea-9829-40e0e9024a08.png)
Можно ли значения таких полей отправлять булевым типом (true/false)?

2.	Если на сервисе Хантфлоу есть поле в виде многоуровневого словаря, то в каком виде будет передаваться значение такого поля на карьерный сайт клиента (через API)?

**Comment by glibin** [comment]
> Можно ли значения таких полей отправлять булевым типом (true/false)?

Если внедрить эти поля как справочники, то можно. Сейчас, вероятно, это просто список значений.

> Если на сервисе Хантфлоу есть поле в виде многоуровневого словаря, то в каком виде будет передаваться значение такого поля на карьерный сайт клиента (через API)?

Будет передаваться конечный элемент (лист дерева).
