### ISSUE TITLE
Нужно удалять кандидатов через API

### ISSUE THREAD

**Issue by DimaDodger** [huntflow/api#126]
Для очистки нашей базы, требуется возможность удалять кандидатов через API. Сейчас есть такая возможность? Если нет, когда можно ожидать реализацию такого метода?

**Comment by glibin** [comment]
Добрый день!

К сожалению, сейчас такой возможности нет и не планируется в ближайшее время.

Вам нужно единоразовое удаление кандидатов или для решения какой-то задачи?

**Comment by DimaDodger** [comment]
Периодически возникает задача очистить нашу базу и удалить кандидатов не связанных ни с одной вакансией. Есть варианты решения данной проблемы?

**Comment by DimaDodger** [comment]
Можно считать разовой задачей

**Comment by glibin** [comment]
@DimaDodger обсудили с коллегами еще раз: поставим в ближайший план добавить метод удаления кандидата. Предварительно, будет в релизе на следующей неделе.

**Comment by glibin** [comment]
Добрый день!

Метод доступен:

```
DELETE https://api.huntflow.ru/account/<account_id>/applicants/<applicant_id>
```
