### ISSUE TITLE
Событие об удалении статуса

### ISSUE THREAD

**Issue by aakolzin** [huntflow/api#127]
Коллеги, добрый день, просьба добавить в события по кандидатам, которые приходят по вебхуку, событие об удалении статуса с кандидата. Иначе при ошибке рекрутера приходит событие о новом статусе, но не приходит об его удалении и процесс обработки событий ломается.

**Comment by glibin** [comment]
Добрый день!

Данная задача есть в ближайших планах, я сообщу о ее выходе в этом тикете.

**Comment by glibin** [comment]
Добрый день!

Данная функциональность стала доступна в вебхуках версии 2.0: https://github.com/huntflow/api/blob/master/ru/webhooks.md#тело-вебхука
