### ISSUE TITLE
Можно ли получить срок и описание предыдущего места работы в API распознавания файла?

### ISSUE THREAD

**Issue by tiqum** [huntflow/api#128]
Мы хотим воспользоваться вашим API для загрузки файла и распознавания резюме кандидата.

Смотрим в документации: https://github.com/huntflow/api/blob/master/ru/upload.md

В секции "Предыдущий опыт" такой ответ:

```
"experience": [
            {
                "position": "Team lead команды мобильного сайта",
                "company": "HeadHunter"
            },
            {
                "position": "Senior frontend developer",
                "company": "HeadHunter"
            }
        ]
```

Не включает срок работы и описание работы.

Вопрос: это актуальный пример ответа API, или такие поля все-таки будут распознаны тоже?

Если это актуальный ответ, как нам после загрузки файла резюме для распознавания потом получить срок и описание предыдущих мест работы?

**Comment by glibin** [comment]
Добрый день!

На текущий момент парсер не распознает периоды работы и описание в опыте работы. 

Мы работаем над улучшением работы парсера, но точных сроков, когда появится данная функциональность подсказать не сможем.
