### ISSUE TITLE
account_id

### ISSUE THREAD

**Issue by vyacheslavt** [huntflow/api#129]
Как узнать account_id пользователя? Возможно я не заметил, но для меня это был квест.
Поискать в админке, поискать в коде админики, ага, что-то похожее, пробуем, пробуем, api возвращает forbidden , наверное нет прав у пользователя, лезем в админку меняем права, все же нет. Не оставляем попытки, запрашиваем api /me , блин и тут нет. Ага вот какой-то id в поле email, давай его попробуем, о! кажется подходит.
Или я плохо искал?

**Comment by glibin** [comment]
Добрый день!

Получить можно здесь: https://github.com/huntflow/api/blob/master/ru/user.md#organizations
