### ISSUE TITLE
отображение резюме, загруженного через API

### ISSUE THREAD

**Issue by plurodel** [huntflow/api#131]
сейчас, если резюме кандидата загружается через API - робот просто прикрепляет на него ссылку в комментарии
нам необходимо, чтобы оно показывалось просто в карточке кандидата.
как это сделать через API?

**Comment by glibin** [comment]
Если вам нужно отображать исходный файл в тексте резюме кандидата, то при добавлении кандидата в блок externals нужно добавить идентификатор файла:

```
"externals": [
        {
            ...
            "files": [
                {
                    "id": 12430
                }
            ],
            ...
        }
    ]
```

https://github.com/huntflow/api/blob/master/ru/applicants.md#добавление-кандидата-в-базу

**Comment by plurodel** [comment]
я имею ввиду предпросмотр резюме, как это получается после добавления через волшебную кнопку

**Comment by glibin** [comment]
Можете продемонстрировать свое пожелание скриншотами?

**Comment by plurodel** [comment]
<img width="996" alt="Screenshot 2020-02-11 at 12 55 48" src="https://user-images.githubusercontent.com/2518834/74226941-7f3e8880-4cce-11ea-9174-b54ee744293a.png">

**Comment by plurodel** [comment]
как на картинке, а не просто ссылка на резюме

**Comment by glibin** [comment]
Спасибо за пояснения. 

К сожалению, сохранять резюме в нормализованном формате из API сейчас нет возможности. Мы планируем добавить такую возможность в будущем, но точных сроков назвать не сможем.

**Comment by plurodel** [comment]
понял, спасибо
