### ISSUE TITLE
Как посмотреть список рекрутеров у вакансии?

### ISSUE THREAD

**Issue by chastoedov** [huntflow/api#133]
Есть задача - по апи брать список рекрутеров (имена), которые работают с вакансией.

Можно смотреть комментарии в истории работы с вакансией, но там не всегда ответственные за вакансию попадаются. Было бы очень удобно в методе получения данные по вакансии указать ответственных в виде массива.

**Comment by glibin** [comment]
Добрый день!

запрос `/account/<account_id>/members`

вернет всех работающих в организации рекрутеров, также возможен фильтр для вакансии (кто работает на вакансии):

`/account/<account_id>/members?vacancy=<vacancy_id>`

а также добавить в ответ заказчиков:

`/account/<account_id>/members?show_watchers=true`

**Comment by chastoedov** [comment]
А как посмотреть закрепленного рекрутера у вакансии?

**Comment by glibin** [comment]
`/account/<account_id>/members?vacancy=<vacancy_id>`

вернет список рекрутеров, работающих по вакансии

**Comment by chastoedov** [comment]
Благодарю!
