### ISSUE TITLE
неправильно указан тип данных у foreign

### ISSUE THREAD

**Issue by AndTolmachev** [huntflow/api#134]
В методе https://github.com/huntflow/api/blob/master/ru/externals.md у foreign указан тип данных number
При этом в примере тип данных - строка
![image001](https://user-images.githubusercontent.com/46557154/74140344-f2c89300-4c05-11ea-92e2-1c2db8be9877.png)
![image002](https://user-images.githubusercontent.com/46557154/74140415-1390e880-4c06-11ea-8205-cf76b3557b4b.png)
Нужно исправить

**Comment by glibin** [comment]
Добрый день!

Исправлено.
