### ISSUE TITLE
Создание вакансии

### ISSUE THREAD

**Issue by vyacheslavt** [huntflow/api#135]
Попробовал несколько разных вариантов CURLOPT_POST, CURLOPT_CUSTOMREQUEST, Content-Length и т.д. но вакансия не создается и разные варианты ответа:

1) Ошибка 301,400
2) Возвращает список вакансий
3) [description] => Internal Server Error

```
        $arParams = array(
            'position' => 'Manufacturing Engineer',
        );
        $jsonDatasEncoded = json_encode($arParams);
        $curl = curl_init("api.huntflow.ru/account/***/vacancies");

        curl_setopt($curl, CURLOPT_POST, true);
        //curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HEADER, false);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $jsonDatasEncoded);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, true);

        curl_setopt($curl, CURLOPT_HTTPHEADER, array(
                'Content-Type: application/json',
                'Authorization: Bearer ' . $this->token,
                //'Content-Length: ' . strlen($jsonDatasEncoded)
        ));


        $json = json_decode(curl_exec($curl));
        echo "<pre>"; print_r($json);  echo "<pre>";
```

**Comment by glibin** [comment]
Добрый день!

Нужно использовать https-схему: `https://api.huntflow.ru/...`

**Comment by vyacheslavt** [comment]
Конечно же я пробовал и https, просто сюда все варианты нет смысла копировать, результат тот же

**Comment by glibin** [comment]
Ошибка 301 возникает, как раз, при использовании http-схемы.

Если ошибка 400, то пришлите тело запроса, а также ваш account_id

**Comment by vyacheslavt** [comment]
В большинстве случаев такая ошибка ниже, остальные ошибки в том числе и 301 возникли уже при переборе вариантов запроса. 301 возникает, если не включена поддержка редиректа и обращение на http.

А эту ошибку я понять не могу, вы можете как-то пояснить?

```
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [type] => server_error
                    [value] => Array
                        (
                            [0] => internal_error
                        )

                )

        )

    [description] => Internal Server Error
)
```

**Comment by glibin** [comment]
Пришлите, пожалуйста, ваш account_id и тело запроса
