### ISSUE TITLE
Выгрузка данных для аналитики

### ISSUE THREAD

**Issue by SemenovDaniil** [huntflow/api#137]
Коллеги, добрый день.
Для аналитики нам необходимо выгрузить данные по вакансиям, рекрутёрам, кандидатам.
К сожалению, API в текущем виде подразумевает огромное количество запросов для выгрузки.
На данный момент, чтобы выгрузить логи кандидатов нам необходимо сделать порядка 176 тысяч запросов.
Подскажите, пожалуйста, как можно выгрузить все данные по логам кандидатов с минимальными временными затратами ?
Есть ли возможность получить доступ напрямую в базу только на чтение, чтобы выгрузка была адекватной по времени?

Account_id 6

**Comment by glibin** [comment]
Добрый день!

> Подскажите, пожалуйста, как можно выгрузить все данные по логам кандидатов с минимальными временными затратами ?

Вы можете запросить единоразово выгрузку всех данных в формате JSON через службу поддержки

> Есть ли возможность получить доступ напрямую в базу только на чтение, чтобы выгрузка была адекватной по времени?

Такой возможности, к сожалению, нет

**Comment by SemenovDaniil** [comment]
> Вы можете запросить единоразово выгрузку всех данных в формате JSON через службу поддержки

К сожалению, единоразовой выгрузкой проблему не решить. Данные нужны каждый день и, возможно, не один раз.

> Такой возможности, к сожалению, нет

А в планах есть реализация интерфейсов для целей аналитики?
Потому что api в текущем виде для этих задач не подходит.

**Comment by glibin** [comment]
Обычно, делается единовременная выгрузка, а дальше обновления доливаются через вебхуки: https://github.com/huntflow/api/blob/master/ru/webhooks.md

**Comment by SemenovDaniil** [comment]
Вебхуки нам не подходят.
Они подразумевают необходимость поднимать и поддерживать целый ряд дополнительных сервисов.

**Comment by glibin** [comment]
К сожалению, на данный момент каких-то других вариантов предложить не могу.
