### ISSUE TITLE
Запрос по вакансии не возвращает заполненное поле

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#138]
Добрый день!

Запрос по вакансии не возвращает заполненного поля Подразделение с продакшена, при этоим на зеркале это было в поле "name": "Отдел". 
Запрос на зеркало:
/account/2/vacancies/115
ответ:
{
   "requirements": null,
   "parent": null,
   "skills": null,
   "vacancy_request_data": [   {
      "displayData":       [
                  {
            "type": "key-value",
            "name": "Код штатной должности",
            "value": "50121411"
         },
                  {
            "type": "key-value",
            "name": "Отдел",
            "value": "ДИРЕКЦИЯ ПО КОКСОАГЛОДОМЕННОМУ ПРОИЗВОДСТВУ · ЕВРАЗ ЗСМК · Дивизион «Сибирь»"
         },
запрос на продакшен:
/account/2/vacancies/115
ответ:
{
   "body": null,
   "applicants_to_hire": 1,
   "position": "СЛЕСАРЬ ДЕЖУРНЫЙ",
   "created": "2019-12-31T07:52:58+03:00",
   "account_division": 2263,
   "education": null,
   "deadline": null,
   "source": null,
   "files": [],
   "conditions": null,
   "additional_fields_list":    [
      "position_code",
      "soft_skills",
      "language",
      "education",
      "pc",
      "bonus",
      "seniority",
      "place",
      "skills",
      "select",
      "area",
      "trip",
      "schedule"
   ],
   "skills": null,
   "area": null,
   "position_code": "50265178",
   "soft_skills": null,
   "select": "Рабочие",
   "state": "OPEN",
   "seniority": null,
   "pc": null,
   "place": "УЧАСТОК 17",
   "company": null,
   "priority": 0,
   "id": 115,
   "hidden": false,
   "money": null,
   "requirements": null,
   "parent": null,
   "multiple": false,
   "language": null,
   "schedule": "ПОСМЕННЫЙ",
   "bonus": null,
   "trip": null,
   "vacancy_request": null
}

**Comment by glibin** [comment]
Добрый день!

В вашем ответе это поле `"account_division": 2263,`

Справочник подразделений можно получить запросом GET `/account/2/divisions`
