### ISSUE TITLE
Поиск кандидатов по телефону, ФИО и т.п.

### ISSUE THREAD

**Issue by 0skolok** [huntflow/api#139]
Здравствуйте! У меня есть несколько вопросов по поводу поиска по кандидатам.
1. Когда в документации появится метод `/account/<account_id>/applicants/search`?
2. Почему не могу найти новых кандидатов? 
Я создал нового кандидата через интерфейс HuntFlow. Пытаюсь его найти через интерфейс — не находит. Через API с помощью метода `/account/<account_id>/applicants/search` тоже самое. Можете подсказать в чем дело?

**Comment by glibin** [comment]
Добрый день!

> Когда в документации появится метод /account/<account_id>/applicants/search?

API все еще в стадии стабилизации, точных сроков пока нет.

> Почему не могу найти новых кандидатов?

Можете прислать ссылку на кандидата?

**Comment by 0skolok** [comment]
>Можете прислать ссылку на кандидата?

Проблема решилась
