### ISSUE TITLE
Поиск по вакансии не выдает название компании

### ISSUE THREAD

**Issue by mcsony** [huntflow/api#140]

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, какой запрос вы отправляете?

**Comment by mcsony** [comment]
https://api.huntflow.ru/account/id/vacancies?opened=1

**Comment by glibin** [comment]
Можете прислать пример ожидаемого ответа? Пока не очень понятно, что вы имеете ввиду.
