### ISSUE TITLE
ошибки при создании/обновлении справочников

### ISSUE THREAD

**Issue by rogozhinsv** [huntflow/api#141]
Добрый день!
При попытке создать справочник валится ошибка, скрин запроса:
![image](https://user-images.githubusercontent.com/40475135/76504671-33ac0580-6459-11ea-9e13-b48fc89d720d.png)

При попытке обновить существующий справочник вообще ничего не происходит - просто ответ 200 приходит.

**Comment by glibin** [comment]
Добрый день!

> При попытке создать справочник валится ошибка, скрин запроса:

Пришлите, пожалуйста, весь запрос (возможно, в postman есть опция Copy as cURL), предварительно удалив авторизационные данные.

> При попытке обновить существующий справочник вообще ничего не происходит - просто ответ 200 приходит.

При попытке обновить текущий справочник должен возвращаться код ответа 200 и идентификатор задачи на обновление.

**Comment by rogozhinsv** [comment]
Добрый день!
1. выгрузил запрос (as cURL):
curl --location --request POST 'http://lanit-api.huntflow.ru/account/2/dictionary' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ***' \
--data-raw '{
    "code": "grade123123",
    "name": "Grade Values",
    "foreign": "grade_v_12",
    "items": [
        {
            "foreign": "0001", 
            "name": "Backend",
            "items": [
                {"name": "Senior", "foreign": "0002", "meta": {"kpi_coefficient": 5, "level": 3}},
                {"name": "Middle", "foreign": "0003", "meta": {"kpi_coefficient": 3, "level": 3}},
                {"name": "Junior", "foreign": "0004", "meta": {"kpi_coefficient": 1, "level": 3}}
            ]
        }
    ]
}'

2. при попытке обновления приходит статус 200 и не приходит задача на обновление, приходят значение справочника как при get-запросе, только со старыми данными

**Comment by glibin** [comment]
Не обратил внимание, вы используете http-схему для запросов. Нужно использовать https.

**Comment by rogozhinsv** [comment]
Да, с https все заработало - и получение и создание, и редактирование справочника.
Но осталась та же самая ошибка с получением двух определенных справочников:
https://lanit-api.huntflow.ru/account/2/dictionary/account_division
https://lanit-api.huntflow.ru/account/2/dictionary/city

Не подскажете, в чем дело?

**Comment by glibin** [comment]
Вопрос задан в отдельном тикете, этот закрою
