### ISSUE TITLE
Как получать конфиденциальные вакансии по АПИ?

### ISSUE THREAD

**Issue by chastoedov** [huntflow/api#143]
Здравствуйте!

Столкнулись с такой задачей - не получается выгрузить некоторые вакансии по апи (которые закрыты от общего просмотра, если правильно понял).

Можно ли как-то получать такие вакансии или какая настройка отвечает за "открытие/закрытие" вакансии от чтения через апи?

**Comment by glibin** [comment]
Добрый день!

Есть два варианта:

1. Добавлять пользователя API Robot на эти вакансии, тогда они будут ему доступны
2. Сделать пользователю API Robot роль управляющего, тогда он будет видеть все вакансии (можно сделать через тех. поддержку)
