### ISSUE TITLE
Изменение статуса кандидата через API

### ISSUE THREAD

**Issue by ds-dhorizon** [huntflow/api#146]
Добрый день!
Просим добавить возможность изменения статуса кандидата через API. Например, методом PUT.

Речь идет о поле status в links

```
"links": [
        {
          "status": 2,
          "updated": "2017-12-19T21:35:09+03:00",
          "changed": "2017-12-19T21:35:09+03:00",
          "vacancy": 1,
          "id": 171
        }
```

**Comment by glibin** [comment]
Добрый день!

Ответ есть здесь: https://github.com/huntflow/api/issues/66
