### ISSUE TITLE
Список этапов подбора для вакансии

### ISSUE THREAD

**Issue by Alien88183** [huntflow/api#147]
Подскажите как получить набор этапов подбора для конкретной вакансии?

**Comment by glibin** [comment]
Добрый день!

Обратили внимание, что это поле сейчас не отдается в API. Исправление выйдет в ближайшие пару дней.

**Comment by glibin** [comment]
Выкатили исправление. Паметр называется `account_vacancy_status_group`

**Comment by Alien88183** [comment]
В сущности вакансии (получаю методом GET /account/{account_id}/vacancies/{vacancy_id}), нет поля account_vacancy_status_group.  Я его правильно пытаюсь получить?

**Comment by glibin** [comment]
Пришлите, пожалуйста, полный URL запроса (мы по нему поймем вауш компанию и идентификатор вакансии), проверим логи и ответим

**Comment by Alien88183** [comment]
Сейчас появилось поле account_vacancy_status_group, в нём приходи id набора этапов подбора. 
Как получить список наборов этапов подбора с списком этапов в них?

**Comment by glibin** [comment]
К сожалению, данного метода пока нет в API (мы работаем над добавлением). Пока вы можете запросить список через поддержку.
