### ISSUE TITLE
Интеграция с Нашим Сайтом 

### ISSUE THREAD

**Issue by Anakin92** [huntflow/api#148]
мы собираемся сделать на нашем сайте онлайн анкету для кандидатов

со Следующими Полями:

ФИО - обязательно для заполнения

Контактные данные - обязательно 

Дата рождения - обязательно

Город 

Сопроводительное письмо/расскажи о себе/почему хочешь работать у нас (формулировку дадим чуть позже)

3 поля для ссылок на социальные сети

Прикрепление резюме - не обязательно

Прикрепление фото - не обязательно

скажите если мы засинхроним это в Huntflow, в каком виде у вас будет это отображаться?

поддерживаете ли вы поля такого рода?

**Comment by glibin** [comment]
Зависит от того, куда вы захотите эти поля добавить. Есть возможность в кандидата (https://github.com/huntflow/api/blob/master/ru/applicants.md#add) + анкета кандидата (https://github.com/huntflow/api/blob/master/ru/questionaries.md) или через платформу откликов (https://github.com/huntflow/api/blob/master/ru/responses.md) – зависит от желаний и потребностей :-)

**Comment by Anakin92** [comment]
мы хотим добавить анкету именно на нашем сайте, и чтобы она уже в Huntflow отображалась в качестве кандидата

**Comment by glibin** [comment]
Тогда, вероятно, вам наиболее подойдут методы https://github.com/huntflow/api/blob/master/ru/applicants.md#add и https://github.com/huntflow/api/blob/master/ru/questionaries.md

Там описано какие данные можно передавать и в какие сущности они будут попадать.
