### ISSUE TITLE
Ошибка при получении справочников

### ISSUE THREAD

**Issue by rogozhinsv** [huntflow/api#149]
Добрый день!
При получении определенных справочников (только двух, со всеми остальными - полный порядок) с хантфлоу валится ошибка:
![image](https://user-images.githubusercontent.com/40475135/77903131-0bab0780-728b-11ea-9f4f-d6d9478cc63f.png)

Запрос:
![image](https://user-images.githubusercontent.com/40475135/77903211-29786c80-728b-11ea-8d41-b092bebc2cf3.png)

Повторюсь, такая ошибка только для двух справочников:
https://lanit-api.huntflow.ru/account/2/dictionary/account_division
https://lanit-api.huntflow.ru/account/2/dictionary/city
С другими справочниками все хорошо.

**Comment by glibin** [comment]
Добрый день!

Не нашли таких справочников у вас, но, судя по контексту, вам нужны справочник подразделений (/account/<account_id>/divisions), а для городов у вас есть справочник city_lanit

**Comment by rogozhinsv** [comment]
city_lanit - помогло, спасибо!
с account_divisions - тоже разобрался
