### ISSUE TITLE
Справочник ролей

### ISSUE THREAD

**Issue by prochanEV** [huntflow/api#15]
По этому адресу(https://github.com/huntflow/api/blob/master/ru/dicts.md#member_type) нету справочника ролей, хотя информация об этом указана тут
https://github.com/huntflow/api/blob/master/ru/user.md

Нужен справочник ролей

**Comment by glibin** [comment]
Спасибо, добавим. 

Возможные роли:

owner – управляющий организацией (главный администратор)
manager – рекрутер
watcher – заказчик
