### ISSUE TITLE
Проблема с получением откликов по вакансии

### ISSUE THREAD

**Issue by rogozhinsv** [huntflow/api#150]
Реализован сервис получения откликов по вакансии на карьерном сайте в соответствии с требованиями вашей апи. Запрос с хантфлоу приходит и отрабатывается без ошибок, но отклики так и не появляются. Подскажите, в чем проблема?
Вот пример запроса с постмэна:
![image](https://user-images.githubusercontent.com/40475135/77917713-913ab180-72a3-11ea-84f3-50da18bf8acd.png)
Вот ответ:
![image](https://user-images.githubusercontent.com/40475135/77917875-c21ae680-72a3-11ea-8098-ed55ac580794.png)

**Comment by glibin** [comment]
Можете прислать ссылку на вакансию в Хантфлоу?
