### ISSUE TITLE
API возвращает большое кол-во кандидатов 

### ISSUE THREAD

**Issue by maddoxdev** [huntflow/api#151]
Добрый день.
Иcпользуется API получения списка кандидатов. Не знаю точно с чем это связано, но total_items в ответе выдает немыслимые 88392.

Можете дать какую-то информацию? Может быть это сбой на вашей стороне или такое кол-во кандидатов было добавлено когда-то через API? В общем хотим выяснить от куда такое количество.

Account: 7115

**Comment by glibin** [comment]
Добрый день!

Насколько я знаю, у вас был изначальные перенос базы + объединение организаций. 

Почему это немыслимая цифра я не очень понимаю, у наших клиентов есть базы и с более полумиллиона кандидатов.

**Comment by maddoxdev** [comment]
> Добрый день!
> 
> Насколько я знаю, у вас был изначальные перенос базы + объединение организаций.
> 
> Почему это немыслимая цифра я не очень понимаю, у наших клиентов есть базы и с более полумиллиона кандидатов.

До переноса было на порядок меньше. Интересует дата переноса. Сможете дать информацию?

**Comment by glibin** [comment]
Объединение организаций было 19 июня 2019.
