### ISSUE TITLE
Использование токена

### ISSUE THREAD

**Issue by BordachevD** [huntflow/api#152]
Добрый день!
У меня есть токен, не знаю, как его активировать в GitKraken

**Comment by BordachevD** [comment]
Для сбора статистики с сайта в Power BI Еще нужны название сервера и бд в PostgreSQL

**Comment by glibin** [comment]
Добрый день!

Информация по использованию токена доступна здесь: https://github.com/huntflow/api/blob/master/ru/personal_token.md

Доступ к БД мы не предоставляем. Для получения данных для аналитики нужно использовать методы API, описанные в документации.
