### ISSUE TITLE
Максимальная пропускная способность системы

### ISSUE THREAD

**Issue by BluzSter** [huntflow/api#154]
Добрый день. Можно ли получить более 30 резюме за один запрос? Если нет, то какая максимальная пропускная способность, у нас есть только информацию про 5 запросов в секунду. Насколько такая пропускная способность отличается от реальной?

**Comment by glibin** [comment]
Добрый день!

> Можно ли получить более 30 резюме за один запрос?

нет


Есть ограничение в 5 запросов в секунду, следует оптимизировать сервисы под это ограничение. В противном случае будет возвращаться ошибка 429

**Comment by BluzSter** [comment]
Спасибо за ответ.
