### ISSUE TITLE
Получить список id рекрутеров

### ISSUE THREAD

**Issue by nhype** [huntflow/api#155]
При добавлении вакансии через API можно указать список сотрудников, которые над ней работают
 
 "coworkers": [1],

 
Откуда можно взять их уникальные идентификаторы?

**Comment by glibin** [comment]
Добрый день!

запрос `/account/<account_id>/members`

вернет всех работающих в организации рекрутеров, также возможен фильтр для вакансии (кто работает на вакансии):

`/account/<account_id>/members?vacancy=<vacancy_id>`

а также добавить в ответ заказчиков:

`/account/<account_id>/members?show_watchers=true`
