### ISSUE TITLE
Создание вакансии

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#157]
Добрый день! Возникла проблема при создании вакансии

Отправляю POST-запрос на /account/{account_id}/vacancies, со своим account_id.  
С headers - Authorization и Content-Type - application/json. И телом запроса:

```
{
    "position": "Manufacturing Engineer",
    "company": "Tesla",
    "money": "$100k",
    "deadline": "2020-09-03",
    "applicants_to_hire": 1,
    "priority": 0,
    "account_division": null,
    "coworkers": [48334],
    "body": "test",
    "requirements": "test",
    "conditions": "test",
    "hidden": false,
    "state": "OPEN",
    "files": []
}
```

В ответ приходит 200 ОК и список вакансий без той, что я хотела создать. В интерфейсе вакансия тоже не появляется.

Подскажите, пожалуйста, что не так с моим запросом? 

При этом боту, через которого я пытаюсь создать вакансию, выданы все доступные права.

**Comment by glibin** [comment]
Добрый день!

Пришлите полный URL запроса. Есть ощущение, что вы используете http-схему, а не https

**Comment by lyubich** [comment]
Спасибо! Все так. Использовала http вместо https
