### ISSUE TITLE
Изменение статуса кандидата

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#159]
Доброе утро! Подскажите, пожалуйста, можно ли и как, если можно, изменить статус кандидата через апи? Смотрела апи работы с кандидатом и не нашла там ничего подходящего https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

**Comment by glibin** [comment]
Добрый день!

Это возможно. Подробности: https://github.com/huntflow/api/issues/66

**Comment by lyubich** [comment]
Спасибо! Все работает!
