### ISSUE TITLE
История работы с кандидатом

### ISSUE THREAD

**Issue by tdn670000** [huntflow/api#160]
Добрый день!
У нас настроены вебхуки для того, чтобы сохранять историю в хранилище данных
Но одно время сервер, принимающий вебхуки, был недоступен

Как мне восстановить историю? временной период с 14.03.2019 по 22.04.2019 включительно
`GET /account/{account_id}/applicants/{applicant_id}/log` - этой ручкой мне придется скачать всю историю по всем кандидатам. Может есть другой способ?

**Comment by glibin** [comment]
К сожалению. Другого способа сейчас нет. 

Вы также можете делать запрос на /applicants на список кандидатов. В блоке links будет информация об изменениях по кандидату. Изменение этапа подбора отражает временная метка changed, изменения по кандидату на вакансии (в том числе комментарии) – updated.

**Comment by tdn670000** [comment]
я уже скачал по всем логи)
оказалось, довольно быстро
спасибо
