### ISSUE TITLE
Изменение подразделений

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#161]
Добрый вечер! Отправляю запрос на изменение подразделений

POST-запрос на api.huntflow.ru/account/{account_id}/all_divisions, со своим account_id.
С headers - Authorization и Content-Type - application/json. И телом запроса:
```
{
    "items": [
        {
            "name": "Подразделение 1234567",
            "foreign": "1234567",
            "meta": {
                "country": "RU",
                "comment": "some text"
            }
        }
    ]
}
```
В ответ приходит 200 ОК и список подразделений которые сейчас существует, а не то, что я указала. И вообще формат ответа странный, включает себя items и meta, а не то, что здесь описано - https://github.com/huntflow/api/blob/master/ru/account_divisions.md .

Подскажите, пожалуйста, как можно поменять структуру подразделений? Что я делаю не так?

**Comment by glibin** [comment]
Кажется, вы используете http-схему запроса, а нужно использовать https: `https://api.huntflow.ru/account/{account_id}/all_divisions`

**Comment by lyubich** [comment]
Спасибо за ответ! Я попробовала! Но теперь в ответ мне приходит 
`
{
    "errors": [
        {
            "type": "common",
            "value": [
                "forbidden"
            ]
        }
    ]
}
`

Я пытаюсь изменить состав подразделений от "лица" бота. Боту предварительно выданы все права. В связи с этим вопрос, кто может менять структуру подразделений? И может ли это делать бот?

**Comment by glibin** [comment]
Делать это может только "бот" с правами управляющего. Уточните, пожалуйста, у поддержки какая роль у пользователя API Robot в вашей организации и попросите поменять на управляющего.

**Comment by lyubich** [comment]
У бота "member_type": "manager".
