### ISSUE TITLE
Как вывести словари для additional_fields_list?

### ISSUE THREAD

**Issue by bora86bora** [huntflow/api#162]
"additional_fields_list": [
        "positions",
        "heads",
        "skills",
        "functions",
        "clusters"
    ],
    "functions": 17582,
    "clusters": 17497,

Как через api можно вытащить справочники для:
-  functions
-  clusters

**Comment by glibin** [comment]
Через запрос на получение справочника: https://github.com/huntflow/api/blob/master/ru/dictionaries.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B0

**Comment by bora86bora** [comment]
А как узнать список {dictionary_code}, что у нас есть? Я не нашел

**Comment by glibin** [comment]
К сожалению, это невозможно сделать из API. 

Пришлите ваш account_id и URL API на адрес hello@huntflow.ru – мы подготовим и перешлем список всех ваших справочников.

**Comment by bora86bora** [comment]
вчера отписал, пока нет ответа.

**Comment by glibin** [comment]
Письмо попало в спам. Ответили.
