### ISSUE TITLE
Дата закрытия вакансии

### ISSUE THREAD

**Issue by chistyakovyo** [huntflow/api#165]
Добрый день
В вакансии есть блок с датой закрытия вакансии и фио, кто с ней работает, но при выгрузке информации через API не вижу этих полей. Как их можно получать?

**Comment by glibin** [comment]
Добрый день! Пришлите, пожалуйста, скриншот? Из ваших слов не очень понятно, какая информация требуется из API

**Comment by chistyakovyo** [comment]
![HF](https://user-images.githubusercontent.com/57222413/80570846-33b19600-8a04-11ea-8b90-7547fae83a4a.jpg)

**Comment by glibin** [comment]
Добрый день!

Мы сейчас готовим документацию для метода https://api.huntflow.ru/account/<account_id>/vacancy/<vacancy_id>/logs

Можете начинать его использовать для получения истории работы по вакансии. 

```
"state": "CLOSED", <-- state, который говорит о факте закрытия вакансии
"created": "2020-01-11T23:59:59+03:00", <-- дата закрытия вакансии
```

Так как вакансия может переоткрываться несколько раз, то обратите внимание, что таких записей в ответе может быть несколько. Метод получения периодов открытия вакансии мы готовим к выпуску.

**Comment by glibin** [comment]
По получению работающих рекрутеров:

запрос `/account/<account_id>/members`

вернет всех работающих в организации рекрутеров, также возможен фильтр для вакансии (кто работает на вакансии):

`/account/<account_id>/members?vacancy=<vacancy_id>`

а также добавить в ответ заказчиков:

`/account/<account_id>/members?show_watchers=true`
