### ISSUE TITLE
Возможность добавления заказчика на этапы через апи

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#166]
Добрый день! Подскажите, пожалуйста, возможно ли через ваше апи добавлять заказчиков к вакансии на этапы? Попробовала поэксперементировать с апи по изменению вакансии с полем "coworkers", но оно добавляет только рекрутеров(

**Comment by glibin** [comment]
Добрый день!

К сожалению, пока такой возможности через API нет.

**Comment by lyubich** [comment]
ок! спасибо за ответ! а есть в планах сделать что-то подобное? или в ближайшее время не появится?

**Comment by glibin** [comment]
К сожалению, в ближайших планах нет :(
