### ISSUE TITLE
Возможность фильтровать кандидатов по большему числу полей

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#167]
Сейчас /account/{}/applicants позволяет фильтровать по статусу и вакансии. Очень не хватает фильтра по источнику, так как поиск /account/{}/applicants/search возвращает только идентификаторы кандидатов, что приводит к необходимости запрашивать их по одному. А это и долго и отнимает больше ресурсов.

Есть менее изящный вариант - сделать возможность запрашивать кандидатов пачками, по 100, например, но тогда можно искать их через поиск и получать через отдельный запрос. Этот вариант требует меньше ресурсов на разработку, но дает больше возможностей в целом.

**Comment by glibin** [comment]
А какая информация требуется по кандидату?

**Comment by nikepan** [comment]
конкретно в нашем случае, вакансии, на которые он рассматривается, и статусы по ним. эта информация возвращается сейчас

**Comment by glibin** [comment]
Мы добавим такую возможность в план разработки, но пока не сможем сориентировать по точным срокам.
