### ISSUE TITLE
Обновление кандидата.

### ISSUE THREAD

**Issue by localroot282** [huntflow/api#168]
Подскажите, пожалуйста, каким образом через Хантфлоу API произвести обновление информации о существующем в базе кандидате. В документации на GitHub такая возможность не описана, однако в issue https://github.com/huntflow/api/issues/40 8 августа 2019 было сказано "пока такого метода нет, но мы планируем его добавить в этом году". Конкретно, нужно обновить резюме (на самом деле - добавить отсутствующее у кандидата резюме) и добавить комментарий. Операция массовая и разовая.

**Comment by glibin** [comment]
Добрый день!

К сожалению, возможности обновить резюме через API так и не появилось.

**Comment by localroot282** [comment]
Очень жаль.
Спасибо за ответ.
