### ISSUE TITLE
Adding vacancy to base

### ISSUE THREAD

**Issue by ilyas0v** [huntflow/api#169]
Hi.
Hope you all are doing ok.

I have faced with issue when I tried to post vacancy information to your API.

I did POST request to  /account/{account_id}/vacancies/ route with required body.

I got this response with 500 status code : 

{
    "errors": [
        {
            "type": "server_error",
            "value": [
                "internal_error"
            ]
        }
    ],
    "description": "Internal Server Error"
}

I wish you will help me ASAP. Thanks.

**Comment by glibin** [comment]
Hello!

Could you, please, provide request body? Are you requesting http**s**://api.huntlfow.ru ?

**Comment by ilyas0v** [comment]
Hi.
Sure
I requested to https://api.huntflow.ru/account/{id}/vacancies with POST method.

Request body is  { position : 'Test Vacancy' }
I didnt complete other field, because in documentation it says it is not required. Position is required field.

**Comment by glibin** [comment]
Could you also provide your account_id?

**Comment by ilyas0v** [comment]
> Could you also provide your account_id?

48873
Here you are.

**Comment by glibin** [comment]
It seems that you are sending invalid JSON. Example of valid:

```
{ "position": "Test Vacancy" }
```

**Comment by ilyas0v** [comment]
No, I didnt send it as JSON format, for sent it via form data

**Comment by glibin** [comment]
Request body should be a valid JSON. You can check about it here: https://github.com/huntflow/api/blob/master/en/general.md#request-body-format-when-sending-a-json

**Comment by ilyas0v** [comment]
Okay. Thanks. 
But what is the 'client_vacancy_request' or 'vacancy_client'.  ?

**Comment by glibin** [comment]
It is a required fields for the recruitment agencies.

You can read it here: https://github.com/huntflow/api/blob/master/ru/agency_vacancies.md#добавление-вакансии

(sorry, it's in Russian)

**Comment by ilyas0v** [comment]
Sorry, 
I couldn't create vacancy via API.

{
	"position" : "PHP Developer",
	"client_vacancy_request" : 54177
}

it is my request body.  I created a client on system, and 54177 is my client's ID.  But still I get this response : 


{
    "errors": [
        {
            "type": "common.vacancy",
            "value": [
                "required 'client_vacancy_request' or 'vacancy_client'"
            ]
        }
    ]
}

**Comment by glibin** [comment]
You are not quite right.

First, you should create a client: https://github.com/huntflow/api/blob/master/ru/agency_clients.md#client-add

After that create a vacancy request for that client: https://github.com/huntflow/api/blob/master/ru/agency_vacancy_requests.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E

And use that vacancy request id to create a vacancy: https://github.com/huntflow/api/blob/master/ru/agency_vacancies.md#vacancy-add

**Comment by ilyas0v** [comment]
Okay. Thanks for your time. I really appreciate it.
