### ISSUE TITLE
Формы обратной связи

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#170]
Добрый день! Через интерфейс есть возможность получения "формы обратной связи" -  https://huntflow.ru/my/{account}/surveys/{type_form}/{id_form}/summary

 А есть ли такая возможность в апи?

**Comment by glibin** [comment]
Добрый день!

Пока такой возможности нет, но планируем добавить в будущем.

**Comment by lyubich** [comment]
А как скоро планируете добавить?

**Comment by glibin** [comment]
К сожалению, в ближайших планах нет.

Сейчас идет стабилизация платформы форм обратной связи и, в лучшем случае, появится в API не раньше осени.

**Comment by lyubich** [comment]
Хорошо, спасибо!
