### ISSUE TITLE
Изменение вакансии

### ISSUE THREAD

**Issue by silischev** [huntflow/api#172]
Здравствуйте.
Пытаюсь изменить вакансию через api как описано в документации https://github.com/huntflow/api/blob/master/ru/vacancies.md#edit
Поле 'applicants_to_hire' не меняет своё значение.
Другие поля (например, priority) меняют.
Тело запроса выглядит таким образом:
`{"id":2515454,"position":"Программист PHP2","state":"OPEN","applicants_to_hire": 2,"priority": 1}`

**Comment by glibin** [comment]
Добрый день!

К сожалению, с запозданием замержили обновление документации (https://github.com/huntflow/api/pull/136/files). 

Ознакомьтесь, пожалуйста, с изменениями https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B8-%D0%B2-%D0%B1%D0%B0%D0%B7%D1%83
