### ISSUE TITLE
How to add additional fields to candidate

### ISSUE THREAD

**Issue by ilyas0v** [huntflow/api#173]
Hi, hope you all having a good day.

I have a question about how to add some relational informations about candidate such like education infos, work experiences, skills and etc.

I am working with your API, but I couldnt find that in your documentation.

Thanks in advance.

**Comment by glibin** [comment]
Hello,

currently it is not possible to modify CV information of the candidate.

But you can add additional fields to applicant via questionaries (https://github.com/huntflow/api/blob/master/ru/questionaries.md) and store information there. 

You can contact support team to add the fields you need.
