### ISSUE TITLE
Список вакансий

### ISSUE THREAD

**Issue by silischev** [huntflow/api#174]
Здравствуйте.
Не отрабатывает параметр `count` при получении списка вакансий - `/account/1234567/vacancies?count=100`.
Ориентируюсь на документацию https://github.com/huntflow/api/blob/master/ru/vacancies.md#vacancies
Всегда возвращается 30 записей.
Есть какой-то способ получить большее количество вакансий?

**Comment by glibin** [comment]
Добрый день! 

К сожалению, API не предоставляет возможности получать более 30 вакансий на страницу.

**Comment by silischev** [comment]
Так он и меньше 30 не дает)
