### ISSUE TITLE
Добавление рекрутера к вакансии

### ISSUE THREAD

**Issue by silischev** [huntflow/api#175]
Добрый день.
Не получается добавить рекрутера к вакансии.
Все права в настройках выставлены.
Делаю такой запрос
`PUT https://api.huntflow.ru/account/123/vacancies/1000`
`{"id":1, "position":"Вакансия", "state":"OPEN", "coworkers": [1, 2]}`
В результате рекрутер не добавляется к вакансии, другие поля меняются.
Пробовал также передавать строку, а не массив в поле `coworkers`, всё равно такой же результат.
Статус вакансии меняется, но рекрутер не добавляется.
Похоже, что это поле никак не валидируется.
Прошу помочь решить эту проблему, а также актуализировать вашу документацию.

**Comment by glibin** [comment]
Добрый день!

К сожалению, возможности добавления рекрутеров на существующую вакансию через API не предусмотрено. Мы планируем добавить такую возможность до конца июня.
