### ISSUE TITLE
Удаление кандидатов.

### ISSUE THREAD

**Issue by localroot282** [huntflow/api#176]
Добрый день!
Для очистки нашей базы от кандидатов с определёнными параметрами возникла потребность удаления кандидатов. В ранее закрытом ишью https://github.com/huntflow/api/issues/126 говорилось, что добавлен метод DELETE https://api.huntflow.ru/account/<account_id>/applicants/<applicant_id>, но при вызове его сейчас получаю результат
{
    "errors": [
        {
            "type": "common",
            "value": [
                "forbidden"
            ]
        }
    ]
}
Подскажите, в чём заключается проблема и как ее исправить?

**Comment by glibin** [comment]
Добрый день!

Скорее всего у технической учетной записи (API Robot) для API не проставлено право на удаление кандидатов. Вы можете попросить управляющего рекрутера проставить это право.
