### ISSUE TITLE
Отсутствует ключи в полях account_vacancy_request

### ISSUE THREAD

**Issue by nkalimbetov** [huntflow/api#177]
Добрый день.
При получение списка схем заявки на вакансию, во многих полях отсутствует значение ключа (key).

Пример:
![image](https://user-images.githubusercontent.com/5275279/84633150-c86b4700-af11-11ea-8d94-9e83aa3ced5b.png)

Из за этого могут не отображаться данные в доп. полях при получение вакансий?
Например, данные в поле ГРАФИК РАБОТЫ / ТИП ЗАНЯТОСТИ точно заполнено.
Если так, как заполнить ключи(key) в полях?

Коробочная версия huntflow. Технодом.

![image](https://user-images.githubusercontent.com/5275279/84633269-f6e92200-af11-11ea-85b9-1acc2769bb40.png)

**Comment by glibin** [comment]
Поле key служебное и, в большинстве случаев, для интеграций не нужно.

Исходя из описанного вами: схема заявки на вакансию и схема вакансии различаются, поэтому наличие полей в заявке не означает, что все они будут в вакансии. Если какие-то поля из заявки нужны в вакансии, то нужно доработать схему вакансии и, при необходимости, их прокидывание в поля вакансии.
