### ISSUE TITLE
Работа  офферами

### ISSUE THREAD

**Issue by lyubich** [huntflow/api#178]
Добрый день! Подскажите, пожалуйста, есть ли или планируется ли добавление функционала для работы с офферами? чтение\формирование...

**Comment by glibin** [comment]
Добрый день!

Есть возможность получить оффер по периоду открытия вакансии:

`/account/<account_id>/applicants/<applicant_id>/vacancy_frame/<vacancy_frame_id>/offer?normalize=true`

Последний период открытия можно получить запросом:

`/account/<account_id>/vacancy/<vacancy_id>/frame`

Также, информация по офферу возвращается в вебхуках.

Других способов работы с офферами пока не предусмотрено.

**Comment by lyubich** [comment]
Спасибо!

**Comment by FreeRiderBysik** [comment]
Виталий, добрый день. 
Что-то не выходит на демо - отправляю запрос:
https://api.huntflow.ru/account/48039/applicants/9106410/vacancy_frame/252315/offer?normalize=true

Получаю ответ:
{
    "errors": [
        {
            "type": "common",
            "value": [
                "not found"
            ]
        }
    ]
}

Хотя оффер есть:
![image](https://user-images.githubusercontent.com/1512168/88158178-612d6a80-cc14-11ea-914a-effe70dc6c3a.png)

**Comment by glibin** [comment]
Добрый день!

Оффер доступен только:
– пользователю с ролью рекрутера, когда он работает над вакансией
– пользователю с ролью управляющего всегда

Кажется, что у вашей технической учетной записи роль рекрутера, и он не назначен на вакансию.

Вы можете добавить его на вакансию самостоятельно или запросить поддержку дать этой учетной записи роль управляющего.

**Comment by FreeRiderBysik** [comment]
Спасибо, добавил в вакансию, помогло. Я об этом не подумал как-то, ожидал получить 403 а не "not found"в таком сценарии.
