### ISSUE TITLE
Как указать почту, на которую отправится заявка на вакнасию

### ISSUE THREAD

**Issue by ShuFFel** [huntflow/api#18]
В документации нет описания поля, в которое можно указать почту человека, подтверждающего заявку на вакансию. 
Также не описано откуда взять id созданной заявки на вакнсию

**Comment by ShuFFel** [comment]
Сейчас методы создания заявки на вакансию возвращают 500, хочется получить информацию по поводу заданных вопросов, потому что опытным путем найти ответ не получается.

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, пример запроса (заголовки и тело), в результате которых возвращается 500.

**Comment by glibin** [comment]
> В документации нет описания поля, в которое можно указать почту человека, подтверждающего заявку на вакансию.

Добавили пример с согласованием заявки: https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E

**Comment by ShuFFel** [comment]
попробовал создать заявку с аппрувером, результат такой же - 500

**Comment by glibin** [comment]
Уточните, о какой организации в Хантфлоу идет речь?

**Comment by ShuFFel** [comment]
instinctools

**Comment by glibin** [comment]
@ShuFFel добрый вечер! 

В теле запроса необходимо передать параметр `account_vacancy_request`, который можно получить из запроса: 

https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BE%D0%BA-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E
