### ISSUE TITLE
Получение списка вакансий

### ISSUE THREAD

**Issue by nkalimbetov** [huntflow/api#180]
Здравствуйте. 

Обращаюсь по адресе: `GET /account/{account_id}/vacancies`
Подскажите, как отсортировать вакансии по дате создание.

И еще подскажите, по какому полю идет сортировка по умолчанию ?

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за очень долгий ответ.

Сортировка происходит по следующему порядку:

1. приоритет вакансии (более приоритетные выше)
2. название вакансии
3. идентификатор вакансии (более новые выше)

Управлять сортировкой пока нельзя.
