### ISSUE TITLE
Рекрутеры

### ISSUE THREAD

**Issue by nkalimbetov** [huntflow/api#181]
Здравствуйте, 
Подскажите, как через api получить список рекрутеров которые работают над определенной вакансией ?

Рекрутеры которые находятся тут:
![image](https://user-images.githubusercontent.com/5275279/85506838-f6880f80-b612-11ea-8781-b90f6705e321.png)

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ.

Ответ есть в этом тикете: https://github.com/huntflow/api/issues/155
