### ISSUE TITLE
Getting 400 bad request when creating "client vacancy request"

### ISSUE THREAD

**Issue by ilyas0v** [huntflow/api#182]
Hello,
Hope you all are doing well.

I have faced with this kind of issue when I tried to create  vacancy request.

**Request url :** 
https://api.huntflow.ru/account/36877/clients/54329/client_vacancy_requests

**This is my request body :** 

`{
	"contacts" : [{
		"id" : 58963
	}],
	"position" : "TEST VACANCY"
}`

**and this is response :** 

`{
    "errors": [
        {
            "type": "common.account_client_vacancy_request",
            "value": [
                "not found"
            ]
        }
    ]
}`

I did the same strategy to create vacancies when I was using demo account, It worked quite well. But now it is another huntflow account, it doesn't work at the same way I did before.

Thanks.

**Comment by glibin** [comment]
Hello, organization with id=36877 is not a recruitment agency and its workflow for the vacancy request creation differs.
Please, check https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md (https://github.com/huntflow/api/blob/master/en/vacancy_requests.md)

**Comment by ilyas0v** [comment]
Hello,  I got it.  
But I couldn't find where can I get the "account_division" attribute.

**Comment by ilyas0v** [comment]
I found account_division and other relational datas. I posted body like this : 

`
{
	"position": "Manufacturing Engineer",
    "money": "$100k",
    "priority": 1,
    "account_division": 24842,
    "budget_classification" : 4195,
    "function" : 4199,
    "position_level" : 4204,
    "body": "<p>Some text</p>",
    "requirements": "<p>Another text</p>",
    "conditions": "<p>Different text</p>",
    "hidden": false,
    "state": "OPEN",
    "fill_quotas": [
        {
            "deadline": "2020-09-03",
            "applicants_to_hire": 1,
            "vacancy_request": 18623
        }
    ]
}
`



And I get this response : 


`
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}
`

**Comment by glibin** [comment]
Could you, please send full request headers and body to hello@huntflow.ru ?

**Comment by ilyas0v** [comment]
> Could you, please send full request headers and body to [hello@huntflow.ru](mailto:hello@huntflow.ru) ?

Sure, I'll send it in 5 mins.

**Comment by ilyas0v** [comment]
> Could you, please send full request headers and body to [hello@huntflow.ru](mailto:hello@huntflow.ru) ?

I sent detailed information about my issue to  "hello@huntflow.ru"

**Comment by ilyas0v** [comment]
Hello,
How can I get list of departments ?
