### ISSUE TITLE
Не добавляется url в вебхуки

### ISSUE THREAD

**Issue by Trahtenberg** [huntflow/api#184]
Здравствуйте, добавляю адрес в вебхуки. Постояно выдаёт ошибку Webhook url can't be reached. Запрос с PING не поступает на сервер. Даже если добавляю url яндекса, всё равно ошибка.

**Comment by glibin** [comment]
Добрый день!

При проверке вебхука отправляется POST-запрос, сервер должен ответить кодом 200 или 204.

URL Яндекса на POST запрос отвечает ошибкой.

Также, на данный момент, не поддерживается работа с самоподписными сертификатами.

**Comment by Trahtenberg** [comment]
Обязательно ли наличие сертификата?

**Comment by Trahtenberg** [comment]
Снимаю вопрос, всё добавилось без сертификата. Считаю что в пунк 3 инструкции по вебхукам, нужно добавить тип (POST) проверочного PING запроса, т.к. не понятно каким методом система проверяет на доступность.
