### ISSUE TITLE
Get list of departments and other vacancy attributes

### ISSUE THREAD

**Issue by ilyas0v** [huntflow/api#185]
Hello,
How can I get list of departments ? I need this for "account_division" property.

Also I need list of "functions" , "budget classifications", "positions levels"

**Comment by glibin** [comment]
Hello,

it's possible via request: GET `/account/<account_id>/divisions`

**Comment by ilyas0v** [comment]
Hello, 
Thanks, I got it.
What about other lists ?    "functions" , "budget classifications", "positions levels"  and others

**Comment by glibin** [comment]
GET `/account/<account_id>/dictionary/{dictionary_code}`
