### ISSUE TITLE
Вопрос по APi

### ISSUE THREAD

**Issue by ashepelevhumans** [huntflow/api#186]
Добрый день.
Интересуют 
- сервисы получения данных в нашу систему обучения (развернута на moodle) - передача из вашей системы данных о кандидатах, чтобы могли автоматически создавать пользователей для последующего обучения
- отображение в нашем личном кабинете в хантфлоу календарей обучения из нашей системы (есть свое API)
- работа со справочниками должностей и структурой компании в хантфлоу, которые нужно получать из нашей системы 

Спасибо!

**Comment by glibin** [comment]
> сервисы получения данных в нашу систему обучения (развернута на moodle) - передача из вашей системы данных о кандидатах, чтобы могли автоматически создавать пользователей для последующего обучения

Вы можете подписаться на webhook и передавать в режиме реального времени данные в свою систему. https://github.com/huntflow/api/blob/master/ru/webhooks.md

> отображение в нашем личном кабинете в хантфлоу календарей обучения из нашей системы (есть свое API)

Хантфлоу поддерживает только календари на базе Microsoft Exchange / Google / Outlook365

> работа со справочниками должностей и структурой компании в хантфлоу, которые нужно получать из нашей системы

Вы можете управлять справочниками, передаваемыми в Хантфлоу :

https://github.com/huntflow/api/blob/master/ru/account_divisions.md
https://github.com/huntflow/api/blob/master/ru/dictionaries.md
