### ISSUE TITLE
Подпись вебхук

### ISSUE THREAD

**Issue by Trahtenberg** [huntflow/api#187]
Здравствуйте, 
при получении вебхук с секретным кодом, не получается воссоздать такую же подпись передаваемую в X-Huntflow-Signature. Делаю следующим образом: 

```
$str = '{"event":{"id" ... }}';      //тело вебхука
$sig = hash_hmac('sha256', $str, 'secret_key');
return $sig;
```

**Comment by glibin** [comment]
Добрый день!

К сожалению, смогу подсказать только пример на языке Python:

```
import hmac
from hashlib import sha256

payload = b"{\"event\": {\"id\": 108, \"type\": \"STATUS\", \"vacancy\": {\"id\": 6, \"applicants_to_hire\": 1, \"position\": \"Test vacancy\", \"company\": null, \"money\": \"rrr\", \"state\": \"OPEN\", \"hidden\": false, \"priority\": 0, \"deadline\": null, \"created\": \"2020-04-14\", \"multiple\": false, \"parent\": null, \"manager\": {\"id\": 10199, \"name\": \"Test member\", \"foreign\": \"69696\"}, \"grade\": {\"id\": 9629, \"name\": \"3\", \"foreign\": \"3\", \"meta\": {\"deadline\": 22}}, \"description\": \"<p>2<\\/p>\", \"fill_quotas\": [{\"id\": 6, \"applicants_to_hire\": 1, \"deadline\": null, \"vacancy_request\": null, \"created\": \"2020-04-14 21:38:04\", \"closed\": null}]}, \"status\": {\"id\": 256, \"name\": \"\\u0412\\u044b\\u0441\\u0442\\u0430\\u0432\\u043b\\u0435\\u043d \\u043e\\u0444\\u0444\\u0435\\u0440\"}, \"rejection_reason\": null, \"comment\": null, \"files\": [], \"survey_answer_of_type_a\": null, \"employment_date\": null, \"calendar_event\": null, \"created\": \"2020-04-15T08:54:39+03:00\", \"vacancy_group_action\": null, \"source\": null, \"applicant\": {\"photo\": null, \"first_name\": \"Test\", \"last_name\": \"Testov\", \"middle_name\": null, \"birthday\": null, \"position\": null, \"company\": null, \"money\": null, \"phone\": null, \"email\": null, \"skype\": null, \"questionary\": null, \"id\": 71}, \"questionary\": {}}, \"author\": {\"id\": 15, \"name\": \"Vitaly Glibin\", \"email\": \"test@example.com\", \"meta\": null}, \"account\": {\"id\": 30, \"name\": \"Test organization\"}}"

signature = hmac.new('123123123'.encode('utf-8'), payload, sha256)
print(signature.hexdigest() == 'ea03e7fda17b8034fbf05fef2a0553dbc6d8e373c981aeecfd3d88bfa6e42a1c')
```

**Comment by Trahtenberg** [comment]
В вашем примере в строке присутствуют пробелы, после символов двоеточия и запятой. Это не является стандартом JSON. Поэтому для создания индентичной подписи, которая приходит в заголовке, нужно форматировать строку и проставлять пробелы.

**Comment by glibin** [comment]
Подпись вычисляется от тела запроса (байт) и не зависит от того, что в этом теле (JSON или что-либо другое)

**Comment by Trahtenberg** [comment]
Всё верно, но тело запроса json у вас подписывается с пробелами. А нам приходит тот же json но БЕЗ пробелов. Таким образом размер и содержание одного и того же тела запроса на вашей стороне и на нашей различаются, соответственно и подписи разные. 
Когда у вас формируется подпись, json выглядит таким образом:

`
{"event": {"id": 108, "type": "STATUS"}}
`

А когда он приходит к нам, он такого вида:

`
{"event":{"id":108,"type":"STATUS"}}
`

Вот тут cказано https://docs.python.org/3/library/json.html как изменить форматирование json и убрать пробелы:
>import json
>json.dumps([1, 2, 3, {'4': 5, '6': 7}], separators=(',', ':'))
'[1,2,3,{"4":5,"6":7}]'

**Comment by glibin** [comment]
Еще раз повторюсь, что подпись запроса со стороны Хантфлоу происходит над набором байт. 
Пример выше приведен для иллюстрации подсчета подписи.

**Comment by Trahtenberg** [comment]
Правильно, но в вашем наборе байт стоят пробелы и подпись вы создаёте вместе с ними. 
Вы не поверите, но проставив пробелы вручную в полученном теле вебхук, подпись стала идентичной как в заголовке. И приведённый вами пример, ещё раз это доказывает!

**Comment by glibin** [comment]
Извините, нет больше возможности вас в чем-то убеждать. 

Мой пример на PHP:

```
<?php
      $payload = "{\"event\": {\"id\": 108, \"type\": \"STATUS\", \"vacancy\": {\"id\": 6, \"applicants_to_hire\": 1, \"position\": \"Test vacancy\", \"company\": null, \"money\": \"rrr\", \"state\": \"OPEN\", \"hidden\": false, \"priority\": 0, \"deadline\": null, \"created\": \"2020-04-14\", \"multiple\": false, \"parent\": null, \"manager\": {\"id\": 10199, \"name\": \"Test member\", \"foreign\": \"69696\"}, \"grade\": {\"id\": 9629, \"name\": \"3\", \"foreign\": \"3\", \"meta\": {\"deadline\": 22}}, \"description\": \"<p>2<\\/p>\", \"fill_quotas\": [{\"id\": 6, \"applicants_to_hire\": 1, \"deadline\": null, \"vacancy_request\": null, \"created\": \"2020-04-14 21:38:04\", \"closed\": null}]}, \"status\": {\"id\": 256, \"name\": \"\\u0412\\u044b\\u0441\\u0442\\u0430\\u0432\\u043b\\u0435\\u043d \\u043e\\u0444\\u0444\\u0435\\u0440\"}, \"rejection_reason\": null, \"comment\": null, \"files\": [], \"survey_answer_of_type_a\": null, \"employment_date\": null, \"calendar_event\": null, \"created\": \"2020-04-15T08:54:39+03:00\", \"vacancy_group_action\": null, \"source\": null, \"applicant\": {\"photo\": null, \"first_name\": \"Test\", \"last_name\": \"Testov\", \"middle_name\": null, \"birthday\": null, \"position\": null, \"company\": null, \"money\": null, \"phone\": null, \"email\": null, \"skype\": null, \"questionary\": null, \"id\": 71}, \"questionary\": {}}, \"author\": {\"id\": 15, \"name\": \"Vitaly Glibin\", \"email\": \"test@example.com\", \"meta\": null}, \"account\": {\"id\": 30, \"name\": \"Test organization\"}}";
      
      $sig = hash_hmac('sha256', $payload, '123123123');
      

    print($sig);
```

Выведет `ea03e7fda17b8034fbf05fef2a0553dbc6d8e373c981aeecfd3d88bfa6e42a1c`, что аналогично результату в примере на Python

**Comment by Trahtenberg** [comment]
Вы видимо не хотите решить проблему на своей стороне. Тело вебхук приходит БЕЗ пробелов, вы формируете с пробелами, что тут не понятного.

**Comment by ArturArutyunov** [comment]
У меня такая же проблема.
Php получает тело запроса, в котором нет пробелов после разделительных символов : и ,
Таким образом проверяется JSON вида 
`$payload = "{\"event\":{\"id\":108,\"type\":\"STATUS\",\"vacancy\":{\"id\": 6,\"applicants_to_hire\":1,\"position\":\"Test vacancy\", .......`
Эта строка отличается от того, что подписано на стороне Huntflow

**Comment by glibin** [comment]
> Вы видимо не хотите решить проблему на своей стороне.

Потому что проблема не на нашей стороне и у десятков клиентов все хорошо с проверкой подписи.

Повторюсь: Хантфлоу подписывает тело запроса (байты), которое передается в запросе на вебхук. То, что ваш PHP-фреймворк работает с телом запроса (вероятно, сначала превращая его из байтов в JSON-объект), а потом вы этот JSON-объект превращаете обратно в байты и пытаетесь проверить подпись, с наибольшей вероятностью не может гарантировать изначальную последовательность байтов, которую вам передал и подписал Хантфлоу.

Надеюсь, я максимально понятно объяснил.

**Comment by Trahtenberg** [comment]
Да, вы правы.
