### ISSUE TITLE
Не приходят значения полей с вебхук по вакансии

### ISSUE THREAD

**Issue by Trahtenberg** [huntflow/api#188]
Здравствуйте,
не приходят значение из текущих полей, хотя в лк они заполнены.
"position": null,
"body": null,
"requirements": null,
"conditions": null,

**Comment by glibin** [comment]
Пришлите, пожалуйста, заголовок `X-Huntflow-Delivery` для проблемных хуков.

**Comment by Trahtenberg** [comment]
537df6a3-177a-444e-9efb-0b839a2c13d2
7d1f5951-418d-4510-bcf4-b9e52f8dc838
7f8c472c-b6c2-4816-81ac-07866b2a2f22
51a1834f-fa06-47c3-b97e-723d4744fee3 - тут данные прошли

**Comment by glibin** [comment]
Проверили логи:

> 537df6a3-177a-444e-9efb-0b839a2c13d2

данные по позиции есть (событие CREATED)

> 7d1f5951-418d-4510-bcf4-b9e52f8dc838

данные по позиции есть (событие JOIN)

> 7f8c472c-b6c2-4816-81ac-07866b2a2f22

данные по позиции есть (событие CREATED)

> 51a1834f-fa06-47c3-b97e-723d4744fee3 

данные по позиции есть (событие OPEN) + body, requirements, conditions


Поля body, requirements, conditions приходят только на события EDIT и OPEN. Документацию уточним, спасибо.

**Comment by Trahtenberg** [comment]
А почему они не приходят при создании вакансии?

**Comment by glibin** [comment]
> А почему они не приходят при создании (CREATE)?

Вероятно, для оптимизация объема передаваемых данных. Сейчас это так работает.

**Comment by Trahtenberg** [comment]
Хорошо, я привязал данные из OPEN.
Надеюсь в ближайшее время изменений не не предвидится.
Благодарю.
