### ISSUE TITLE
Вопрос по вебхуку при объединении дубликатов

### ISSUE THREAD

**Issue by ilyha** [huntflow/api#189]
Добрый день! 
В вебхуке с типом "DOUBLE", информация об учетной записи которая остается в системе после объединения есть в поле "applicant". А как узнать ID записи которая после объединения будет удалена?

**Comment by glibin** [comment]
Для удаленной записи приходит отдельное событие REMOVED

**Comment by ilyha** [comment]
Отдельное событие на удаление я видел, но тогда получается чтобы разобраться что кандидат А объединен  с кандидатом  Б надо отслеживать цепочку хуков удаление, объединение. Что сложно, хотелось бы именно в сообщении с типом DOUBLE видеть идентификаторы обеих учеток

**Comment by ilyha** [comment]
тогда уточняющий вопрос в теле запроса есть поле sourse, что в нем хранится при типе "DOUBLE"?

**Comment by glibin** [comment]
Там хранится идентификатор удаленного кандидата, но на это не стоит завязываться, так как он может поменяться в будущем.
