### ISSUE TITLE
Добавить поле modified

### ISSUE THREAD

**Issue by bzvyagintsev** [huntflow/api#19]
Можете в ответ на запросы сущностей добавить поле modified?

**Comment by glibin** [comment]
Богдан, уточните, какую задачу вы хотите решить?

**Comment by bzvyagintsev** [comment]
При получении данных от АПИ, понимать, изменился ли объект

**Comment by glibin** [comment]
Спасибо за предложение, обсудим с командой о возможности имплементации.

Сейчас для получения информации об изменениях можно использовать вебхуки: https://github.com/huntflow/api/blob/master/ru/webhooks.md
