### ISSUE TITLE
Изменение этап подбора

### ISSUE THREAD

**Issue by ilyha** [huntflow/api#190]
Каким методом изменить статус кандидата на заявку?
На данный момент могу только устанавливать его в методе [Добавление кандидата на вакансию](https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E)

**Comment by glibin** [comment]
Добрый день!

Ответ есть здесь: https://github.com/huntflow/api/issues/66

**Comment by ilyha** [comment]
спасибо
