### ISSUE TITLE
Создание справочника через API

### ISSUE THREAD

**Issue by FreeRiderBysik** [huntflow/api#191]
Добрый день. Я из Синимекс.
Мне надо проверить работу со справочниками через API. На демо ни одного справочника нет. 
Нашёл что я могу создать справочник сам через API. Сделали пользователся "API Robot" управляющим рекрутером для этого.
Оправляю на https://api.huntflow.ru/account/48039/dictionary POST запрос:
{
    "code": "company_name",
    "name": "Компания",
    "items": [
        {"name": "АО Синимекс-Информатика", "foreign": "0001"},
        {"name": "ООО Синимекс-Консалтинг", "foreign": "0002"},
        {"name": "Синимекс-ДатаЛаб", "foreign": "0003"}
    ]
}

Получаю ответ:
{
    "status": "ok",
    "payload": {
        "task_id": "386bf14b-bcc3-41e6-9da5-f0efc1c01b5e"
    },
    "meta": {
        "data": {
            "code": "company_name",
            "name": "Компания",
            "items": [
                {
                    "name": "АО Синимекс-Информатика",
                    "foreign": "0001"
                },
                {
                    "name": "ООО Синимекс-Консалтинг",
                    "foreign": "0002"
                },
                {
                    "name": "Синимекс-ДатаЛаб",
                    "foreign": "0003"
                }
            ]
        },
        "account_id": 48039
    }
}

Далее иду смотреть статус данной задачи, а там:
{
    "created": 1595577699.3628216,
    "updated": 1595577699.3904645,
    "state": "failed",
    "states_log": [
        {
            "state": "enqueued",
            "timestamp": 1595577699.3628216,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.358732,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.36448,
            "comment": "",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.3652737,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.366597,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.3673542,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3688211,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.369736,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3771274,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.377929,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3794324,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.380103,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3813,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.3821619,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.383184,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.3839185,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3850842,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.385918,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3873496,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "inprogress",
            "timestamp": 1595577699.3881514,
            "comment": null,
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "enqueued",
            "timestamp": 1595577699.3893461,
            "comment": "too_freq",
            "datetime": "2020-07-24T08:01:39+00:00"
        },
        {
            "state": "failed",
            "timestamp": 1595577699.3904645,
            "comment": "Job failed for 10 times and would be removed from the queue",
            "datetime": "2020-07-24T08:01:39+00:00"
        }
    ],
    "created_datetime": "2020-07-24T08:01:39+00:00",
    "updated_datetime": "2020-07-24T08:01:39+00:00",
    "task_id": "386bf14b-bcc3-41e6-9da5-f0efc1c01b5e"
}

Подскажите, что я делаю не так?

**Comment by glibin** [comment]
Добрый день!

Спасибо за сообщение об ошибке. Проблема вызвана ошибкой на нашей стороне. Мы уже исправляем проблему и сообщим о результате в данном тикете.

**Comment by glibin** [comment]
Доброе утро! Проблема исправлена. Попробуйте, пожалуйста, еще раз.

**Comment by FreeRiderBysik** [comment]
Спасибо! Справочник доступен.

**Comment by FreeRiderBysik** [comment]
Спасибо! Справочник доступен.
