### ISSUE TITLE
Дубликаты кандидатов с одинаковыми id

### ISSUE THREAD

**Issue by MadPigeon** [huntflow/api#192]
Есть объекты типа `applicants` с id `9074972, 8520753, 9160189`, где get возвращает по два объекта. json-объекты не идентичны, как и объекты external.
В чём может быть причина подобного? На чьей стороне проблема?

**Comment by glibin** [comment]
Добрый день!

Можете уточнить в чем различие? Быстрый просмотр показал, что это разные кандидаты, поэтому вопрос про идентичность непонятен.

**Comment by MadPigeon** [comment]
На каждый из id возвращается по _два_ почти что идентичных объекта кандидата, проблема в этом, тут все три примера проявления проблемы

**Comment by glibin** [comment]
Добрый день!

К сожалению, так и не поняли суть проблемы. Могли бы привести более детальные примеры?

**Comment by MadPigeon** [comment]
Ошибка не повторилась при повторном запросе, так что не смогу предоставить данные, которые составляли проблему.
