### ISSUE TITLE
Функционал добавления рекрутера к вакансии

### ISSUE THREAD

**Issue by silischev** [huntflow/api#195]
Здравствуйте.
Обещали добавить данный функционал в течении июня - https://github.com/huntflow/api/issues/175
На сегодняшний день он уже работает?

**Comment by glibin** [comment]
Добрый день!

Функционал пока не готов. 
Я сообщу о более точном сроке до конца сегодняшнего дня.

**Comment by glibin** [comment]
Уточнил: задача появится на продакшне до следующего четверга (13.08)

**Comment by silischev** [comment]
Спасибо за информацию!
