### ISSUE TITLE
Проблема с получением справочника подразделений

### ISSUE THREAD

**Issue by FreeRiderBysik** [huntflow/api#197]
Добрый день.

Я из Синимекс. Делаю задачку по автоматизации работы с офферами.
У нас в оффере есть поле "Подразделение" где пользователь выбирает подразделение из списка, в JSON это выглядит как  
... "account_division": 23419, ...
Т.е. id значения из справочника account_division (так же как и другие справочные значения, например для company_name).
Но проблема в том, что справочник account_division через API запросить не получается. 
 404 Not Found: [{"errors": [{"type": "common.account_dictionary", "value": ["Unknown dictionary"]}]}]

Посмотрев загрузку страницы вижу, что AccountDivisions загружается не как другие справочники, а со всеми настройками аккаунта:
![image](https://user-images.githubusercontent.com/1512168/89886755-d4078100-dbd5-11ea-9a55-204489413912.png)
Хотя по структуре похож на обычный справочник.

Подскажите, как быть, какие есть варинаты?
Мне надо из оффера тянуть название подразделения.

**Comment by glibin** [comment]
Добрый день!

Для получения справочника подразделений нужно использовать запрос:

GET `/account/<account_id>/divisions`

**Comment by FreeRiderBysik** [comment]
Спасибо!
