### ISSUE TITLE
Не работает постраничный вывод кандидатов

### ISSUE THREAD

**Issue by 1ton** [huntflow/api#198]
Изменение значения входного параметра page никак не влияет на результат выдачи запроса https://api.huntflow.ru/account/${accountId}/applicants?page=${pageNumber}

**Comment by glibin** [comment]
Добрый день!

Была выявлена и уже исправлена проблема во вчерашнем релизе.

Прошу прощения за возникшие неудобства.

**Comment by 1ton** [comment]
Проверил - теперь работает, спасибо.
