### ISSUE TITLE
Метод работы с пользователями системы

### ISSUE THREAD

**Issue by DStelmash** [huntflow/api#199]
Добрый день! Подскажите есть ли в системе готовые методы API по работе с пользователями. Задача стоит следующая. В рамках создания по API новой вакансии в нее необходимо так же добавлять пользователей, которые будут работать над данной вакансией. Список пользователей можем передавать так же с запросом на создание вакансии.

**Comment by glibin** [comment]
Добрый день!

Ответ есть здесь: https://github.com/huntflow/api/issues/155

**Comment by DStelmash** [comment]
спасибо! в принципе это то что нужно
