### ISSUE TITLE
Как авторизоваться с использованием токена?

### ISSUE THREAD

**Issue by k911a** [huntflow/api#20]
Прошу привести пример POST запроса для авторизации с использованием токена. Вдоль и поперек перечитал руководство - не понятно на какой адрес делать запрос. Так же не понятно, на какой адрес делать GET запрос для тестирования авторизации. Написано "использовать метода /me" - но на какой адрес делать запрос?

**Comment by glibin** [comment]
Вероятно, вам был предоставлен персональный токен. Подробнее об его использовании моно почитать здесь: https://github.com/huntflow/api/blob/master/ru/personal_token.md

**Comment by k911a** [comment]
Я это уже читал. Приведите пример POST запроса с использованием персонального токена.

**Comment by glibin** [comment]
Пример на языке Python:


```python
files = {'file': ('resume.pdf', open('./resume.pdf', 'rb'), 'application/pdf')}

headers = {
    'Authorization': 'Bearer <personal_token>',
    'User-Agent': 'MyApp/1.0 (hello@huntflow.ru)',
    'X-File-Parse': 'true'
}

print(requests.post('https://api.huntflow.ru/account/202/upload', headers=headers, files=files).json())
```

**Comment by k911a** [comment]
Интересует на PHP. Просто авторизация. Без отправки файла. Пробую через Postman.

Делаю POST запрос на адрес:
https://api.huntflow.ru/account/18557

Заголовки:
Authorization: dbd8fbe1...
User-Agent: App/1.0 (hello@huntflow.ru)

Почту естественно пишу свою. Что тут не так? На какой адрес следует делать запрос?

**Comment by glibin** [comment]
> Интересует на PHP. Просто авторизация. Без отправки файла. Пробую через Postman.

С PHP помочь не сможем, к сожалению.

> 
> Делаю POST запрос на адрес:
> https://api.huntflow.ru/account/18557

Но этот url не принимает POST запросы. Попробуйте отправить на любой другой url из документации, например: https://github.com/huntflow/api/blob/master/ru/applicants.md#add

> 
> Заголовки:
> Authorization: dbd8fbe1...
> User-Agent: App/1.0 ([hello@huntflow.ru](mailto:hello@huntflow.ru))
> 
> Почту естественно пишу свою. Что тут не так? На какой адрес следует делать запрос?
