### ISSUE TITLE
Вопросы к API

### ISSUE THREAD

**Issue by Pavel-CBUP** [huntflow/api#200]
Добрый день.

Воспользовался вашим API и у меня возник ряд вопросов. Ответа я не нашел.

1. можно ли получить список всех вакансий сразу ( не по-странично)?
1.1. не понял как работает page=N&count=M а конкретно count=M. как не вбиваю значение он все равно показывает только 30.
2. можно ли получить вакансии на дату?  т.е список вакансий за период времени.
3. можно ли получить статус вакансии на дату? т.е какой статус у вакансии был месяц назад, или хранится только актуальная дата?

**Comment by glibin** [comment]
Добрый день!

> можно ли получить список всех вакансий сразу ( не по-странично)?

нет

> не понял как работает page=N&count=M а конкретно count=M. как не вбиваю значение он все равно показывает только 30.

максимальное количество вакансий на страницу – 30

**Comment by Pavel-CBUP** [comment]
-нет
Жалко... это создает мне много проблем для загрузки в нашу аналитическую систему)

-максимальное количество вакансий на страницу – 30
так он и меньше не выводит, такое ощущение как будто count=M вообще не работает)

-Информацию можно получить в данном тикете: #165
спасибо. но вроде не совсем то что я хотел увидеть) но теперь понимаю как это работает.

ок. закрываю. спасибо)
