### ISSUE TITLE
Редактирование справочников

### ISSUE THREAD

**Issue by Ilinalexaer** [huntflow/api#201]
Добрый день!

Необходимо ли при внесении изменений в справочник (метод PUT /account/{account_id}/dictionary/{dictionary_code}) передавать все значения справочника или можно передать только изменяемое значение/дополнительное значение?

**Comment by aleks-v-k** [comment]
Добрый день. Нужно передавать все актуальные значения справочника. Если каких-то значений нет, то это интерпретируется как их удаление.

**Comment by Ilinalexaer** [comment]
Спасибо!

**Comment by fominua** [comment]
> Добрый день. Нужно передавать все актуальные значения справочника. Если каких-то значений нет, то это интерпретируется как их удаление.

А сейчас уже не так? Ожидалось как раз такое поведение. Однако не могу перезаписать значения в справочнике или изменить их. Справочник только пополняется новыми значениями.
