### ISSUE TITLE
Добавить в лог инфо об изменениях полей кандидатов

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#203]
Сейчас есть [логи кандидата](https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D0%BC
). В них есть куча полезной информации. Но не хватает информации о том, что кто-то поменял значения каких-то полей кандидата, например компанию или ожидаемую зп. Было бы круто, если бы эту информацию тоже можно было посмореть.

**Comment by frontdevops** [comment]
Здравствуйте! Поддерживаю Николая. Нам нужно видеть что кто-то внес изменения. Например, есть хук на добавление комментария и его удаление. Но вот если кто-то поменял комментарий - то хук не срабатывает. Так же хочется видеть все изменения которые вообще происходят, всю активность, вплоть до переписки через мессенджеры и почту

**Comment by glibin** [comment]
Добрый день!

> Было бы круто, если бы эту информацию тоже можно было посмореть.

К сожалению, такая информация пока недоступна в API и не планируется к разработке в ближайшее время.
