### ISSUE TITLE
Исправить метод получения списка вакансий для внешнего сайта

### ISSUE THREAD

**Issue by splatglobal** [huntflow/api#204]
**Здравствуй**, дорогая команда разработки!

Не так давно, а именно 24 марта 2020 года мы вместе с вами настроили получение списка вакансий на наш сайт [https://splat.ru/team](https://splat.ru/team), путём:
с вашей стороны добавлением поля "Выгружать вакансию на splat.ru"
![image](https://user-images.githubusercontent.com/70330223/91451300-f5c76000-e885-11ea-8cc1-9ffea3a53bf9.png)
с нашей стороны написанием скрипта для "расшивания" приходящих данных на сайт в соответствующую категорию на страницу [https://splat.ru/team](https://splat.ru/team).

Сегодня, 27.08 в 16:40 по МСК коллеги из HR сказали, что на нашем сайте количество вакансий отличается от того, что имеется в личном кабинете [Huntflow](https://huntflow.ru/my/splat_hr),

Помогите разобраться, где проблема?

**Comment by chistyakov** [comment]
Здравствуйте, @splatglobal !

Я уточнил настройки для организации Splat.
У Вас подключен АПИ и не подключена платформа откликов.

Судя по логам на стороне Хантфлоу Ваш скрипт периодически получает список вакансий.
Для этого используется соответсвующий метод АПИ Хантфлоу. Его описание: https://github.com/huntflow/api/blob/master/ru/vacancies.md#vacancies

Для проверки данных, возвращаемых Хантфлоу, вы можете вручную отправить запрос.
Пример запроса:
```
curl --location --request GET \
'https://api.huntflow.ru/account/33768/vacancies?opened=1&page=1&total=10' \
--header 'Authorization: Bearer <token>'
```

Возвращает ли Хантфлоу вакансии, которых нет на https://splat.ru/team ?

**Comment by chistyakov** [comment]
Обратите внимание, что Хантфлоу предоставляет альтернативный способ публикации вакансии на карьерном сайте.

Его описание: https://github.com/huntflow/api/blob/master/ru/responses.md

При этом подходе Ваш карьерный сайт должен реализовать описанный HTTP АПИ
