### ISSUE TITLE
Битая ссылка в документации

### ISSUE THREAD

**Issue by eugenyProchan** [huntflow/api#205]
На странице [справочники](https://github.com/huntflow/api/blob/master/ru/dictionaries.md ).

Внизу битая ссылка вот в этой строке
где payload.task_id –– уникальный идентификатор задачи. [Как отслеживать статус задачи](https://github.com/huntflow/api/blob/master/ru/delayed_tasks.py)

сейчас там https://github.com/huntflow/api/blob/master/ru/delayed_tasks.py выдает 404.

Поправьте, пожалуйста.

**Comment by aleks-v-k** [comment]
Правильная ссылка: https://github.com/huntflow/api/blob/master/ru/delayed_tasks.md
Спасибо, поправим.
