### ISSUE TITLE
Проблема с вебхуками

### ISSUE THREAD

**Issue by toxaw** [huntflow/api#207]
Встретил такой баг, что у вас вебхуки шлих запросы асинхронно - из-за этого происходит задвоение данных на конечном сервере 
![ZTQ4Mzd](https://user-images.githubusercontent.com/33651909/92271071-d5377f80-eeef-11ea-93fc-a58d997046f1.png)

**Comment by glibin** [comment]
Добрый день!

Это разные типы событий, которые создаются одновременно при создании вакансии. Реагировать вы можете только на нужный тип события (например, на открытие вакансии).

**Comment by toxaw** [comment]
Добрый день! на самом деле мы реагируем на все события и нам важно знать все изменения, поэтому не можем выбрать конкретное. Также от вас прилетаю параллельные запросы, даже с учетом наших внутренних блокировок задвоения это не спасает. Одновременно в одно и тоже время создаются 2 вакансии

**Comment by toxaw** [comment]
Добрый день, при создании вакансии всегда приходит 3 события JOIN CREATED и OPEN?

**Comment by glibin** [comment]
> Добрый день, при создании вакансии всегда приходит 3 события JOIN CREATED и OPEN?

Может прийти больше событий JOIN, если при создании вакансии передается большее число работающих по вакансии рекрутеров (кол-во JOIN = кол-ву рекрутеров)
