### ISSUE TITLE
Получение списка заявок на вакансии

### ISSUE THREAD

**Issue by dorofema** [huntflow/api#208]
Добрый день! Настраиваем интеграцию с BI. Получаем данные через API, столкнулись с неожиданным результатом запроса при получении заявок на вакансии. Если запрашивать весь список, то заявок как будто нет, результат нулевой. В то же время, если запросить заявку, указав ID конкретной вакансии, то заявка возвращается. В чём может быть проблема? Как получить весь список заявок?

**Comment by dorofema** [comment]
Описание API брали отсюда:
https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#vacancy-request-list

Запрос `GET /account/{account_id}/vacancy_request` возвращает пустой список (`{items:[]}`)
Запрос `GET /account/{account_id}/vacancy_request?vacancy_id={vacancy_id}` возвращает заявки на вакансии, как ожидается.
Я подразумеваю, что раз заявки на вакансии есть, метод `GET /account/{account_id}/vacancy_request` должен вернуть их все.
Я что-то неправильно понимаю, или API ведет себя неверно?

**Comment by glibin** [comment]
Добрый день!

Метод `GET /account/{account_id}/vacancy_request` возвращает только заявки, которые не взяты в работу (не привязаны к вакансии). Поэтому может возвращаться пустой список. 

К сожалению, в API пока нет возможность получать все заявки на вакансии.

**Comment by dorofema** [comment]
Спасибо за ответ!
Конечно, очень хотелось бы, чтобы такое АПИ появилось.

К слову, в описании АПИ это не прозрачно (что без указания вакансии возвращаются только не привязанные заявки), как мне кажется, будет понятнее, если это указать.
