### ISSUE TITLE
Добавление рекрутеров в вакансию

### ISSUE THREAD

**Issue by DStelmash** [huntflow/api#209]
Добрый день! Настраиваем интеграцию с амоCRM для кадрового агентства. При создании вакансии в HF по API необходимо в список тех кто может работать с вакансией добавлять список рекрутеров, по умолчанию у нас сейчас все заявки вешаются на APIбота и по факту сотрудники которые были выбраны для работы с вакансией не видят ее, приходится открывать вакансию и вручную добавлять рекрутеров. В текущих методах есть описание для передачи списка сотрудников которые работают над вакансией, но только это реализовано не для кадрового агентства. Как нам можно автоматически добавлять сотрудников к вакансии?

**Comment by glibin** [comment]
Добрый день!

При создании вакансии можно передать параметр coworkers со списком работающих по ней рекрутеров.

Чуть подробнее здесь: https://github.com/huntflow/api/issues/155

**Comment by DStelmash** [comment]
Данный параметр доступен для компаний КАДРОВЫЕ АГЕНТСТВА?

**Comment by glibin** [comment]
Да, этот параметр также должен быть доступен для кадровых агентств. Уточним и обновим документацию.

**Comment by DStelmash** [comment]
понял. Спасибо

**Comment by DStelmash** [comment]
Поробовали написать запрос с учетом указанного параметра. Но в вакансию рекрутер не подвязался 

Код запроса
{
  "client_vacancy_request": 26993,
  "deadline": "2030-09-03",
  "applicants_to_hire": 2,
  "priority": 1,
  "body": "",
  "requirements": "",
  "conditions": "",
  "coworkers": [
    22090
  ]
}
