### ISSUE TITLE
Эндпойнт vacancy_request

### ISSUE THREAD

**Issue by mikhaylovma** [huntflow/api#21]
Добрый день! 
Почему-то не отдает список заявок на вакансии по сабжевому эндпойнту.
Заявка точно есть в интерфейсе, а в апи пустой массив items
Если в интерфейсе посмотреть id заявки и подставить в апи (vacancy_request/{id}) - получаем server_error

**Comment by mikhaylovma** [comment]
проблема на всех аккаунтах, но вот конкретный:
аккаунт 20727
заявка 6498

**Comment by mikhaylovma** [comment]
Сюда же - в документации описаны методы GET и POST
При POST мы передаем список полей и указываем схему
При GET же нам переденные ранее поля не возвращаются, кроме Position - money, hard_skills и тд
Это очень печально :(
Можно ли как-то их все же получать в GET?

**Comment by glibin** [comment]
Добрый день!

Уточните и пришлите, пожалуйста, какие запросы вы отправляете (без указания токена), какой ответ получаете и какой ожидаете?

**Comment by mikhaylovma** [comment]
https://api.huntflow.ru/account/АККАУНТ/vacancy_request
Ожидаю получить одну запись, описанную в vacancy_requests.md
Получаю 
{
    "items": []
}

https://api.huntflow.ru/account/АККАУНТ/vacancy_request/ID
Получаю 
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}
