### ISSUE TITLE
Фильтрация списка кандидатов

### ISSUE THREAD

**Issue by dorofema** [huntflow/api#210]
Добрый день!

Пытаюсь использовать АПИ получения [списка кандидатов](https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D0%B2).
Постраничный список возвращается нормально, но при попытке фильтровать по статусу и/или вакансии - всегда пустой результат (total: 0).

К примеру, `https://api.huntflow.ru/account/3760/applicants?status=18848` (Вышел на работу) возвращает пустой список, хотя если запрашивать без фильтра, то в результатах есть кандидаты с этим статусом.
Указание одновременно и статуса, и вакансии не помогает.

Я недопонимаю синтаксис или логику фильтрации? Подскажите, пожалуйста.

**Comment by glibin** [comment]
Добрый день!

Это может быть связано со спецификой работы фильтра (по умолчанию, он показывает только кандидатов по вакансиям, на которых работает текущий пользователь (в данном случае, API Robot)).

Пришлите, пожалуйста, вывод запроса `/me`, мы поменяем настройку, чтобы отдавались данные по всем открытым вакансиям.

**Comment by dorofema** [comment]
Добрый день!

Результат запроса /me:

{
    "name": "API Robot",
    "position": "",
    "email": "api3760@huntflow.ru",
    "phone": "",
    "locale": "ru_RU"
}

Есть есть ещё какие-то ограничения видимости для данного пользователя - снимите, пожалуйста.

**Comment by glibin** [comment]
Готово, попробуйте выполнить запрос.
