### ISSUE TITLE
История изменений квот по найму

### ISSUE THREAD

**Issue by paul23093** [huntflow/api#211]
Подскажите, пожалуйста, как можно получить историю изменений квот по найму по конкретной вакансии?
Пытался через vacancy_id/quotas, но тут всегда только последняя информация, нет истории.

Пример: https://api.huntflow.ru/account/4405/vacancy/2382558/quotas

Ответ:

{'2382558': {'items': [{'id': 390237,
    'vacancy_frame': 231217,
    'vacancy_request': None,
    'created': '2020-04-29 19:16:28',
    'changed': '2020-09-11 18:00:28',
    'applicants_to_hire': 14,
    'deadline': None,
    'already_hired': 1,
    'closed': None,
    'work_days_in_work': 93,
    'work_days_after_deadline': None,
    'removed': None,
    'account_info': {'id': 38682,
     'email': '*',
     'name': '*'}}],
  'total': 1,
  'page': 1,
  'count': 30}}

Заранее спасибо!

**Comment by glibin** [comment]
Добрый день!

Изменение квот можно получать через вебхуки https://github.com/huntflow/api/blob/master/ru/webhooks.md#vacancy

К сожалению, документация немного устарела. Данные по квотам будут в объекте `fill_quotas` у объекта `event.vacancy`

**Comment by dorofema** [comment]
Добрый день! Аналогичный вопрос, но по логам изменений статуса вакансий. Как их можно получить?

**Comment by paul23093** [comment]
@dorofema Я так понимаю, Вам нужен такой запрос:
https://api.huntflow.ru/account/{account_id}/vacancy/{vacancy_id}/logs
