### ISSUE TITLE
Некорректно загружается файл (NodeJS)

### ISSUE THREAD

**Issue by slavanchikus** [huntflow/api#212]
Файл загружается, но открыть его не получается
Вот ссылка загруженного файла - https://store.huntflow.ru/uploads/named/v/q/i/vqirix6k4eyibftlhj2avnt443rdwt4i.pdf/is9l44qfo6l3unf2r8w27j.pdf?s=jhY8nH0ygnl-E9jVf64y2Q&e=1600312948

    import fetch from 'node-fetch'
    import FormData from 'form-data'
    
    export const uploadFile = (file) => {
        const form = new FormData()
    
        const fileStream = fs.createReadStream(file)
    
        form.append('file', fileStream)
    
        return fetch(`https://api.huntflow.ru/account/${account_id}/upload`, {
            method: 'POST',
            headers: {
                Authorization: 'Bearer GGWP',
            },
            body: form
        })
            .then((res) => res.json())
            .then((res) => {
                if (res.errors || res.error) {
                    throw new Error(JSON.stringify(res))
                } else {
                    return res
                }
            })
        .    catch((err) => {
                throw err
            })
    }

ответ:
{"name":"is9l44qfo6l3unf2r8w27j.pdf","url":"https://store.huntflow.ru/uploads/named/v/q/i/vqirix6k4eyibftlhj2avnt443rdwt4i.pdf/is9l44qfo6l3unf2r8w27j.pdf?s=jhY8nH0ygnl-E9jVf64y2Q&e=1600312948","content_type":"application/pdf","id":10192046}

**Comment by glibin** [comment]
Добрый день!

При переходе по ссылке отдается ошибка 410 Gone – это значит, что закончился срок действия ссылки.

Уточните, вы открываете файл сразу после загрузки?

**Comment by slavanchikus** [comment]
упс, моя ошибка в роуте была, разобрался в проблеме)
