### ISSUE TITLE
Не получается у кадрового агентства передать параметр coworkers

### ISSUE THREAD

**Issue by DStelmash** [huntflow/api#213]
Попробовали написать запрос с учетом указанного параметра. Но в вакансию рекрутер не подвязался 

Код запроса
{
  "client_vacancy_request": 26993,
  "deadline": "2030-09-03",
  "applicants_to_hire": 2,
  "priority": 1,
  "body": "",
  "requirements": "",
  "conditions": "",
  "coworkers": [
    22090
  ]
}

_Originally posted by @DStelmash in https://github.com/huntflow/api/issues/209#issuecomment-694367286_

**Comment by glibin** [comment]
Добрый день!

А пришлите идентификатор созданной вакансии?

**Comment by DStelmash** [comment]
https://huntflow.ru/my/odgers#vacancy/2542395
https://huntflow.ru/my/odgers#vacancy/2542396
вот две ссылки на вакансии которые создавались с подобным запросом

**Comment by glibin** [comment]
Доброе утро! 

Обнаружили проблему на нашей стороне. Исправление будет доступно до конца недели.

**Comment by DStelmash** [comment]
Очень ждем исправлений!

**Comment by DStelmash** [comment]
Подскажите есть ли информация по исправлениям?

**Comment by glibin** [comment]
Добрый день!

Исправление должно выйти на этой неделе. 
Как только исправление будет выпущено, я напишу в данном тикете.

**Comment by DStelmash** [comment]
Примерно можете сориентировать, чтобы мы могли планировать работу разработчиков со своей стороны

**Comment by glibin** [comment]
Релиз должен быть в среду вечером. Если будет раньше, то я напишу.

**Comment by DStelmash** [comment]
спасибо!

**Comment by glibin** [comment]
Добрый день!

Попробуйте, пожалуйста, выполнить запрос с `coworkers`

**Comment by DStelmash** [comment]
ок, о результат сообщю

**Comment by DStelmash** [comment]
теперь данные о рекрутерах подтягиваются. Спасибо
