### ISSUE TITLE
Не приходит событие на изменение данных вакансии

### ISSUE THREAD

**Issue by toxaw** [huntflow/api#215]
Есть проблема, при изменении вот этих 
![image](https://user-images.githubusercontent.com/33651909/94122797-a90e7f00-fe5b-11ea-9385-ce304567cfa0.png)
полей, не приходит событие об изменении вакансии. Но если мы поменяем видимость, то изменения приходят.

**Comment by glibin** [comment]
Добрый день!

Нам потребуется некоторое время на изучение проблемы. Вернемся с рассказом как только будет информация.

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ.

Проблема, действительно, присутствует. Передали коллегам на изучение и исправление.

**Comment by razorbet** [comment]
Добрый день! Подскажите проблема исправлена?

**Comment by glibin** [comment]
Добрый день!

Проблема будет исправлена в течение ближайших двух недель.
