### ISSUE TITLE
Отломался account_id

### ISSUE THREAD

**Issue by theabdyko** [huntflow/api#216]
Здравствуйте

Сейчас работаю с вашей API
У нас по какой то причине отвалился id аккаунта на аккаунте к которому привязан наш токен.
Без данного id не можем получить доступ к различным эндпоинтам, кроме как
- https://api.huntflow.ru/me
- https://api.huntflow.ru/accounts

Прилагаю коды запроса:

-----------------------------------------------------------------------------------------------
## Запрос на получение информации по аккаунту:
```
curl --location --request GET 'https://api.huntflow.ru/me' \
--header 'Authorization: Bearer my_token' \
--header 'User-Agent: App/1.0 (incaseoffire@example.com)'
```

Ответ:
```
{
    "name": "API Robot",
    "position": "",
    "email": "test@mail.test",
    "phone": "",
    "locale": "ru_RU"
}
```
### Как видно - нету id 

-----------------------------------------------------------------------------------------------

## Запрос на получение информации о доступных организациях:
```
curl --location --request GET 'https://api.huntflow.ru/accounts' \
--header 'Authorization: Bearer my_token' \
--header 'User-Agent: App/1.0 (incaseoffire@example.com)'
```

Ответ:
```
{
    "items": []
}
```
### Как видно - список организаций тоже пуст 
-----------------------------------------------------------------------------------------------

Не понятно - почему так произошло - это сбой в системе или наши ребята через веб интерфейс хантфлоу что-либо заблокировали. Так же остается вопрос как добавить организации доступные данному аккаунту.

Заранее спасибо, жду от вас:
- Ответа, как восстановить id для доступов к эндпоинтам
- Как добавить организации доступные данному аккаунту.
- Желательно причину (если это произошло на нашей стороне), чтоб мы больше ничего не ломали.

**Comment by glibin** [comment]
Добрый день!

Уточните, к какой организации был привязан данный токен?

**Comment by theabdyko** [comment]
@glibin 
Компания "Mad devs"

**Comment by glibin** [comment]
Вашими коллегами был удален технический аккаунт API Robot из организации, связанный с токеном.
Вы можете обратиться к коллегам из подбора, чтобы они обратились в поддержку (через встроенный в Хантфлоу чат) для восстановления доступа у аккаунта.

**Comment by theabdyko** [comment]
@glibin Спасибо большое )
Будем восстанавливать
