### ISSUE TITLE
Получение событий общего лога

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#217]
Было бы круто, если бы можно было получать события общего лога всех кандидатов через эндпоинт.
Это решает проблему недоставки вебхуков. Например, если отвалилась связь (заросла дыра безопасности), мы можем об этом довольно долго не знать. И не понятно, что потом делать с пропущенными записями (видимо полный синк только).
А так мы можем просто забирать данные за определенный период. В целом такое можно сделать и отдельным сервисом, но если будет такая возможность из коробки, будет замечательно.

**Comment by glibin** [comment]
Добрый день!

Спасибо за идею, но пока в ближайших планах этого нет.
