### ISSUE TITLE
Привет! Есть ряд вопросов по интеграции HuntFlow

### ISSUE THREAD

**Issue by pollykettu** [huntflow/api#218]
Наши ресурсы внутренние - закрытые для внешних ПОшек, но мы бы хотели пользоваться всеми плюшками.

Есть ряд вопросов:

1. Нужно открыть доступ для вашего сервера приложений, чтобы он туда ходил?
2. Доступ с этого сервера идёт с фиксированного или плавающего IP?
3. Текстовое описание механизма работы - сможете ли дать описание как у вас работает процесс интерграции с xchange?

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, вы уже клиент Хантфлоу или планируете приобрести?

**Comment by pollykettu** [comment]
@glibin добрый день!
Планируем, сейчас тестируем.

**Comment by glibin** [comment]
Не могли бы вы отправить письмо с вопросами с указанием названия вашей организации и менеджера по продажам со стороны Хантфлоу на адрес hello@huntflow.ru?
