### ISSUE TITLE
Обновление "Personal Notes"  у applicants

### ISSUE THREAD

**Issue by vgandzyuck** [huntflow/api#219]
Есть ли возможность обновления "Personal Notes" через предоставленный api?

**Comment by glibin** [comment]
Добрый день!

Что вы имеете ввиду?

**Comment by vgandzyuck** [comment]
Имеется ли возможность обновления блока "Personal Notes" у кандидата через api

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/22315319/94661458-bfab4f00-030f-11eb-9924-8df9fecb0eec.png">

**Comment by glibin** [comment]
Добавить комментарий можно следующим образом:

POST /account/<account_id>/applicants/<applicant_id>/log

```
{
"comment": "Комментарий"
"applicant": 5143712
}
```

**Comment by vgandzyuck** [comment]
@glibin 

<account_id> - process.env.HUNTFLOW_ACCOUNT_ID
<applicant> - applicantId

POST https://api.huntflow.ru/account/${process.env.HUNTFLOW_ACCOUNT_ID}/applicants/${applicantId}/log

Request failed with status code 404

**Comment by glibin** [comment]
пришлите полный запрос и полный ответ (удалив аутентификационную информацию)

без них нет возможности вам помочь

**Comment by vgandzyuck** [comment]
```js
const makeRequst = async (method, url, body, headers = {}) => {
  const result = await axios[method](
    `https://api.huntflow.ru/${url}`,
    body,
    {
      headers: {
        Authorization: `Bearer ${process.env.HUNTFLOW_TOKEN}`,
        ...headers,
      },
    },
  );

  return result && result.data;
};


const updateApplicantLog = async (data, applicantId) => {
  const result = await makeRequst(
    'post',
    `/account/${process.env.HUNTFLOW_ACCOUNT_ID}/applicants/${applicantId}/log`,
    data,
  );

  return result;
};
```

```js
const data = {
  comment: "test",
  files: [ 10341029 ],
  applicant: 9840173
};

process.env.HUNTFLOW_ACCOUNT_ID === 57672
```

**Comment by glibin** [comment]
1. у вас при конкатенации получается два слеша https://api.huntflow.ru//account...
2. убедитесь, что отправляете данные в формате JSON

**Comment by vgandzyuck** [comment]
Все вероно, спасибо, заработался
