### ISSUE TITLE
Авторизация и тестирование токена

### ISSUE THREAD

**Issue by k911a** [huntflow/api#22]
![12](https://user-images.githubusercontent.com/16066311/49073860-d6347b00-f24c-11e8-929c-536d3a67b806.PNG)

Пытаюсь протестировать токен, как написано у вас в руководстве тут:
https://github.com/huntflow/api/blob/master/ru/personal_token.md

Отправляю запрос через Poastman (на PHP). Возвращает ошибку. В чем причина?

**Comment by glibin** [comment]
Перед токеном необходимо указать слово "Bearer ", подробнее: https://github.com/huntflow/api/blob/master/ru/personal_token.md#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BF%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0
