### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by No0key** [huntflow/api#221]
Добрый день.
Возможно ли добавить в вебхуки по кандидатам параметр, содержащий департамент account_division .
Сейчас он есть только в вебхуках по вакансии, а нужен именно у кандидата.
И еще вопрос, возможно добавить в окно кандидата и в вебхуки по кандидату поле "Город"?
Нужно получать данные о том в каком городе будет работать кандидат при его изменении, а не вакансии
У нас уже есть поле для департамента и оно добавлено в вакансию. 
А точнее, вопрос в 3 полях вакансии: Департамент (добавлен) 2. Удаленно remotely (добавлен) 3. Город (не добавлен)
Хотелось бы указывать эти данные в вакансии один раз, а не в каждом кандидате.
По сути, эти поля не нужно отображать в интерфейсе кандидата. Заполнять их будут в вакансии.

Можете ли вы значения этих полей из вакансии просто отдавать в webhook-ах по кандидатам этой вакансии?
Например, у вас как раз в вебхуке кандидата есть объект vacanсy, в котором уже есть параметры.
http://joxi.ru/brRWMq5sOYoWym

**Comment by glibin** [comment]
Добрый день!

По вопросам добавления полей в вакансию и кандидата вы можете обратиться в техническую поддержку сервиса.

Дополнительные поля вакансии и кандидата доступны для получения в вебхуках.

**Comment by No0key** [comment]
Вы наверное неправильно поняли, мы уже писали в техническую поддержку, они направили к вам. 
У нас уже в вакансии есть 3 поля - удаленно, регион и отдел. Они прилетают в вебхуках по вакансиям. 

Но мы ловим вебхуки по кандидатам. В хуках по кандидатам есть сущность Vacancy, в которой передаётся отдел https://i.imgur.com/UnVJAkB.png (отдел вроде берётся из самой вакансии).

Вопрос: Можно ли добавить ещё 2 поля (удалённо и регион) в хуки по кандидатам? Которые так же бы брались из описания вакансии.

**Comment by glibin** [comment]
Добрый день! Эти поля должны туда попадать автоматически после внедрения справочников.
