### ISSUE TITLE
Исчезли Request ID

### ISSUE THREAD

**Issue by dorofema** [huntflow/api#222]
Добрый день!

Ранее выгружила список вакансий с помощью запроса: https://api.huntflow.ru/account/{account_id}/vacancies.
В столбце vacancy_request присутствовали ID заявок на вакансии (при наличии). 
Сейчас там пусто по всем вакансиям. Хотя заявки у вакансий есть.

Что-то изменилось? Как исправить?

**Comment by glibin** [comment]
Пришлите пример вакансии, по которой должна быть заявка, но она не возвращается в API?

Также, обращу внимание, что нужно использовать запрос на квоты для получения информации о заявках по вакансии:

https://github.com/huntflow/api/blob/master/ru/vacancies.md#квоты-к-найму
