### ISSUE TITLE
Добавить Personal Notes у кандидата

### ISSUE THREAD

**Issue by denismart** [huntflow/api#223]
При добавлении Personal Notes для кандидата ловлю следующую ошибку:
`
"errors": [
        {
            "type": "common"
        }
    ]
`

Вот curl:
```
curl --location --request POST 'https://api.huntflow.ru/account/52702/applicants/9827058/log' \
--header 'Authorization: Bearer XXX' \
--header 'User-Agent: App/1.0 (XXX@gmail.com)' \
--form 'comment=kuku' \
--form 'applicant=59268'
```

applicant_id в uri это id кандидата? 
applicant в параметрах это id комментатора? (может ли он быть "заказчиком", которые добавляются в настройках?)

**Comment by glibin** [comment]
Добрый день!

Запросы необходимо отправлять в формате JSON:

```
...
-H "Content-Type: application/json" \
-d '{"comment":"kuku","applicant":59268}' \
...
```

**Comment by glibin** [comment]
applicant_id – это идентификатор кандидата
applicant – это также идентификатор кандидата

**Comment by denismart** [comment]
> applicant_id – это идентификатор кандидата
> applicant – это также идентификатор кандидата

Так они должны быть одинаковые? Немного непонятно зачем два тогда указывать.
