### ISSUE TITLE
Получить список id заказчиков

### ISSUE THREAD

**Issue by denismart** [huntflow/api#224]
Можно ли получить список id заказчиков, те что в настройках?
И можно с помощью их id оставлять personal notes у кандидатов?

**Comment by glibin** [comment]
> Можно ли получить список id заказчиков, те что в настройках?

Ответ есть здесь: https://github.com/huntflow/api/issues/155

> И можно с помощью их id оставлять personal notes у кандидатов?

такой возможности нет
