### ISSUE TITLE
Удаляются ли загруженные, но не использованные файлы?

### ISSUE THREAD

**Issue by denismart** [huntflow/api#225]
Подскажите пожалуйста, переносим большую базу данных из другого сервиса к вам, удобнее всего нам было бы загрузить сначала файлы, а потом создать кандидатов.
Есть ли какой-то срок действия у загруженных, но не использованных файлов или они хранятся вечно?

**Comment by denismart** [comment]
Я так понимаю, что при загрузке выдается временная ссылка, но вопрос именно про file id, так как нам именно его прикреплять к кандидату при создании.

**Comment by glibin** [comment]
Загруженные файлы хранятся вечно :)
