### ISSUE TITLE
Получение данных о кандидате и рекрутере

### ISSUE THREAD

**Issue by DStelmash** [huntflow/api#226]
Добрый день! Подскажите какими методами API можно получать следующую информацию из вакансии для рекрутинговой компании:
- Название проекта
- Должность кандидата
- Компания
- Причина отказа
- Резюме кандидата (ФИО, фото, текущая позиция, опыт работы, образование)
- Статус резюме
- Комментарии/Примечания к вакансии
-Данные рекрутеров, задействованных в проекте (ФИО, должность, телефон, почта)

**Comment by glibin** [comment]
Добрый день!

Вопрос выглядит слишком широким. Можете привести примеры для каждого пункта из интерфейса?

**Comment by DStelmash** [comment]
Коллеги?!

**Comment by DStelmash** [comment]
Вы меня целенаправленно игнорируете или как? Может мне нужно завести новый запрос?

**Comment by glibin** [comment]
Добрый день!

Можете прислать скриншоты экрана из интерфейса Хантфлоу, данные по которым вы хотите получить из API?
