### ISSUE TITLE
Не парсятся файлы

### ISSUE THREAD

**Issue by slavanchikus** [huntflow/api#227]
Привет, парсинг делается, но лишь у части файлов, многие файлы парсятся коряво с потерей кодировки. Ну закачивая резюме с парсингом или без не увидели никакой разницы в анкете.
Пользовались https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0-%D0%B2-%D0%B1%D0%B0%D0%B7%D1%83

+ Еще одна проблема, в ноде не получилось даже прокинуть хедер X-File-Parse при загрузке файла, сервер отвечает ошибкой "server_error"

**Comment by glibin** [comment]
Добрый день!

Парсер Хантфлоу не дает 100% качества распознавания и может не распознавать файлы или распознавать некорректно.

При добавлении кандидата в Хантфлоу нужно использовать результат парсинга для заполнения полей и их передачи.

**Comment by slavanchikus** [comment]
Но распаристь резюме с hh.ru он же может?
Главная проблема что мы не можем добитсья такого результата https://gyazo.com/2a52df72bee526df9d96ae734c24904c
Хотя файлом передаем резюмеху с hh
Один файл передаем как https://github.com/huntflow/api/blob/master/ru/applicants.md#add так и в https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

**Comment by glibin** [comment]
Резюме с ХХ в каком формате вы передаете?

**Comment by slavanchikus** [comment]
пдф

**Comment by glibin** [comment]
Добрый день!

Можете прислать пример запроса?

Также, можно посмотреть пример реализации на Python: https://github.com/huntflow/api-response/blob/master/handler.py#L91

**Comment by slavanchikus** [comment]
```
fetch("chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js", {
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors"
}); ;
fetch("https://www.aviasales.ru/about/api/files/upload", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryUjqdfiTsBUOFLFnQ",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "cookie": "__cfduid=da0fdf581a2b57dba93386d1b55df84861603181575; auid=CtYgeV+OnAdgFwYUC6HiAg==; nuid=6a1fccb9-fd5f-43e9-80f0-0c09fedae1cf; email=slava.beliakov%40aviasales.ru; currency=rub; know_english=true; cache_visa_filter=%5B%5D; form_hint_closed=true; last_search=MOW1011LED17111; _sp_id.dc27=a63f1058-df54-4bb0-b5ad-c77575f19ebc.1603187046.5.1603291248.1603286241.437e3ea9-4105-4234-8a8c-9e1312b47491; ab-live=false"
  },
  "referrer": "https://www.aviasales.ru/about/vacancies/2557509/resume",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "------WebKitFormBoundaryUjqdfiTsBUOFLFnQ\r\nContent-Disposition: form-data; name=\"file\"; filename=\"Беляков Вячеслав Николаевич.pdf\"\r\nContent-Type: application/pdf\r\n\r\n\r\n------WebKitFormBoundaryUjqdfiTsBUOFLFnQ--\r\n",
  "method": "POST",
  "mode": "cors"
}); ;
fetch("https://www.aviasales.ru/about-assets/images/78e6dda4b6cd14eb6199bd60e8f7b157.svg", {
  "referrer": "https://www.aviasales.ru/about-assets/landing.0715dfdd59f025bf6f4b.css",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors"
});
```

ответ
{"name":"Беляков Вячеслав Николаевич.pdf","url":"https://store.huntflow.ru/uploads/named/t/x/u/txuo05toev21ga8olqudal6wpen2u9iu.pdf/%25D0%2591%25D0%25B5%25D0%25BB%25D1%258F%25D0%25BA%25D0%25BE%25D0%25B2%2B%25D0%2592%25D1%258F%25D1%2587%25D0%25B5%25D1%2581%25D0%25BB%25D0%25B0%25D0%25B2%2B%25D0%259D%25D0%25B8%25D0%25BA%25D0%25BE%25D0%25BB%25D0%25B0%25D0%25B5%25D0%25B2%25D0%25B8%25D1%2587.pdf?s=WlUaTPFBT1-l-HuoSCs-Sw&e=1603338612","content_type":"application/pdf","id":10630387}

**Comment by slavanchikus** [comment]
https://www.aviasales.ru/about/api/files/upload проксирует на вашу ручку, ничего более

**Comment by glibin** [comment]
Для парсинга данных необходимо передать заголовок X-File-Parse: true

**Comment by slavanchikus** [comment]
обновите в доке плиз, что прокидывать заголовк нужно x-file-parse, именно с маленьких букв
в браузере форм дата автоматически ловеркейсит
на ноде же - нет
неочивидная проблема если честно(

**Comment by slavanchikus** [comment]
запрос:
fetch("https://www.aviasales.ru/about/api/files/upload", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryHPTHJNsDTIQN9OIT",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "x-file-parse": "true"
  },
  "referrer": "https://www.aviasales.ru/about/vacancies/2559858/resume",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "------WebKitFormBoundaryHPTHJNsDTIQN9OIT\r\nContent-Disposition: form-data; name=\"file\"; filename=\"Кожемякина Полина.pdf\"\r\nContent-Type: application/pdf\r\n\r\n\r\n------WebKitFormBoundaryHPTHJNsDTIQN9OIT--\r\n",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});

ответ:
{"name":"Кожемякина Полина.pdf","url":"https://store.huntflow.ru/uploads/named/m/u/m/mumifly40fxpcmwz175xa9v5xsfpjp7j.pdf/%25D0%259A%25D0%25BE%25D0%25B6%25D0%25B5%25D0%25BC%25D1%258F%25D0%25BA%25D0%25B8%25D0%25BD%25D0%25B0%2B%25D0%259F%25D0%25BE%25D0%25BB%25D0%25B8%25D0%25BD%25D0%25B0.pdf?s=wEpAIJuqpfhvkUu0xZQ4tA&e=1604538596","text":"Кожемякина Полина\nЖенщина, 25 лет, родилась 3 октября 1995\n\n+7 (928) 4550060\n\nnice.ktoto@inbox.ru — предпочитаемый способ связи\n\nПроживает: Краснодар\n\nГражданство: Россия, есть разрешение на работу: Россия\n\nНе готова к переезду, готова к редким командировкам\n\nЖелаемая должность и зарплата\n\nJunior specialist\nНачало карьеры, студенты\n\n• Искусство, Развлечения, Масс-медиа\n\nЗанятость: частичная занятость\n\nГрафик работы: гибкий график, сменный график\n\nЖелательное время в пути до работы: не имеет значения\n\nОбразование\n\nВысшее\n\n2017 КубГУ\nЖурналистики\n\nКлючевые навыки\n\nЗнание языков Русский — Родной\n\nАнглийский — A1 — Начальный\n\nРезюме обновлено 4 ноября 2020 в 15:30","content_type":"application/pdf","fields":{"salary":null,"name":{"middle":null,"last":"Кожемякина","first":"Полина"},"phones":["+7 (928) 4550060"],"birthdate":{"month":10,"day":3,"precision":"day","year":1995},"experience":null,"position":"Junior specialist","email":"nice.ktoto@inbox.ru"},"id":10793782}

как выглядит все на деле в карточке
https://gyazo.com/adbc2161e37d69880acee9683fded389

как видите парсинга нет

**Comment by glibin** [comment]
Добрый день!

Я ранее оставлял комментарий с примером реализации вашего запроса.

Настоятельно рекоммендую с ним ознакомиться: https://github.com/huntflow/api-response/blob/master/handler.py#L91

**Comment by slavanchikus** [comment]
погодите, я не понимаю, вы видете респонс? файл приходит распаршенный, но в самом хантфлоу, в карточке кандидата,  парсинг файла не отображается, вы можете это пофиксить? иначе пол смысла парсинга в апи теряется

**Comment by slavanchikus** [comment]
походу есть представление
https://gyazo.com/d04a39bf6183f804b892f839da411b5c
здесь в апи доке указано что body это текст резюме и что туда нужно передавать стрингу
но если туда нужно передавать респонс распаршенного файла, для отображения самого парсинга в карточке кандидата, то поправьте плиз доку и распишите, как это сделать правильно
