### ISSUE TITLE
Получение обновленных данных за период

### ISSUE THREAD

**Issue by chistyakovyo** [huntflow/api#228]
Добрый день.
Настраиваем аналитику по воронкам, использовали api для получения данных.
Теперь возник вопрос, как получать только обновленные данные по вакансиям, кандидатам, а не подтягивать заново всю базу? Например обновление раз в день всех измененных записей за последние 24 часа. 
Не нашел в api информации, кроме как использовать вебхук.

**Comment by glibin** [comment]
Добрый день!

На данный момент получение обновлений возможно только через вебхуки.

**Comment by chistyakovyo** [comment]
Можете доработать API, чтобы была возможность получать данные, обновленные за последние n дней, например? Это нормальная практика и судя по другим запросам у большинства клиентов с этим сложности и вопросы.

**Comment by chistyakovyo** [comment]
Добрый день
Есть ли новости по этому вопросу? Планируется ли получение данных через api за выбранный период?
