### ISSUE TITLE
Получение accaunt_id и client_id

### ISSUE THREAD

**Issue by k911a** [huntflow/api#23]
![1](https://user-images.githubusercontent.com/16066311/49083214-70082200-f265-11e8-8f7a-a270f897bae9.PNG)

Авторизация проходит успешно.

Чтобы создать заявку, требуется account_id. Как я могу его получить? И как я могу получить client_id? 
![2](https://user-images.githubusercontent.com/16066311/49083408-ed339700-f265-11e8-9b5d-3b253876cd60.PNG)

В руководстве не сказано, что нужно отправить в заголовке, чтобы получить client_id

**Comment by glibin** [comment]
Для персонального токена не требуется client_id

Для получения account_id: https://github.com/huntflow/api/blob/master/ru/user.md#organizations

**Comment by k911a** [comment]
![3](https://user-images.githubusercontent.com/16066311/49083702-d477b100-f266-11e8-8162-38c7e5d9f00b.PNG)

ок. работает. оставлю тут скрин, как напоминание для себя о том, что нужно передавать и соответствующие данные в заголовке.
