### ISSUE TITLE
Вопросы по вебхукам

### ISSUE THREAD

**Issue by toxaw** [huntflow/api#230]
Хотел бы узнать, почему при создании вакансии приходит одновременно(параллельно) событие OPEN,EDIT,EDIT а не один OPEN?
![image](https://user-images.githubusercontent.com/33651909/96153314-39e5f100-0f16-11eb-8cc4-6407b4128681.png)

Пояснение почему на EDIT есть создание вакансии у Нас:

1) EDIT может прийти первым чем OPEN от Вас;
2) Есть вероятность того что к нам OPEN не придет от Вас и чтобы при  EDIT создавалась вакансия.

**Comment by glibin** [comment]
Добрый день!

Это связано с технической особенностью работы вебхуков. 
Мы добавим задачу на доработку последовательной отдачи событий, но пока точных сроков реализации назвать не смогу.
