### ISSUE TITLE
Получение данных о рекрутере

### ISSUE THREAD

**Issue by DStelmash** [huntflow/api#231]
Добрый день можем ли мы по API получать данные о рекрутерах которые принимают участие в подборе кандидатов по вакансии. Тип лицензии для рекрутинговых агентств

**Comment by glibin** [comment]
Добрый день!

Ответ есть в этом тикете: https://github.com/huntflow/api/issues/133

Работает независимо от типа организации.

**Comment by DStelmash** [comment]
Добрый день! Как я понял из ответа в запросе #133 мы получим только список по рекрутерам, а будет ли в этих данных e-mail адрес рекрутера?

**Comment by glibin** [comment]
Да, будет

**Comment by DStelmash** [comment]
Спасибо!
