### ISSUE TITLE
Нужна помощь по описанию и флоу получения статусов по заявкам/вакансиям

### ISSUE THREAD

**Issue by george-cloud-first** [huntflow/api#233]
Привет, прикручиваем интеграцию - хотим создавать заявки и мониторить результат их обработки:

1. факт создания
2. взята ли в работу или отклонена
3. создана ли вакансия,  ведется ли найм(кол-во уже нанятых)
4. закрыта ли заявка наймом(сколько человек наняли по ней)
5. не закрыта(если наняли кол-во меньше указанного или по другой причине с указанием такой причины)  

Статусы заявок, вакансий, вебхуки - не позволяют этого понять. Промежуточные статусы что кого-то смотрят/собеседуют нам не интересны.

просьба описать алгоритмы получения таких состояний заявки которые нам нужны, последовательность вызовов, значащие поля которые нужны анализировать и проверять, вебхуки которые нужно смотреть:
- [ ] факт создания - тут я понимаю что появляется id заявки, и по этому id мы будем искать все остальное
- [ ] взята ли в работу или отклонена
- [ ] создана ли вакансия,  ведется ли работа(кол-во уже нанятых)
- [ ] закрыта ли заявка наймом(сколько человек наняли по ней)
- [ ] не закрыта(если наняли кол-во меньше указанного или по другой причине с указанием такой причины)

**Comment by glibin** [comment]
> факт создания - тут я понимаю что появляется id заявки, и по этому id мы будем искать все остальное

Мы готовим документацию и возможность получать информацию по заявкам в реальном времени через вебхуки, но точных сроков пока не смогу назвать. Пока можно периодически вызывать метод получения списка заявок: https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#получение-списка-заявок-на-вакансию

> взята ли в работу или отклонена

Получить информацию о заявке можно запросом: /account/{account_id}/vacancy_request/{vacancy_request_id}

Если заявка взята в работу, то у нее будет заполнено поле vacancy
Если заявка отклонена, то вернется ответ 404

> создана ли вакансия, ведется ли работа(кол-во уже нанятых)
> закрыта ли заявка наймом(сколько человек наняли по ней)
> не закрыта(если наняли кол-во меньше указанного или по другой причине с указанием такой причины)

вероятно, ответ есть в предыдущем пункте + информация о наймах: https://github.com/huntflow/api/blob/master/ru/vacancies.md#fill-quotas
