### ISSUE TITLE
Возвращает ошибку в странном формате

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#235]
При попытке удалить тэг (Который через профиль кандидата находится), возвращает ошибку
```
{"errors": [{"type": "common", "value": ["not found"]}]}
```
По идее второй уровень вложенности массивов излишний, так как список ошибок у нас в массиве errors. В части ошибок value возвращается строкой.
В итоге выходит неконсистентно.

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, информацию о запросе (адрес, тело запроса, код и тело ответа).
