### ISSUE TITLE
В хуке не передаётся поле город

### ISSUE THREAD

**Issue by No0key** [huntflow/api#236]
Добрый день!
Аккаунт 44326.

При создании новой вакансии мы заполняем поле "Регион" (https://prnt.sc/vcmmch), но в вебхуке по кандидату не передаётся это поле.
Вот блок vacancy который прилетает:
    "vacancy": {
      "id": 2544476,
      "applicants_to_hire": 2,
      "position": "тест",
      "company": "Группа поддержки тестирования · Отдел тестирования · Департамент разработки",
      "money": "500",
      "state": "OPEN",
      "hidden": false,
      "priority": 0,
      "deadline": null,
      "account_division": {
        "id": ххххх,
        "name": "Группа поддержки тестирования"
      },
      "created": "2020-09-23",
      "multiple": false,
      "parent": null,
      "remotely": "Нет",
      "fill_quotas": [
        {
          "id": ххххх,
          "applicants_to_hire": 1,
          "deadline": null,
          "vacancy_request": null,
          "created": "2020-09-23 14:59:34",
          "closed": null
        },
        {
          "id": ххххх,
          "applicants_to_hire": 1,
          "deadline": null,
          "vacancy_request": 21190,
          "created": "2020-09-29 15:07:52",
          "closed": null
        }
      ],
      "frame_id": хххххх
    },

**Comment by glibin** [comment]
Добрый день!

Уточнил информацию у коллег. Проблема, действительно, присутствует. Исправление выйдет в течение следующей недели.

**Comment by No0key** [comment]
Добрый день! Нет новостей ?

**Comment by glibin** [comment]
Добрый день!

Проблема исправлена.
