### ISSUE TITLE
Базовый урл API коробочной версии

### ISSUE THREAD

**Issue by kuatro** [huntflow/api#237]
Добрый день! 

Какой базовый URL API для коробочной версии продукта? В документации не указано.

**Comment by glibin** [comment]
Добрый день!

Это зависит от настроек конкретно размещения. Обратитесь к менеджеру поддержки, он вам сообщит адрес API для вашей инсталляции.

**Comment by kuatro** [comment]
Благодарю за быстрый ответ!
