### ISSUE TITLE
Айдишки в разных токенах

### ISSUE THREAD

**Issue by paul23093** [huntflow/api#238]
Добрый день.

У нас по какой-то причине решили использовать отдельные токены для двух разных городов.

Почти стопроц уверен в том, какой будет ответ, но всё таки:
Правильно ли я понимаю, что нет никаких гарантий, что, например, айдишки вакансий могут быть одинаковыми для разных токенов? (или любые другие айдишки)

Заранее спасибо.

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, это токены для разных организаций или для одной?

Проверить можно вызвав метод /accounts (https://github.com/huntflow/api/blob/master/ru/user.md#получение-информации-о-доступных-организациях) и сравнив результаты с каждым токеном

**Comment by paul23093** [comment]
Токены для одной организации.

**Comment by paul23093** [comment]
Токены для разных организаций

**Comment by paul23093** [comment]
Предусмотрена ли какая-то отдельная процедура соединения данных по двум организациям?
Сейчас встал вопрос о том, чтобы смотреть общую статистику по городам, но лить данные по двум токенам в одну таблицу вызовет проблему дубликата айдишек, хотя вакансии будут разные.
И если с вакансиями ещё всё несложно (можно было бы добавить поле города с условием на токен), то соединять все остальные данные уже не так просто.

**Comment by glibin** [comment]
Если обе организации находятся на одном физическом сервере (возможно, у вас выделенный Хантфлоу), то идентификаторы пересекаться не будут.
