### ISSUE TITLE
Данные приходят не в полном объеме.

### ISSUE THREAD

**Issue by rsungatovich** [huntflow/api#239]
Здравствуйте! 

Запрашиваю данные по этому эндпоинту (по другим аналогично) данные приходя не в полном объеме:
`GET /account/{account_id}/vacancies`

Также в запросе использовал параметры count и page с кол-вом объектов и текущей страницей, результат тот же.

Не могли бы подсказать, в чем может быть дело?

**Comment by rsungatovich** [comment]
P.s. апи интегрируется с Google Data Studio.

**Comment by glibin** [comment]
Добрый день!

Из вопроса не очень понятно каких данных не хватает. Как вариант, можно попробовать передать параметр  `?include_dictionaries=true` и в ответе будут приходить данные из внедренных полей-справочников.

**Comment by rsungatovich** [comment]
Например, приходят не все объекты с вакансиями по этому эндпоинту /account/{account_id}/vacancies. Коннектор в Google Data Studio отображает только 2 вакансии в таблице, хотя их должно быть больше. Параметр прибавил только один объект к списку, но этого все равно не достаточно.

Использую запрос по токену и id компании вот в этом коннекторе: 
![image](https://user-images.githubusercontent.com/64484993/99040882-f7f2ae00-259a-11eb-825e-62e5fa65ae7f.png)

**Comment by rsungatovich** [comment]
Похоже проблема в самом коннекторе, через который запрашиваются данные, спасибо!
