### ISSUE TITLE
Добавление вакансии в базу

### ISSUE THREAD

**Issue by k911a** [huntflow/api#24]
Возникает ошибка при попытке добавить вакансию в базу. В теле POST запроса передаю только одно обязательное поле. Ниже на скриншотах показан передаваемые заголовки и тело запроса.

![1](https://user-images.githubusercontent.com/16066311/49089752-a9488e00-f275-11e8-9099-6bb78447fcd4.PNG)

![2](https://user-images.githubusercontent.com/16066311/49089776-b4032300-f275-11e8-94bf-04c84f26192d.PNG)

**Comment by glibin** [comment]
Судя по ответу, у вас версия Хантфлоу для кадровых  агентств. 

Для них, при создании вакансии, требуется передача идентификатора заявки на вакансию в клиентском модуле. К сожалению, для клиентского модуля на данный момент нет API.
