### ISSUE TITLE
Передача даты выхода на работу кандидата

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#240]
Добрый день!

Есть задача передавать в ХФ статус "Вышел на работу" и дату выхода. Ранее это делали с помощью 
POST /account/{account_id}/applicants/{applicant_id}/vacancy
в котором можно было передать поле EMPLOYMENT_DATE.
С некоторых пор этого поля нет. Как передавать дату выхода на работу при передаче статуса "Вышел на работу"?

**Comment by glibin** [comment]
Добрый день!

Можете прислать пример запроса, а также ответ от сервера на этот запрос?

**Comment by Nikolay1791** [comment]
Запрос:
 {
     "vacancy": 3789,
     "status": 8,
     "comment": "Проведен прием в SAP HCM",
     "fill_quota": 3924
 }

Ответ:
{
    "id": 19208,
    "vacancy": 3789,
    "status": 8,
    "rejection_reason": null,
    "changed": "2020-11-13T13:18:28+03:00",
    "updated": "2020-11-13T13:18:28+03:00"
}

**Comment by glibin** [comment]
Добрый день!

В вашем примере вы не передаете поле "employment_date", поэтому я не очень понимаю суть вопроса и проблемы.

**Comment by Nikolay1791** [comment]
Добрый день!
Наша задача - при изменении статуса вакансии на статус «Вышел на работу» передать Дату приема на работу.
Для изменения статуса вакансии используем API «Добавление кандидата на вакансию» https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant
В описании нет поля employment_date
В какое поле запроса необходимо передать эту дату ?

**Comment by glibin** [comment]
Да, такая возможность пока не задокументирована, но вы можете ее использовать. 
Документацию обновим в ближайшем будущем.
