### ISSUE TITLE
Возвращается не тот результат, что ожидается.

### ISSUE THREAD

**Issue by rsungatovich** [huntflow/api#242]
Добрый день!

У меня такой вопрос, по этому эндпоинту: `GET /account/{account_id}/applicants`  (Получение списка кандидатов)
в поле **status** при отправки данных статус кандидата указывается строкой, а когда мы его получаем GET запросом, статус приходит в таком формате как показано в скрине. Не могли бы подсказать почему приходит такой результат?
![image](https://user-images.githubusercontent.com/64484993/99234184-41decc80-2805-11eb-83fb-f271f8e3d0f2.png)

**Comment by glibin** [comment]
Добрый день!

Извините, я совсем не понял вопрос :( 

Можете прислать примеры запросов и ответов с чуть более подробным описанием проблемы?

**Comment by rsungatovich** [comment]
По этому эндпоинту `/account/{account_id}/applicant` в поле **status** приходит пятизначное число, как показано в скрине. Это так должно быть, или здесь что-то не так?

**Comment by glibin** [comment]
Это числовой идентификатор этапа. Уточните, в чем вы видите здесь проблему?

**Comment by rsungatovich** [comment]
Нет, это я и хотел уточнить. Просто в документации к апи в поле статус указано однозначное число, из-за чего возникли сомнения. Также, мне сообщили, что поле статус заполняется строкой, а не числом, когда его отправляют со стороны клиента. Можно ли как нибудь получить этот статус в виде строки, а не идентификатор этапа? Чтобы человеку было удобно анализировать эти данные.

**Comment by glibin** [comment]
Да, вот здесь: https://github.com/huntflow/api/blob/master/ru/dicts.md#vacancy_statuses

**Comment by rsungatovich** [comment]
Спасибо, то что надо!)
