### ISSUE TITLE
Время закрытия вакансии.

### ISSUE THREAD

**Issue by rsungatovich** [huntflow/api#244]
Добрый день!

Не подскажите, могу ли я получить данные по времени, которое ушло на закрытие вакансии? Например, сколько времени понадобилось для того, чтобы закрыть вакансию. В интерфейсе приложения есть такая возможность, а в документации к апи не могу найти, где это поле возвращается.

**Comment by glibin** [comment]
Добрый день!

Информация доступна по этому запросу: https://github.com/huntflow/api/blob/master/ru/vacancies.md#квоты-к-найму

**Comment by rsungatovich** [comment]
Благодарю!
