### ISSUE TITLE
Восстановление данных с бд

### ISSUE THREAD

**Issue by stokolyas-alexey** [huntflow/api#246]
Добрый день.

Был аккаунт, получили от тех. отдела данные. Как можно залить данные в новый аккаунт?

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, что вы имеете ввиду?

**Comment by stokolyas-alexey** [comment]
у меня был 2 аккаунта, на первом были данные о кандидатах, так получилось, что оплатил второй аккаунт, я получил данные от тех поддержки, как их можно восстановить на нужном аккаунте

**Comment by glibin** [comment]
Добрый день!

К сожалению, здесь мы сможем только ответить на вопросы по использованию методов API.
По поводу переноса данных между аккаунтами вам, все таки, нужно обратиться в поддержку (на всякий случай, приложите ссылку на этот тикет).
