### ISSUE TITLE
Вебхуки. Подключение к API 1С Предприятие, которая находится во внутренней сети

### ISSUE THREAD

**Issue by kalaysolay** [huntflow/api#248]
Привет, не было ли каких-то кейсов и их решений, когда необходимо было в вебхуках указать сервис системы, которая находится во внутренней сети, то бишь когда ИБ режет доступы в интернет? Через какие-нибудь VPN-туннели или еще как-то?

**Comment by glibin** [comment]
Добрый день!

Обычно, в этих случаях мы предлагаем клиентам размещение на выделенных серверах Хантфлоу. 
В этом случае возможно поднятие защищенного IPSec тоннеля между инфраструктурами.

Альтернативно можно использовать различные сервисы типа ngrok

**Comment by kalaysolay** [comment]
Спасибо за ответ
