### ISSUE TITLE
Выгрузка employment_date

### ISSUE THREAD

**Issue by plurodel** [huntflow/api#25]
Подскажите, пожалуйста, возможно ли вытаскивать поле employment_date (дату выхода на работу)? Есть информация, что это можно сделать с помощью ручки "account/{acc}/applicants/{appl}/log".
Можно ли это сделать более удобно? например, выгрузка кандидатов с фильтром по вакансии/статусу и в этом списке показывать это поле?

**Comment by glibin** [comment]
Есть метод для выгрузки кандидатов по статусу: https://github.com/huntflow/api/blob/master/ru/applicants.md#applicants
