### ISSUE TITLE
Редактирование кандидата

### ISSUE THREAD

**Issue by jsden** [huntflow/api#250]
подскажите, возможно записать комментарий для кандидата? Возможно его редактировать через api?

**Comment by glibin** [comment]
Добрый день!

Возможность добавления комментария по кандидату описана здесь: https://github.com/huntflow/api/issues/47

Функционал редактирования комментария по кандидату пока недоступен в API

**Comment by jsden** [comment]
Спасибо, еще подскажите пожалуйста. При обращении по https://api.huntflow.ru/account/2567392/vacancies/10568954  Получаю ответ - {"errors": [{"type": "common", "value": ["forbidden"]}]}   Не понимаю причины

**Comment by jsden** [comment]
И еще подскажите, как проще всего узнать id аккаунта? /me возвращает {"name": "API Robot", "position": null, "email": "api... там нет id

**Comment by glibin** [comment]
> Спасибо, еще подскажите пожалуйста. При обращении по https://api.huntflow.ru/account/2567392/vacancies/10568954 Получаю ответ - {"errors": [{"type": "common", "value": ["forbidden"]}]} Не понимаю причины

Не нашли вакансии с таким идентификатором

> И еще подскажите, как проще всего узнать id аккаунта? /me возвращает {"name": "API Robot", "position": null, "email": "api... там нет id

https://github.com/huntflow/api/blob/master/ru/user.md#organizations

**Comment by jsden** [comment]
Делаю get запрос к /me, получаю ответ
"name": "API Robot", "position": null, "em....
Когда делаю get запрос к
/account/zitar/applicants/10568885/log
получаю ответ
404: Not Found
Заголовки не меняются
помогите пожалуйста.
