### ISSUE TITLE
Нет данных в API, которые есть в web версии

### ISSUE THREAD

**Issue by bladeelves** [huntflow/api#251]
1. По запросу https://api.huntflow.ru/account/37736/vacancies нет вакансий 2474452,2566959 и еще несколько, но в web представлении они есть
2. https://api.huntflow.ru/account/37736/applicants/10115930/log нет движений, хотя в web представлении они есть

**Comment by glibin** [comment]
Добрый день!

Данные вакансии скрыты от коллег. 
Для того, чтобы они стали доступны, управляющий рекрутер должен добавить пользователя API Robot на них или обратиться в поддержку, чтобы этой учетной записи выдали роль управляющего (будут доступны все вакансии).
