### ISSUE TITLE
Вэбхук вакансий не возвращает текстовые описания

### ISSUE THREAD

**Issue by HtmlMak** [huntflow/api#252]
Вот идентификатор вэбхука 92ca1c9e-242b-4623-93bb-b16aa5969408.
body, requirements, conditions с значениями null, хотя у самой вакансии есть описания. и при получении данных по апи напрямую всё ок

**Comment by glibin** [comment]
Добрый день!

Поля body, requirements, conditions приходят только на события EDIT и OPEN. 

Подскажите, это решит вашу задачу?

**Comment by HtmlMak** [comment]
Спасибо!
Да, я добавлю тогда условие на проверку события.

Просто в описании про это не говорится, боюсь, ещё не раз откроют подобный issue)
Но этот можно закрывать

**Comment by glibin** [comment]
Документацию поправим :)
