### ISSUE TITLE
Можно ли менять этапы работы с кандидатом через API

### ISSUE THREAD

**Issue by kalaysolay** [huntflow/api#253]
Можно ли менять этапы работы с кандидатом через API?
Планировался такой процесс, что хантфлоу передает во внутреннюю систему данные кандидата на проверку.
Во внутренней системе чел проверяет кандидата и говорит ок или не ок. Если не Ок, то меняется этап на "отклонен".
Порылся среди описания АПИ, нашел только добавление комментариев.
Если такого нет, то реально ли реализовать и какая процедура в таких случаях?

**Comment by glibin** [comment]
Добрый день!

Ответ доступен здесь: https://github.com/huntflow/api/issues/66

**Comment by kalaysolay** [comment]
Спасибо:)
