### ISSUE TITLE
Загрузка файла через api

### ISSUE THREAD

**Issue by user9099** [huntflow/api#254]
Загружаю файл с резюме как описано здесь - https://github.com/huntflow/api/blob/master/ru/upload.md. Получаю ответ без кода ошибки. Но по ссылке его не появляется - https://huntflow.ru/.../applicants/filter/all. Или нужно смотреть по другому адресу?
Что значит id при загрузке файла? И как получить ссылку на этого кандидата в базе через api, чтобы его присвоить нужной вакансии, например?

**Comment by HtmlMak** [comment]
Привет! Сталкивался недавно с этим недавно, тут алгоритм немного другой.
Загрузка файлов это просто загрузка файлов, она нужна для распознания информации. 

Есть демо репозиторий https://github.com/huntflow/api-response.
После распознания файла необходимо добавить кандидата в базу https://github.com/huntflow/api/blob/master/ru/applicants.md#add

**Comment by glibin** [comment]
@HtmlMak спасибо за ответ :-)
