### ISSUE TITLE
Интеграция с Huntflow

### ISSUE THREAD

**Issue by AnnKostina** [huntflow/api#256]
Добрый день.
Мы реализуем интеграцию для нового сайта Бургер Кинг.
Для продуктивной среды используется метод https://burgerking.huntflow.ru/bk/multivacancy/add (не проверяли еще)
Сейчас мы хотим протестировать интеграцию в тестовом личном кабинете, подскажите какой URL должен быть для добавления анкет на тестовую среду?

**Comment by glibin** [comment]
Добрый день!

Коллеги подсказали, что уже ответили на вопрос.

**Comment by AnnKostina** [comment]
Да, спасибо.
