### ISSUE TITLE
Не передается отклик

### ISSUE THREAD

**Issue by AnnKostina** [huntflow/api#257]
Добрый день!
Пытаюсь отправить запрос для Бургер Кинг:

{
    "f": ​"Testov"​,
    "i": ​"Test"​,
    "o": ​"Testovich"​,
    "b_day": ​"7"​,
    "b_month": ​"4"​,
    "b_year": ​"2002"​,
    "tel": ​"+7 (903) 645-2222"​,
    "vacancy": ​"Повар-кассир"​,
    "city": ​"Ковров"​,
    "metro": ​""​,
    "restaurant": ​"ул Лопатина 7А ТЦ Ковров Молл 2 этаж"​,
    "restaurant_num": ​"628"​,
    "citizenship": ​"Россия"​,
    "email": ​""​,
    "from_rest": ​"0"​,
    "site": ​"main"
}

Ответ получаем: 
{
    "errors": [
        {
            "type": "request",
            "value": "invalid_request_body"
        }
    ]
}

URL: https://burgerking.huntflow.ru/bk/multivacancy/add 
Подскажите пожалуйста, какие не верно передаем параметры?
Спасибо.

**Comment by glibin** [comment]
Скорее всего вы отправляете невалидный JSON.

Пришлите полный HTTP запрос

**Comment by AnnKostina** [comment]
Спасибо, проблему решили.
