### ISSUE TITLE
Кодировка ответов

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#258]
добрый день

API отдаёт ответы с контентом: Content-Type: application/json; charset=UTF-8

казалось бы UTF-8 и хотелось бы во всех строках видеть нормальные русские буквы, вместо кодов вида

 "\u041d\u0418\u0423 \u0412\u0428\u042d"

понятно, что для многих сред это не проблема, но мы часто используем curl в консоли, человеческие буквы сильно упростили бы жизнь без дополнительных преобразований

**Comment by glibin** [comment]
Добрый день!

Согласен, что такой вариант был бы более удобен. 
Запишем в пожелания по доработке API Хантфлоу.

**Comment by UncleMiF** [comment]
добрый день

а когда можно ожидать подобную косметику?
