### ISSUE TITLE
Описание дополнительных полей

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#259]
добрый день

для НИУ ВШЭ добавлены дополнительные поля

можете описать подробно их значение для примера полностью заполненной вакансии 2566359 (оставил только поля с вопросами):

{

                "parent": null, — это что?

                "account_division": 28470, — что это? с чем стыкуется

                "account_vacancy_status_group": null, — что это? с чем стыкуется, почему пусто

                "company": null,  — что это? с чем стыкуется, почему пусто

                "source": null, — что это? с чем стыкуется, почему пусто

                "hidden": false, — от каких «коллег» может быть скрыта вакансия? как это учитывать на внешней публичной витрине?

                "priority": 1, — на что влияет приоритет?

                "multiple": false, — что это?

                "additional_fields_list": ["catalogues", "campus", "project", "for_student"], — что это? технический список доп. полей?

                "catalogues": 6399, — что это? с чем стыкуется

                "campus": 6472, — что это? в чём семантика? с чем стыкуется

                "project": "Постоянный", — что это? какие могут быть значения? почему не ID на справочник?

                "for_student": "Да", — а почему поле не boolean?

                "blocks": [], — что это? что здесь может быть?

                "vacancy_request": null

}

fill_quotas в этой структуре отсутствует, поле упразднено?

нужны описания всех задействованных в стыковках справочников — как получить их значения

/account/…/dictionary/campus — расскажите про структуру справочника

слышали про /account/…/dictionary/prof — расскажите про структуру справочника, где он используется в полях выше?

**Comment by glibin** [comment]
Добрый день!

Описание полей доступно по ссылке: https://github.com/huntflow/api/blob/master/ru/vacancies.md#add

Все остальные поля, кроме дополнительно внедренных (указаны в `additional_fields_list`), являются полями для внутреннего использования, можете не обращать на них внимания, они могут измениться в любой момент.

Единственные поля, которые не добавлены в описание (исправим):
– account_vacancy_status_group - идентификатор набора этапов подбора (могут не использоваться в вашей организации)

> /account/…/dictionary/campus — расскажите про структуру справочника

Описание структуры справочников: https://github.com/huntflow/api/blob/master/ru/dictionaries.md

> слышали про /account/…/dictionary/prof — расскажите про структуру справочника, где он используется в полях выше?


В вакансии внедрены следующие дополнительные поля:

catalogues – поле типа словарь, подключен словарь prof
campus – поле типа словарь, подключен словарь campus
project – поле типа список (внутреннее хранение строкой), возможные варианты: ["Краткосрочный", "Постоянный"]
for_student – поле типа список (внутреннее хранение строкой), возможные варианты: ["Да", "Нет"]
