### ISSUE TITLE
Возможность получить только активные вакансии

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#260]
добрый день

нам для интеграции данных HF с витриной портала нужен механизм получения списка отфильтрованных вакансий (например только активных state == 'OPEN', и при этом, вероятно, не скрытых hidden == false)

https://api.huntflow.ru/account/…/vacancies?someFilter…

в идеале, чтобы можно было критерием управлять, но для начала достаточно и преднастроенного:

https://api.huntflow.ru/account/…/vacancies/activeOnly

также было бы удобно сразу в списке получить раскрытое описание этих вакансий, и без пейдженатора

обоснование для получения списка активных вакансий:

со временем всех вакансий может быть десятки тысяч

вебхуки могут дать сбой и потребуется полная пересинхронизация

нам с витрины нужно удалить неактуальные и получить информацию только по актуальным

без загрузки HF десятками тысяч запросов, и без перелистывания страничек — просто один список активных вакансий, которых в моменте вряд ли будет много — мы бы обошлись одним запросом, который могли бы повторять по необходимости, сочитая с вебхуками или даже без них — в упрощённой реализации

**Comment by glibin** [comment]
Добрый день!

К сожалению, таких методов для получения вакансий пока нет.

Для списка вакансий есть параметр opened (https://github.com/huntflow/api/blob/master/ru/vacancies.md#получение-списка-вакансий), чтобы получать только открытые вакансии. Открытых вакансий, как правило, не очень много (не тысячи).

В 2021 мы планируем добавить возможность поиска вакансий в API, что может улучшить выборку вакансий под ваш запрос.


Также предложу рассмотреть вариант использования нашей платформы публикации вакансий и сбора откликов (https://github.com/huntflow/api/blob/master/ru/responses.md). Подробности можно уточнить у менеджеров поддержки.
