### ISSUE TITLE
Касательно авторизации при использовании вебхуков

### ISSUE THREAD

**Issue by kalaysolay** [huntflow/api#261]
Всем привет,
если я правильно понимаю, в широком смысле адрес вебхука - это просто какой-то обычный рест.
Вопрос: хантфлоу предоставляет только авторизацию по хэшу на основе секретного ключа? или есть какие-то варианты типа token или base64 (basic auth) на основе логина пароля?

**Comment by glibin** [comment]
Добрый день!

Хантфлоу сейчас предоставляет возможность валидации данных на основе подписи запроса секретным ключом.

Других вариантов на данный момент нет. Ваше пожелание внесем в список для дальнейшего планирования развития  API/вебхуков.
