### ISSUE TITLE
проблема получения кандидатов

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#263]
Добрый день!
 
Перестал работать запрос кандидатов из продуктивного ХФ по статусу:
GET /account/{account_id}/applicants?status=4
возвращает:
{
   "items": [],
   "page": 1,
   "count": 30,
   "total": 1,
   "total_items": 0
}  
С зеркала запрос работает.

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, передаваемый account_id

**Comment by Nikolay1791** [comment]
2

**Comment by Nikolay1791** [comment]
запрос кандидатов из продуктивного ХФ начал работать
