### ISSUE TITLE
Добавление или получение email пользователя от имени которого создан лог

### ISSUE THREAD

**Issue by SergeyBusluk** [huntflow/api#264]
Добрый день. Я работаю над интеграцией huntflow и рабочего тасктрекера.  В пространстве тасктрекера идет привязка юзера к его email. В связи с этим я бы хотел возможность узнать email юзера, который работает над кандидатом. В своей задачи я обращаюсь сюда GET /account/{account_id}/applicants/{applicant_id}/log, где необходимая для меня информация содержит только следующее:           
"account_info": {
                "id": 99999,
                "name": "Иванов Иван"
            }
Можете ли вы добавить сюда еще информацию  по email?
Можно ли как-то узнать email по этому id? 
Спасибо за внимание!

**Comment by glibin** [comment]
Добрый день!

Можно воспользоваться информацией из этого тикета: https://github.com/huntflow/api/issues/155
