### ISSUE TITLE
Получение резюме в "сыром" виде (в виде одной сущности)

### ISSUE THREAD

**Issue by dvmatyun** [huntflow/api#266]
Добрый день, есть ли какой либо способ получить резюме одним файлом/текстом? (не распаршеный в JSON)

**Comment by glibin** [comment]
Добрый день!

Ваш вопрос не очень понятен. Подскажите, какую задачу вы хотите решить?

**Comment by dvmatyun** [comment]
Хочу перенести резюме кандидата в читабельном человеку виде в свою систему. Другими словами, получить полную информацию о кандидате, которую он о себе предоставил (опять таки в читабельном человеку виде).

**Comment by glibin** [comment]
Добрый день!

Сформировать нужный вам читабельный вид из JSON вы можете самостоятельно. 
В другом виде получить резюме из API возможности нет.
