### ISSUE TITLE
Connection: close

### ISSUE THREAD

**Issue by poepwrj** [huntflow/api#267]
Добрый день. 
Помогите разобраться с ситуацией, пожалуйста.

Пытаюсь сделать запрос GET /me с авторизацией по токену. В ответ получаю: 
400
	Date: Fri, 25 Dec 2020 05:51:09 GMT
	Content-Type: text/html
	Content-Length: 264
	Connection: close

Подключаюсь к "api.huntflow.ru", по 443 Передаю в заголовках:
        Content-Type: application/json; charset=UTF-8
        User-Agent:  <приложение> (<емейл>)
        Authorization: Bearer <токен>

**Comment by aleks-v-k** [comment]
Не знаю в какой вы операционной системе. Но если доступен терминал с linux, то
попробуйте выполнить команду в консоли (должны быть установлены `curl` и `sed`)

```
curl -v 'https://api.huntflow.ru/me' -H 'Authorization: Bearer <токен>' 2>&1 | sed 's/Authorization: Bearer.*/Authorization: Bearer XXX/g'
```
И если ошибка есть, то покажите ее вывод. **ОЧЕНЬ ВАЖНО:** перед тем как постить, внимательно проверьте, что в вывод не попал ваш токен.

**ВАЖНО:** Если ошибки нет и возвращается ожидаемый ответ, то постить его сюда не нужно (там будет имейл, телефон акаунта которому принадлежит токен).

Если моя команда отрабатывает без ошибок, то проблема где-то в вашем способе посылки запроса. К сожалению, вы не показали тело ответа.

**Comment by poepwrj** [comment]
Добрый день, Александр.

Спасибо за Ваш ответ, ваша команда помогла разобраться, и в итоге авторизация у меня прошла нормально.

Буду очень Вам признателен если у Вас есть возможность подсказать как правильно послать запрос из 1С.
У меня получается два варианта развития событий:
Либо    405
                Date: Fri, 25 Dec 2020 16:44:53 GMT
                Content-Type: text/html; charset=UTF-8
                Content-Length: 87
                Connection: keep-alive
                Access-Control-Allow-Origin: *
                Access-Control-Allow-Headers: x-requested-with, content-type
                Access-Control-Allow-Methods: POST, GET, OPTIONS
<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>

Либо:   404
                Date: Fri, 25 Dec 2020 16:47:09 GMT
                Content-Type: text/html; charset=UTF-8
                Content-Length: 69
                Connection: keep-alive
<html><title>404: Not Found</title><body>404: Not Found</body></html>

Текст кода простой:
                Соединение = Новый HTTPСоединение("api.huntflow.ru", , , , , , ssl);                                 // Новое соединение с использованием ssl
Заголовки = Новый Соответствие;                                                                                                      // Описание заголовков
                Заголовки.Вставить("Content-Type", "application/json; charset=UTF-8");
                Заголовки.Вставить("User-Agent",  "1C huntflow (" + МойЕмайл + ")");
                Заголовки.Вставить("Authorization", Bearer  " + МойТокен + "");

                Запрос = Новый HTTPЗапрос("GET  /me", Заголовки);                                                               //И Сам запрос, Если передаю как на примере ответ 404, если просто «/me», - 405
Ответ = Соединение.ОтправитьДляОбработки(Запрос);

В строке Запрос = Новый HTTPЗапрос("GET  /me", Заголовки); передаю разные варианты обращений к Вашему рессурсу:
Если «GET  /me»  - ошибка 404;
Если « /me» - ошибка 405.


PS. Да, я тоже ненавижу 1С-ников ;)

**Comment by aleks-v-k** [comment]
Добрый день.
К сожалению с 1С дел не имел. Могу подсказать только то, что показывает гугл, но вы и без меня это найдете. Проверить у меня нет возможности.
