### ISSUE TITLE
Перестали работать запросы интеграции

### ISSUE THREAD

**Issue by george-cloud-first** [huntflow/api#268]
в ответ прилетает ошибка, на нашей стороне изменений не было
```
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}
```

**Comment by aleks-v-k** [comment]
Добрый день.

Отправьте, пожалуйста, на hello@huntflow.ru информацию о том, какие запросы вы отсылаете (url, заголовки) с указанием организации.
