### ISSUE TITLE
Доработка API Хантфлоу

### ISSUE THREAD

**Issue by VizgalovS** [huntflow/api#269]
1. Можно ли переименовать название уже существующих полей на форме?
2. Сколько времени требуется для добавления полей в API для обмена со сторонними программами без добавления дополнительных справочников?
3. Сколько времени требуется для добавления полей в API для обмена со сторонними программами с добавлением дополнительных справочников?
4. Где в Хантфлоу API можно посмотреть системное наименование поля «Дата запланированного выхода»?
5. Есть ли возможность самостоятельно обновлять в Хантфлоу иерархические справочники (Подразделения)?
6. Работали ли с интеграцией жира? Как осуществлялась интеграция?

**Comment by aleks-v-k** [comment]
Добрый день.

1-3. Не очень понятно о какой форме речь и какие поля добавлять в какие методы. Если речь о полях вакансии, то сейчас через API поменять схему вакансии нельзя.
4. Есть запрос истории работы с кандидатом, в ответе будет список действий по кандидату, думаю что вы говорите о поле `employment_date`. https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D0%BC
5. Изменение подразделений описано тут https://github.com/huntflow/api/blob/master/ru/account_divisions.md
6. Если имеется в виду atlassian Jira, то нет, не интегрировались, насколько мне известно.

**Comment by aleks-v-k** [comment]
По поводу 6 - интеграции с jira уточнение. Да, наши клиенты делали интеграцию, силами своих специалистов (с использованием нашего API)

**Comment by VizgalovS** [comment]
По поводу вопроса 2 и 3. Нам была предоставлена информация, что Хантфлоу можно доработать, создав дополнительные поля. 
Информация из данных полей может передаваться по API?

**Comment by VizgalovS** [comment]
По поводу вопроса 2 и 3. Нам была предоставлена информация, что Хантфлоу можно доработать, создав дополнительные поля.
Информация из данных полей может передаваться по API?

**Comment by aleks-v-k** [comment]
Все равно непонятно про какие дополнительные поля речь.

Если речь про доп. поля вакансии, то да, они возвращаются вместе с остальными (стандартными) полями.
Если речь про анкету кандидата, то получить ее можно так: https://github.com/huntflow/api/blob/master/ru/questionaries.md#view

**Comment by VizgalovS** [comment]
Пример.
Доработка на добавление в карточку вакансии поля "Город" - город в котором будет работать кандидат, в которое должна передаваться информация из Jira. Так же хотелось бы использовать данное поле в аналитике отчётов.
Возможно ли такое?

**Comment by VizgalovS** [comment]
Является ли "Идентификатор статуса" - status в истории работы с кандидатом идентификатором этапа подбора кандидата на вакнсию?

**Comment by glibin** [comment]
Добрый день!

> Возможно ли такое?

Возможно

> Является ли "Идентификатор статуса" - status в истории работы с кандидатом идентификатором этапа подбора кандидата на вакнсию?

Да, является
