### ISSUE TITLE
Изменение статуса кандидата

### ISSUE THREAD

**Issue by jsden** [huntflow/api#270]
Добрый день! подскажите, возможно ли изменение статуса кандидата?
Здесь не нашел - https://github.com/huntflow/api/blob/master/ru/applicants.md

**Comment by aleks-v-k** [comment]
Добрый день.

Описано тут: https://github.com/huntflow/api/issues/66

**Comment by jsden** [comment]
Спасибо за подсказку, прочитал то что ниже - 
`Добавление кандидата на вакансию
POST /account/{account_id}/applicants/{applicant_id}/vacancy

В теле запроса необходимо передать JSON вида:

{
    "vacancy": 988,
    "status": 1230,
    "comment": "Привет",
    "files": [
        {
            "id": 1382810
        }
    ],
    "rejection_reason": null,
    "fill_quota": 234
}
`

Вопросы
Если мне нужно изменить этап для кандидата, что указывать для vacancy?  Делать PUT запрос на   /account/{account_id}/applicants/{applicant_id}/vacancy ?

**Comment by glibin** [comment]
Добрый день!

Минимальный набор параметров для смены этапа:

```
{
"vacancy": 988,
"status": 1230
}
```

остальные параметры зависят от задачи и требований при передаче.

**Comment by jsden** [comment]
Спасибо за ответ, не помогло.
Получаю ответ от сервера - {"errors": [{"type": "common.applicant", "value": ["error.too_freq"]}]}" И через PUT и через POST
еще мне непонятно, что мне нужно поменять этап у кандидата,  как у вас написано, надо  отправить запрос  на /account/{account_id}/applicants/{applicant_id}/vacancy, где в url  присутствует  vacancy - вакансия, это правильно?
