### ISSUE TITLE
Возможность получения резюме кандидата в формате файла(pdf)

### ISSUE THREAD

**Issue by SergeyBusluk** [huntflow/api#271]
Крайне необходима возможность получения по апи резюме в pdf формате. В документации не нашел соответствующую информацию. Если такой возможности сейчас нет, есть ли вариант добавить такой функционал в апи хантфлоу?

**Comment by glibin** [comment]
Добрый день!

Сейчас такой возможности нет. Мы планируем добавить эту функциональность в этом полугодии.

**Comment by SergeyBusluk** [comment]
Понял, спасибо за оперативный ответ.

**Comment by razorbet** [comment]
Добрый день! 
Подскажите, возможность получения по апи резюме в pdf формате удалось реализовать. Если нет, то какие сроки на добавление этого функционала?
