### ISSUE TITLE
Постраничный запрос

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#274]
здравствуйте

https://github.com/huntflow/api/blob/master/ru/general.md#pagination

здесь не указаны какие-либо лимиты, но опытным путём удалось установить, что кроме значения 1 все прочие трактуются как 30, будь то 2, 10, 20, 100, 1000…

получается кроме 1 и 30 ничего не работает?

**Comment by glibin** [comment]
Добрый день!

Уточните, для какого запроса?

**Comment by UncleMiF** [comment]
при запросе списка вакансий:

https://api.huntflow.ru/account/12769/vacancies

**Comment by glibin** [comment]
Добрый день!

Действительно, есть ограничение на запрос с пагинацией. 

Я передал задачу на исправление.
