### ISSUE TITLE
Рандомизируется url файла

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#276]
здравствуйте

у нас готов синхронизатор всех открытых вакансий работающий в режиме add/delete/modify

но по какой-то причине файл вакансии 2579562
каждый раз отдаётся с меняющимся хвостом, что заставляет загрузчик модифицировать имеющуюся запись по этой вакансии из раза в раз (сравниваем JSON через lodash.isequal):

files[0].url:

…?s=hoRE7SR-TZR4aoMqnaoCdQ&e=1611129498
…?s=SKEAEJV7AFNtVq-jjOTIdQ&e=1611129539

можете отказаться от этой рандомизации?

или хотя бы добавить в объект вакансии штамп времени любой модификации, чтобы мы отталкивались от штампа при сравнении

**Comment by glibin** [comment]
Добрый день!

Ссылка на файл имеет срок жизни, поэтому каждый раз при запросе данных вам отдается ссылка с определенным сроком жизни. Ориентироваться на изменения можно по идентификатору файла files[].id

**Comment by UncleMiF** [comment]
а какой у ссылки срок жизни?

получается, если мы будем на что-то ориентироваться (files[].id) и не будем постоянно обновлять ссылку — она протухнет?

но об этом мы даже не узнали бы и через Web-хуки… и будет дохлая ссылка в итоге

такое вам точно надо?

**Comment by glibin** [comment]
Добрый день!

> а какой у ссылки срок жизни?

обычно, 12 часов

> получается, если мы будем на что-то ориентироваться (files[].id) и не будем постоянно обновлять ссылку — она протухнет?

если вы завяжетесь на files[].id, то будет гарантия, что файл с таким id не изменится.

> такое вам точно надо?

Предполагается, что пользователь забирает файл и сохраняет его себе при необходимости.
