### ISSUE TITLE
Профобласти — несколько значений

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#277]
здравствуйте

в данных о вакансии ВШЭ передаётся признак catalogues (собственно -s уже говорит о нескольких значениях)

но это не массив, а значение, а в дизайне у нас предусмотрены мульти-теги на основе областей

не предполагается переделать на массив? и мультивыбор в админке HF? как вообще предполагается несколько значений вводить и передавать?

**Comment by glibin** [comment]
В Хантфлоу внедрено это поле с возможностью единственного выбора.

Если необходимо сделать множественный, то необходимо обратиться в службу поддержки клиентов.
