### ISSUE TITLE
Иинтеграция с Хантфлоу в части передачи орг.структуры (НИУ ВШЭ)

### ISSUE THREAD

**Issue by aastorozhuk** [huntflow/api#278]
1. Какую информацию необходимо передавать в блоке meta? Если не ошибаюсь, то блок meta не обязательный атрибут, можем без него обойтись?

**Comment by glibin** [comment]
Добрый день!

> Какую информацию необходимо передавать в блоке meta? Если не ошибаюсь, то блок meta не обязательный атрибут, можем без него обойтись?

Да, это необязательный параметр

> Также у нас были проблемы с id подразделений при разовой загрузке орг.структуры. При интеграции проблема останется или нет?

Поясните, о какой проблеме идет речь?

**Comment by aastorozhuk** [comment]
Наши ID выглядят вот так, буквенно-цифровые значения. Это будет проблемой при интеграции?
![image](https://user-images.githubusercontent.com/77738107/105330242-20bea180-5be3-11eb-887a-0b9d2f67bae4.png)

**Comment by aastorozhuk** [comment]
Скажите, пожалуйста, будут ли комментарии?

И скажите это обращение видно только мне и вам?

**Comment by glibin** [comment]
Проблем с такими идентификаторами быть не должно.

Если вы уже загружали подразделения, то можно получить текущий список из API: GET /account/<account_id>/divisions

**Comment by UncleMiF** [comment]
> И скажите это обращение видно только мне и вам?

всем видно, не понятно, почему приватные вопросы обсуждаются в публичном доступе

**Comment by glibin** [comment]
Вы пишете issue в публичный репозиторий, доступный всему интернету.

Для обсуждения приватных вопросов по API можно запросить данные у клиентского сервиса.

**Comment by aastorozhuk** [comment]
окей

**Comment by aastorozhuk** [comment]
> 1. Какую информацию необходимо передавать в блоке meta? Если не ошибаюсь, то блок meta не обязательный атрибут, можем без него обойтись?
