### ISSUE TITLE
Отклонение заявки заказчика на вакансию 

### ISSUE THREAD

**Issue by AlecsandrS** [huntflow/api#279]
Подскажите, возможно ли после того как заявка на вакансию будет отклонена. Средствами API зафиксировать факт её отклонения и получить комментарий который был оставлен при отклонении заявки. Именно при отклонении, в остальных случаях я вижу заявку и могу с ней работать. А после отклонения она исчезает, видимо удаляется.

**Comment by glibin** [comment]
Добрый день!

Мы планируем добавить в этом полугодии вебхуки на заявки по вакансиям. 
В этом варианте вы сможете сразу узнать изменения по статусу заявки.
