### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by erastovpavel** [huntflow/api#280]
Добрый день! Скажите пожалуйста ваше API предназначено только для сервера? Пытаюсь из браузера посылать запросы - получаю ошибку CORS.

**Comment by nikepan** [comment]
логично вроде)

**Comment by erastovpavel** [comment]
> логично вроде)

Логично, что API нельзя из браузра использовать? :)
Я не смог найти в документации упоминание о том, что на клиенте нельзя реализовать интеграцию. В итоге на клиенте есть возможность как-то интегрироваться или можно только с сервера запросы посылать вам?

**Comment by nikepan** [comment]
я не разработчик хантфлоу) большинство апишек не работает из браузера, так как это позволяет очень легко несанкционированно получить доступ к системе.
в некоторых сервисах, типа slack, вроде можно, но это мессенджер, который может получить данные только для своей же учетной записи. а в сервисах, в которых можно прочитать и модифицировать все данные (с постоянным токеном), это довольно рисково.

**Comment by erastovpavel** [comment]
У того же https://potok.io все работает с клиента, там так же как и в хантфлоу дается токен.

**Comment by glibin** [comment]
Добрый день!

Делать интеграции c API Хантфлоу из браузера мы не рекомендуем, так как на данный момент токен не может быть ограничен на определенные области действий и позволяет любому человеку (если токен находится в публичном виде на клиенте) получить полный доступ к базе резюме клиента, что может нарушать 152-ФЗ.
