### ISSUE TITLE
Использование гиперссылки.

### ISSUE THREAD

**Issue by VizgalovS** [huntflow/api#281]
Добрый день. Можно доработать ХФ таким образом, чтобы значение в поле использовать как гиперссылку?
Передавать через АПИ ссылку на сайт, после чего использовать один из двух вариантов:
1. Гиперссылка будет являтся отдельным полем?
2. Передавать в поле текст, но сделать его кликабельным (переходить по гиперссылке)?

**Comment by glibin** [comment]
Добрый день!

Вы про дополнительные поля для кандидатов?

**Comment by VizgalovS** [comment]
Да.

**Comment by glibin** [comment]
Тогда ответ положительный :-)

Вам необходимо обратиться к менеджерам клиентского сервиса для добавления поля кандидату с типом "ссылка" и видимостью в профиле кандидата.

**Comment by VizgalovS** [comment]
Это будет именно отдельное поле с типом ссылка (первый вариант)?
Или можно реализовать второй вариант?

**Comment by glibin** [comment]
Это будет одно поле с типом "ссылка" (и соответствующей валидацией). В интерфейсе будет кликабельна как ссылка.
