### ISSUE TITLE
приходит ответ в формате html

### ISSUE THREAD

**Issue by stokolyas-alexey** [huntflow/api#282]
Здравствуйте, хотелось бы узнать как работать с вашим API на python? 
Я отправляю get запрос с параметрами
    params={
        'User-Agent': 'App/1.0 (email)',
        'Host': 'api.huntflow.ru',
        'Authorization': 'Bearer {}'.format('token')
    }
и получаю ответ в формате html

**Comment by glibin** [comment]
На какой адрес вы отправляете запрос? Можете прислать пример кода?

**Comment by stokolyas-alexey** [comment]
params={
        'User-Agent': 'App/1.0 (mail)',
        'Host': 'api.huntflow.ru',
        'Authorization': 'Bearer {}'.format(''token')
    }
    response = requests.get('https://huntflow.ru/',params)

**Comment by bukhalo** [comment]
@stokolyas-alexey 

```diff
--- file.py	2021-02-01 19:29:26.000000000 +0300
+++ file-fix.py	2021-02-01 19:29:35.000000000 +0300
@@ -3,4 +3,4 @@
         'Host': 'api.huntflow.ru',
         'Authorization': 'Bearer {}'.format(''token')
     }
-    response = requests.get('https://huntflow.ru/',params)
+    response = requests.get('https://api.huntflow.ru/',params)

```

**Comment by stokolyas-alexey** [comment]
я внес изменения в код, но теперь он мне пишет
<Response [404]>
b'<html><title>404: Not Found</title><body>404: Not Found</body></html>'

**Comment by glibin** [comment]
Добрый день!

По адресу `https://api.huntflow.ru/` нет рабочих ресурсов, поэтому ответ 404. Попробуйте сделать запрос на любой описанный ресурс в документации, например: `https://api.huntflow.ru/me`

**Comment by stokolyas-alexey** [comment]
Спасибо, теперь ошибка сменилась на 401 код

**Comment by glibin** [comment]
В этом случае похоже, что вы передаете некорректный токен API

**Comment by stokolyas-alexey** [comment]
Да, я увидел в документации, что некорректный токен, или токена вообще не существует, но токен я просто скопировал из письма, как может быть скопированный токен невалидным?

**Comment by stokolyas-alexey** [comment]
<Response [401]>
{"errors": [{"type": "oauth", "value": ["bad_authorization"]}], "description": "Invalid access token"}
Такая ошибка вылезла, даже после смены токена, как быть? что делать?

**Comment by glibin** [comment]
Добрый день!

К сожалению, тут мы не можем помочь, так как не понимаем, почему у вас не работает токен, который должен работать. Возможно, вы некорректно передаете параметры в коде.

**Comment by stokolyas-alexey** [comment]
params={
        'User-Agent': 'App/1.0 (вставляю почту)',
        'Host': 'api.huntflow.ru/me',
        'Authorization': 'Bearer {}'.format('вставляю токен')
    }
    response = requests.get('https://api.huntflow.ru/me', params)
    print(response)
    вот пример передачи параметров в коде

**Comment by glibin** [comment]
Параметр Host некорректен. Его можно опустить при использовании библиотеки requests

**Comment by stokolyas-alexey** [comment]
не помогло

**Comment by stokolyas-alexey** [comment]
Как можно решить данную проблему? Как бы 5 дней прошло, я предоставил параметры, код, даже токен уже поменяли

**Comment by glibin** [comment]
К сожалению, мы не консультируем по вопросам использования языков программирования.

Но для вас сделаем исключение:

```
import requests

TOKEN = '<ваш токен>'
headers = {
    'User-Agent': 'App/1.0 (email@example.com)',
    'Authorization': 'Bearer {}'.format(TOKEN)
}

response = requests.get('https://api.huntflow.ru/me', headers=headers)

assert response.status_code == 200
```

**Comment by glibin** [comment]
Если пример не сработает, напишите на hello@huntflow.ru письмо со ссылкой на данный тикет или добавьте этот адрес в копию переписки с группой поддержки, где вам передавался токен доступа к API
