### ISSUE TITLE
Доступ к апи хантфлоу

### ISSUE THREAD

**Issue by VizgalovS** [huntflow/api#283]
Каким образом можно получить информацию, есть ли доступ у учётной записи к API хантфлоу?

**Comment by glibin** [comment]
Добрый день!

Не очень понял вопрос, но, возможно, нужно сделать запрос на 

https://github.com/huntflow/api/blob/master/ru/user.md#me

или 

https://github.com/huntflow/api/blob/master/ru/user.md#получение-информации-о-доступных-организациях
