### ISSUE TITLE
Вопрос по сохранению за заявкой на вакансию указанного подразделения

### ISSUE THREAD

**Issue by aastorozhuk** [huntflow/api#285]
Добрый день!
Подскажите как ведёт себя система в следующей ситуации?
Настраиваем регулярную загрузку актуальной орг.структуры в Хантфлоу. Менеджеры будут создавать заявки на вакансию, указывая в форме актуальное подразделение. 
Вопрос:
Будет ли в формах заявок, ушедшие в архив как отработанные, сохраняться прежнее название подразделения указанное в момент подачи, если через неторое время название подразделение изменится и в будущем будет попадать в Хантфлоу под другим именем? Не подменит ли новое название старое?
Аналогично для подразделений актуальных в момент подачи, но упраздняемых в будущем. Не произойдет ли стирания из архивной заявки?

**Comment by glibin** [comment]
Добрый день!

Коллеги передали, что ответят вам в почте.
