### ISSUE TITLE
Передача значения нестандартного поля по API

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#286]
Добрый день!
Для нашей компании было добавлено кастомное поле в вакансию. 
И возникло два вопроса :)
1. Как передать значение этого поля при создании вакансии через API?
2. Как использовать значение этого поля при создании исходящего вебхука?

Вопрос не по теме - где-то через веб-интерфейс можно увидеть файлы, переданные через API в Huntflow? Управлять содержимым этого хранилища?

Виталий

**Comment by SikSpears** [comment]
Речь идет о текстовом поле JiraIssue. Вот пример JSON'а, который передается:
{
	"position":"Тест",
	"JiraIssue":"Тест-123",
	"company":"",
	"money":"1000",
	"priority":0,
	"coworkers":"",
	"body":"",
	"requirements":"",
	"conditions":"",
	"hidden":"",
	"state":"OPEN",
	"files":[11893805]
}

**Comment by glibin** [comment]
> Как передать значение этого поля при создании вакансии через API?

Передать можно вместе с параметрами запроса. 
Вы можете прислать идентификатор вашей организации на hello@huntflow.ru со ссылкой на данный тикет, и мы пришлем перечень дополнительных параметров для передачи для вашей организации
