### ISSUE TITLE
Обновление кандидата

### ISSUE THREAD

**Issue by rgnmng** [huntflow/api#287]
Здравствуйте,
Необходимо обновить статус кандидата по его ID, в документации подобного не нашла. Есть ли на данный момент возможность или планируется ли добавление метода на обновление кандидата?
Заранее спасибо!

**Comment by glibin** [comment]
Добрый день!

Вы имеете ввиду обновление карточки кандидата (ФИО/контакты)?

**Comment by rgnmng** [comment]
Да, карточку кандидата, но поле event-status-name (получаем инфу от вас хуком и отправляем в Битрикс24, нужно при изменении статуса в Б24 менять статус кандидата в Хантфлоу). Возможно ли отправлять к вам вебхук, например, с ID кандидата и менять данное поле?

**Comment by glibin** [comment]
По изменению статуса кандидата можно получить информацию здесь: https://github.com/huntflow/api/issues/66
