### ISSUE TITLE
хантфлоу и прием откликов через гугл-форму

### ISSUE THREAD

**Issue by syanbasheva-svg** [huntflow/api#288]
Можно ли интегрировать гугл-форму с откликами от кандидатов с хантфлоу? 
И были ли успешные кейсы интеграции с тильдой?

**Comment by glibin** [comment]
Добрый день!

К сожалению, не сможем здесь что-то подсказать. Все клиенты делают интеграцию с Хантфлоу API и другими сервисами на свое усмотрение. О каких-то технических ограничений для этого мы не слышали.
