### ISSUE TITLE
вопросы по хэндлеру "Добавление кандидата в базу"

### ISSUE THREAD

**Issue by remort** [huntflow/api#29]
два вопроса:
- что есть account_id в url вызова ? откуда его брать ? это статичный ID клиента в вашем сервисе ?
- как загружать файлы ? у нас резюме в виде pdf-файлов. я вижу параметр files.id в теле запроса. как я понимаю файл грузится другим хэндлером и в ответ я получаю ID загруженного файла и использую уже в этом хэндлере ?

**Comment by glibin** [comment]
Добрый день!

> что есть account_id в url вызова ? откуда его брать ? это статичный ID клиента в вашем сервисе ?

получить его можно отсюда: https://github.com/huntflow/api/blob/master/ru/user.md#organizations

> как загружать файлы ?

https://github.com/huntflow/api/blob/master/ru/upload.md

**Comment by remort** [comment]
Спасибо
