### ISSUE TITLE
Получение списка подстатусов этапа подбора "Отказ"

### ISSUE THREAD

**Issue by kuatro** [huntflow/api#290]
Добрый день!

В документации описан [метод](https://github.com/huntflow/api/blob/master/ru/dicts.md#vacancy_statuses) для получения списка этапов подбора. 
Но "внутри" этапа "Отказ" имеются также подстатусы, получить которые не представилось возможным.

Может быть, этот метод просто незадокументирован? Есть ли какая-то возможность получить список подстатусов статуса "Отказ" через API?

**Comment by glibin** [comment]
Добрый день!

Список можно получить по следующему адресу:

```
GET /account/<account_id>/rejection_reasons
```
