### ISSUE TITLE
Дополнительные поля для комментариев

### ISSUE THREAD

**Issue by ahilis** [huntflow/api#292]
Нашел в тикетах возмодность добавления комментариев:
POST /account/<account_id>/applicants/<applicant_id>/log
там только два поля.
Какие еще данные можно отправить вместе с тектом? Интересуют:
1) Дата, отличная от NOW()?
2) Перенос строки. Видел, что с фронта уходит символ "↵", но при отправке его в API, он же и возвращается, вместо 
переноса

**Comment by glibin** [comment]
Добрый день!

> Дата, отличная от NOW()?

дата всегда запишется текущей

> Перенос строки. Видел, что с фронта уходит символ "↵", но при отправке его в API, он же и возвращается, вместо
переноса

перенос строки возможен, нужно использовать специальные символы переноса строки типа \r\n
