### ISSUE TITLE
Пул адресов, с которых отправляется вебхук

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#293]
Добрый день!
Подскажите, пожалуйста, есть-ли фиксированный пул адресов (адрес?) с которого будет приходить запрос по созданному webhook'у из huntflow? 
Эта информация необходима для организации whitelist на нашей стороне для получения запроса.
Спасибо!

**Comment by glibin** [comment]
Добрый день!

Такой пул адресов мы предоставить можем, но мы не можем давать гарантии, что он не изменится в будущем.

Наиболее оптимальный вариант использовать подпись запроса для проверки отправителя.

Если вы готовы взять на себя риск возможного изменения адресов, то напишите на hello@huntflow.ru с указанием ссылки на данный тикет и вашей организации в Хантфлоу.
