### ISSUE TITLE
Задваиваются затраиваются вебхуки

### ISSUE THREAD

**Issue by ovladimiro** [huntflow/api#294]
Через Альбато настроена интеграция хантфлоу с другими сервисами.

Почему то вчера (20.02.2021) вебхуки начали задваивать и затраивать информацию.
В бизнес процессах мы ничего не меняли.
Альбато служба поддержки сказали, что это на вашей стороне причина.

https://huntflow.ru/my/911hr#vacancy/2563442/filter/105966/id/12072131
https://huntflow.ru/my/911hr#vacancy/2563442/filter/105966/id/12072100
https://huntflow.ru/my/911hr#vacancy/2563442/filter/105966/id/12072181

вот как пример резюме по ним были затроены вебхуки...

___
Владимир

**Comment by glibin** [comment]
Добрый день!

У каждого события есть заголовок X-Huntflow-Delivery, пришлите его для всех проблемных событий, пожалуйста, мы разберемся с ситуацией.

**Comment by ovladimiro** [comment]
https://prnt.sc/106kuhz
https://prnt.sc/106kvs8

**Comment by ovladimiro** [comment]
[2021-02-25T12_52_28.137Z_new.albato.ru_chat_log.html.zip](https://github.com/huntflow/api/files/6043044/2021-02-25T12_52_28.137Z_new.albato.ru_chat_log.html.zip)

**Comment by ovladimiro** [comment]
это переписка с Альбато.... мало ли пригодится

**Comment by ovladimiro** [comment]
спросите у них, как различить две заявки?какой есть параметр отличный для каждого запроса
давайте другие скрины prnt.sc/106kz9j
для 1555 в Б24 prnt.sc/106l05b
и второй prnt.sc/106l0r3

**Comment by glibin** [comment]
Добрый день!

При добавлении кандидата на вакансию создается два типа события по вебхукам: VACANCY-ADD (факт добавления на вакансию) и STATUS (кандидат добавляется на конкретный статус).

В теле вебхука есть поле event.type с типом события:

<img width="255" alt="Screenshot 2021-02-26 at 11 27 38" src="https://user-images.githubusercontent.com/463881/109275325-a4446180-7825-11eb-974c-3f4971474bca.png">

Перечень всех типов доступен здесь: https://github.com/huntflow/api/blob/master/ru/webhooks.md#типы-действий-над-кандидатом

Кажется, вам нужно получать данные только по конкретным типам и фильтровать ненужные.
