### ISSUE TITLE
Загрузка exсel и pdf. 

### ISSUE THREAD

**Issue by stokolyas-alexey** [huntflow/api#295]
Добрый день.Уточните пожалуйста вопрос как загрузить файл excel в систему.
Также как и pdf?

**Comment by glibin** [comment]
Добрый день!

Если вы имеете ввиду возможность прикрепить файл к кандидату, то можно использовать метод https://github.com/huntflow/api/blob/master/ru/upload.md#загрузка-и-распознавание-файлов для загрузки файла, но не передавать заголовок `X-File-Parse: true` для распознавания.

**Comment by stokolyas-alexey** [comment]
А huntflow получается сам распознает, к какому кандидату прикрепить файл?

**Comment by glibin** [comment]
Нет, действия по загрузке файла и прикрепления к конкретному кандидату разделены.

В результате загрузки файла вы получите идентификатор загруженного файла, а дальше сможете его использовать для передачи, например, в комментарии по вакансии по кандидату.

**Comment by stokolyas-alexey** [comment]
Спасибо
