### ISSUE TITLE
История работы с кандидатом

### ISSUE THREAD

**Issue by stokolyas-alexey** [huntflow/api#296]
В API указано как получить историю работы с кандидатом.
Вопрос заключается в следующем, можно ли загрузить с помощью API историю работы с кандидатом?
Если можно, то с помощью каких команд это можно сделать?
Заранее спасибо

**Comment by stokolyas-alexey** [comment]
и ещё вопрос как прикрепить файл к созданному кандидату, если файл загружен и заем id файла

**Comment by glibin** [comment]
Добавить комментарий можно следующим образом:

POST /account/<account_id>/applicants/<applicant_id>/log

```
{
"comment": "Комментарий"
"applicant": <applicant_id>
}
```

Перечень возможных параметров доступен тут: https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

**Comment by stokolyas-alexey** [comment]
а если я хочу поменять статус или добавить письмо с эл почты?

**Comment by glibin** [comment]
По смене статуса можно посмотреть здесь: https://github.com/huntflow/api/issues/66

> добавить письмо с эл почты

что вы имеете ввиду?
