### ISSUE TITLE
Не отображаются вакансии на корп сайте, размещенные через API ХФ

### ISSUE THREAD

**Issue by VelvetNZ** [huntflow/api#297]
Добрый день.

С корп сайта пропали вакансии, размещенные в ХФ через API. 

![Capture1](https://user-images.githubusercontent.com/79808542/109431274-b1747280-7a16-11eb-9d31-4257d1117498.PNG)

**Comment by glibin** [comment]
Добрый день!

К сожалению, недостаточно информации. 

Пришлите, пожалуйста, запрос, которым вы подгружаете информацию о вакансиях, а также ваш account_id.

**Comment by VelvetNZ** [comment]
Здравствуйте.

 "serverAddress": "https://api.huntflow.ru",
      "pathToVacancies": "/account/1032/vacancies/",
      "pathToApplicants": "/account/1032/applicants/",
      "pathToUpload": "/account/1032/upload",
      "pathToDivisions": "/account/1032/divisions",

Этого достаточно?

**Comment by glibin** [comment]
Добрый день!

Также необходим полный запрос (параметры, заголовки, без авторизационных данных) за вакансиями, а также идентификатор вакансии, которая не попадает.
