### ISSUE TITLE
Как получить число отказов по каждому этапу за выбранный временной диапазон? 

### ISSUE THREAD

**Issue by moroz6dmitry0** [huntflow/api#298]
Сейчас я получаю список вакансий, для каждой вакансии по id получаю список кандидатов, и для каждого кандидата получаю историю работы с кандидатом. Фильтрую, удаляя события, выходящие за пределы диапазона времени.
Однако, в объекте события не содержится информация, какому этапу соответствует отказ. Могу я получить эту информацию каким-нибудь образом?

**Comment by glibin** [comment]
Добрый день!

Отказ – это тоже этап подбора. Вы можете получить перечень этапов подбора (https://github.com/huntflow/api/blob/master/ru/dicts.md#vacancy_statuses), взять оттуда отказ и фильтровать по нему. Также, в объекте может быть доп. параметр rejection_reason с указанием причины отказа (судя по соседним тикетам, вы его уже нашли).
