### ISSUE TITLE
Запрос на добавление типа изменений «движение по процессу»

### ISSUE THREAD

**Issue by vitkhab** [huntflow/api#30]
Здравствуйте.

Моя задача: по событию перемещения кандидата по процессу найма (из одного статуса в другой) отправлять нотификацию в Slack.

Описание ситуации: при перемещении карточки кандидата, мы обычно отправляем ему письмо, назначаем время интервью, оставляем комментарий. Каждое действие генерирует событие которое приходит в приложение.

Проблема: среди трех-четырех отправленных на вебхук сообщений я не могу определить критерий, по которому однозначно можно было бы судить о перемещении кандидата из одной категории в другую. Обычно, среди полученных по вебхуку нотификаций есть абсолютно идентичные, имеющие одинаковые “body” сообщений. 

Для решения проблемы, мне нужен признак по которому я мог бы отследить именно движение кандидата по процессу. Так как я сам не нахожу признака, я предлагаю ввести новый тип изменений {“event” : {“type: “APPLICANT-MOVED” } }
В будущем я бы хотел видеть более детализированные типы изменений и по другим событиям, например «MAIL-SENT», «CALENDAR-EVENT-CREATED» и т.д.

**Comment by glibin** [comment]
Для движения по процессу есть вебхук с type=STATUS, который отражает на какой этап был передвинут кандидат.

Изменения по отправке писем и событий календаря мы планируем добавить в обозримом будущем.

**Comment by vitkhab** [comment]
Проблема в том, что если при передвижении кандидата дополнительно отправить письмо, создать встречу в календаре и так далее, то приходит несколько событий с type=Status. Часто абсолютно одинаковых, совсем без различий в `body` пришедшего события.
Если я буду ориентироваться на type=Status, то на одно передвижения кандидата я буду присылать несколько нотификаций подряд. И я очень не хочу добавлять хранение состояний в свое приложение. Как я могу обоуйти проблему?

**Comment by glibin** [comment]
Мы сейчас готовим апдейт, в котором будет приходить дополнительный флаг, позволяющий корректно обработать эту ситуацию. Как только он выйдет, мы вам сообщим.

**Comment by glibin** [comment]
Поведение исправлено. Теперь генерируется только одно событие на одно действие пользователя.
