### ISSUE TITLE
Получение детального комментария

### ISSUE THREAD

**Issue by dinaintervolga** [huntflow/api#300]
Здравствуйте.
Кандидату на вакансию можно оставить комментарий через настраиваемые формы.
Получаю ID такого комментария методом /account/{account_id}/applicants/{applicant_id}/log
А как получить содержимое комментария по ID (с учетом, что там не просто текст, а заполнение формы) или по ID кандидата?

**Comment by glibin** [comment]
Добрый день!

К сожалению, функционала работы с формами обратной связи пока нет в API. 
Мы планируем ее добавить во втором квартале этого года.

**Comment by dinaintervolga** [comment]
Благодарю за ответ.
