### ISSUE TITLE
Не получаю список вакансий

### ISSUE THREAD

**Issue by spac3wyrm** [huntflow/api#301]
Добрый день!

Работают через api под следующей УЗ: {"name": "API Robot", "position": null, "email": "api55099@huntflow.ru", "phone": null, "locale": "ru_RU"}

1. Делаю запрос на получение [вакансий:]
https://api.huntflow.ru/account/55099/vacancies

Получаю ответ:
{"items": [], "page": 1, "count": 30, "total": 1}

Т.е. список пустой

2. Делаю запрос на получение списка кандидатов:
https://api.huntflow.ru/account/55099/applicants?page=1&count=30

Получаю нормальный ответ, но массив вакансий (links) всегда и у всех пустой.

Дайте пожалуйста комментарии по обеим ситуациям - что я делаю не так?

**Comment by glibin** [comment]
Добрый день!

У технического аккаунта API токена выставлено право "Видит только свои вакансии". Если это нужно изменить, то вы можете попросить управляющего рекрутера вашей организации сделать это в настройках организации для учетной записи API Robot.
