### ISSUE TITLE
Не получается подключиться к API

### ISSUE THREAD

**Issue by nastyabir** [huntflow/api#303]
Привет. 
Пытаюсь подключиться к API из питона и ловлю 404 ошибку. Подскажите пожалуйста что делаю не так?
import requests
header_params = {
    'GET': '/me HTTP/1.1',
    'Host': 'api.huntflow.ru',
    'Accept': '*/*',
    'User-Agent': 'App/1.0 (anastasiya.bir@instamart.ru)',
    'Authorization': 'Bearer my_token'
    }

requests.get(url = 'https://api.huntflow.ru/', headers=header_params)

Вместо my_token - указываю свой персональный токен

**Comment by glibin** [comment]
Добрый день!

Нужно поменять:

```
requests.get(url = 'https://api.huntflow.ru/me', headers=header_params)
```

а `'GET': '/me HTTP/1.1',` убрать (также, как и `Host`, `Accept`)

**Comment by nastyabir** [comment]
Сработало, спасибо!
