### ISSUE TITLE
account_division по foreign

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#304]
Добрый день!
Для нас добавили справочник организаций (структуру) в ХФ. Если этот справочник получить с помощью GET, то видно, что у элемента есть ID и foreign (который ID в нашей внутренней базе департаментов).
Но API создания новой вакансии ждет ID справочника именно в ХФ.
Есть-ли возможность создавать вакансию с указанным департаментом по foreign?
Спасибо!

**Comment by glibin** [comment]
Добрый день!

К сожалению, такая возможность сейчас есть для заявок на вакансии. Для вакансии такую возможность мы планируем добавить во втором квартале этого года.
