### ISSUE TITLE
Подключение к Power BI

### ISSUE THREAD

**Issue by Pavel-Qiwi** [huntflow/api#305]
Добрый день.
есть персональный токен, как оформить подключение api к Power BI из документации не очень понял как это сделать.

**Comment by glibin** [comment]
Добрый день!

К сожалению, мы не сможем проконсультировать по функционалу и возможностям Power BI

**Comment by Pavel-Qiwi** [comment]
Добрый день!
Я хотел уточнить не про функционал, а найти помощь в подключении API к BI.

По сути это же должна быть ссылка, где указывается потом токен?
Я пробовал использовать как базовый адрес api.huntflow, который указан в документации, но оформить подключение не получилось.

Скачайте Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Vitaly Glibin ***@***.***>
Отправлено: Friday, March 19, 2021 11:24:33 AM
Кому: huntflow/api ***@***.***>
Копия: Белоусов Павел Александрович ***@***.***>; Author ***@***.***>
Тема: Re: [huntflow/api] Подключение к Power BI (#305)


Добрый день!

К сожалению, мы не сможем проконсультировать по функционалу и возможностям Power BI

**Comment by glibin** [comment]
Если есть curl под рукой, то работоспособность токена можно проверить запросом:

```
curl -H 'Authorization: Bearer your_token' -H 'Accept: */*' -H 'User-Agent: App/1.0 (incaseoffire@example.com)' https://api.huntflow.ru/accounts
```

**Comment by Pavel-Qiwi** [comment]
К сожалению, нет под рукой




С уважением,
Белоусов Павел

***@***.***D4B956.38DBC540]
Тел.:+7 (916) 666-55-69

**Comment by Pavel-Qiwi** [comment]
Я пытаюсь сделать так:
***@***.***D71CD7.5A8DFC80]

Но полуаю вот это
***@***.***D71CD7.5A8DFC80]


Либо так

***@***.***D71CD7.5A8DFC80]
Но такая ошибка
***@***.***D71CD7.5A8DFC80]




С уважением,
Белоусов Павел

***@***.***D4B956.38DBC540]
Тел.:+7 (916) 666-55-69

**Comment by glibin** [comment]
Скриншоты не подгрузились :(

**Comment by Pavel-Qiwi** [comment]
![1](https://user-images.githubusercontent.com/80900126/111788738-7953a780-88d1-11eb-812c-f515b854b0e4.jpg)
<img width="340" alt="2" src="https://user-images.githubusercontent.com/80900126/111788773-82447900-88d1-11eb-832d-2ca6921310bf.png">
<img width="440" alt="3" src="https://user-images.githubusercontent.com/80900126/111788785-86709680-88d1-11eb-8449-68d766388ec6.png">
<img width="337" alt="4" src="https://user-images.githubusercontent.com/80900126/111788799-8a9cb400-88d1-11eb-8117-9bf30afbbcc1.png">
вот код запроса в BI
<img width="599" alt="5" src="https://user-images.githubusercontent.com/80900126/111789325-0eef3700-88d2-11eb-8f3b-b57b80690d02.png">

а теперь?

**Comment by glibin** [comment]
Все верно, по пути / нет каких ресурсов

запросите /accounts для получения идентификатора организации (account_id) и далее используйте его в других запросах

**Comment by Pavel-Qiwi** [comment]
вот так?
![image](https://user-images.githubusercontent.com/80900126/111792456-54f9ca00-88d5-11eb-8739-deeb62ed2a73.png)

**Comment by glibin** [comment]
К сожалению, у нас нет возможности консультировать по настройке PowerBI ввиду отсутствия соответствующего опыта.

**Comment by Pavel-Qiwi** [comment]
Моей коллеге, Беловой Александре, делали подключение в Tableu, может они похожи?

Скачайте Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Vitaly Glibin ***@***.***>
Отправлено: Friday, March 19, 2021 5:45:25 PM
Кому: huntflow/api ***@***.***>
Копия: Белоусов Павел Александрович ***@***.***>; Author ***@***.***>
Тема: Re: [huntflow/api] Подключение к Power BI (#305)


К сожалению, у нас нет возможности консультировать по настройке PowerBI ввиду отсутствия соответствующего опыта.

**Comment by glibin** [comment]
Добрый день!

К сожалению, опыта настройки Tableu у нас тоже нет.
