### ISSUE TITLE
Текст в Data

### ISSUE THREAD

**Issue by spac3wyrm** [huntflow/api#306]
Добрый день!
После миграции из старой системы в новую видим картину, когда API отдается все данные о кандидате в текстовом теге. Пример:

Алексей Богданов, [15.03.21 16:05]
API возвращает по нему данные в следующем формате:

**Comment by spac3wyrm** [comment]
Извиняюсь, не тот пример запостил, вот корректный вариант:
{

    "auth_type":"NATIVE",
    "files":[
        {
            "url":"https://store.huntflow.ru/uploads2/named/a/8/2/a829de1ddc85458635e57394f32fdc2d.html/6920188536510050188.html?s=qySuppJ8yXhRkfmwbsF2VQ&e=1615856688",
            "id":13933846,
            "content_type":"text/html",
            "name":"6920188536510050188.html"
        }
    ],
    "updated":"2021-01-21T15:28:05+03:00",
    "account_source":265837,
    "foreign":"13698679",
    "created":"2021-01-21T15:28:05+03:00",
    "key":null,
    "portfolio":{
    },
    "data":{
        "body":"Коновалова Лилия Менеджер 30.11.1995 г.р. (25 лет) Воронеж не готова к переезду Контакты: +7 (951) 862-78-42 klikon3029@gmail.com Резюме от 20.01.2021 (HH.ru) Управление персоналом, тренинги • Управление персоналом Занятость: полная занятость График работы: полный день не готова к командировкам Образование: высшее         Общий стаж: 3 года 2 месяца Опыт работы Октябрь.2020 — настоящее время 4 месяца Россельхозбанк Ведущий менеджер-операционист Обслуживание клиентов, продажа банковских продуктов. Июль.2018 — Октябрь.2020 2 года 4 месяца Сбербанк www.sbrf.ru, Финансовый сектор Менеджер по работе с клиентами Продажа банковских продуктов, выполнение плановых показателей, консультация клиентов Декабрь.2017 — Июль.2018 8 месяцев Сбербанк www.sbrf.ru, Финансовый сектор Продавец-консультант Продажа банковских продуктов и консульиация клиентов Обо мне Стрессоустойчивая, усидчивая, ответственная, пунктуальная. Легко обучаема. Образование 2017 Воронежский государственный аграрный университет им. Императора Петра I, Воронеж Экономика и менеджмента, Маркетинг Знание языков Русский — Родной Английский — A1 — Начальный Дополнительная информация Гражданство: Россия Желательное время в пути до работы: Не имеет значения Права категории B Разрешение на работу: Россия"
    },
    "id":13242257

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, в чем ваш вопрос?

**Comment by spac3wyrm** [comment]
Добрый день!
Вопрос в том, почему данные о пользователе в теге "data" выглядят как сплошной текст? Например у кандидата приведенного ниже тег data выглядит как структурированный json, где все поля (образование, дата рождения, email и тд) разложены по отдельным тегам.

https://huntflow.ru/my/qiwihr#applicants/filter/103487/id/11024429

**Comment by glibin** [comment]
Добрый день!

Это зависит от источника получения кандидата. 

При загрузке из файла в поле data.body подставляется текст резюме из файла.
Для резюме из нормализованных источников (джоб-сайты), формат данных нормализован и доступен в JSON.

**Comment by spac3wyrm** [comment]
Спасибо за ответ. В данном случае в качестве источника использовался estaff. В таком случае тоже данные берутся из файла? Дополнительно вопрос - как можно связать анкеты в huntflow с анкетами, загруженными из estaff?

**Comment by glibin** [comment]
> В таком случае тоже данные берутся из файла?

Скорее всего, да. 

> Дополнительно вопрос - как можно связать анкеты в huntflow с анкетами, загруженными из estaff?

Уже после произведенного переноса связать данные никак нельзя.
