### ISSUE TITLE
Получение кода API (бекенд)

### ISSUE THREAD

**Issue by Dzevriya** [huntflow/api#307]
Добрый день!
Я из компании Badoo. Для интеграции с внутренним сайтом нам необходим код API (бекенд) Ханфлоу. 
Подскажите, пожалуйста, в какие сроки я смогу получить запрашиваемый код?

**Comment by glibin** [comment]
Добрый день!

К сожалению, не очень понимаю ваш вопрос. Уточните, что вы имеете ввиду?

**Comment by Dzevriya** [comment]
Добрый день, Виталий! Нам нужен код вашей API для интеграции с нашими внутренними сервисами. 
Вы можете его предоставить?)


—
Носова Джеврия
Badoo
+7 926 317 1830

**Comment by glibin** [comment]
Могу предположить, что вам нужен ключ API. 

Для этого управляющий рекрутер вашей организации может обратиться в поддержку через чат в интерфейсе Хантфлоу или почту support@huntflow.ru

**Comment by Dzevriya** [comment]
Спасибо, да, речь про ключ. Спасибо!
