### ISSUE TITLE
id пользователя.

### ISSUE THREAD

**Issue by VizgalovS** [huntflow/api#308]
Добрый день.
По запросу GET /me описанном в https://github.com/huntflow/api/blob/master/ru/user.md, мы получили ответ без указания id.
{
   "name": "API Robot",
   "position": null,
   "email": "otp-api@huntflow.ru",
   "phone": null,
   "locale": "ru_RU"
}
Как получить id пользователя текущего токена?

**Comment by glibin** [comment]
Добрый день! 

А для чего он вам нужен? 

Если вам нужен account_id, то его можно получить https://github.com/huntflow/api/blob/master/ru/user.md#organizations
