### ISSUE TITLE
Coworkers

### ISSUE THREAD

**Issue by VizgalovS** [huntflow/api#309]
По ссылке https://github.com/huntflow/api/blob/master/ru/vacancies.md описан запрос на изменение вакансии.
Поле рекрутеры представленны массивом coworkers[]. Из примера не понятно, какое поле является элементами этого массива. Наименование и тип (имя рекрутера или его id)

**Comment by VizgalovS** [comment]
По какому запросу можно обратьиться к списку пользователей / рекрутеров?

**Comment by VizgalovS** [comment]
3. При получении списка вакансий используются параметры 
mine
opened
count, page
Требуется получить список закрытых вакансий в которых одно из доработанных полей имеет определённое значение. Возможна ли доработка АПИ со сотроны ХФ для учёта этого поля или другой способ получения заявок по заданному фильтру?

**Comment by glibin** [comment]
1. https://github.com/huntflow/api/issues/155
3. Такая доработка есть в планах на второй квартал
