### ISSUE TITLE
Отправка письма генерирует два события типа “COMMENT”

### ISSUE THREAD

**Issue by vitkhab** [huntflow/api#31]
При отправке письма кандидату, на webhook приходит два события с типом “COMMENT”. При этом сам комментарий может отсутствовать. При этом обе нотификации отличаются только в графе `{ “event” : { “applicant” : { “photo” : { “url” } } } }` в параметре `e` GET-запроса (последняя часть url).

Я ожидаю, что события с типом “COMMENT” будут генерироваться только при написании комментария кандидату. Что если тип события “COMMENT”, то в `body` запроса будет указан сам комментарий.

**Comment by glibin** [comment]
Добрый день!

Скорее всего, это связано с тем, что у комментария было событие или отправка письма, что порождает генерацию еще одного вебхука. Мы уже работаем над исправлением это проблемы.

Как только она будет исправлена, мы напишем в этом тикете.

**Comment by glibin** [comment]
Поведение исправлено. Теперь генерируется только одно событие (на момент написания комментария/действия).
