### ISSUE TITLE
Некорректное отображение Company при запросе через API

### ISSUE THREAD

**Issue by aastorozhuk** [huntflow/api#310]
Добрый день!

Мы настроили выгрузку вакансий с Хантфлоу к нам на Корпоративный портал, но при выгрузке получаем не корректные подразделения, хотя в Ханфлоу они указаны корректно.
Вот пример: 
 
![example](https://user-images.githubusercontent.com/77738107/112288119-15006180-8c9e-11eb-84bc-bcfd8d913849.png)

Таких подразделений у нас нет, как и нет их в Хантфлоу

Прошу помочь решить проблему. 

Приведу описание настроек API

Всего мы используем 3 метода:

— данные при обходе страниц списка вакансий https://api.huntflow.ru/account/12769/vacancies?opened=1&page=’ + page

— точные данные по вакансии https://api.huntflow.ru/account/12769/vacancies/’ + id

— забираем справочники (их всего два пока — prof & campus) https://api.huntflow.ru/account/12769/dictionary/’ + name

Поле company в данных содержит подразделение — мы его и отображаем.

Ранее открытые тикеты:

https://github.com/huntflow/api/issues/259 
https://github.com/huntflow/api/blob/master/ru/vacancies.md#add

**Comment by glibin** [comment]
Добрый день!

В вашей организации внедрены нормализованные подразделения, это значит, что в вакансии вам следует ориентироваться на поле account_division.

Сам справочник подразделений можно получить по запросу: GET /account/{account_id}/divisions
