### ISSUE TITLE
Ошибка 500 при добавлении кандидата на вакансию 

### ISSUE THREAD

**Issue by 9zigen** [huntflow/api#311]
Запрос

POST https://api.huntflow.ru/account/{secret}/applicants/{secret}/vacancy
Accept: application/json
User-Agent: App/1.0
Content-Type: application/json
Authorization: Bearer SECRET

{
  vacancy: 2658166, // реальное значение
  status: 108990, // реальное значение
  comment: 'API ОТКЛИК С HEADHUNTER',
  files: [],
  rejection_reason: null,
  fill_quota: null
}

Ответ

HTTP/1.1 500 Internal Server Error
Date: Thu, 25 Mar 2021 22:07:26 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 107
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: x-requested-with, content-type
Access-Control-Allow-Methods: POST, GET, OPTIONS

{
  "errors": [
    {
      "type": "server_error",
      "value": [
        "internal_error"
      ]
    }
  ],
  "description": "Internal Server Error"
}

Response code: 500 (Internal Server Error); Time: 396ms; Content length: 107 bytes

**Comment by glibin** [comment]
Добрый день!

> status: 108990, // реальное значение

статус удален, поэтому на него невозможно взять кандидата. Задачу на корректную обработку ошибки поставим.

**Comment by 9zigen** [comment]
Да, вы правы. Спасибо!
    {
      "id": 108990,
      "name": "Новые",
      "type": "user",
      "removed": "2021-02-05 09:41:31",
      "order": 1
    },
