### ISSUE TITLE
Фильтрация по списку кандидатов не соответствует документации

### ISSUE THREAD

**Issue by oudesab** [huntflow/api#313]
[Получение списка кандидатов](https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D0%B2)
> GET /account/{account_id}/applicants вернёт список кандидатов компании.
> 
> Принимаемые параметры:
> 
> status — этап подбора. Если передается, то вернутся только кандидаты, которые сейчас находятся на вакансиях на указанном этапе
> 
> vacancy — вакансия. Используется дополнительно к status для фильтрации кандидатов по вакансии на указанном этапе

Используется персональный токен.

Если передать только параметр `status`, то данные не возвращаются:
```
Sending: GET http://api.huntflow.ru:443/account/<account_id>/applicants?page=1&count=30&status=<status_id>
Response: {"items": [], "page": 1, "count": 30, "total": 1, "total_items": 0}
```
Если передать только параметр `vacancy`, то  данные фильтруются по вакансии:
```
Sending: GET http://api.huntflow.ru:443/account/<account_id>/applicants?page=1&count=30&vacancy=<vacancy_id>
Response: {"items": [<item>, ..., <item>], "page": 1, "count": 30, "total": <total>, "total_items": <total_items>}
```
Если в дополнение к параметру `vacancy` добавить параметр `status`, то  данные фильтруются по вакансии и этапу подбора:
```
Sending: GET http://api.huntflow.ru:443/account/<account_id>/applicants?page=1&count=30&vacancy=<vacancy_id>&status=<status_id>
Response: {"items": [<item>, ..., <item>], "page": 1, "count": 30, "total": <total>, "total_items": <total_items>}
```
Т.е. параметр `status` зависит от `vacancy`, а не наоборот, как указано в документации.

**Comment by glibin** [comment]
Добрый день!

На данный момент API работает указанным вами образом. Уточню у разработки изменение поведения, на описанное в документации.

**Comment by grmnga** [comment]
Добрый день. На сегодняшний день наблюдаем ту же ситуацию - при попытке отфильтровать кандидатов только по параметру `status` данные не возвращаются. Когда стоит ожидать изменение поведения на описанное в документации?

**Comment by saginsa** [comment]
@grmnga как-будто все работает как в документации на текущий момент. Т.е. фильтрую в облачной HF только по статусу и выводит список.

**Comment by grmnga** [comment]
@saginsa У нас проблема сохраняется - если фильтровать только по статусу, то возвращается пустой массив items. Если к фильтру по статусу добавить ещё и по вакансии, то приходит нормальный ответ. Вот [здесь](https://github.com/huntflow/api/issues/39) и [здесь ](https://github.com/huntflow/api/issues/87), вроде, подобные проблемы были.
