### ISSUE TITLE
Нестандартный справочник

### ISSUE THREAD

**Issue by UncleMiF** [huntflow/api#314]
добрый день

получили информацию, что в аккаунте 12769 у нас есть справочник divisions, который не доступен стандартным запросом (по /account/12769/dictionary/divisions)

+ имеет собственную структуру выдачи

почему нельзя было его реализовать в едином стиле со справочниками campus и prof?

**Comment by UncleMiF** [comment]
добрый день

вопрос актуален, ждём ответа

вы думаете как это переделать? или нам адаптироваться к текущему решению?

**Comment by glibin** [comment]
Да, к сожалению, это нестандартный справочник.

Справочник подразделений можно получить по запросу: GET /account/{account_id}/divisions
