### ISSUE TITLE
Получение списка заявок на вакансию

### ISSUE THREAD

**Issue by osotov** [huntflow/api#315]
Добрый день!
Столкнулся с аналогичной проблемой #21 
В интерфейсе вижу заявки на вакансию, которые еще не взяли в работу.
Отправляю запрос GET /account/{account_id}/vacancy_request - получаю:
```
[]
```
Через developer tools в браузере нахожу id одной из таких заявок на вакансию, отправляю запрос на GET /account/{account_id}/vacancy_request/{vacancy_request_id} - получаю:
```
{
    "errors": [
        {
            "type": "common",
            "value": [
                "Unknown vacancy request"
            ]
        }
    ]
}
```
Ожидаю увидеть результатом GET /account/{account_id}/vacancy_request заявки на вакансии, непривязанные к вакансиям.

**Comment by glibin** [comment]
Можете прислать идентификатор заявки, которую ожидаете получить?

**Comment by osotov** [comment]
Например, 28222

**Comment by glibin** [comment]
Добрый день!

Для технической учетной записи, связанной с API не проставлено право работать с заявками. Вы можете попросить управляющего рекрутера выставить соответствующее право для записи API Robot:

<img width="367" alt="Screenshot 2021-04-05 at 16 16 40" src="https://user-images.githubusercontent.com/463881/113577685-50017e00-962a-11eb-9939-27a506075fed.png">

**Comment by osotov** [comment]
Теперь всё работает. Спасибо!
