### ISSUE TITLE
Ошибка "Webhook url can't be reached"

### ISSUE THREAD

**Issue by alexsokolovby2019** [huntflow/api#316]
для проверки интеграции отключили вебхуки. Теперь проблема включить.
![image](https://user-images.githubusercontent.com/47452308/113301656-ed497300-9307-11eb-9bd8-4aaa0b8549e5.png)

вот urls:
https://script.google.com/macros/....exec?event=HF&type=candidate

https://script.google.com/macros/....exec?event=HF&type=vacancy

**Comment by alexsokolovby2019** [comment]
https://script.google.com/macros/s/AKfycbyxuj3Ol4kW0lCLcx6tdO3QLP27AbD9aXTy4pIeQuKGUz-iw1NN/exec?event=HF

**Comment by glibin** [comment]
Добрый день!

Вероятно, по какой-то причине адрес перестал отвечать кодом 200 на POST запрос. 

Подскажите, приходит ли запрос типа PING на указанные адреса от Хантфлоу?

**Comment by alexsokolovby2019** [comment]
а можно в скайпе пообщаться? alexsokolov_by

**Comment by alexsokolovby2019** [comment]
"Подскажите, приходит ли запрос типа PING на указанные адреса от Хантфлоу?"
Как это проверить?

**Comment by alexsokolovby2019** [comment]
![image](https://user-images.githubusercontent.com/47452308/113400210-1d495280-93aa-11eb-9fae-1b2374b1fa1a.png)

**Comment by alexsokolovby2019** [comment]
у скрипта есть лог,  я вижу, что запрос от HF туда долетает. Вот такой запрос:
request:{"parameter":{"event":"HF","type":"applicant"},"contextPath":"","contentLength":38,"queryString":"event=HF&type=applicant","parameters":{"event":["HF"],"type":["applicant"]},"postData":{"type":"application/json","length":38,"contents":"{\"id\": 11657, \"name\": \"*instinctools\"}","name":"postData"}}

**Comment by alexsokolovby2019** [comment]
https://drive.google.com/file/d/16DPavElPIG5eRZcgoa422HgsA3Q86KMr/view?usp=sharing
вот видео

**Comment by alexsokolovby2019** [comment]
Вопрос актуален на 05.04.2021.
Результат исследований:
При попытке актуализировать вебхук от Хантфлоу прилетает вот такой запрос:
request :{"parameters":{"event":["HF"],"type":["vacancy"]},"postData":{"contents":"{\"id\": 11657, \"name\": \"*instinctools\"}","length":38,"name":"postData","type":"application/json"},"contextPath":"","parameter":{"type":"vacancy","event":"HF"},"contentLength":38,"queryString":"event=HF&type=vacancy"}

как бы мы не обрабатывали этот запрос (возвращаем результат с 200) Хантфлоу отвечает "Webhook url can't be reached"

**Comment by glibin** [comment]
Добрый день!

Не могли бы вы прислать полные урлы для вебхуков на hello@huntflow.ru с указанием ссылки на данный тикет?

**Comment by alexsokolovby2019** [comment]
Отправил 2-мя письмами

**Comment by alexsokolovby2019** [comment]
убрал все логирование
вижу по скорости 3 сек 1-й и 4-5 сек 2-й вебхук

что еще можно сделать?

**Comment by glibin** [comment]
Разобрались в почте
