### ISSUE TITLE
Использование персонального токена

### ISSUE THREAD

**Issue by AndrewKr86** [huntflow/api#319]
Получили токен через саппорт. Все ок. Но, делается запрос по вашему примеру, но почему то возвращает некорректные данные. Использовал и вашу библиотеку и отдельно делал запрос результат один и тот же. Язык Python.
Подскажите что может быть не так?
Ответ:
![IMG_20210403_192823](https://user-images.githubusercontent.com/82083830/113830191-08483700-978f-11eb-9117-d79426037b3f.jpg)

**Comment by glibin** [comment]
Добрый день!

Ответ на экране выглядит корректным.

Подскажите, какое ожидаемое поведение для вас?

**Comment by AndrewKr86** [comment]
По крайней мере почта совсем другая. Это больше похоже на тестовый ответ. Далее когда пытаюсь получить список вакансий, то выдает всего 2 вакансии, те что используются в примере вашей документации

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, примеры запросов и ответов (чувствительные данные нужно будет удалить).
