### ISSUE TITLE
Не удается добавить Кандидата

### ISSUE THREAD

**Issue by mlenzovet** [huntflow/api#32]
1. ID 8656
2. Добавляем кандидата "Тестов Тест Тестович":
https://github.com/huntflow/api/blob/master/ru/applicants.md#add
3. Получаем код 200
4. В админке он не появляется, в списке кандидатов он не появляется

Что делать, помогите?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, запрос (заголовки и тело).

**Comment by mlenzovet** [comment]
@glibin примеры запросов в архиве.
Токены удалены
[Запросы.zip](https://github.com/huntflow/api/files/2851277/default.zip)

**Comment by glibin** [comment]
Из архива не понять в чем возникла проблема. Если кандидат добавился, то в результате должен вернуться его идентификатор. Проверить, что кандидат есть можно запросом GET /account/{account_id}/applicants/{applicant_id}

**Comment by mlenzovet** [comment]
@glibin в ответ мы получаем response.json (который представлен в архиве) и в нем нет пользователя, которого мы пытались добавить. При этом HTTP 200.

В итоге:
1. Добавляем пользователя ( запрос в архиве)
2. В ответ получаем HTTP 200 и список пользователей (скриншот в архиве)
3. В этом списке нет пользователя, которого мы пытались добавить, его ID узнать не можем (ответ в архиве)

Что делать?

**Comment by glibin** [comment]
судя по скриншоту вы используете http://api.huntflow.ru, а схема должна быть https

**Comment by mlenzovet** [comment]
Спасибо, кандидат добавился.

Пожалуйста, укажите явно в документации, что http и https дают разные результаты без сообщения об ошибке.

**Comment by glibin** [comment]
Данная информация указана здесь: https://github.com/huntflow/api/blob/master/ru/general.md#общая-информация
