### ISSUE TITLE
Нет данных

### ISSUE THREAD

**Issue by MIGbi** [huntflow/api#320]
Добрый день,

Проверьте пожалуйста аккаунт 57184 . Почему методы /me и /accounts возвращают ошибку 404. Но при этом метод /vacancies возвращает мне 30 вакансий, но предположу, что они тестовые. Наша организация занесла в хантфлоу уже сотни вакансий.
Токен использовал тот, который выслал нам сопровождающий нас менеджер.

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, запросы, которые отправляете (адреса и заголовки запросов), а также, заголовки и тело ответа от сервиса. Данные токена нужно можно из запроса.

**Comment by MIGbi** [comment]
Добрый день,

Высылаю скрин из Postman. На нём виден и метод, и ответ, и часть токена. Если нужно прислать весь токен, то сообщите об этом и сообщите конкретную почту на которую я смогу его переслать с соблюдением правил безопасности.
Все методы взяты из вашей документации

Метод /me возвращает 404-ую ошибку (то же самое и метод  /accounts)

***@***.***D72D35.55B104A0]

Метод /vacancies возвращает следующий текст:


{
    "items": [
        {
            "id": 2583744,
            "position": "Администратор",
            "company": null,
            "money": "38 000 gross+10 000 gross ежемес",
            "state": "CLOSED",
            "created": "2021-01-23T17:24:12+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33617,
            "applicants_to_hire": 3,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2654207,
            "position": "Врач терапевт на проект по вакцинации",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2021-03-15T17:34:35+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33342,
            "applicants_to_hire": 13,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2570751,
            "position": "Главный врач",
            "company": null,
            "money": "120 000",
            "state": "CLOSED",
            "created": "2020-12-10T19:15:55+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33383,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2662596,
            "position": "медицинская сестра процедурного кабинета",
            "company": null,
            "money": "35000",
            "state": "OPEN",
            "created": "2021-04-05T09:57:29+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 38197,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2655722,
            "position": "Менеджер по работе с НСИ",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2021-03-17T19:52:56+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33479,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2655717,
            "position": "Руководитель службы эксплуатации",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2021-03-17T19:44:55+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33618,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2653865,
            "position": "Санитарка",
            "company": null,
            "money": null,
            "state": "OPEN",
            "created": "2021-03-15T10:19:23+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 38201,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2655723,
            "position": "Старший администратор",
            "company": null,
            "money": null,
            "state": "OPEN",
            "created": "2021-03-17T19:55:51+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 33617,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2583742,
            "position": "Финансовый контролер",
            "company": null,
            "money": "120 000 gross+kpi",
            "state": "OPEN",
            "created": "2021-01-23T17:19:53+03:00",
            "hidden": false,
            "priority": 1,
            "deadline": null,
            "account_division": 38070,
            "applicants_to_hire": 3,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616429,
            "position": "1_РЕЗЕРВ",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2019-04-04T16:50:55+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616686,
            "position": "Bookkeepper",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2015-09-22T14:07:18+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2604904,
            "position": "CММ- менеджер",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2015-01-12T11:37:19+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616064,
            "position": "Cтарший бухгалтер по учету основных средств и материалов",
            "company": null,
            "money": "69000 – 69000",
            "state": "CLOSED",
            "created": "2014-02-18T17:11:12+04:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 2,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2604663,
            "position": "Digital  маркетолог",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2017-08-07T10:17:01+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616977,
            "position": "Event -менеджер",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2017-06-19T15:56:06+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 2,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2576412,
            "position": "HR",
            "company": null,
            "money": null,
            "state": "OPEN",
            "created": "2020-12-17T11:30:04+03:00",
            "hidden": true,
            "priority": 0,
            "deadline": null,
            "account_division": 33467,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2604644,
            "position": "HR BP/HR менеджер",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2017-07-19T09:42:31+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616283,
            "position": "HR Generalist ЗПИФ МЕД",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2020-02-20T18:05:46+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2663681,
            "position": "HR-менеджер",
            "company": null,
            "money": null,
            "state": "OPEN",
            "created": "2021-04-06T16:55:32+03:00",
            "hidden": true,
            "priority": 0,
            "deadline": null,
            "account_division": 33467,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2615821,
            "position": "HR ПЭТ Технолоджи",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2019-03-06T11:47:42+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 2,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616512,
            "position": "HR Руководитель департамента МЦВЛ",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2018-07-24T14:15:20+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616796,
            "position": "HR Руководитель департамента центров ядерной медицины ПЭТ",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2018-09-04T13:12:53+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616289,
            "position": "HR С&B",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2020-02-20T18:08:43+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616620,
            "position": "HR специалист по кадрам МЦВЛ",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2018-08-20T16:46:58+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616170,
            "position": "HR Старший менеджер по персоналу",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2018-06-18T16:48:36+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2605578,
            "position": "IT",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2009-01-20T11:20:06+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616743,
            "position": "IT Support КИПР",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2018-03-21T18:11:00+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2616616,
            "position": "IT - support (КИПР)",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2017-04-12T18:17:00+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2604820,
            "position": "IT директор",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2015-03-18T14:50:20+03:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        },
        {
            "id": 2604708,
            "position": "JAVA диволопер",
            "company": null,
            "money": null,
            "state": "CLOSED",
            "created": "2013-07-17T12:23:09+04:00",
            "hidden": false,
            "priority": 0,
            "deadline": null,
            "account_division": 40718,
            "applicants_to_hire": 1,
            "account_vacancy_status_group": null,
            "parent": null,
            "multiple": false,
            "vacancy_request": null
        }
    ],
    "page": 1,
    "count": 30,
    "total": 97
}






***@***.***D72D35.55B104A0]

С уважением, Шубин Дмитрий
Эксперт по аналитическим данным

+7 495 9884770 (доб.6050)
+7 903 6148108 (моб.)
Россия, Москва, 123112, ул. Тестовская, 10
***@***.******@***.***>      www.medinvest-group.ru<http://www.medinvest-group.ru/>

Правила использования информации<https://medinvest-group.ru/terms/>

**Comment by glibin** [comment]
@MIGbi я удалил ваш ответ, так как там могут содержаться чувствительные данные. Пришлите, пожалуйста, запросы /me и /accounts, которые отправляете (адреса и заголовки запросов), а также, заголовки и тело ответа от сервиса на адрес hello@huntflow.ru со ссылкой на данный тикет

**Comment by MIGbi** [comment]
Благодарю за оперативную помощь!
