### ISSUE TITLE
Метод vacancy_request возвращает пустой массив

### ISSUE THREAD

**Issue by MIGbi** [huntflow/api#322]
Ситуация аналогичная с описанной в данной заявке https://github.com/huntflow/api/issues/315 
При запросе /account/{account_id}/vacancy_request получаю `[]`

При этом наш менеджер подтверждает, что у записи API Robot выставлены все права и они аналогичны правам управляющего рекрутера.
![image](https://user-images.githubusercontent.com/55535148/114709750-a448e400-9d35-11eb-91ac-9c299cfc841d.png)

**Comment by glibin** [comment]
Добрый день!

Судя по скриншоту, вы отправляете запрос на получение вакансий, а не заявок на вакансию.
Документация по заявкам доступна здесь: https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#vacancy-request-list

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, ваш account_id

**Comment by MIGbi** [comment]
57184

**Comment by glibin** [comment]
Добрый день!

На данный момент в вашей организации не создано ни одной заявки на вакансию, поэтому возвращается пустой массив.

**Comment by MIGbi** [comment]
Спасибо!
