### ISSUE TITLE
Метод перемещения кандидата на другой этап

### ISSUE THREAD

**Issue by aleksandernovikov** [huntflow/api#323]
Добрый день!
Искал в доках по API, но не нашел метод который перемещает кандидата на другой этап подбора.
Помимо перемещения, необходимо оставить комментарий к кандидату.
такого метода тоже не обнаружил.

Благодарю заранее.

**Comment by aleksandernovikov** [comment]
кажется нашел в issues https://github.com/huntflow/api/issues/66

**Comment by aleksandernovikov** [comment]
отсылаю put запрос на url `/account/{account_id}/applicants/{applicant_id}/vacancy` с данными ```json
{
        "vacancy": 2664194,
        "status": 113243,
    }```
возвращается 500 ошибка.

**Comment by Rubinovna** [comment]
Добрый день! 

Удалите, пожалуйста, последнюю запятую в теле запроса:

{ 
"vacancy": 2664194, 
"status": 113243
}

**Comment by aleksandernovikov** [comment]
> Добрый день!
> 
> Удалите, пожалуйста, последнюю запятую в теле запроса:
> 
> {
> "vacancy": 2664194,
> "status": 113243
> }

Благодарю за ответ, в моих данных проблем нет, это кусок python dict кода который приводится в корректный json

**Comment by aleksandernovikov** [comment]
такого плана запрос
```python
...
    payload = {
        "vacancy": vacancy_id,
        "status": to_status_id
    }

    response = requests.put(url, data=payload, headers=headers)
...
```

**Comment by aleksandernovikov** [comment]
создал репозиторий с простым скриптом показывающим суть проблемы https://github.com/aleksandernovikov/huntflow_applicant_status/blob/main/main.py

**Comment by aleksandernovikov** [comment]
Разобрался с этим вопросом - конкретно этот эндпоинт не принимает form-data, хочет только json. Уверен что это необходимо исправить, ведь в 500 ошибку падать продакшену последнее дело.

Ну и неплохо было бы это это исправить и задокументирвать )))
