### ISSUE TITLE
Изменение ID кандидата при объединении

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#327]
Обнаружили следующее поведение:
Если добавить "похожего" кандидата в базу ХФ предлагает их объединить - это удобно. Однако при слиянии остается кандидат с новым ID, а старый ID  - удаляется.
В случае, когда работа с кандидатом интегрируется по его ID с внешними системами это недопустимо - при изменении ID на новый ожидаемо рвется настроенная по ID связь. 
Что можно предпринять, чтобы в случае объединения кандидатов существующая связь по ID не нарушалась?

**Comment by SikSpears** [comment]
При объединении huntflow кидает хук с событием double, где в поле source Id первого кандидата, а в applicant.id - id нового. Тем не менее мне кажется это очень странным поведением, когда уже существующие и, возможно, используемые объекты перетираются более новыми с заменой ID.

**Comment by glibin** [comment]
Добрый день!

При запросе кандидата (`/account/{account_id}/applicants/{applicant_id}`) по старому идентификатору вернется новый кандидат (с новый id). 
Поддержку методов работы с кандидатами с обработкой старого идентификатора мы планируем, но, к сожалению, дать какой-то ориентир по срокам пока не могу.

**Comment by SikSpears** [comment]
Благодарю за ответ
