### ISSUE TITLE
Вопросы по реализации части методов

### ISSUE THREAD

**Issue by aleksandrgordienko** [huntflow/api#329]
Организация `20246`. Помогите разобраться, пожалуйста.
1. Как узнать, используются ли в аккаунте справочники? Для получения содержимого справочника есть метод `/account/{account_id}/dictionary/{dictionary_code}`, а как получить список всех существующих кодов справочников в аккаунте? 
2. Получение схемы анкеты кандидата `/account/{account_id}/applicants/questionary` возвращает пустой ответ вида `{}`. Это ошибка? Или причина в том, что в указанном аккаунте нет настроенной анкеты?
3. Метод `/vacancies/{vacancies_id}/responses` на тестовых примерах возвращает 404. В следствие этого нет пока возможности понять работает ли `/vacancies/{vacancies_id}/responses/{responses_id}/letters`.
4. Метод `/account/{account_id}/applicants` при передаче значения параметра count больше допустимого (например, 100) начинает возвращать ошибку `{"errors": [{"type": "common", "value": ["Invalid request"]}]}`, вместо автоустановки длины страницы в 30. Возможно это исправить?

**Comment by aleksandrgordienko** [comment]
@glibin, спасибо за ответ!
3) По указанным методам информацию брал [отсюда](https://github.com/huntflow/api/blob/master/ru/responses.md).
4) Про 30 элементов максимум на страницу в этом методе понятно. Непонятно поведение при передаче значения больше 30ти. Остальные методы, поддерживащие pagination, просто заменяют бОльшее число на 30 и работают. А `/account/{account_id}/applicants` начинает падать, если `count` больше 30 передан. Получается, если вы измените максимальное значение на 25, то вызов этого метода перестанет работать у тех, у кого-то было настроено 30.

**Comment by glibin** [comment]
> 3) По указанным методам информацию брал отсюда.

это документация по платформе откликов и подразумевается, что это апи реализуется на стороне карьерного сайта. После осуществления интеграции Хантфлоу обращается к этому апи для публикации и сбора откликов 

> 4) Про 30 элементов максимум на страницу в этом методе понятно. Непонятно поведение при передаче значения больше 30ти. Остальные методы, поддерживащие pagination, просто заменяют бОльшее число на 30 и работают. А /account/{account_id}/applicants начинает падать, если count больше 30 передан. Получается, если вы измените максимальное значение на 25, то вызов этого метода перестанет работать у тех, у кого-то было настроено 30.

Уточним и исправим некорректное поведение, спасибо!
