### ISSUE TITLE
Получение company в GET /account/{account_id}/vacancies/{vacancy_id} для Кадровых агенств

### ISSUE THREAD

**Issue by dezollon** [huntflow/api#330]
Добрый день.
Просьба добавить параметр company в ответ на указанный запрос (https://github.com/huntflow/api/blob/master/ru/agency_vacancies.md) аналогично с запросом https://github.com/huntflow/api/blob/master/ru/vacancies.md#edit с этой страницы

**Comment by glibin** [comment]
Добрый день!

Можете, пожалуйста, привести пример запроса, для которого вы бы хотели получить поле company?

**Comment by dezollon** [comment]
Добрый день. 
мы выгружаем данные для аналитики и там необходимо указывать компанию, поскольку названия самих вакансий часто повторяются.

**Comment by glibin** [comment]
Добрый день! 

Передал ваш запрос на доработку. По срокам смогу сориентировать чуть позже.

**Comment by glibin** [comment]
Добрый день!

Проверьте, пожалуйста.
