### ISSUE TITLE
Как отфильтровать нужную вакансию в списке вакансий?

### ISSUE THREAD

**Issue by VladimirTugulev** [huntflow/api#336]
Здравствуйте. По запросу https://cdek-api.huntflow.ru/account/2/vacancies я получаю список всех вакансий. Подскажите, как отфильтровать определённую по её названию?

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности сейчас нет. Мы планируем добавить поиск по вакансиям в API в ближайшем будущем.
