### ISSUE TITLE
Невозможно увеличить кол-во объектов на странице при запросе кандидатов 

### ISSUE THREAD

**Issue by kuga14** [huntflow/api#337]
https://api.huntflow.ru/account/${accountId}/applicants?page=${pageNumber}&count=${pageCount}
При попытке установления входного параметра count в значение больше дефолтного 30, получаю ошибку 
{"errors": [{"type": "common", "value": ["Invalid request"]}]}

**Comment by Bolkonyashka** [comment]
Присоединяюсь. Также, параметр total_items отвечает за общее количество записей, а параметр total - за количество страниц, что не совсем очевидно из названия и не сходится с документацией https://github.com/huntflow/api/blob/master/ru/general.md#pagination

**Comment by glibin** [comment]
Добрый день!

> При попытке установления входного параметра count в значение больше дефолтного 30, получаю ошибку

Да, на данный момент, получение более 30 кандидатов за один запрос недоступно.

**Comment by kuga14** [comment]
> Добрый день!
> 
> > При попытке установления входного параметра count в значение больше дефолтного 30, получаю ошибку
> 
> Да, на данный момент, получение более 30 кандидатов за один запрос недоступно.

Планируются ли работы по добавлению такой возможности в ближайшей перспективе?

**Comment by glibin** [comment]
Да, мы планируем выпускать крупное обновление API эти летом.
