### ISSUE TITLE
Пропала интеграция Jira и Хантфлоу, компания Karuna

### ISSUE THREAD

**Issue by NastyaKaruna** [huntflow/api#339]

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, в чем ваш вопрос?

**Comment by NastyaKaruna** [comment]
добрый день! У нас сломалась интеграция с джирой, можете продлить еще раз на месяц доступ к нашему тестовому аккаунту, пожалуйста?

**Comment by glibin** [comment]
Добрый день!

Напишите, пожалуйста, на support@huntflow.ru ваш вопрос. Мои коллеги из службы заботы вам помогут.
