### ISSUE TITLE
Поле последнего изменения вакансии

### ISSUE THREAD

**Issue by Jeinara** [huntflow/api#341]
Хотелось бы иметь в вакансии не только поле createdDate, но и modifiedDate для сортировки по последним изменениям

**Comment by glibin** [comment]
Добрый день!

К сожалению, пока такая информация недоступна в API.
Как альтернативный вариант можно использовать вебхуки (https://github.com/huntflow/api/blob/master/ru/webhooks.md#типы-действий-по-вакансиям) для отслеживания изменений по вакансии.
