### ISSUE TITLE
Возможность получения резюме кандидата в формате файла(pdf)

### ISSUE THREAD

**Issue by razorbet** [huntflow/api#342]
Добрый день!
Подскажите, возможность получения по АПИ резюме в pdf формате удалось реализовать? Если нет, то какие сроки на добавление этого функционала?

https://github.com/huntflow/api/issues/271

**Comment by glibin** [comment]
Добрый день!

Пока данного метода нет в API, но есть в планах (точных сроков пока не смогу назвать).

Можете описать задачу, для которой вам необходим данный метод, чтобы мы могли иметь возможность скорректировать приоритет этой задачи?
