### ISSUE TITLE
Как правильно написать строку запроса на отправку данных.

### ISSUE THREAD

**Issue by olemanCdek** [huntflow/api#345]
СДЭК.
Добрый день, какая строка с запросом должна быть при помещении на сайт подразделений и должностей?
в мануале указано,что она выглядит следующим образом "/account/{account_id}/upload"
При получении данных мы прописываем строку /account/{account_id}/divisions или /account/{account_id}/dictionary/position_name, т.е. в конце указываем название справочника,который надо получить.
А при отправке данных получается не надо указывать название загружаемого справочника,просто прописать /account/{account_id}/upload и там сайт сам разберется куда относятся данные,так чтоли?
Если нет,то, где указать ,что данные относятся к справочнику divisions  или position_name?

**Comment by olemanCdek** [comment]
![Uploading image.png…]()

**Comment by olemanCdek** [comment]
![image](https://user-images.githubusercontent.com/84950516/119976812-dbbbd900-bfe1-11eb-9765-ef5885baf1c8.png)

**Comment by olemanCdek** [comment]
это если попытаться, как вы видите на скрине ,отправить json на  /account/80778/upload

**Comment by glibin** [comment]
Добрый день!

Метод `/account/80778/upload` используется для загрузки файлов.

Для загрузки справочников используются свои методы: 

Подразделения:
https://github.com/huntflow/api/blob/master/ru/account_divisions.md#метод-для-загрузки-подразделений

Справочники:
https://github.com/huntflow/api/blob/master/ru/dictionaries.md#редактирование-справочника
