### ISSUE TITLE
Добавление кандидата на вакансию

### ISSUE THREAD

**Issue by panopticum** [huntflow/api#346]
Добрый день!
Мы успешно добавляем кандидатов в базу.
После чего необходимо вновь добавленных кандидатов перекинуть на вакансию "Студент" в статусе "Новый", но добавляются они только в статусе "Оффер принят", что нам не очень подходит.
Подскажите, возможно ли добавление кандидатов на вакансию со статусом "Новый"? 
И с какими статусами можно добавлять кандидатов на вакансию?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, пример запроса на взятие кандидата на вакансию.

**Comment by panopticum** [comment]
Добрый день!

Пример запроса на взятие кандидата на вакансию:

{
    "vacancy": 2688169,
    "status": 115055,
    "comment": "Привет",
    "files": [
        {
            "id": 1382810
        }
    ],
    "rejection_reason": null,
    "fill_quota": 574853
}

Если указываем "status" 115055 "Оффер принят", то все ок, но нам этот
вариант не подходит, и мы хотим указать статус 115048 "Новые".
Скрины запросов во вложении

ср, 2 июн. 2021 г. в 13:31, Vitaly Glibin ***@***.***>:

**Comment by panopticum** [comment]
![Huntflow  Добавление кандидата на вакансию  Статус ОФФЕР ПРИНЯТ](https://user-images.githubusercontent.com/78788628/120472287-c0bce080-c3b6-11eb-90a0-cf8c191f6f37.PNG)
![Huntflow  Добавление кандидата на вакансию  Статус НОВЫЙ](https://user-images.githubusercontent.com/78788628/120472290-c1ee0d80-c3b6-11eb-8a1c-739592349f85.PNG)

**Comment by glibin** [comment]
Вы передаете status: 115055 , поэтому кандидат на него и попадает.
Полный перечень доступных этапов можно получить здесь: https://github.com/huntflow/api/blob/master/ru/dicts.md#vacancy_statuses

**Comment by panopticum** [comment]
Мы получаем список доступных этапов через:
![image](https://user-images.githubusercontent.com/78788628/121477881-6be22100-c9d9-11eb-8298-18bdfd9dc044.png)
Потом пытаемся перекинуть кандидата на этап из полученного списка, передавая status: 115048:
![image](https://user-images.githubusercontent.com/78788628/121478061-a51a9100-c9d9-11eb-8910-7ba650fddb35.png)
И получаем ошибку: "Fill quota is only acceptable for \"hired\" status"

**Comment by glibin** [comment]
Для этого этапа не нужно передавать поле fill_quota

**Comment by panopticum** [comment]
Спасибо за помощь!
