### ISSUE TITLE
Определение пользователя по логу

### ISSUE THREAD

**Issue by golovansergey** [huntflow/api#350]
Зевнул, когда работал с историей работы с кандидатом, принял `id` за `id` кандидата, а это оказался идентификатор лога... Теперь у меня есть jsonы событий без айдишек кандидатов. Можно ли по идентификатору лога восстановить id кандидата?

**Comment by glibin** [comment]
Добрый день!

Быстрого решение придумать не смогли. Попробуйте перезапросить весь набор данных.
