### ISSUE TITLE
Поиск по базе через api

### ISSUE THREAD

**Issue by regenun** [huntflow/api#351]
Добрый день!
Можно ли искать по базе по номеру телефона/почте/имени через api?
Необходимо делать запрос, чтобы возвращался какой-либо ответ

**Comment by regenun** [comment]
и еще момент
хочу получить информацию по вакансиям компании
вместо account_id подставляю id компании 
но получаю 
 "type": "common",
        "value": [
          "forbidden"


что делаю не так?

**Comment by Rubinovna** [comment]
Добрый день! 

Да, искать кандидатов можно, метод недокументированный, можно посмотреть в ответе https://github.com/huntflow/api/issues/85

Попробуйте использовать в вашем примере такой запрос:
/applicants/search?q=петров&?q=илья

**Comment by regenun** [comment]
Добрый день!
Спасибо

по такому запросу получаю id пользователей и какой-то score

есть ли возможность получать еще какую-либо информацию?

**Comment by Rubinovna** [comment]
По поиску вы получаете id кандидата, информацию по кандидату можно получить
GET /account/{account_id}/applicants/{applicant_id}
Историю работы — GET /account/{account_id}/applicants/{applicant_id}/log

**Comment by regenun** [comment]
и еще момент 
Есть ли возможность смотреть по всем кандидатам внутри хф компании, а не исходя из {account_id}?

**Comment by Rubinovna** [comment]
Такой возможности нет, запрос всегда включает в себя {account_id} — аккаунт вашей организации.
