### ISSUE TITLE
Назначение заказчика на вакансию.

### ISSUE THREAD

**Issue by BykZit** [huntflow/api#353]
Добрый день.
Помогите пожалуйста разобраться с проблемой:
Передаю put запрос для добавления заказчика к вакансии

PUT /account/{account_id}/vacancies/2695798
{
	"position": "Тест",
	"coworkers": [
		62123
	]
}

Приходит ответ с кодом 200:
{"id": 2695798, "parent": null, "account_division": null, "account_vacancy_status_group": null, "position": "\u0422\u0435\u0441\u0442", "company": null, "money": null, "state": "OPEN", "created": "2021-06-11T11:37:32+03:00", "source": null, "hidden": false, "priority": 0, "body": null, "requirements": null, "conditions": null, "deadline": null, "applicants_to_hire": 1, "multiple": false, "additional_fields_list": [], "files": [], "vacancy_request": null}

При этом все данные вакансии "Тест" очистились, но заказчик с id 62123 так и не добавился.
Права "Назначать коллег на вакансии" установлены.

Как на самом деле правильно добавить заказчика?
Как при этом не затереть остальные данные по вакансии?

Спасибо.

**Comment by glibin** [comment]
Добрый день! 

Для добавления заказчика на вакансию необходимо использовать метод (к сожалению, он не документирован):

POST /account/<account_id>/vacancy/<vacancy_id>/member/<account_member_id>

и передавать в теле доступные этапы подбора:

```
{
    "permissions": [
        {"permission": "status", "value": <идентификатор доступного заказчику статуса 1>},
        {"permission": "status", "value": <идентификатор доступного заказчику статуса 2>}
    ]
}
```

Для удаления с вакансии, необходимо использовать метод DELETE:

DELETE /account/<account_id>/vacancy/<vacancy_id>/member/<account_member_id>

**Comment by BykZit** [comment]
Огромное спасибо!
Все получилось!
