### ISSUE TITLE
Сломалась интеграция Jira и ХФ, компания Karuna

### ISSUE THREAD

**Issue by NastyaKaruna** [huntflow/api#354]
дравствуйте, у нас опять поломалась интеграция ХФ и Джиры, вы могли бы продлить аккаунт API Robot

Ответить12:45
Служба заботы Хантфлоу
Здравствуйте, у нас опять поломалась интеграция ХФ и Джиры, вы могли бы продлить аккаунт API Robot
Добрый день, Анастасия! Уточните, пожалуйста, возникла ошибка, что время жизни access_token завершилось?

13:05Ответить
да верно

Ответить13:24
Служба заботы Хантфлоу
да верно
В таком случае необходимо выполнить обновление пары access и refresh токенов по инструкции: https://github.com/huntflow/api/blob/master/ru/authorization.md#oauth_refresh_token.

13:26Ответить
мне кажется что вы просто усложняете, в прошлый раз мы также сложно решали и в итоге вы просто обновили аккаунт API Robot и все заработало

Ответить13:29
могу вас попросить это сделать?

Ответить13:29
Служба заботы Хантфлоу
могу вас попросить это сделать?
Уточним данный вопрос и вернемся к вам.

13:31Ответить
Спасибо, с нетерпением жду

Ответить13:31
Также проверили Токен - токен у нас рабочий

Ответить14:24
Подскажите, пжлста, есть ли какие-то новости?

Ответить14:24
пжлста продлите Karuna-API.

Ответить14:24
Служба заботы Хантфлоу
Подскажите, пжлста, есть ли какие-то новости?
Все еще разбираемся, как только будут новости — сразу напишем. Постараемся как можно скорее

14:25Ответить
Служба заботы Хантфлоу
Спасибо, подскажите, сколько по времени ожидать?
В течение часа-двух, постараемся поскорее

14:29Ответить
Служба заботы Хантфлоу
мне кажется что вы просто усложняете, в прошлый раз мы также сложно решали и в итоге вы просто обнов
Анастасия, проверили: учетная запись Karuna API действует до 18.06.2021. По всей видимости, нарушилось что-то другое. Попробуйте проделать, пожалуйста, вышеописанные действия по инструкции. Либо можете задать вопрос нашим техническим специалистам вот тут: https://github.com/huntflow/api

14:54Ответить

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, на адрес hello@huntflow.ru последние 6 цифр вашего API токена. Постараемся оперативно решить проблему.
