### ISSUE TITLE
При обновлении справочника Подразделения обновляется только последний элемент

### ISSUE THREAD

**Issue by olemanCdek** [huntflow/api#355]
Отправляю json ( прикреплен к задаче), при отправке его на сайт получаю сообщение со статусом OK и содержанием внутри Task_id и Уид последнего подразделения в списке jsonа (СДЭК Франчайзи). Все остальное не загружается, хоть и не пишет никаких ошибок.
В чем причина?
[Подразделения.txt](https://github.com/huntflow/api/files/6674543/default.txt)

**Comment by olemanCdek** [comment]
{"status": "ok", "payload": {"task_id": "c3d8bdef-ef4d-4925-817b-8f5f4d9c54da"}, "meta": {"data": {"items": [{"name": "\u0421\u0414\u042d\u041a \u0424\u0440\u0430\u043d\u0447\u0430\u0439\u0437\u0438", "foreign": "24199896-8381-11ea-bb9d-005056a4b52e"}]}, "account_id": 80778}}
Ответ на json, прикрепленный к задаче в текстовом документе "Подразделения"

**Comment by glibin** [comment]
Добрый день!

У вас некорректно составлен объект запроса. Пример объекта: https://github.com/huntflow/api/blob/master/ru/account_divisions.md#пример-запроса

**Comment by olemanCdek** [comment]
что именно не корректно? по этому примеру и делалось всё. У меня три начальных (основных) уровня подразделений, он берет последний только уровень

**Comment by glibin** [comment]
Тем, что в одном объекте (на одном уровне) множество ключей items
