### ISSUE TITLE
Вопрос по получаемым данным из API

### ISSUE THREAD

**Issue by MonVii** [huntflow/api#356]
Здравствуйте!
У меня вопрос относительно вашего API.
Подскажите, пожалуйста, можно ли с помощью метода GET /account/{account_id}/vacancies либо метода GET /account/{account_id}/vacancies/{vacancy_id} получать параметры со следующими данными:
1. какой именно рекрутер ведет вакансию;
2. дату закрытия вакансии;
3. указанный для вакансии проект. В самом Hunt Flow для вакансии можно задать такую сущность как "Проект".
Возможно, все эти данные ваше API возвращает, но в документации их не увидела.
Заранее спасибо!

**Comment by glibin** [comment]
Добрый день!

> какой именно рекрутер ведет вакансию;

Ответ можно посмотреть тут: https://github.com/huntflow/api/issues/155

> дату закрытия вакансии;

Можно получить запросом на https://api.huntflow.ru/account/{account_id}/vacancy/{vacancy_id}/logs

> указанный для вакансии проект. 

Кажется, у вас внедрены дополнительный поля вакансии. Значение поля должно возвращаться в запросе /account/{account_id}/vacancies/{vacancy_id}

**Comment by MonVii** [comment]
спасибо большое!
последний только вопрос: аналогичные параметры доступны и для [вебхуков](https://github.com/huntflow/api/blob/master/ru/webhooks.md)?

**Comment by glibin** [comment]
В вебхуках на действия по вакансиям приходит событие на закрытие с датой и временем действия.

Также приходят и дополнительные поля вакансии.

**Comment by MonVii** [comment]
отлично, еще раз спасибо!
