### ISSUE TITLE
Интеграция почты с сервисом huntflow

### ISSUE THREAD

**Issue by primepartners** [huntflow/api#357]
у нас есть корпоративная почта, на которую соискатели направляют резюме. речь о том, что нужно чтобы эти резюме АВТОМАТИЧЕСКИ попадали в хантфлоу
Как это сделать?
Токен имеется

**Comment by glibin** [comment]
Добрый день!

Вы можете написать скрипт интеграции, который будет периодически проверять ваш ящик, а далее через методы API добавлять кандидатов в Хантфлоу (https://github.com/huntflow/api/blob/master/ru/applicants.md#add).

**Comment by glibin** [comment]
Также, можно воспользоваться интеграционными сервисами типа Zapier или Albato

**Comment by primepartners** [comment]
Уточните, пожалуйста, куда вставлять этот скрипт?25.06.2021, 11:18, "Vitaly Glibin" ***@***.***>:
Добрый день!
Вы можете написать скрипт интеграции, который будет периодически проверять ваш ящик, а далее через методы API добавлять кандидатов в Хантфлоу (https://github.com/huntflow/api/blob/master/ru/applicants.md#add).
