### ISSUE TITLE
Набор вопросов по получению данных (заявки, сотрудники, квоты)

### ISSUE THREAD

**Issue by VladimirTugulev** [huntflow/api#358]
Здравствуйте.

Мы реализуем систему сбора данных из HuntFlow и загрузки их в нашу базу (для последующего использования этих данных в различной отчётности).

Как через API получить основную часть нужных нам данных мы разобрались (с помощью инструкции по api и представителя HuntFlow - Надежды).

Осталось несколько вопросов. Прошу помочь и указать, как организовать получение следующих данных:

**1. Перечень ВСЕХ ЗАЯВОК со следующими их характеристиками:**
- ID заявки (id)
- Должность (position)
- Дата создания заявки (created)
- ID создавшего заявку пользователя (account_info -> id)
- Имя создавшего заявку пользователя (account_info -> name)
- ID должности по штатному расписанию (values -> position)
- ID подразделения (values -> account division)
- Название подразделения (values -> work_place)
- Причина создания заявки (values -> reason)
- Желаемая дата выхода по заявки (values -> deadline)

**2. Перечень ВСЕХ рекрутеров и заказчиков со следующими их характеристиками:**
- ID сотрудника (id)
- Имя сотрудника (name)

**3. Перечень ВСЕХ когда-либо созданных по вакансиям КВОТ со следующими их характеристиками:**
- ID вакансии, по которой создана квота
- ID квоты
- ID заявки, на основе которой создана квота (если квота создана на основе заявки)
- Дата создания квоты
- Дата закрытия квоты
- Количество кандидатов, которых требуется нанять по квоте
- Набор нанятых по квоте кандидатов. Для каждого кандидата указывается:
   > Дата найма кандидата по квоте
   > ID кандидата

ВАЖНО:
Мы не можем реализовать нашу систему пока не узнаем, как эти данные получать.
Прошу дать чёткие и понятные указания по организации их получения (что и как делать).
Ваши инструкции я перенесу в техническое задание по созданию системы.
На его основе наши разработчики приступят к работе.

**Comment by glibin** [comment]
Добрый день!

> Перечень ВСЕХ рекрутеров и заказчиков со следующими их характеристиками:

Ответ есть здесь: https://github.com/huntflow/api/issues/155

> Перечень ВСЕХ ЗАЯВОК со следующими их характеристиками:
> Перечень ВСЕХ когда-либо созданных по вакансиям КВОТ со следующими их характеристиками:

К сожалению, готовых методов API для данных задач сейчас нет.

Организовать получение этих данных можно через службу поддержки с запросом на выгрузку вашей базы в формате JSON, а дальнейшие изменения можно получать через вебхуки (или договориться о периодической выгрузке базы на ваш SFTP-сервер, зависит от вашей задачи).

**Comment by VladimirTugulev** [comment]
> Добрый день!
> 
> > Перечень ВСЕХ рекрутеров и заказчиков со следующими их характеристиками:
> 
> Ответ есть здесь: #155
> 
> > Перечень ВСЕХ ЗАЯВОК со следующими их характеристиками:
> > Перечень ВСЕХ когда-либо созданных по вакансиям КВОТ со следующими их характеристиками:
> 
> К сожалению, готовых методов API для данных задач сейчас нет.
> 
> Организовать получение этих данных можно через службу поддержки с запросом на выгрузку вашей базы в формате JSON, а дальнейшие изменения можно получать через вебхуки (или договориться о периодической выгрузке базы на ваш SFTP-сервер, зависит от вашей задачи).

Опишите, пожалуйста, алгоритм получения данных по 2 и 3 вопросу через вебхуки. Чтобы я вставил Ваше описание в тех.задание для разработчиков (что, как и в какой форме мы должны делать, чтобы получать данные).

**Comment by glibin** [comment]
Добрый день!

Документация по вебхукам находится здесь: https://github.com/huntflow/api/blob/master/ru/webhooks.md

Получить всю необходимую информацию можно там. Консультаций по разработке технических заданий для интеграций мы не проводим.

**Comment by VladimirTugulev** [comment]
Виталий, здравствуйте.
Внимательно прочитал описание вебхуков.
Возникли следующие вопросы:
1. Нет вебхуков для фиксации информации о появляющихся заявках на вакансии (которые ещё не взяты в работу).
Как фиксировать их (и необходимую по ним информацию)?
2. Вебхук VACANCY, в котором фиксируются действия по вакансиям.
Не нашёл, в каких реквизитах этого вебхука сидят следующие данные:
 - ID созданной по вакансии квоты
 - ID заявки, на основе которой создана квота (если квота создана на основе заявки)
 - Дата создания квоты
 - Дата закрытия квоты
 - Количество кандидатов, которых требуется нанять по квоте
 - Набор нанятых по квоте кандидатов. Для каждого кандидата:
    - Дата найма кандидата по квоте
    - ID кандидата
Где мне взять эти данные?

**Comment by glibin** [comment]
> Нет вебхуков для фиксации информации о появляющихся заявках на вакансии (которые ещё не взяты в работу).
Как фиксировать их (и необходимую по ним информацию)?

Вебхуки на данную функциональность есть, но документация по ним находится в стадии оформления.

> Вебхук VACANCY, в котором фиксируются действия по вакансиям.

Уточните, пожалуйста, в каком кейсе вам нужна эта информация? 
Получить информацию по квоте можно через API: https://github.com/huntflow/api/blob/master/ru/vacancies.md#fill-quotas

**Comment by VladimirTugulev** [comment]
> > Нет вебхуков для фиксации информации о появляющихся заявках на вакансии (которые ещё не взяты в работу).
> > Как фиксировать их (и необходимую по ним информацию)?
> 
> Вебхуки на данную функциональность есть, но документация по ним находится в стадии оформления.
> 
> > Вебхук VACANCY, в котором фиксируются действия по вакансиям.
> 
> Уточните, пожалуйста, в каком кейсе вам нужна эта информация?
> Получить информацию по квоте можно через API: https://github.com/huntflow/api/blob/master/ru/vacancies.md#fill-quotas

Виталий,
здравствуйте.

1. По заявкам (которые нужно получать все, в том числе и пока не прикреплённые к вакансиям):
Коль нет пока оформленной документации, но сам вебхук есть: напишите, пожалуйста, название вебхука для фиксации появления и правки этих заявок. И скажите, из каких его реквизитов брать вот эти данные:
- ID заявки (id)
- Должность (position)
- Дата создания заявки (created)
- ID создавшего заявку пользователя (account_info -> id)
- Имя создавшего заявку пользователя (account_info -> name)
- ID должности по штатному расписанию (values -> position)
- ID подразделения (values -> account division)
- Название подразделения (values -> work_place)
- Причина создания заявки (values -> reason)
- Желаемая дата выхода по заявки (values -> deadline)

2.  По вебхуку VACANCY и квотам:
Нас интересуют прикрепляемые к вакансиям квоты и изменения по ним (когда в карточке вакансии меняют количество кандидатов, которых требуется нанять по квоте).
Сейчас (и мы это проверяли с Надеждой), по API можно получить информацию только о тех квотах вакансии, которые прикреплялись к ней после последнего её переоткрытия. А нам нужны ВСЕ квоты (они отражаются на фронте в карточке вакансии). По каждой квоте нам нужны следующие данные:
- ID вакансии, по которой создана квота
- ID квоты
- ID заявки, на основе которой создана квота (если квота создана на основе заявки)
- Дата создания квоты
- Дата закрытия квоты
- Количество кандидатов, которых требуется нанять по квоте
- Набор нанятых по квоте кандидатов. Для каждого кандидата указывается:
- Дата найма кандидата по квоте
- ID кандидата
Как их можно получить? По какому вебхуку и из каких его реквизитов?

Без данных по всем заявкам и всем квотам мы не можем создать наш куб, который закроет все потребности в отчётности (которая сейчас ведётся вручную в различных excel-файлах на основе выборок из HF).

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ. 
Мы готовим небольшую доработку, которая выйдет в ближайший день-два, и я вернусь с ответами на ваши вопросы.

**Comment by VladimirTugulev** [comment]
Ок, понял. Очень жду.

**Comment by VladimirTugulev** [comment]
Виталий, здравствуйте.
Всё никак не дождусь ответа от Вас. Уже полтора месяца.
Ответьте, пожалуйста, поскорее.

**Comment by glibin** [comment]
Добрый день!

> По заявкам (которые нужно получать все, в том числе и пока не прикреплённые к вакансиям):
Коль нет пока оформленной документации, но сам вебхук есть: напишите, пожалуйста, название вебхука для фиксации появления и правки этих заявок. И скажите, из каких его реквизитов брать вот эти данные:

По вакансии теперь приходит вебхук с типом VACANCY_REQUEST_ATTACH, в котором содержится информация о заявке, которая взята в работу по вакансии. Из доступной мне информации, перечисленные вами поля там должны приходить

> По вебхуку VACANCY и квотам:
> Нас интересуют прикрепляемые к вакансиям квоты и изменения по ним (когда в карточке вакансии меняют количество кандидатов, которых требуется нанять по квоте).

При изменении числа людей к найму приходит вебхук с типом EDIT с обновленной информацией по квотам. Всю дополнительную информацию можно дозапросить через API.

Нанятые по квоте кандидаты сейчас в API не возвращаются, но их можно получать через вебхуки по кандидату и передвижению кандидата на системный этап выхода на работу.

**Comment by VladimirTugulev** [comment]
> Добрый день!
> 
> > По заявкам (которые нужно получать все, в том числе и пока не прикреплённые к вакансиям):
> > Коль нет пока оформленной документации, но сам вебхук есть: напишите, пожалуйста, название вебхука для фиксации появления и правки этих заявок. И скажите, из каких его реквизитов брать вот эти данные:
> 
> По вакансии теперь приходит вебхук с типом VACANCY_REQUEST_ATTACH, в котором содержится информация о заявке, которая взята в работу по вакансии. Из доступной мне информации, перечисленные вами поля там должны приходить
> 
> > По вебхуку VACANCY и квотам:
> > Нас интересуют прикрепляемые к вакансиям квоты и изменения по ним (когда в карточке вакансии меняют количество кандидатов, которых требуется нанять по квоте).
> 
> При изменении числа людей к найму приходит вебхук с типом EDIT с обновленной информацией по квотам. Всю дополнительную информацию можно дозапросить через API.
> 
> Нанятые по квоте кандидаты сейчас в API не возвращаются, но их можно получать через вебхуки по кандидату и передвижению кандидата на системный этап выхода на работу.

Виталий,
здравствуйте.

Спасибо за ответ. Правда он оставил вопросы открытыми.
1. Как через VACANCY_REQUEST_ATTACH получить заявку (в том числе пока не прикреплённую к вакансии) с её характеристиками? Всяко её крутил, не могу никаких данных получить. Дайте, пожалуйста, ПРИМЕР запроса с GET, чтобы через эту строчку получить данные по заявкам (прикреплённым и не прикреплённым к вакансиям).
2. По алгоритму с EDIT также не ухватил, как получить информацию о всех квотах по вакансии (и тех, что прикреплялись к ней до переоткрытия вакансии). Опять же, дайте, пожалуйста, ПРИМЕР запросов с GET, через которые можно получить все квоты, которые прикреплялись к вакансии и до и после её переоткрытия.

Заранее спасибо. Владимир

**Comment by glibin** [comment]
Добрый день!

> Как через VACANCY_REQUEST_ATTACH получить заявку (в том числе пока не прикреплённую к вакансии) с её характеристиками? Всяко её крутил, не могу никаких данных получить. Дайте, пожалуйста, ПРИМЕР запроса с GET, чтобы через эту строчку получить данные по заявкам (прикреплённым и не прикреплённым к вакансиям).

В теле вебхука приходит объект vacancy_request с полными данными по заявке (с полями), поэтому никакой дополнительный запрос тут не нужен.

```
{
  "event": {
    "id": 419,
    "type": "VACANCY_REQUEST_ATTACH",
    "vacancy": {
      "id": 91,
      "applicants_to_hire": 1,
      "position": "awe",
      "company": null,
      "money": null,
      "state": "OPEN",
      "hidden": false,
      "priority": 0,
      "deadline": null,
      "account_division": {
        "id": 2544,
        "name": "Департамент ИТ"
      },
      "account_region": {
        "id": 5,
        "name": "Бегуницы"
      },
      "created": "2021-09-01",
      "multiple": false,
      "parent": null,
      "reason": "Новая позиция",
      "category": {
        "id": 2011,
        "name": "Топ-менеджер",
        "foreign": "Топ-менеджер",
        "meta": {
          "deadline": 90
        }
      },
      "fill_quotas": [
        {
          "id": 71,
          "applicants_to_hire": 1,
          "deadline": "2021-09-01",
          "vacancy_request": 8,
          "created": "2021-09-01 13:22:28",
          "closed": null
        }
      ],
      "frame_id": 91,
      "body": null,
      "requirements": null,
      "conditions": null
    },
    "created": "2021-09-01T13:22:28+03:00"
  },
  "account": {
    "id": 11,
    "name": "Huntflow"
  },
  "vacancy_request": {
    "id": 8,
    "account_vacancy_request": 13,
    "account": 1,
    "vacancy": 91,
    "position": "awe",
    "created": "2021-09-01 13:21:29",
    "updated": "2021-09-01 16:22:28",
    "changed": "2021-09-01 13:22:28",
    "removed": null,
    "states": [],
    "status": "approved",
    "account_info": {
      "id": 1,
      "name": "Денис",
      "email": "test@example.com"
    },
    "values": {
      "position": "awe",
      "account_division": 2544,
      "category": 2011,
      "_reason": {
        "reason": "Новая позиция",
        "reason_replacement": null
      },
      "money": null,
      "requirements": "<p>q</p>",
      "body": null,
      "deadline": "01.09.2021",
      "calc_deadline": null
    },
    "taken_by": {
      "id": 1,
      "name": "Денис",
      "email": "test@example.com"
    }
  },
  "vacancy_frame_fill_quota": {
    "id": 71,
    "vacancy_frame": 91,
    "vacancy_request": 8,
    "created": "2021-09-01 13:22:28",
    "changed": "2021-09-01 13:22:28",
    "applicants_to_hire": 1,
    "deadline": "2021-09-01",
    "already_hired": 0,
    "closed": null,
    "work_days_in_work": null,
    "work_days_after_deadline": null,
    "removed": null,
    "account_info": {
      "id": 1,
      "email": "test@example.com",
      "name": "Денис"
    }
  }
}
```

> По алгоритму с EDIT также не ухватил, как получить информацию о всех квотах по вакансии (и тех, что прикреплялись к ней до переоткрытия вакансии). Опять же, дайте, пожалуйста, ПРИМЕР запросов с GET, через которые можно получить все квоты, которые прикреплялись к вакансии и до и после её переоткрытия.

В вебхуке EDIT приходит информация по актуальным квотам у вакансии (fill_quotas). В них есть поле vacancy_request (данные по заявке можно получить здесь: https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#vacancy-request-view):

```
{
  "event": {
    "id": 106,
    "type": "EDIT",
    "vacancy": {
      "id": 5,
      "applicants_to_hire": 1,
      "position": "awes",
      "company": null,
      "money": "100",
      "state": "OPEN",
      "hidden": false,
      "priority": 0,
      "deadline": null,
      "account_division": {
        "id": 6592,
        "name": "Команда подбора"
      },
      "account_region": null,
      "created": "2021-07-27",
      "multiple": false,
      "parent": null,
      "division": {
        "id": 10976,
        "name": "Южный филиал",
        "foreign": "4581"
      },
      "responsible_recruiter": {
        "id": 13733,
        "name": "Маринина Марина Игоревна",
        "foreign": "61260"       
      },      
      "deadline_days": null,
      "comment": null,
      "description": "<p>ewq</p>",
      "fill_quotas": [
        {
          "id": 5,
          "applicants_to_hire": 1,
          "deadline": null,
          "vacancy_request": null,
          "created": "2021-07-27 13:41:01",
          "closed": null
        }
      ],
      "frame_id": 5,
      "body": null,
      "requirements": null,
      "conditions": null
    },
    "created": "2021-09-01T15:51:53+03:00"
  },
  "account": {
    "id": 17,
    "name": "Huntflow"
  }
}
```
