### ISSUE TITLE
Просмотр кандидатов пользователя

### ISSUE THREAD

**Issue by regenun** [huntflow/api#359]
добрый день
задача следующая - получить кандидатов (и логи) определенных пользователей в системе
Можно ли это реализовать каким-либо образом?
Через просмотр вакансий получается узнать id отдельного пользователя, но можно ли с этим id как-то далее работать?

Спасибо

**Comment by efimusmaximus** [comment]
Добрый день

Подскажите, какие именно логи по кандидатам и пользователям вам нужны? Имеете в виду действия по вакансиям?

**Comment by regenun** [comment]
Извините, некорректно объяснил
Можно ли у отдельного рекрутера посмотреть кандидатов?

Задача такая - по запросу через api узнать, какие кандидаты у рекрутера А имеют назначения по календарю и на когда именно

**Comment by bugoga47** [comment]
Также, интересует этот вопрос - как через api узнать список кандидатов  у конкретного рекрутера?

**Comment by efimusmaximus** [comment]
Коллеги, простите за такую длительную задержку с ответом.

К сожалению, прямого метода для получения списка кандидатов, добавленных конкретным рекрутером нет. Но вы можете сформировать его самостоятельно используя набор запросов описанных ниже

1) Получить список кандидатов: https://github.com/huntflow/api/blob/5e8747c76f6bf6774a5150b9ccc5b0ba6910778b/ru/applicants.md#applicants  
2) Получить лог по id каждого кандидата: https://github.com/huntflow/api/blob/5e8747c76f6bf6774a5150b9ccc5b0ba6910778b/ru/applicants.md#applicant_logs
3) Посмотреть id аккаунта рекрутера в первой записи "type": "ADD"
