### ISSUE TITLE
404 Not Found response

### ISSUE THREAD

**Issue by iMakushov** [huntflow/api#36]
Пытаюсь проверить авторизацию по персональному токену, но получаю ответ 404 Not Found
Нужна ли учетная запись в HuntFlow для работы персонального токена?
Моя текущая учетка, на которую был выдан токен, удалена из ХФ сейчас

**Comment by glibin** [comment]
Добрый день! Подскажите, каким образом вы проверяете авторизацию?

Персональный токен привязан к определённой учётной записи в Хантфлоу.
