### ISSUE TITLE
Уровень вложенности подразделения all_divisions

### ISSUE THREAD

**Issue by mazuretsma** [huntflow/api#360]
Добрый день, очень важная просьба.
Как можно увеличить вложенности подразделений для
`POST /account/{account_id}/all_divisions`
Текущая максимальная глубина в 5 уровней, как указано здесь [https://github.com/huntflow/api/blob/master/ru/account_divisions.md](url) это большая проблема. Это не позволяет нам загружать множество важных подразделений, имеющиеся на данный момент в нашей компании?

**Comment by glibin** [comment]
Добрый день!

Да, базовая вложенность подразделений 5.

Изменить на большее количество можно при размещении вашего Хантфлоу на выделенном инстансе. Для уточнения информации можно обратиться в службу заботы через внутренний чат в интерфейсе Хантфлоу или на почту support@huntflow.ru

**Comment by glibin** [comment]
Добрый день!

Обсудили с командой и увеличились вложенность до 10.
