### ISSUE TITLE
ошибка type: common value: forbidden при загрузке подразделений

### ISSUE THREAD

**Issue by aastorozhuk** [huntflow/api#361]
Здравствуйте!
При попытке загрузить структуру подразделений, следуя этому гайду https://github.com/huntflow/api/blob/master/ru/account_divisions.md сталкиваемся с ошибкой type: common value: forbidden
Скриншот
![image](https://user-images.githubusercontent.com/77738107/124118406-f74f4f00-da79-11eb-9828-ff80aff077b4.png)

При этом, например, запрос /me или /accounts проходим успешно.
 
![image](https://user-images.githubusercontent.com/77738107/124118223-c4a55680-da79-11eb-8765-b4abcb5b5643.png)

Вопрос: В чем может быть проблема?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, ваш  account_id.

**Comment by aastorozhuk** [comment]
61755

**Comment by glibin** [comment]
Ваш токен имеет привязку к роли рекрутера, а для управления подразделениями необходима роль управляющего. Обратитесь в поддержку клиентов (можно сделать через встроенный чат в интерфейсе Хантфлоу) для изменения роли для токена API со ссылкой на данный тикет.

**Comment by aastorozhuk** [comment]
Ок, спасибо.
А роль управляющего включает в себя роль рекрутера?

**Comment by glibin** [comment]
Да, конечно
