### ISSUE TITLE
Добавьте пожалуйста новый источник резбме - портал IRecommend.work

### ISSUE THREAD

**Issue by Madminder** [huntflow/api#363]
Наш проект развивается и у нас уже есть часть клиентов, которая хочет чтобы мы направляли резюме кандидатов в Вашу ATS. Прошу добавить системный account_source "IRecommend.Work", чтобы не заставлять каждого клиента добавлять руками новый источник.
Заранее спасибо!

**Comment by glibin** [comment]
Добрый день!

С пожеланиями об интеграции с сервисами можно обращаться на адрес support@huntflow.ru
