### ISSUE TITLE
Вопрос по вебхукам

### ISSUE THREAD

**Issue by raymann89** [huntflow/api#364]
Всем привет!

Контекст:
Работаю над автоматизацией процессов внутри компании и хочу забирать сотрудников из Хантфлоу после того, как они приняли оффер и переносить в другие системы.

Проблема:
Сделал вебхук, который отслеживает изменения по кандидату.
Но сейчас он реагирует на ВСЕ/ЛЮБЫЕ изменения.
Мне приходится фильтровать их на принимающей стороне.

Вопросы:
1. Можно ли и как настроить вебхук на конкретное поведение?
Например, только на изменение статуса на "Принят оффер".

2. Если такой возможности нет, может есть обходные пути решения?
3. Планируете ли добавлять такую возможность и когда?

**Comment by raymann89** [comment]
Дополнение:
в хуке не передается поле Telegram у пользователя, которое есть в анкете.
Скрин Хантфлоу
![Снимок экрана от 2021-07-14 19-09-34](https://user-images.githubusercontent.com/48382803/125655667-d998420b-7d0d-426b-9662-ce55a7289f77.png)
Скрин JSON'а
![Снимок экрана от 2021-07-14 19-11-06](https://user-images.githubusercontent.com/48382803/125655742-a38ea071-037b-4fd8-b5f0-7b6f0ed09102.png)

На сколько я предполагаю оно дополнительное/кастомное.
Можно добавить плиз?

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ.

> Можно ли и как настроить вебхук на конкретное поведение?

К сожалению, пока такой возможности нет.

> Если такой возможности нет, может есть обходные пути решения?

Фильтровать на стороне вашего решения события по event→type STATUS и нужному статусу event→status→id

> Планируете ли добавлять такую возможность и когда?

В ближайших планах у нас этого нет.

> в хуке не передается поле Telegram у пользователя, которое есть в анкете.

Создадим задачу на доработку, но точных сроков по реализации пока подсказать не смогу

**Comment by raymann89** [comment]
Добрый день!
Спасибо, что наконец-то ответили.
Будем ждать добавление Телеграма в вебхук.

> В ближайших планах у нас этого нет.
А вы понимаете масштаб неудобства?
114 ненужных запросов за один час, с 12 до 13 (еще не самый активный).
Это конечно не DDOS атака, но все равно неприятно.
Если для интеграции с вами использовать платформы Zapier и Integromat, можно считать, что Вебхуки у вас есть, но по факту нет. Ибо они быстро израсходуют лимит тасков (пример в скрине).
![Снимок экрана от 2021-07-22 15-20-26](https://user-images.githubusercontent.com/48382803/126638271-cbfd80d2-fef7-46c9-bf85-4f95932e57ab.png)

**Comment by glibin** [comment]
Спасибо! Хороший довод, обсудим с командой и подумаем как ускорить доработку.

**Comment by raymann89** [comment]
> Спасибо! Хороший довод, обсудим с командой и подумаем как ускорить доработку.

Благодарю!
Мы пока принимаем ваши хуки в Jira, надеюсь у них таких ограничений нет)

**Comment by raymann89** [comment]
Привет!

> > в хуке не передается поле Telegram у пользователя, которое есть в анкете.
> 
> Создадим задачу на доработку, но точных сроков по реализации пока подсказать не смогу

А можно получить честный ответ)
Создали задачу на доработку?
Потому, что добавить существующее поле в АПИ дело 5 минут.
И раз уж у вас есть поле и АПИ, а мы платим за это деньги,
Было бы круто сделать.

**Comment by glibin** [comment]
> Создали задачу на доработку?

Добрый день!

Задача на доработку находится в тестировании и, ориентировочно, выйдет в декабре.

**Comment by glibin** [comment]
> Создали задачу на доработку?

Добрый день!

Задача на доработку находится в тестировании и, ориентировочно, выйдет в декабре.
