### ISSUE TITLE
Ограничение на получение данных

### ISSUE THREAD

**Issue by Dmitryi** [huntflow/api#365]
Здравствуйте.

Пытаюсь одним запросом получить информацию по всем кандидатам, но ограничение по дефолту на последние 30 карточек/резюме кандидатов т.е. count=30. Добавил пагинацию, но всё тоже самое. ```https://api.huntflow.ru/account/<id>/applicants?page=1&count=100```
Как получить информацию по всем резюме, которые находятся в нашем аккаунте?

**Comment by glibin** [comment]
Добрый день!

Получить все данные одним запросом невозможно из-за ограничений на объем передаваемых данных. 
Последовательными запросами с учетом пагинации можно получить весь набор данных.

**Comment by Dmitryi** [comment]
Виталий, а возможно ли изменить это правило и сделать так что бы получать одним запросом всем данные?

**Comment by glibin** [comment]
@Dmitryi к сожалению, такой возможности нет

**Comment by Dmitryi** [comment]
@glibin Виталий можно добавить счётчик общего колличества страниц. Например, что бы в ответе можно было бы получить ответ сколько всего страниц (page). Как правило, обозначается  "$total_pages"

**Comment by Dmitryi** [comment]
С количеством страниц разобрался. Больше не актуально.
Но, возникло другое пожелание возможно ли добавить два поля место проживания - Страна и Город?

**Comment by glibin** [comment]
@Dmitryi вы можете добавить необходимое вам число полей в дополнительную информацию о кандидате через службу заботы (в чате внутри сервиса или через почту support@huntflow.ru)
