### ISSUE TITLE
Log validation error при обновлении до статуса "Предложение принято"

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#366]
Доброго дня!
Мы успешно передаем статусы в ХФ по кандидату через API. Но как только пытаемся передать статус 89036 получаем ответ:
{
    "errors": [
        {
            "type": "common.applicant",
            "value": [
                "Log validation error"
            ]
        }
    ]
}
Что бы это значило и как с этим бороться?
При этом в следующий статус - 89039 - удалось кандидата сдвинуть.

Статус точно есть - получаем его запросом к справочнику статусов:
            "id": 89036,
            "name": "Предложение принято",
            "type": "user",
            "removed": null,
            "order": 10

**Comment by glibin** [comment]
Добрый день!

Можете, пожалуйста, прислать полное тело проблемного запроса?

**Comment by SikSpears** [comment]
{
    "vacancy": 2711458,
    "comment": null,
    "status": 89036,
    "rejection_reason": null,
    "employment_date": "2021-07-30"
}

**Comment by glibin** [comment]
Добрый день!

В теле запроса также требуется передача параметра applicant с идентификатором кандидата.
employment_date необходимо передавать только на этапе с типом hired.

**Comment by SikSpears** [comment]
Добрый день! 
Благодарю, проверим. А зачем в теле передавать id applicant если он передается в самой ссылке?

**Comment by SikSpears** [comment]
Дело было именно в employment date. Спасибо!

**Comment by glibin** [comment]
> А зачем в теле передавать id applicant если он передается в самой ссылке?
