### ISSUE TITLE
Каким методом можно получить историю изменения вакансии

### ISSUE THREAD

**Issue by MIGbi** [huntflow/api#367]
Добрый день,
Как можно получить историю изменения вакансии как показано на следующем рисунке:
![status_Closed](https://user-images.githubusercontent.com/55535148/126337050-8d5f447e-adb4-4108-bba1-85cd47b127dd.png)

Обязательно нужны не только основные статусы CLOSED, OPEN и HOLD, но и подкатегории статусов изображенных на следующем рисунке:
![status_List](https://user-images.githubusercontent.com/55535148/126338287-fe6ed49e-10ee-4a26-9743-dcc99d5675da.png)

**Comment by glibin** [comment]
Добрый день!

Мы готовим документацию для метода https://api.huntflow.ru/account/<account_id>/vacancy/<vacancy_id>/logs

Можете начинать его использовать для получения истории работы по вакансии.
