### ISSUE TITLE
POST /account/{account_id}/applicants не пропускает спецсимволы

### ISSUE THREAD

**Issue by kvsystems** [huntflow/api#368]
POST /account/{account_id}/applicants
"externals": [{"data": **{ "body": "Тут не проходят спецсимволы"}** }]

response:
```json
[{  "errors": [{ "type":  "common" }]  }]
```
Как передать в поле body спец символы? html сущности передаются но не обрабатываются должным образом во вьюхе сообщения

**Comment by glibin** [comment]
Добрый день!

Данные в body интерпретируются как текст, поддержка html не предусмотрена.

По поводу ошибки: пришлите, пожалуйста, полное тело запроса.

**Comment by kvsystems** [comment]
Вот такое тело не пройдёт, будет ошибка на всех трех ковычках, и на переносе строки.

```js
let body = '

Ковычки 1 "Текст"

Ковычки 2 «Текст»

Ковычки 3 ‹Текст›

';
```

обертка их в html-сущности не распознается методом записи и они придут просто в таком виде прямо в отклик:

```
Ковычки 1 &quotes;Текст&quotes;
Ковычки 2 &laquo;Текст&raquo;
Ковычки 3 &lsaquo;Текст&rsaquo;
``` 

Перенос строки \r\n, \r, \n вообще сразу вызывают ошибку, естественно оформленные пользователями отклики на проходят в метод

И самое неприятное что ошибка всегда одна, может есть расширенный вариант?
``` shell
[{  "errors": [{ "type":  "common" }]  }]
```

Эти моменты очень неудобны.

**Comment by WeirdCarrotMonster** [comment]
Добрый день, не могу воспроизвести вашу проблему. Отправка всех вариантов кавычек, как их переносов строк, корректно создает кандидата:
```json
{
    "data": {
        "body": "\"Кавычки 1\"\n«Кавычки 2»\r‹Кавычки 3›\r\nПеренос строки"}, 
        "auth_type": "NATIVE", 
        "files": []
    }
]
```
![изображение](https://user-images.githubusercontent.com/935751/130440781-aceb2010-1c5e-49b6-a16e-a8f5376baf98.png)

Уточните, пожалуйста, полное тело запроса.

**Comment by kvsystems** [comment]
Пример тела:
```json
{
  "last_name":"Тест",
  "first_name":"Тест",
  "phone":"+7 (999) 999-99-99",
  "email":"h@jam.de",
  "externals":[{
    "data":{
       "body":"

	Ковычки 1 "Текст"

	Ковычки 2 «Текст»

	Ковычки 3 ‹Текст›

	"
      },
			
    "auth_type": "NATIVE"
  }]
}
```

Результат ответа: 
```json 
[{  "errors": [{ "type":  "common" }]  }]
```

**Comment by WeirdCarrotMonster** [comment]
Судя по всему, у вас некорректно сформирован JSON. Если тело запроса уходит в таком виде, в каком вы представили, то причина в переносе строки в body - стандарт не поддеживает такие переносы, их необходимо формировать через `\n`
