### ISSUE TITLE
Расхождения в данных полученных методом QUOTAS и отчетом построенным в интерфейсе HuntFlow

### ISSUE THREAD

**Issue by MIGbi** [huntflow/api#369]
Добрый день,
Скажите пожалуйста почему метод quotas возвращает вакансию только с одним значением vacancy_frame, но в отчете построенным в интерфейсе HF по одной вакансии два разных vacancy_frame.

![image](https://user-images.githubusercontent.com/55535148/126795987-15925e3f-c0f0-428a-9f2f-f1b1a2e86bfa.png)

Идентификатор вакансии: 2696860. При этом API возвращает vacancy_frame = 440886 (надо нанять 3 человека) . А отчет в интерфейсе HF кроме указанного идентификатора vacancy_frame  возвращает еще и 423836 (надо нанять 4 человека).

![image](https://user-images.githubusercontent.com/55535148/126796761-9fcf65ad-e7ec-4f6b-a495-1b28129f2d9e.png)

Как можно получить информацию по обоим vacancy_frame?

Идентификатор нашего аккаунта 57184

**Comment by glibin** [comment]
Добрый день!

Данный запрос отображает квоты только последнего периода открытия вакансии. 
У нас в планах есть доработки по возможности получения всех квот вакансии.

**Comment by MIGbi** [comment]
Сориентируйте пожалуйста по срокам претворения в жизнь планируемой доработки.

**Comment by glibin** [comment]
Добрый день!

https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancies/-vacancy_id-/frames/-frame_id-/quotas
