### ISSUE TITLE
Резюме при добавлении кандидата в базу

### ISSUE THREAD

**Issue by fedotovdmitry** [huntflow/api#37]
Подскажите как правильно прикреплять резюме (или прочие файлы) при добавлении кандидата в базу, тк метод, описанный в документации работает так, что для нового кандидата при добавлении создается новое пустое резюме, и файлы к нему не прикрепляются.
Как в таком случае можно загружать и прикреплять файл резюме через API?

```
POST /account/.../applicants HTTP/1.1
Host: api.huntflow.ru
Authorization: Bearer ...
Content-Type: application/json
Cache-Control: no-cache

{
    "last_name": "Имя",
    "first_name": "Фамилия",
    "externals": [
        {
            "files": [
                {
                    "auth_type": "NATIVE",
                    "id": 4826583
                }
            ]
        }
    ]
}
```

**Comment by glibin** [comment]
Похоже, что вы некорректно отправляете запрос. Корректный (https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0-%D0%B2-%D0%B1%D0%B0%D0%B7%D1%83):

```
"externals": [
        {
            "data": {
                "body": "Текст резюме\nТакой текст"
            },
            "auth_type": "NATIVE",
            "files": [
                {
                    "id": 12430
                }
            ],
            "account_source": 208
        }
    ]
```

**Comment by fedotovdmitry** [comment]
прошу прощения, json немного не тот скинул.
отправляется вот такой:
 
```
{
    "last_name": "Имя",
    "first_name": "Фамилия",
    "externals": [
        {
            "auth_type": "NATIVE",
            "files": [
                {
                    "id": 4826583
                }
            ]
        }
    ]
}
```

**Comment by glibin** [comment]
Вы можете добавить поле 
```
"data": {
                "body": "Текст резюме\nТакой текст"
            },
```

и добавится текст резюме. Сам текст можно получить при загрузке файла из поля text: https://github.com/huntflow/api/blob/master/ru/upload.md

**Comment by fedotovdmitry** [comment]
да, я понимаю, но вопрос в том, что не прикрепляется файл

**Comment by glibin** [comment]
Пришлите запрос, а также идентификатор кандидата, который был создан

**Comment by fedotovdmitry** [comment]
ИД созданного кандидата - 4726390

```
POST /account/20727/applicants HTTP/1.1
Host: api.huntflow.ru
Authorization: Bearer ...
Content-Type: application/json
Cache-Control: no-cache

{
    "last_name": "Имя",
    "first_name": "Фамилия",
    "externals": [
        {
            "auth_type": "NATIVE",
            "files": [
                {
                      "id": 4826583
                }
            ]
        }
    ]
}
```

**Comment by glibin** [comment]
Проверили по базе, файл добавился к резюме.
