### ISSUE TITLE
Как получить фио контактного лица, указанного в вакансии?

### ISSUE THREAD

**Issue by regenun** [huntflow/api#371]
Добрый день
При просмотре информации о вакансии не выводится информация о прикрепленном к данной вакансии контактном лице
Есть необходимость в получении через api имени (фио) контактного лица у определенной вакансии 
Как это можно сделать?

Спасибо

**Comment by glibin** [comment]
Добрый день! Уточните, пожалуйста, ваш account_id и, если есть возможность, прислать скриншот интерфейса с указанием места с данными о контактном лице, которое вам необходимо получить через API

**Comment by regenun** [comment]
account_id - 28651
Необходимо получить Контактное лицо 

<img width="1440" alt="Снимок экрана 2021-07-28 в 10 01 49" src="https://user-images.githubusercontent.com/14872391/127278611-a1ff876e-0bc6-44c6-882a-0487bb212855.png">

**Comment by regenun** [comment]
ожидаю ответ

**Comment by glibin** [comment]
Добрый день!

В запросе на вакансию возвращается поле client:

<img width="292" alt="Screenshot 2021-08-11 at 11 21 30" src="https://user-images.githubusercontent.com/463881/128995547-26a82b46-a709-44d8-9716-d820b18649aa.png">

Далее делаете запрос на клиента (https://github.com/huntflow/api/blob/master/ru/agency_clients.md#получение-клиента)

<img width="424" alt="Screenshot 2021-08-11 at 11 23 33" src="https://user-images.githubusercontent.com/463881/128995634-954f3ef7-a8bc-4ebc-b831-120abfeb32d5.png">

Подскажите, это то, что вам нужно?

**Comment by regenun** [comment]
не совсем
дело в том, что у клиента может быть 3-4 контактных лица, но к определенной вакансии относится только 1 контактное лицо
если я буду делать запрос на клиента, то получу все контактные лица

**Comment by WeirdCarrotMonster** [comment]
Понял ваш запрос, но на данный момент такого функционала нет.

**Comment by regenun** [comment]
есть ли возможность добавить это в ближайшее время?

**Comment by WeirdCarrotMonster** [comment]
К сожалению, я не могу ответить на этот вопрос.

**Comment by regenun** [comment]
Хорошо, есть ли у Вас возможность узнать по данному вопросу ответ?

**Comment by WeirdCarrotMonster** [comment]
Я передал запрос руководству. Ответим сразу, как появится какое-то решение.

**Comment by regenun** [comment]
Есть ли примерные сроки?

**Comment by WeirdCarrotMonster** [comment]
Выкатили релиз с доработкой, пример данных в документации: https://github.com/huntflow/api/blob/master/ru/agency_vacancies.md#получение-вакансии
