### ISSUE TITLE
Как получить информацию про уровень вакансии?

### ISSUE THREAD

**Issue by zhgolubeva** [huntflow/api#372]
Добрый день! В нашем кабинете есть свойство вакансии "уровень вакансии", но не понимаю, где лежит информация про него.

Спасибо!

**Comment by WeirdCarrotMonster** [comment]
Добрый день, на данный момент возможности получить дополнительные поля вакансии нет.

**Comment by WeirdCarrotMonster** [comment]
Добрый день. Если я правильно понимаю, вам нужны дополнительные поля вакансии. Их список содержится в ключе `additional_fields_list`, сами поля находятся в корневом документе.

Метод получения информации о вакансии: https://github.com/huntflow/api/blob/master/ru/vacancies.md#получение-вакансии
