### ISSUE TITLE
Нужна помощь с кодами ответов API Huntflow по методу /logs

### ISSUE THREAD

**Issue by ashteyn1** [huntflow/api#375]
В качестве кодов успешного ответа для метода /logs присутствуют 200 и 204
Хочется понять, является ли 204 классическим по смыслу (No Content), и можно ли быть уверенным, что ответ в таком случае не будет иметь в теле содержимого, т.е. валидных логов по запросу?

**Comment by glibin** [comment]
Добрый день!

Подскажите, в каком случае вам возвращается 204 при обращении к /logs?

**Comment by ashteyn1** [comment]
Добрый день, пока такой ситуации не было, но у нас есть уже интеграция с вами, и сейчас к ней мы хотим добавить проверку карточки по logs. Для этого мы хотим добавить интерпретацию респонза. Наш главный вопрос сейчас в том, можем ли мы считать 204 за успех, как 200, или не можем?

**Comment by WeirdCarrotMonster** [comment]
Не до конца понимаю ваш вопрос. Можете уточнить, какой метод API вы используете?

**Comment by ashteyn1** [comment]
Используем https://cdek-api.huntflow.ru/account/${ACCOUNT_ID}/applicants/${APPLICANT_ID}/log
Мы пытаемся написать механизм, который будет обращаться к вам по конкретному аппликанту и по данным из его лога определять необходимость выполнения дальнейшего сценария обработки аппликанта. Вопрос в том: если нам придёт 204 - стоит ли нам вообще смотреть в тело ответа? Или тело будет только при ответе 200?

**Comment by WeirdCarrotMonster** [comment]
Я не вижу в коде или документации поддержки статуса 204 для этого эндпоинта. 

https://github.com/huntflow/api/blob/master/ru/applicants.md#получение-истории-работы-с-кандидатом
