### ISSUE TITLE
Проблема с добавлением вакансии

### ISSUE THREAD

**Issue by yanglyev23** [huntflow/api#377]
Добрый день, возникла проблема с добавлением вакансии, хотя все обязательные поля я указал.
![image](https://user-images.githubusercontent.com/25932639/128668478-66afd695-f70c-45d5-bd4e-3a26d0e54137.png)
![image](https://user-images.githubusercontent.com/25932639/128668569-2b4ab1ec-237c-4805-a3af-a8c4cd7e49b5.png)

**Comment by glibin** [comment]
Добрый день!

Судя по ошибке, у вас компания кадровое агентство, поэтому API отличается https://github.com/huntflow/api/blob/master/ru/agency_vacancies.md#vacancy-add
