### ISSUE TITLE
Просмотр файлов, прикрепленных к кандидату

### ISSUE THREAD

**Issue by fedotovdmitry** [huntflow/api#38]
Файлы, прикрепленные при добавлении кандидата на вакансию, видны через API только при просмотре лога работы с кандидатом, в схеме ответа `get /account/.../applicants/...` файлов почему-то нет, это нормально?

**Comment by glibin** [comment]
При прикреплении кандидата на вакансию происходит запись в лог и соответствующие файлы прикрепляются к логу. Да, это нормально.

**Comment by fedotovdmitry** [comment]
То есть в ответе `/account/123/applicants/123` файлы и не должны отображаться? это достаточно неудобно

**Comment by glibin** [comment]
Да, не должны.
