### ISSUE TITLE
Получение обновлений о интервью по вебхук

### ISSUE THREAD

**Issue by ggorshenin** [huntflow/api#380]
Добрый день. На данный момент у нас настроена автоматизация о уведомлении о предстоящих интервью в слак через вебхуки. Но сталкиваемся с такой проблемой: вебхуки присылают информацию о назначении интервью, но если поменять, например, дату интервью - информация по вебхуку не приходит.
В итоге если мы назначаем интервью 10ого числа, а потом переносим его на 15ое - автоматизация все еще будет считать, что интервью должно быть 10ого, т.к. обновлений никаких не получает. Прошу помочь, как нам получать вебхуки о изменении даты интервью?

**Comment by WeirdCarrotMonster** [comment]
Добрый день, на данный момент вебхуки на изменение событий календаря не отправляются. Ваш кейс мне понятен, подниму вопрос о добавлении такого функционала.

**Comment by ggorshenin** [comment]
Добрый день, есть информация о добавлении этой фичи?

**Comment by solar-wind** [comment]
Дополню. Эта ситуация очень болезненна для нас. Часто коллеги смотрят на уведомления о собеседованиях в канале Slack как на основной источник информации. Офис-менеджеры ориентируются на эти сообщения для того, чтобы встретить кандидата, подготовить резюме. 
Сейчас выглядит так, что наша автоматизация и Хантфлоу работают плохо и ненадежно. Постоянно возникают вопросы где верная информация, в канале или календаре.

**Comment by glibin** [comment]
Добрый день!

Вышло обновление вебхуков (версия 2.0), где такая функциональность поддержана: https://github.com/huntflow/api/blob/master/ru/webhooks.md#тело-вебхука
