### ISSUE TITLE
Получить информацию из Оффера кандидата

### ISSUE THREAD

**Issue by mazuretsma** [huntflow/api#382]
Добрый день. У нас сейчас задача, получить поля "Заработная плата" и "Дата выхода" из Оффера.
Подскажите, как получить с помощью API информацию из Оффера кандидата?
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/86667369/129896442-e16bce04-f153-4247-951a-8d9e85259c71.png">

**Comment by WeirdCarrotMonster** [comment]
Добрый день, вы можете получить оффер по периоду открытия вакансии, используя метод 
`GET /account/{account_id}/applicants/{applicant_id}/vacancy_frame/{vacancy_frame_id}/offer`

Последний период открытия вакансии можно получить запросом
`GET /account/{account_id}/vacancy/{vacancy_id}/frame`

Примеры ответов сервера:
`GET /account/11/vacancy/40/frame`
```json
{
  "frame_begin": "2021-08-19 05:24:07",
  "frame_end": null,
  "vacancy": 40,
  "hired_applicants": null,
  "workdays_before_deadline": null,
  "removed": null,
  "workdays_in_work": 0,
  "id": 41
}
```

`GET /account/11/applicants/79/vacancy_frame/41/offer`
```json
{
  "id": 3,
  "account_applicant_offer": 10,
  "created": "2021-08-19T05:25:11+03:00",
  "values": {
    "whom_name": "test test test",
    "position_name": "123123",
    "whom_date": "19.08.2021",
    "offer_text": "<p>offer text</p>"
  }
}
```

**Comment by glibin** [comment]
Скорее всего, это значит, что у кандидата нет заполненного оффера, но нужно детальнее смотреть с полным информацией о запросе и ответе
