### ISSUE TITLE
Список этапов для каждой вакансии

### ISSUE THREAD

**Issue by MilaSharmanova** [huntflow/api#383]
Можно ли получить набор / упорядоченный список этапов для каждой вакансии? Сейчас можно выгрузить все этапы отбора, но ведь не все этапы присутствуют во всех вакансиях.

**Comment by WeirdCarrotMonster** [comment]
Добрый день, ID списка этапов передается в ключе `account_vacancy_status_group` вакансии. Способ получения этапов в списке сейчас уточняю.

**Comment by MilaSharmanova** [comment]
Здравствуйте. Уточняю, удалось ли понять, как по идентификатору account_vacancy_status_group узнать список этапов?

**Comment by WeirdCarrotMonster** [comment]
На данный момент такого функционала нет. Я передал запрос руководству.

**Comment by MilaSharmanova** [comment]
Спасибо! Когда можно будет уточнить, появился ли функционал?

**Comment by glibin** [comment]
Добрый день!

> Когда можно будет уточнить, появился ли функционал?

Ближе к концу этого года.

**Comment by MilaSharmanova** [comment]
Спасибо!
