### ISSUE TITLE
Выгрузка кандидатов по конкретным вакансиям вне зависимости от статуса

### ISSUE THREAD

**Issue by MilaSharmanova** [huntflow/api#384]
Можно ли выгружать кандидатов по конкретным вакансиям вне зависимости от статуса? Сейчас в ридми написано "vacancy — вакансия. Используется дополнительно к status для фильтрации кандидатов по вакансии на указанном этапе". 

Сейчас получается, чтобы скачать всех кандидатов вакансии мне нужно скачивать совсем всех кандидатов. Потому что отдельно по вакансии нельзя, списка привязанных к вакансии этапов у меня тоже нет (см issue #383).

**Comment by WeirdCarrotMonster** [comment]
Добрый день, API списка кандидатов позволяет использовать фильтры `vacancy` и `status` по отдельности. Неоднозначность описания в документации поправим.

**Comment by MilaSharmanova** [comment]
Спасибо!
