### ISSUE TITLE
Вопрос по получаемым данным из API

### ISSUE THREAD

**Issue by Svyatoslav94** [huntflow/api#386]
Коллеги, Добрый день.
По выгрузке данных у нас возник ряд вопросов.
1. При выгрузке карточки кандидата по методу api.huntflow.ru/account/*****/applicants/ applicants _id или аналогично если историю раскрыть (+log) мы не видим как выгрузить, кто «поставил дату создания кандидата в системе»
![image](https://user-images.githubusercontent.com/89248573/130411280-939d43a5-bc63-47c3-9a17-bccccad0f546.png)
Как и в целом нет доступа к «личным заметкам»
Возможно ли в целом получить информацию из «личных заметок», т.к. в дальнейшем мы планируем еще ряд статусов оттуда забирать.
2. При выгрузки карточки вакансии по пути api.huntflow.ru/account/*****/vacancies/Vacancy_ID
нет статусов вакансии. Конкретно нас интересуют:
-Взята в работу
-Закрыта
![image](https://user-images.githubusercontent.com/89248573/130411440-a5c3f1e3-f0b9-4861-9c1c-ba9aab608a4f.png)

Из всех данных нам доступно поле «created», но оно скорее всего берется также не отсюда.
Подскажите, каким методом мы можем выгрузить даты взятия работы и закрытия вакансии?

3. В карточке вакансии есть количество по квоте и количество нанятых по квоте.
 
![image](https://user-images.githubusercontent.com/89248573/130411463-88261bc0-1b41-44a7-b95d-746d7a783a26.png)

Используя api.huntflow.ru/account/*****/vacancies мы видим только количество по квоте.
 
![image](https://user-images.githubusercontent.com/89248573/130411476-77ea4281-b4fe-4e16-b4f6-6422ee3e0997.png)

Но именно количество нанятых по квоте ( в нашем примере «2») нет.
Подскажите, каким методом мы можем выгрузить количество нанятых по квоте?

**Comment by glibin** [comment]
Добрый день!

> При выгрузке карточки кандидата по методу api.huntflow.ru/account/*****/applicants/ applicants _id или аналогично если историю раскрыть (+log) мы не видим как выгрузить, кто «поставил дату создания кандидата в системе»

https://github.com/huntflow/api/blob/master/ru/applicants.md#applicant_logs

> При выгрузки карточки вакансии по пути api.huntflow.ru/account/*****/vacancies/Vacancy_ID
нет статусов вакансии. Конкретно нас интересуют:

ответ есть в тикете: https://github.com/huntflow/api/issues/367

> В карточке вакансии есть количество по квоте и количество нанятых по квоте.

информация доступна здесь:

https://github.com/huntflow/api/blob/master/ru/vacancies.md#fill-quotas
