### ISSUE TITLE
Пустой список кандидатов при фильтрации по статусу

### ISSUE THREAD

**Issue by osotov** [huntflow/api#389]
Добрый день. Возникла проблема аналогичная #87.
Делаю запрос GET https://api.huntflow.ru/account/14767/applicants?status=40528&page=1&count=30
Получаю:
```
{
    "items": [],
    "page": 1,
    "count": 30,
    "total": 1,
    "total_items": 0
}
```

Хотя в интерфейсе вижу кандидатов, находящихся в этом статусе. Ситуация аналогична для других статусов.
В настройках технической учетной записи не стоит галочка на пункте «Видит только свои вакансии».
А если сделать запрос GET /account/{account_id}/applicants/{applicant_id} на кандидата, который находится в статусе с id 40528, то в результате получаю его данные.

**Comment by WeirdCarrotMonster** [comment]
Добрый день, можете привести пример ID кандидата, который должен попадать в список?

**Comment by osotov** [comment]
Конеретно по этому статусу прямо сейчас нет кандидатов, поэтому возьмем другой: GET https://api.huntflow.ru/account/14767/applicants?status=84164&page=1&count=30. В ответе снова нет кандидатов, а их должно быть очень много. Например: 17884310, 17863762, 17828405

**Comment by glibin** [comment]
Добрый день!

Проверьте, пожалуйста, сейчас

**Comment by osotov** [comment]
Теперь данные доступны. Спасибо!
P.S. Это можно было сделать через какие-то настройки в интерфейсе?

**Comment by glibin** [comment]
@osotov к сожалению, только через техническую поддержку.
