### ISSUE TITLE
Получение списка кандидатов по Этапу подбора

### ISSUE THREAD

**Issue by AndreyOborin** [huntflow/api#39]
Добрый день. Не получается сделать запрос с отбором по Этапу отбора (Status).
Делаю такой запрос:
"/account/22403/applicants?page=1&count=30?status=53722" 53722 - код этапа подбора.

Запрос результат возвращает, но без применения фильтра по этапу подбора.

**Comment by glibin** [comment]
Похоже, что у вас неверный запрос:

`/account/22403/applicants?page=1&count=30**?**status=53722`

должно быть: 

`/account/22403/applicants?page=1&count=30&status=53722`

**Comment by AndreyOborin** [comment]
Спасибо. Сейчас попробую.

**Comment by AndreyOborin** [comment]
Что-то не работает, возвращается 2 массива external и links, оба пустые.

**Comment by glibin** [comment]
Пришлите пример ответа?

**Comment by AndreyOborin** [comment]
{"external": [], "links": []}

**Comment by glibin** [comment]
по какому кандидату?

**Comment by AndreyOborin** [comment]
Это в целом такой ответ приходит. Вместо списка кандидатов
--
Отправлено из Mail.ru для Android вторник, 16 апреля 2019г., 14:26 +05:00 от Vitaly Glibin  notifications@github.com :

**Comment by KrukovskiyVA** [comment]
Да, действительно. Всё ещё имеется такая проблема.

**Comment by KrukovskiyVA** [comment]
Кароч, ошибка в документации. Пишется следующее:
"vacancy — вакансия. Используется дополнительно к status"

По факту всё наоборот. vacancy может использоваться всегда. А вот status только в дополении к vacancy.

/account/{accountID}/applicants?vacancy={id}&status={id}

Запрос такого вида отрабаывает нормально.

**Comment by AndreyOborin** [comment]
Ок, спасибо. 
--
Отправлено из Mail.ru для Android вторник, 28 мая 2019г., 15:59 +05:00 от Viktor Krukovskij  notifications@github.com :

**Comment by glibin** [comment]
@AndreyOborin спасибо за долгое ожидание.

Мы проверили ваш аккаунт и у технической учетной записи API была настройка видимости только своих вакансий по этапам на открытых вакансиях. Мы ее поменяли на видимость всех вакансий и поэтому сейчас ваш запрос по этапу подбора без указания вакансии должен работать корректно:

`/account/22403/applicants?page=1&count=30&status=53722`
