### ISSUE TITLE
Проблемы с загрузкой файлов

### ISSUE THREAD

**Issue by kvsystems** [huntflow/api#390]
Каждый день сталкиваемся с проблемой загрузки резюме от кандидатов.
1. Не проходят файлы такого вида doc(text/html) например, а такие резюме существуют
2. Не проходят PDF с большим количеством изображений, по видимому из-за X-File-Parse: true (который нам нужен даже для таких портфолио)
3. Совершенно не понятна логика работы чтения полей X-File-Parse: true, например из резюме судя по ответу поля были прочитаны и были прочитаны верно, в отклике они не появляются, висит просто вложение

Хотелось бы получить расширенную информацию:
1. Ограничения X-File-Parse: true (количество полей, картинок, объем, MIME, расширения файлов)
2. Ограничения POST /account/{account_id}/upload (размеры, MIME, расширения файлов)
3. Примеры запросов для отображения полей из резюме, подробное описание работы сервиса

Заранее благодарен

**Comment by WeirdCarrotMonster** [comment]
Добрый день.

1. На данный момент загрузка файлов с типом `text/html` не поддерживаются системой из соображений безопасности
2. Может возникать проблема с извлечением текста из больших PDF-файлов. К сожалению, я не могу назвать точных ограничений - это больше зависит от самой структуры файла. Максимальный поддерживаемый размер загружаемого файла - 15 мегабайт.
3. Заголовок `X-File-Parse` используется только для извлечения данных файла в момент загрузки. Внутри системы эти данные не сохраняются. 

Для распознавания файлов предполагается использовать следующий порядок работы:
1. Загружаете файл с передачей `X-File-Parse: true`
2. Получаете в ответе поля `fields` и `text`
3. Используете их для [создания кандидата](https://github.com/huntflow/api/blob/master/ru/applicants.md#add) - поля из `fields` как основной набор данных, `text` - как текст прикрепленного резюме, вместе с ссылкой на файл

Кроме ограничения на размер файла, есть так же ограничение по типу. Допускается загрузка файлов со следующими content-type:
```
application/7z
application/CDFV2
application/encrypted
application/gzip
application/ics
application/java-archive
application/json
application/msword
application/octet-stream
application/oxps
application/pdf
application/pgp
application/pgp-signature
application/photoshop
application/postscript
application/rtf
application/vnd.android.package-archive
application/vnd.apple.keynote
application/vnd.apple.numbers
application/vnd.apple.pages
application/vnd.ms-excel
application/vnd.ms-excel.sheet.12
application/vnd.ms-excel.sheet.macroenabled.12
application/vnd.ms-office
application/vnd.ms-outlook
application/vnd.ms-powerpoint
application/vnd.ms-project
application/vnd.ms-tnef
application/vnd.ms-visio.drawing
application/vnd.ms-visio.viewer
application/vnd.ms-word.document.12
application/vnd.ms-word.document.macroenabled.12
application/vnd.ms-xpsdocument
application/vnd.oasis.opendocument.graphics
application/vnd.oasis.opendocument.presentation
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.text
application/vnd.openxmlformats-officedocument.presentationml.presentation
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.visio
application/wps-office.doc
application/x-7z-compressed
application/x-font-opentype
application/x-gzip
application/x-iwork-pages-sffpages
application/x-photoshop
application/x-rar
application/x-rar-compressed
application/x-setupscript
application/x-shockwave-flash
application/x-tar
application/x-zip-compressed
application/xml
application/zip
audio/mp3
audio/mpeg
image/bmp
image/erf
image/gif
image/heic
image/heic-sequence
image/heif
image/heif-sequence
image/jpeg
image/jpg
image/pjpeg
image/png
image/svg+xml
image/tiff
image/vnd.adobe.photoshop
image/x-ms-bmp
image/x-pcx
message/rfc822
multipart/related
text/calendar
text/css
text/csv
text/php
text/plain
text/rtf
text/vcard
text/x-asm
text/x-c
text/x-csharp
text/x-pascal
text/x-php
text/x-python
text/xml
video/mp4
video/quicktime
video/x-ms-wmv
video/x-msvideo
```
