### ISSUE TITLE
Получение списка заказчиков вакансии

### ISSUE THREAD

**Issue by snk26** [huntflow/api#391]
Приветствую!
Вижу в документации что параметр coworkers можно передать при добавлении новой вакансии, а при запросе вакансии параметр coworkers не выводится.
https://github.com/huntflow/api/blob/master/ru/vacancies.md

Помогите получить данные о заказчиках через API.

**Comment by SikSpears** [comment]
Добрый день! Тоже очень интересует этот вопрос.

**Comment by glibin** [comment]
Добрый день!

Ответ есть здесь: https://github.com/huntflow/api/issues/155
