### ISSUE TITLE
Не видим новых полей с данными

### ISSUE THREAD

**Issue by Dmitryi** [huntflow/api#392]
Добавили новые 4 поля в форму "Заполнить доп. информацию": Страна, Город, Discord и Соц. сети.
Хотим добавить в парсер новые поля, для сбора данных, но из 4х полей видим только одно - Соц. сети.
Где можно увидеть данные по новым полям?

**Comment by WeirdCarrotMonster** [comment]
Добрый день, можете уточнить ID кандидатов, с которыми возникают проблемы?

**Comment by Dmitryi** [comment]
Евгений, не видно по всей базе резюме, т.е. по всем кандидатам. Парсер не видит новых данных и не создаёт новой колонки в файле.

**Comment by glibin** [comment]
Добрый день!

Можете прислать свой account_id, а также примеры запросов/ответов, где вы ожидаете увидеть новые поля.

**Comment by Dmitryi** [comment]
@glibin  Виталий, отправил на вашу почту glibin.v@gmail.com
