### ISSUE TITLE
Настройка Rest соединения

### ISSUE THREAD

**Issue by Svyatoslav94** [huntflow/api#394]
Добрый день.

В рамках решения внутренних задач мы планируем настроить соединение HuntFlow с Data Services Designer (SAP).
В рамках подключения дана следующая информация:
https://help.sap.com/viewer/e54136ab6a4a43e6a370265bf0a2d744/4.2.9/en-US/5747cbeb6d6d1014b3fc9283b0e91070.html
"Укажите расположение WADL. Вы можете ввести URL-адрес или путь к локальному файлу WADL."
Попытки ввести https://api.huntflow.ru/ не увенчались успехом. Может Вы уже сталкивались с данным кейсом.

Возможно с Вашей стороны выдать нам файл WALD или путь к нему?

Спасибо.

**Comment by glibin** [comment]
Добрый день!

У нас нет WADL.
