### ISSUE TITLE
Не могу назначить рекрутера на вакансию

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#396]
Пытаюсь назначить рекрутера post запросом  
.../account/6/vacancy/16165/member/2916  

 Возвращает
```
{
    "errors": [
        {
            "type": "common",
            "value": [
                "pipeline.error.no_statuses"
            ]
        }
    ]
}
```

При запросе вакансии, в которой есть рекрутер, возвращает доуступ без статусов

```
"permissions": [
                {
                    "permission": "vacancy",
                    "value": null,
                    "vacancy": 16144
                }
            ]
```

Что нужно передать в телке, чтобы привязать рекрутера к вакансии на все статусы? (не перечисляя их, так как это не верно для рекрутера)

**Comment by glibin** [comment]
Добрый день, а откуда вы взяли идентификатор 2916?

**Comment by nikepan** [comment]
![image](https://user-images.githubusercontent.com/1618220/132220705-80a27307-177f-4336-b928-c4e8fbebed06.png)
из базы участников
общая задача - мигрируем из одной зеркала. нужно смигрировать назначенных рекрутеров. этот рекрутер точно есть в базе назначения

**Comment by glibin** [comment]
Из вашего скрина, судя по всему, нужно использовать поле id=2807.

**Comment by nikepan** [comment]
Спасибо! на 2807 возвращает

```
{
    "errors": [
        {
            "type": "validation.head",
            "value": [
                "error.recruiter_teams.empty_head"
            ]
        }
    ]
}
```

**Comment by glibin** [comment]
Это очень странно (и похоже на баг), но попробуйте в теле запроса передать:

```
{"head": 10}
```

10 взято из поля на вашем скрине (соответственно для нужного рекрутера брать его значение head)

**Comment by nikepan** [comment]
Сработало. спасибо!

**Comment by glibin** [comment]
Спасибо, баг заведем.
