### ISSUE TITLE
Снова не могу назначить рекрутера

### ISSUE THREAD

**Issue by nikepan** [huntflow/api#397]
Не успел вписать в предыдущий issue)

Если у пользователя пустой head, то его никак не привязывает.
Пытался без тела, и {"head": null}

У member вот такое содержимое

```
{
        "id": 3456,
        "member": 3621,
        "member_type": "manager",
        "head": null,
        "name": "****",
        "email": "*****",
        "meta": null,
        "permissions": []
}
```

Возвращает
```
{
    "errors": [
        {
            "type": "validation.head",
            "value": [
                "error.recruiter_teams.empty_head"
            ]
        }
    ]
}
```

**Comment by glibin** [comment]
Добрый день!

Самое быстрое сейчас: назначить руководителя рекрутеру. И потом назначить на вакансию. С ситуацией разберёмся и починим

**Comment by nikepan** [comment]
сработало. спасибо!
