### ISSUE TITLE
Как получить кандидатов у конкретного рекрутера

### ISSUE THREAD

**Issue by bugoga47** [huntflow/api#398]
Добрый день! Можно ли у отдельного рекрутера посмотреть кандидатов? Или же по какой схеме осуществляется связь (поля в запросе) между рекрутер <-> кандидат ?

**Comment by glibin** [comment]
Добрый день!

К сожалению, жесткой привязки конкретного рекрутера и кандидата нет.

Кандидат может рассматриваться на произвольном числе вакансий и связь кандидата с рекрутером можно попробовать построить через нее.

**Comment by bugoga47** [comment]
Реализовал, спасибо!
