### ISSUE TITLE
История удаления статусов

### ISSUE THREAD

**Issue by gde2313** [huntflow/api#399]
Здравствуйте! 

Логируем у себя историю работы с кандидатами. Вопрос в сохранении истории удаления, например, статуса у кандидата

Ручка /account/{account_id}/applicants/{applicant_id} возвращает текущий срез. Можно взять текущий срез, сравнить с тем, что мы у себя сохранили и из сравнения понять, что было удалено. Но такой формат выглядит не очень надёжно

Есть ли сейчас возможность получать информацию об удалённых статусах у кандидата?

**Comment by glibin** [comment]
Добрый день!

Сейчас в разработке находится задача по нотификации об удалении/изменении статусов кандидата через вебхуки. 

Приблизительный срок релиза – конец октября.

**Comment by glibin** [comment]
Добрый день!

Изменения теперь приходят в вебхуках версии 2.0: https://github.com/huntflow/api/blob/master/ru/webhooks.md#тело-вебхука
