### ISSUE TITLE
Изменение данных кандидата

### ISSUE THREAD

**Issue by AndreyOborin** [huntflow/api#40]
Добрый день.

Каким методом/запросом производится изменение данных существующего кандидата в Хантфлоу, например изменение этапа подбора по всем или одной вакансии. 

В документации есть методы, Добавления кандидата и кандидата по вакансии, подойдут ли эти методы для изменения данных по кандидату.

**Comment by vovadenisov** [comment]
Аналогичный вопрос. Есть ли возможность обновить резюме у кандидата или надо создавать нового если резюме могло измениться?

**Comment by glibin** [comment]
> изменение этапа подбора по всем или одной вакансии.

Изменение этапа подбора у кандидата возможно методом PUT, формат данных аналогичен добавлению на этап: https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

> Есть ли возможность обновить резюме у кандидата?

К сожалению, пока такого метода нет, но мы планируем его добавить в этом году.
