### ISSUE TITLE
Удаление заявки на вакансию

### ISSUE THREAD

**Issue by BykZit** [huntflow/api#400]
Добрый день!
Подскажите пожалуйста несколько моментов работы по API:
1. Есть ли возможность удалить заявку?
2. Есть ли возможность открепить заявку от вакансии?
3. Что произойдет с заявкой при удалении вакансии?
Спасибо!

**Comment by glibin** [comment]
Добрый день!

> Есть ли возможность удалить заявку?

Удалить заявку сейчас нельзя, но если она еще не взята в работу, то ее можно отклонить

> Есть ли возможность открепить заявку от вакансии?

Такой возможности сейчас нет

> Что произойдет с заявкой при удалении вакансии?

Она удалится вместе с вакансией

**Comment by BykZit** [comment]
Добрый день.
А как можно отклонить заявку по API, подскажите, пожалуйста.
