### ISSUE TITLE
Вопрос с конференции

### ISSUE THREAD

**Issue by Dmitryi** [huntflow/api#403]
Добрый день.
Сегодня (23.09.2021) прошел митап по API. Спасибо за доклады.
Возникли дополнительные вопросы.
У каждого клиента своя виртуалка на которой отдельная база хантфлоу, БД - PostgreSQL.
Вопрос: Возможно ли подключаться к БД по ssh и тащить данные из PostgreSQL напрямую?
На виртуалке навеняка линукс стоит.

**Comment by glibin** [comment]
Добрый день!

> У каждого клиента своя виртуалка на которой отдельная база хантфлоу, БД - PostgreSQL.

Нет, это не так. Облачные клиенты находятся на общем железе с логическим разделением баз.

> Возможно ли подключаться к БД по ssh и тащить данные из PostgreSQL напрямую?

Возможности подключиться напрямую к БД мы не предоставляем.

**Comment by Dmitryi** [comment]
Хорошо.
Спасибо.
