### ISSUE TITLE
Справочник подразделений

### ISSUE THREAD

**Issue by chepurovsky** [huntflow/api#406]
Добрый день!
Как получить справочник подразделений, при включенном подразделении?
В списке вакансий есть поле account_division, содержащее ID подразделений. Они имеют числовые значения.
Как прочитать сам справочник с айди и названиями подразделений?
В разделе Справочники нет информации об этом. В разделе "Работа с сервисом" тоже.

**Comment by glibin** [comment]
Добрый день!

Справочник подразделений можно получить по запросу: GET /account/{account_id}/divisions

**Comment by chepurovsky** [comment]
Виталий, добрый день!
Спасибо, получилось. Есть еще вопросы:

1. нет очень нужной связки менеджер-вакансия - поле coworkers в  таблице vacancies - отсутствует, а в описании есть.
Есть какая-то другая таблица связей вакансий и менеджеров? Как ее тогда загрузить (в описании этого нет)?
2. Не хватает справочников, и не ясно, как их загрузить:
    a. reject_reason (ссылается блок links из таблицы vacancies)
    b. account_vacancy_status_group (ссылается из таблицы vacancies)
    c. specialization (ссылается из таблицы vacancies)



С уважением,
Чепуровский Игорь
+7 968 680 0361
5 окт. 2021 г., 15:34 +0300, Vitaly Glibin ***@***.***>, писал:

**Comment by glibin** [comment]
> 1. нет очень нужной связки менеджер-вакансия - поле coworkers в  таблице vacancies - отсутствует, а в описании есть. Есть какая-то другая таблица связей вакансий и менеджеров? Как ее тогда загрузить (в описании этого нет)?

Как получить список пользователей в системе, а также список работающих по вакансии можно здесь: https://github.com/huntflow/api/issues/103

> a. reject_reason (ссылается блок links из таблицы vacancies)

`GET /account/<account_id>/rejection_reasons`

> b. account_vacancy_status_group (ссылается из таблицы vacancies)

Это идентификатор набора этапов подбора. К сожалению, он пока недоступен в API

>     c. specialization (ссылается из таблицы vacancies)

Вероятно, это ваш специфичный справочник. Пришлите, пожалуйста, ваш account_id, попробуем найти.

**Comment by chepurovsky** [comment]
Виталий, спасибо большое! И особенно за оперативность!!!!:)

account_id, вероятно 2.  Компания Ланит.
Во всяком случае на чтение к сервису обращаемся вот так https://lanit-api.huntflow.ru/account/2/divisions

И еще вопрос - нужен город вакансии. Его как-то ведут и заполняют. В инструкции этого нет.

По coworkers - понял, попробую.
А как среди них определить ответственного менеджера (отвечающего за вакансию), если их работает несколько над одной большой или сложной вакансией?

С уважением,
Чепуровский Игорь
+7 968 680 0361
5 окт. 2021 г., 15:44 +0300, Vitaly Glibin ***@***.***>, писал:

**Comment by glibin** [comment]
> specialization (ссылается из таблицы vacancies)

это справочник, его значения можно получить запросом https://github.com/huntflow/api/blob/master/ru/dictionaries.md#get 

в вашем случае dictionary_code = specialization

> И еще вопрос - нужен город вакансии.

Уточните, что это за поле?

> А как среди них определить ответственного менеджера (отвечающего за вакансию), если их работает несколько над одной большой или сложной вакансией?

Это вам нужно выяснять у бизнеса :)

**Comment by chepurovsky** [comment]
Виталий, про город вакансии задал вопрос «бизнесу» - ответят - поясню.
Ответственного за вакансию видимо нет…:) «бизнес" сказал, что все менеджеры равнозначны - вопрос снимается.

Остальное, что сегодня ответили постараюсь оперативно опробовать, и если не получится что-то - уточню детали.

С уважением,
Чепуровский Игорь
+7 968 680 0361
5 окт. 2021 г., 16:04 +0300, Vitaly Glibin ***@***.***>, писал:

**Comment by chepurovsky** [comment]
Виталий, добрый день!
Бизнес ответил про «город».
Поле «город» в системе называется «Регион»:

Как его получить корректно?

С уважением,
Чепуровский Игорь
+7 968 680 0361
5 окт. 2021 г., 16:04 +0300, Vitaly Glibin ***@***.***>, писал:

**Comment by glibin** [comment]
Добрый день!

Возможно, я так до конца и не понял о каком регионе речь, но есть такой справочник, возможно, это он:

GET /account/<account_id>/regions

**Comment by glibin** [comment]
Добрый день!

Данные точно должны быть в ответе при запросе конкретной вакансии https://github.com/huntflow/api/blob/master/ru/vacancies.md#получение-вакансии

**Comment by aleks-v-k** [comment]
@chepurovsky в полях вакансии теперь должно появиться поле account_region, можете проверить?

**Comment by chepurovsky** [comment]
Да спасибо, появился ID региона в вакансиях.
Только мы уже перешли на забор данных выгрузками JSON-файлов. Из-за того что по этой схеме через REST абсолютно нереально организовать забор данных… К сожалению.
И вот в этих выгрузках нет справочника регионов.
Ирина наверняка на эту тему с вами связывалась уже.

С уважением,
Чепуровский Игорь
+7 968 680 0361
10 нояб. 2021 г., 10:15 +0300, Aleksandr Kuznetsov ***@***.***>, писал:

**Comment by glibin** [comment]
Добрый день!

Тикет закрою, так как сутевого про API больше ничего нет.
