### ISSUE TITLE
Вопрос по API

### ISSUE THREAD

**Issue by evgkit** [huntflow/api#41]
Здравствуйте!

Как через API добавить кандидата на этап подбора "Отклики" ("Responces") ? 
Этап выделен красным на скриншоте: https://i.imgur.com/ryUp10d.png 

Насколько я понял данный этап является системным и появляется только в тех вакансиях, к которым подключены публикации с работных сайтов, чтобы на него добавлялись отклики. Очень хочу класть туда кандидатов по API, подскажите как это можно сделать, как мне получить идентификатор этого этапа?

Использую https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

**Comment by glibin** [comment]
Добрый день! 

Данный этап работает через функционал платформы откликов. 
Вы можете реализовать API (https://github.com/huntflow/api/blob/response/ru/responses.md)  на своем карьерном сайте и подключить сбор откликов с него к Хантфлоу.
