### ISSUE TITLE
Запрос на подтверждение по электронной почте

### ISSUE THREAD

**Issue by mykhayloi** [huntflow/api#411]
Всем здравствуйте, 

Я работаю над интеграцией Huntflow со Slack. При этом я хочу иметь возможность уведомлять конкретного пользователя Slack, когда его одобрения необходимо для создания вакансии. Однако при создании вакансии нет возможности добавить《пользователя  на утверждение》. Нужно ли мне каким-то образом настраивать мою учётную запись использования этой функции?

![img1](https://user-images.githubusercontent.com/79649530/136752482-aa27c12b-ffc8-42bc-bbd2-a04a615cefc1.PNG)
![InkedScreen Shot 2021-10-06 at 12 44 42 PM_LI](https://user-images.githubusercontent.com/79649530/136752468-1fa3751d-a29a-4044-ba52-8b606ba06614.jpg)

Вот как выглядит пользовательский интерфейс с двух точек зрения. Я не знаю, как настроить свою учетную запись (первое изображение), чтобы оно выглядело как второе изображение.

**Comment by glibin** [comment]
Добрый день!

Мы сейчас обновляем документацию по вебхукам и возможность обработки вебхуков на заявку на вакансию там будет добавлена. Я сообщу в этом тикете, когда она выйдет.
