### ISSUE TITLE
автоматизация перехода кандидата по статусам 

### ISSUE THREAD

**Issue by kirillchernin** [huntflow/api#418]
подскажите возможно ли привязать автоматизацию перехода кандидата по статусу

на другой статус в зависимости от заполненой анкеты обратной связи? 
или
выбранных ответов на вопросы в анкете обратной связи?

**Comment by aleks-v-k** [comment]
Здравствуйте.
Непонятно какая автоматизация имеется в виду в контексте API. Возможно стоит задать задать этот вопрос в нашу поддержку hello@huntflow.ru
