### ISSUE TITLE
account_info в log

### ISSUE THREAD

**Issue by Svyatoslav94** [huntflow/api#419]
Коллеги, Добрый день.
По адресу api.huntflow.ru/account/account_ID/applicants/applicant_ID/log
у нас есть метка того, кто поставил  тот или иной статус (account_info)
![image](https://user-images.githubusercontent.com/89248573/139000332-82f6b54e-8849-42a9-8118-da8109f31461.png)
При этом ID того, кто поставил статус, не соответствует данным и справочника api.huntflow.ru/account/account_ID/members.
Просьба проконсультировать, откуда мы можем выгрузить справочник account_info/id из логирования?

**Comment by Fosly** [comment]
у меня поле account_info.id из /applicant_ID/log соответствует полю member (не id) из запроса /account_ID/members
