### ISSUE TITLE
Интеграция Huntflow с hh.ru

### ISSUE THREAD

**Issue by sergienja** [huntflow/api#42]
Коллеги, привет!

Нам нужно настроить интеграцию Huntflow и hh.ru и сделать так, чтобы резюме с hh.ru автоматически подтягивались бы в Huntflow.

Подскажите, пожалуйста, каким образом это мы можем реализовать и есть ли готовые решения?

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой функциональности в Хантфлоу API нет.
