### ISSUE TITLE
Добавление coworkers при создании вакансии

### ISSUE THREAD

**Issue by raymann89** [huntflow/api#420]
Добрый день!

**Ссылка** 
https://github.com/huntflow/api/blob/master/ru/vacancies.md#add
**Апишка**
POST /account/{account_id}/vacancies
**Поле** 
coworkers | array | Нет | Список рекрутеров, работающих над вакансией

Вопрос
В какой формате и какие данные пользователей нужно отправить, чтобы добавить в вакансию?

**Comment by aleks-v-k** [comment]
Здравствуйте, нужно в этом массиве передавать идентификаторы рекрутеров, см. https://github.com/huntflow/api/issues/155

**Comment by raymann89** [comment]
Добрый день!
Не работает.

Пробовал вот какие варианты:
1. Сначала не обратил внимание на "идентификатор" и пихал в массив целый объект member
2. потом попробовал id
3. потом member
Подсмотрел вот тут https://github.com/huntflow/api/issues/209
Не работает.
Можете пожалуйста прислать пример как это должно вышлядеть.

И самый главный вопрос, как сделать так, чтобы вместо какого-то идентификатора, отправлять почту?
Объясню почему.
На стороне платформы (CRM) мы выбираем рекрутера который будет работать по вакансии, а CRM не знает идентификатора пользователя в вашей системе. Поэтому придется "хардкодить" видимо и все равно заходить еще раз на Хантфлоу и руками проставлять нужного рекрутера.

Вот примеры вакансий 
https://huntflow.ru/my/indriver/view/vacancy/2784643
https://huntflow.ru/my/indriver/view/vacancy/2784646

**Comment by aleks-v-k** [comment]
На данный момент добавление coworkers по email не реализовано.
Возможно не понимаю ваш кейз, но почему не сделать так: подгружаете рекрутеров через HF API (у них есть email в ответе) далее по email рекрутера выбранного в CRM находите его идентификатор и подставляете его в запрос на создание вакансии.

**Comment by raymann89** [comment]
Кейс поняли нормально, просто я не думал еще о такой реализации.
Придется видимо так, да.

Спасибо за быстрый ответ!
А можно как-то по имейлу получать данные одного рекрутера, аля
https://api.huntflow.ru/account/40605/members?email=test@gmail.com

Чтобы каждый раз не запрашивать список и не проходить оп нему поиском

**Comment by aleks-v-k** [comment]
К сожалению сейчас такой возможности нет (фильтровать по email). В целом нужность метода понятна: при большом количестве рекрутеров запрос всего их списка каждый раз будет неоптимальным решением. Но если в вашем случае количество рекрутеров < 100, то это не должно быть проблемой.
Пока не могу сказать будем ли мы такое реализовывать (выборку по email), ориентировочно смогу сказать на следующей неделе (после 14.11).

**Comment by glibin** [comment]
Добрый день!

У нас в планах есть доработка по возможностям поиска среди пользователей организации, однако, каких-то точных сроков реализации пока назвать не сможем.
