### ISSUE TITLE
Как получить резюме в json формате?

### ISSUE THREAD

**Issue by saginsa** [huntflow/api#422]
Есть задача - формировать текстовое резюме в собственном формате.
Для этого необходимо получать информацию по резюме кандидата хотя-бы в каком-то формате, но полном.

Вот пример запроса, который нашел самым подходящим

https://api.huntflow.ru/account/65315/applicants/19016572

В рамках него получаю информацию на то, что резюме взято из hh

"external": [
        {
            "id": 18657502,
            "applicant": 19016572,
            "auth_type": "HH",
            "updated": "2021-10-18T17:55:12+03:00",
            "account_source": 293605
        }
    ],

Можно ли каким-то образом получать не отдельными ссылками на резюме откуда было импортировано, а непосредственно документ с информацией по резюме?

**Comment by aleks-v-k** [comment]
Здравствуйте.
Вы можете использовать `id` из элемента этого списка для получения резюме, см. https://github.com/huntflow/api/blob/master/ru/externals.md (если я правильно понял вопрос)
