### ISSUE TITLE
Публикация комментариев с файлами

### ISSUE THREAD

**Issue by Ezergil** [huntflow/api#423]
Коллеги, привет

Переливаю базу из одной HRM системы в вашу через Api
Предварительно залил все файлы и сохранил себе их айдишники
Сейчас гружу историю работы с кандидатами и столкнулся с проблемой при заливке комментария с прикреплённым файлом: 

запрос: POST /accounts/2/applicants/4545/log

Тело запроса:

{"applicant":4545,"vacancy":104,"comment":"тут текст","files":[{"id":6121}]}

Ответ сервера : 

{"id": 115395, "applicant": 4545, "type": "COMMENT", "account": 23, "vacancy": 104, "vacancy_frame": 104, "status": 43, "rejection_reason": null, "calendar_event": null, "email": null, "sms": null, "phone_call": null, "applicant_offer": null, "survey_answer_of_type_a": null, "recruitment_evaluation": null, "group_action": null, "vacancy_group_action": null, "comment": "тут текст", "source": null, "employment_date": null, "data": null, "created": "2021-11-05 17:42:59", "hired_in_fill_quota": null, "work_days_in_work": null, "work_days_after_deadline": null, "workdays_until_employment_date": null, "workdays_after_deadline_for_employment_date": null, "removed": null, "files": [], "im": []}

Массив файлов в ответ вернулся пустым. Айди файла валидный. В чём может быть проблема?

**Comment by aleks-v-k** [comment]
Здравствуйте.
В списке файлов нужно передвать просто идентификаторы. В вашем случае надо заменить
```
"files":[{"id":6121}]
```
на
```
"files":[6121]
```
