### ISSUE TITLE
Фильтрация рекрутеров по нескольким вакансиям

### ISSUE THREAD

**Issue by adzhiasan** [huntflow/api#424]
Добрый день!

Подскажите, пожалуйста, есть ли возможность фильтровать рекрутеров по значениям нескольких вакансий?
По примеру #417 попробовал сделать следующий запрос:
```
/members/search?only_current_status=1&info=true&vacancy={first_vacancy_id}&vacancy={second_vacancy_id}&page=1&count=30
```
Однако получил `404: Not Found`.

Запрос вида:
```
/members?vacancy={first_vacancy_id}&vacancy={second_vacancy_id}
```
также не дал ожидаемых результатов.

**Comment by aleks-v-k** [comment]
Здравствуйте, поиск по рекрутерам не реализован на данный момент.
Пока все что доступно описано тут (есть фильтрация по одной вакансии): https://github.com/huntflow/api/issues/133

**Comment by adzhiasan** [comment]
Спасибо!
