### ISSUE TITLE
500 ошибка при загрузке фото

### ISSUE THREAD

**Issue by dev-skvortsov** [huntflow/api#425]
Добрый день!
Подскажите, пожалуйста, в чем может быть причина вот такой ошибки при загрузке файла (фото кандидата): 500 статус, в ошибке только "type": "server_error". 

ссылка на файл (оригинал): https://stat.jcat.ru/images/boards/hh/ae82f5ce45d0ee2d9f328c5ece973eaea4d39af7_medium.jpeg

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, заголовки запроса (исключая токен)

**Comment by dev-skvortsov** [comment]
![Screenshot_20211123_091406](https://user-images.githubusercontent.com/94625725/142978487-0400050b-9e7c-4221-b57c-e69a826a72bd.png)

В основном загрузка работает корректно, но очень редко получаем вот такую ошибку. Конкретно это фото не загружается ни с сервера, ни с Postman.

**Comment by glibin** [comment]
Вот таким запросом файл загружается:

```
curl -X POST -F 'file=@/Users/glibin/Downloads/ae82f5ce45d0ee2d9f328c5ece973eaea4d39af7_medium.jpeg' -H 'Authorization: Bearer <token>' https://api.huntflow.ru/account/<account_id>/upload
```

К сожалению, не получается воспроизвести.
