### ISSUE TITLE
Получение данных статистики по API

### ISSUE THREAD

**Issue by maxvydrin** [huntflow/api#426]
Добрый день, не нашел прямых методов как забирать статистику по API для вывода на дашборде

Нужны следующие данные

- Данные по интервью скрипта "Вакансии"->"Назначенные интервью" за период времени
- Данные по отправленным письмам и полученным ответам скрипта "Вакансии"->"Конверсия писем кандидатов" за период времени
- Данные по этапам воронок скрипта "Вакансии"->"Воронка" за период времени 
- Нанято и открытых вакансий за период по данным скрипта Скрипт "Вакансии"->"Время закрытия вакансий"

Подскажите куда  копать.

**Comment by glibin** [comment]
Добрый день!

На данный момент в API нет методов для получения статистических данных.

**Comment by Dmitryi** [comment]
@maxvydrin Вам нужно написать в тех поддержку из Хантфлоу с запросом скачать базу резюме. Запрос должен отправить тот на ком зарегистрирован аккаунт администратора в вашей компании. Через 2 дня вам пришлют ссылку. Скачаете, обработаете данные, визуализируете и готово )))

**Comment by maxvydrin** [comment]
спасибо за ответы! 

Я хочу дашборд обновлять в реальном режиме времени, ну или хотя бы раз в сутки. По 5 основным показателям. Базу резюме, что предоставит huntflow - это же единовременное действие?

**Comment by glibin** [comment]
Для обновления в реальном времени рекомендуем произвести единоразовую выгрузку через API, а далее изменения получать через вебхуки https://github.com/huntflow/api/blob/master/ru/webhooks.md

**Comment by maxvydrin** [comment]
Есть ли в планах реализовать API для статистики?

**Comment by glibin** [comment]
> Есть ли в планах реализовать API для статистики?

Добрый день!

В планах пока нет.
