### ISSUE TITLE
Обновление анкет

### ISSUE THREAD

**Issue by AsyaLightmap** [huntflow/api#427]
Добрый день!

Перед нами стоит задача переместить данные из раздела external в основной раздел по каждой анкете кандидата. 
Я правильно понимаю, что методом https://github.com/huntflow/api/blob/master/ru/upload.md обновляются все данные организации, имеющиеся в Huntflow? Нет ли способа это сделать более прицельно, чтобы протестировать метод на отдельных анкетах, например,  URL вида /account/{account_id}/upload/applicants/{applicant_id} ?

**Comment by glibin** [comment]
Добрый день!

К сожалению, не очень понятен ваш вопрос. Можете рассказать чуть подробнее, какая задача и как пытаетесь ее решить с помощью API?

**Comment by AsyaLightmap** [comment]
![image](https://user-images.githubusercontent.com/94842384/143416637-f34e004c-9164-4293-a75e-72a1bbe085f0.png)
Во вкладках есть информация о кандидате (Личные заметки, Linkedin, Резюме), как например на скриншоте это город.
Эти данные необходимо переносить наверх, в основной раздел. 

Я смотрела в исходном коде вкладки - это поле external JSON-а. Таким образом, чтобы перенести данные методом https://github.com/huntflow/api/blob/master/ru/upload.md я локально у себя создаю документ с перезаполненными полями из external и, если есть такая возможность, предварительно протестировать на нескольких анкетах. Вопрос в том, есть ли способ не перезаписывать всю базу данных?

**Comment by glibin** [comment]
Добрый день!

Можете посмотреть пример как заполняются поля для кандидата: https://github.com/huntflow/api-response/blob/master/handler.py

Также есть методы работы с дополнительной информацией по кандидату: https://github.com/huntflow/api/blob/master/ru/questionaries.md#работа-с-анкетами-кандидатов

Надеюсь, смог помочь с вопросом.
