### ISSUE TITLE
API стал работать в разы медленнее

### ISSUE THREAD

**Issue by Aqquila1** [huntflow/api#428]
Привет! В последние несколько дней запросы к API стали обрабатываться в несколько раз дольше. В чем может быть проблема?

**Comment by Aqquila1** [comment]
Я точно не уверен какая почта стоит в headers при запросе, но она должна быть с доменом skyeng

**Comment by glibin** [comment]
Добрый день!

Здесь мы отвечаем на вопросы по использованию API.

По этому вопросу лучше обратиться в поддержку support@huntflow.ru
