### ISSUE TITLE
Выгрузка форм обратной связи через апи

### ISSUE THREAD

**Issue by bankTochka** [huntflow/api#429]
Добрый день! активно пользуемся формами, но раньше не было возможность их тянуть через апи, чтобы после анализировать информацию в дашбордах например. 
Скажите, сейчас появилась такая возможность?  если нет, то есть ли какой-то другой способ массово работать с результатами форм обратной связи?

**Comment by glibin** [comment]
Добрый день!

Мы планируем добавить возможность получения информации о формах обратной связи в ближайшем будущем. 

Более подробную информацию я смогу предоставить на следующей неделе.

**Comment by bankTochka** [comment]
т.е. их даже просто выгрузить никак нельзя?

**Comment by glibin** [comment]
Да, верно.
