### ISSUE TITLE
Логи кандидата возвращают не все вакансии

### ISSUE THREAD

**Issue by Amirna55** [huntflow/api#430]
Добрый день! При запросе
GET /account/{account_id}/applicants/{applicant_id}/log 
у некоторых кандидатов не приходят часть вакансий. Например, в Huntflow, вижу, что у кандидата 6 вакансий, а через API только 5. Похоже на ошибку на стороне API. Что нужно сделать, чтобы в логах кандидата приходили все вакансии?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, account_id, applicant_id, идентификаторы вакансий, которые должны быть видны и какой из них недоступен. А также последние 6 символов токена API.

**Comment by Amirna55** [comment]
Добрый день!
account_id = 69791
applicant_id = 13950836
Последние 6 символов токена API = 0e1d4f
Вакансия, которая не приходит в логе = 2670770


С уважением,
Марина Ковелева
Консультант

***@***.******@***.***>
novardis.com


***@***.***<https://novardis.com/>
***@***.***<https://www.facebook.com/novardisconsulting>
***@***.***<https://www.linkedin.com/company/novardis/>

**Comment by glibin** [comment]
Кажется, что вы не учитываете постраничный вывод данных: https://github.com/huntflow/api/blob/master/ru/general.md#постраничный-вывод

**Comment by Amirna55** [comment]
Да, все верно, постраничный вывод не учитывали.
Спасибо!

С уважением,
Марина Ковелева
Консультант

***@***.******@***.***>
novardis.com


***@***.***<https://novardis.com/>
***@***.***<https://www.facebook.com/novardisconsulting>
***@***.***<https://www.linkedin.com/company/novardis/>
