### ISSUE TITLE
Получение полной информации о рекрутере 

### ISSUE THREAD

**Issue by romutchio** [huntflow/api#431]
В логах кандидата указывается малая часть информации о рекрутере "account_info": {"id": 82065, "name": "Попова Мария"}

Возможно ли как-то по id получить расширенную информацию, скажем почту и прочее?

**Comment by glibin** [comment]
Добрый день!

Есть возможность получить всех рекрутеров в организации. Информация доступна в этом тикете: https://github.com/huntflow/api/issues/133
