### ISSUE TITLE
Ускорение загрузки логов кандидатов 

### ISSUE THREAD

**Issue by dorofema** [huntflow/api#432]
Добрый день!
Загружаем в систему аналитики логи перемещения кандидатов по статусам. Для этого вытягиваем около 1800 страниц со списками кандидатов. И потом по каждому запрашиваем лог. Суммарно получается около 60 тысяч запросов. В среднем один запрос на текущий момент отрабатыавает за 0,3-0,4с. Всё обновление в теории занимает около 6 часов. На практике - падает.
Есть ли какие-то способы это ускорить?
Варианты, которые наверное могли бы помочь: 
- выгружать логи не по отдельному кандидату, а по всем - постранично;
- фильтровать типы логов и/или сами статусы (нужны только STATUS, и часть статусов);
- ускорить отработку запросов...

Что можно сделать?

**Comment by SemenovDaniil** [comment]
Поддерживаем запрос.
Хотелось бы получить доступный интерфейс для загрузки данных из системы в целях аналитики.
У нас страниц с логом кандидатов больше 10000, выгрузить все логи просто нереально.

**Comment by glibin** [comment]
Добрый день!

Для ускорения выгрузки рекомендуем единоразово выгрузить из API, а затем использовать вебхуки для получения изменений (https://github.com/huntflow/api/blob/master/ru/webhooks.md)
