### ISSUE TITLE
Интегрировать форму, шаблон заявки ХФ, на сайт.

### ISSUE THREAD

**Issue by OlegKlimec** [huntflow/api#434]
Нам необходимо, чтобы при нажатии «Отправить резюме» на сайте, Открывалась форма 
**имя
мыло
телефон
поле для заметок**
*ссылка для прикрепления файла
и капча

И эта форма должна напрямую забивать кандидатов в ХФ. Возможно такое реализовать?

**Comment by glibin** [comment]
Добрый день!

Ознакомьтесь со статьей, там есть ссылка на репозиторий с кодом для реализации.

**Comment by glibin** [comment]
https://huntflow.ru/blog/sbor-otklikov-avtomatom/
