### ISSUE TITLE
Формирование ссылки

### ISSUE THREAD

**Issue by adzhiasan** [huntflow/api#435]
Добрый день!
Вопрос не совсем по *API*: подскажите, пожалуйста, для чего в ссылке на сайте *Huntflow* нужна часть до символа `#`?

Пример:
```
https://huntflow.ru/my/<someText>#vacancy/12345
```
или
```
https://huntflow.ru/my/<someText>#applicants/filter/all
```

В примере заменил эту часть на `<someText>`. По умолчанию туда вписывается что-то похожее на название организации.
Однако, заменив её на последовательность цифр, букв, ничего не изменяется. Страница загружается та же. 
В случае же, если эта часть остаётся пустой, получаем "Страница не найдена".

**Comment by glibin** [comment]
Добрый день!

Это короткое название организации. 
Если вы вбиваете произвольный текст, то система пытается найти доступную организацию для этого короткого названия (или берет первую доступную, если не находит).

**Comment by adzhiasan** [comment]
Спасибо!
