### ISSUE TITLE
Добавление вакансии на HH через API

### ISSUE THREAD

**Issue by Jeinara** [huntflow/api#436]
Добрый день. Ситуация такая: мы создаём вакансию сначала в базе HF, затем сами создаём вакансию в HH. Есть ли в API возможность связать эти две вакансии, и если есть, то через какое поле? В документации ничего подходящего найти не получилось.

**Comment by glibin** [comment]
Добрый день!

К сожалению, сделать это через API сейчас невозможно.

Однако, можно опубликовать вакансию прямо из Хантфлоу, тогда привязка будет происходить автоматически.
