### ISSUE TITLE
Ошибка при добавлении кандидата

### ISSUE THREAD

**Issue by Jss2k** [huntflow/api#437]
Добрый день
При добавлении кандидата в ответ приходит ошибка { type: 'validation.externals', value: [Array] }

в запрос уходит JSON вида
{"last_name":"Last","first_name":"First","phone":"800000000","email":"email@gmail.com","position":"Backend developer","externals":[{"data":{"body":"test"},"auth_type":"NATIVE","account_source":131679}]}

где я делаю что-то не так?

**Comment by glibin** [comment]
Добрый день!

Скорее всего, указан некорректный источник резюме. Информация должна быть доступна в полном теле ответа.

**Comment by Jss2k** [comment]
Спасибо большое
