### ISSUE TITLE
Что содержится в выгрузке по вакансиям?

### ISSUE THREAD

**Issue by MaximRW1975** [huntflow/api#439]
Добрый день! При выгрузке выкансии по api, возвращается история вакансии по этапам или выгрузка содержит только актуальную информацию по вакансии на момент выгрузки? Если содержится актуальная информация, подскажите, пожалуйста, возможно ли выгружать информацию по вакансии с ее историей по этапам?

**Comment by glibin** [comment]
Добрый день!

Есть возможность выгружать как текущее состояние, так и исторические данные (открытия, приостановку и тп)

**Comment by MaximRW1975** [comment]
А можете подсказать как выгрузить исторические данные?

**Comment by glibin** [comment]
Есть недокументированный метод: https://github.com/huntflow/api/issues/367

В новой версии API (ориентировочная дата релиза начало 2022) метод будет описан и документирован.
