### ISSUE TITLE
Причины закрытия вакансии в ХФ

### ISSUE THREAD

**Issue by fakdabt** [huntflow/api#440]
Добрый день!
Подскажите, пожалуйста, каким методом можно получить расшифровку причин приостановки и закрытия вакансий, которые получаем через метод `https://api.huntflow.ru/account/<account_id>/vacancy/<vacancy_id>/logs`

Например:
![image](https://user-images.githubusercontent.com/95346011/144211463-217b25ad-6209-407c-b28e-19bcb4949c72.png)

Для приостановки метод возвращает причину `"account_vacancy_hold_reason": 8486`, для закрытия - `"account_vacancy_close_reason": 8504`, но метода, который возвращает справочник причин, я в документации не нашёл.

**Comment by glibin** [comment]
Добрый день!

К сожалению, такого метода нет в текущей версии API, но будет доступен в следующей версии, которая, ориентировочно, выйдет в начале 2022. Актуальный список причин сейчас можно запросить через службу поддержки support@huntflow.ru

**Comment by slider82** [comment]
Добрый день, подскажите пожалуйста не появились ли методы для получения причин?

**Comment by glibin** [comment]
Добрый день!

Причины закрытия: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancy_close_reasons

Причины приостановки: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancy_hold_reasons
