### ISSUE TITLE
Фильтрация кандидатов по нескольким значениям меток

### ISSUE THREAD

**Issue by adzhiasan** [huntflow/api#441]
Добрый день!

Подскажите, пожалуйста, есть ли возможность фильтровать кандидатов по значениям нескольких меток по примеру #417?
В данный момент запрос вида, представленного ниже, не возвращает кандидатов:
```
/applicants/search?only_current_status=1&info=true&tag={first_tag_id}&tag={second_tag_id}
```

**Comment by glibin** [comment]
Добрый день!

Указание нескольких меток работает как оператор "И", то есть, у кандидатов должны быть, например, обе метки (как в вашем примере). Оператор "ИЛИ" для меток сейчас недоступен.

**Comment by adzhiasan** [comment]
Спасибо!
