### ISSUE TITLE
Возможность приложить файлы к заметке через API 

### ISSUE THREAD

**Issue by Suvmsh** [huntflow/api#443]
Есть ли возможность добавить файл к заметке ("type": "COMMENT",) через API?

`{

"applicant": 20203055,

"type": "COMMENT",

"files": [

{

"id": 21592476

}

]

} `- не работает

**Comment by glibin** [comment]
Добрый день!

Попробуйте вместо массива объектов передать массив идентификаторов: `"files": [21592476]`

**Comment by Suvmsh** [comment]
Спасибо. Получилось. Хотелось бы в документации видеть это.

**Comment by Suvmsh** [comment]
Также заметил ошибку. 
![111Снимок](https://user-images.githubusercontent.com/95474308/144606984-3a234f1f-b574-4534-8f61-19a5fd006447.JPG)

**Comment by glibin** [comment]
Исправим, спасибо
