### ISSUE TITLE
Получить почту hr, открывшего вакансию

### ISSUE THREAD

**Issue by igorkolechkin** [huntflow/api#446]
Добрый день. Подскажите, пожалуйста, как мне получить почту hr, который или которые создали данную вакансию?

**Comment by Fosly** [comment]
Тут есть информация #103

**Comment by igorkolechkin** [comment]
Благодарю. Я видел этот пост. Но при запросе на account/{account_id}/members?vacancy={vacancy_id} я получаю список все manager и watch, имеющих отношение к этой вакансии. А как мне дальше узнать кто именно создал? Я не нашел там никакого ключа ,который говорил бы о том, что именно этот manager создал данную вакансию. Подскажите, может я что-то пропустил

**Comment by Fosly** [comment]
В моей практике vacancy/**id**/logs возвращает историю самой вакансии, там есть данные по статусу CREATED и manager ID который создал.

**Comment by igorkolechkin** [comment]
Благодарю
