### ISSUE TITLE
Изменение рекрутера у вакансии

### ISSUE THREAD

**Issue by charararara** [huntflow/api#449]
Здравствуйте!
Я не могу поменять у вакансии ответственного рекрутера. 
Пытался через https://github.com/huntflow/api/blob/master/ru/vacancies.md#edit 
Других методов в документации не нашёл.
Сами поля меняются, но не рекрутер. Хотя при добавлении вакансии я указываю COWORKER и рекрутеры устанавливаются.

**Comment by glibin** [comment]
Добрый день!

На данный момент в текущей версии API нет возможности назначить друго рекрутера на вакансию. Мы работаем над тем, чтобы добавить такую возможность в новую версию API, которая запланирована к выпуску в первом квартале 2022.

**Comment by charararara** [comment]
Добрый день!

Нет ли новостей по данной доработке?
