### ISSUE TITLE
Как изменить формат (поля, строки) выгружаемого отчёта.

### ISSUE THREAD

**Issue by budarinsergei1990** [huntflow/api#45]
Коллеги, добрый день.
Необходимо изменить формат отчёта, выгружаемого из Вашей системы - каким образом это можно сделать? Это можно сделать программно через код?

С уважением,
Сергей.

**Comment by glibin** [comment]
Добрый день!

Вы имеете ввиду отчет в формате xlsx?

**Comment by budarinsergei1990** [comment]
Да, этот отчёт.

**Comment by glibin** [comment]
Кастомизация этого отчета невозможна. Вы можете создать свой на базе методов API, указанных в этой документации.

**Comment by budarinsergei1990** [comment]
То есть подразумеваете, что мы должны использовать методы API, и из получаемых данных по этим методам собрать отчёт "с нуля"?

**Comment by glibin** [comment]
Да, именно так.
