### ISSUE TITLE
Проблема с переводом на предыдущий этап

### ISSUE THREAD

**Issue by Yana-Kraynova** [huntflow/api#450]
На зеркале через API переводим кандидатов на предыдущий этап. Обнаружили ситуацию с ошибкой.

 

Посмотрите, пожалуйста.

 

applicant_id = 1358878
vacancy_id = 28780, 28781, 28782, 28783
28780 - родительская, остальные ее дочки.если мы пытаемся сделать переход на другой этап по родителю, то все ок
post https://rbru-mirror-api.huntflow.ru/account/2/applicants/1358878/vacancy

{
   "vacancy": 28780,
   "status": 46,
   "comment": "Необходимо заполнить карточку оффера перед тем, как перевести кандидата на этап Оффер. Заполните карточку и удалите последний этап Ожидание финального решения.",
   "rejection_reason": null
}
 

а если тот же самый запрос, но по дочке, то ХФ с ошибкой отвечает

 

{
   "vacancy": 28782,
   "status": 46,
   "comment": "Необходимо заполнить карточку оффера перед тем, как перевести кандидата на этап Оффер. Заполните карточку и удалите последний этап Ожидание финального решения.",
   "rejection_reason": null
}
 

{
    "errors": [
        {
            "type": "validation.vacancy",
            "value": [
                "Unable to add applicant on nested vacancy"
            ]
        }
    ]
}

в итоге мы не можем по дочке вернуть кандидата на предыдущий этап

**Comment by glibin** [comment]
Добрый день!

Попробуйте использовать метод PUT, вместо POST.
