### ISSUE TITLE
Получение грейда вакансии

### ISSUE THREAD

**Issue by MaximRW1975** [huntflow/api#452]
Добрый день! Возможно ли получить грейд для вакансии? В документации по выгрузке вакансии и кандидатов такого поля не увидел

**Comment by glibin** [comment]
Добрый день!

Скорее всего, это конфигурируемое поле для вакансии в вашей организации. Его значение должно возвращаться в запросе по вакансии https://github.com/huntflow/api/blob/master/ru/vacancies.md#vacancy
