### ISSUE TITLE
Прикрепление кандидата к вакансии

### ISSUE THREAD

**Issue by gorant20** [huntflow/api#453]
Добрый день, пытаюсь прикрепить кандидата к вакансии, согласно документации https://github.com/huntflow/api/blob/master/ru/applicants.md
Отправляем запрос с валидным json, содержащим все необходимые поля, заранее получив из Huntflow id вакансии и кандидата.
При запросе из браузера спустя 60 секунд скрипт падает с 504 ошибкой по таймауту, при запросе из postman получаем internal server error. 
Скажите пожалуйста, этот метод вообще рабочий, может быть с нашей стороны есть какие то ошибки?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, заголовки и тело запроса, а также заголовки и тело ответа (информацию о токене нужно удалить).

**Comment by ovechkinki** [comment]
Пробуем запрос через postman, если передавать form-data, то получаем ошибку сервера https://disk.yandex.ru/i/1Fy1A0w-_eY7Tg
Если передавать raw json, то ответ приходит https://disk.yandex.ru/i/Y4B3HzHO4868sQ
При это при попытке отправки запроса из php скрипта - по прежнему возникает 504 ошибка спустя 60 секунд ожидания ответа сервера huntflow
запрос на адрес:
https://sokolov-api.huntflow.ru/account/2/applicants/52500/vacancy
body:
{"vacancy":"786","status":1}
наличие/отсутствие в json элемента "files" на ответ не влияет.
Есть какие то нюансы, которые не описаны и нужно их указывать при запросе через php скрипты?

**Comment by gorant20** [comment]
Пробуем запрос через postman, если передавать form-data, то получаем ошибку сервера https://disk.yandex.ru/i/1Fy1A0w-_eY7Tg
Если передавать raw json, то ответ приходит https://disk.yandex.ru/i/Y4B3HzHO4868sQ
При это при попытке отправки запроса из php скрипта - по прежнему возникает 504 ошибка спустя 60 секунд ожидания ответа сервера huntflow
запрос на адрес:
https://sokolov-api.huntflow.ru/account/2/applicants/52500/vacancy
body:
{"vacancy":"786","status":1}
наличие/отсутствие в json элемента "files" на ответ не влияет.
Есть какие то нюансы, которые не описаны и нужно их указывать при запросе через php скрипты?
