### ISSUE TITLE
Что значит "auth_type" = "NATIVE"

### ISSUE THREAD

**Issue by Amirna55** [huntflow/api#457]
Добрый день!
Подскажите, пжл, что значит "NATIVE" в "auth_type" ?
"external": [
        {
            "id": 14100712,
            "applicant": 14532035,
            "auth_type": "NATIVE",
            "updated": "2018-05-15T17:43:26+03:00",
            "account_source": 316743
        }
    ],

**Comment by Fosly** [comment]
Источник резюме. NATIVE - напрямую с huntflow добавлено

**Comment by glibin** [comment]
Добрый день!

Это текстовый формат резюме. Как правило, такие резюме добавляются вручную или из файлов.
