### ISSUE TITLE
Не найдена история по кандидату

### ISSUE THREAD

**Issue by Fosly** [huntflow/api#458]
Добрый день.
Запрос https://api.huntflow.ru/account/71690/applicants/16731995/log возвращает 
```
{
    "errors": [
        {
            "type": "common",
            "value": [
                "not found"
            ]
        }
    ]
}
```
Как у кандидата может отсутствовать какая-либо история? Числится на вакансии 2712280.

**Comment by glibin** [comment]
Добрый день!

Возможно, кандидат объединен как дубликат, поэтому по старому идентификатору не возвращается история.

Попробуйте запросить информацию о кандидате  https://api.huntflow.ru/account/71690/applicants/16731995  и проверьте, что идентификаторы кандидатов совпадают (если нет, то в ответе будет актуальный идентификатор после объединения дубликатов).
