### ISSUE TITLE
Ошибка отображения подразделения при получении вакансии

### ISSUE THREAD

**Issue by DimaDodger** [huntflow/api#46]
`GET /account/23115/vacancies/2441766`
Получаем ответ:
```
{
  ...
  "company": null,
  ...
}
```
Однако в админке установлено "Сопровождение АБС · Банковское Ядро · IT"

**Comment by glibin** [comment]
Добрый день! 

Судя по описанию, в вашей организации подключен справочник подразделений. В этом случае идентификатор подразделения приходит в поле account_division (подробнее https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%BF%D0%BE%D0%BB%D1%8F-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0).

Список подразделений можно получить запросом `/account/<account_id>/divisions`

**Comment by DimaDodger** [comment]
Спасибо, данные увидел. Не могу найти описания данного справочника в вашей документации, где можно посмотреть описание? Это не первый справочник на который нет описания, есть более полное описание api?

**Comment by glibin** [comment]
Данное API находится в бета-стадии. Как только оно будет зафиксировано, мы добавим его описание в документацию.
