### ISSUE TITLE
Вопрос по API vacancies

### ISSUE THREAD

**Issue by raymann89** [huntflow/api#460]
Добрый день!
Помогите разобраться плиз, при работе с АПИ возникает ошибка:

Собираюсь автоматически создавать заявки на вакансии через "https://api.huntflow.ru/account/40605/vacancies".
Ситуация:

Если отправляю в     "requirements" и "conditions" пустой текст без форматирования (скрин [1),]
![Снимок экрана от 2022-01-17 14-09-28](https://user-images.githubusercontent.com/48382803/149760553-4917cce9-6db4-40f3-840b-db23aeee9c23.png)
все проходит ок.
А если добавляю хотя бы перенос на следующую строку (срин 2)
![Снимок экрана от 2022-01-17 14-09-45](https://user-images.githubusercontent.com/48382803/149760595-5018d054-eee8-4e44-9380-e308024df0ba.png), приходит ошибка (скрин 3)
![Снимок экрана от 2022-01-17 14-10-06](https://user-images.githubusercontent.com/48382803/149760626-76554585-0b2e-46d1-a10c-ec8e4d3205f6.png)

Как этого избежать?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста заголовки и тело запроса, при которых возникает ошибка.
