### ISSUE TITLE
Возможный баг в логах кандидата

### ISSUE THREAD

**Issue by Yana-Kraynova** [huntflow/api#461]
Добрый день!

Заметили странность в логах кандидата.

Кандидат https://rbru-mirror.huntflow.ru/my/raiffeisen#vacancy/28774/filter/29/id/1358851

Карточка оффера была заполнена 12 ноября

Получаем логи через запрос get https://rbru-mirror-api.huntflow.ru/account/2/applicants/1358851/log

В первом логе в объекте applicant_offer в поле created указана дата и время запроса лога, хотя должна быть указана дата создания карточки оффера (12 ноября). 

В теле запроса баг или все верно?

{
    "items": [
        {
            "id": 8045193,
            "type": "STATUS",
            "account": 6741,
            "vacancy": 28774,
            "status": 29,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": {
                "id": 373,
                "account_applicant_offer": 8,
                "created": "2022-01-17 18:06:53",
                "removed": null
            },
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:06:15+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 6741,
                "name": "Мельников Александр Михайлович"
            }
        },
        {
            "id": 8045192,
            "type": "STATUS",
            "account": 6741,
            "vacancy": 28774,
            "status": 33,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:05:13+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 6741,
                "name": "Мельников Александр Михайлович"
            }
        },
        {
            "id": 8045191,
            "type": "STATUS",
            "account": 6741,
            "vacancy": 28774,
            "status": 26,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:05:10+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 6741,
                "name": "Мельников Александр Михайлович"
            }
        },
        {
            "id": 8045190,
            "type": "STATUS",
            "account": 1,
            "vacancy": 28774,
            "status": 28,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": null,
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:04:37+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 1,
                "name": "System Account"
            }
        },
        {
            "id": 8045189,
            "type": "RESPONSE",
            "account": 1,
            "vacancy": 28774,
            "status": 28,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": "http://home-test.raiffeisen.ru/career/vacancy/21822\nhttp://home-test.raiffeisen.ru/career/vacancy/21822\nhttp://home-test.raiffeisen.ru/career/vacancy/21822",
            "source": "12546_21822",
            "employment_date": null,
            "created": "2021-11-12T15:04:37+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 1,
                "name": "System Account"
            }
        },
        {
            "id": 8045188,
            "type": "VACANCY-ADD",
            "account": 1,
            "vacancy": 28774,
            "status": 28,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": null,
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:04:37+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 1,
                "name": "System Account"
            }
        },
        {
            "id": 8045187,
            "type": "ADD",
            "account": 1,
            "vacancy": null,
            "status": null,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": null,
            "source": null,
            "employment_date": null,
            "created": "2021-11-12T15:04:36+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 1,
                "name": "System Account"
            }
        }
    ],
    "page": 1,
    "count": 30,
    "total": 1
}

**Comment by glibin** [comment]
Добрый день!

Да, выглядит как баг. Передал на исправление.

**Comment by Yana-Kraynova** [comment]
Виталий, на проде и зеркале заметили неправильный формат даты в объекте с оффером. 
Ниже запросы и кусочки логов. Скрины приложить не удалось. 

GET https://rbru-mirror-api.huntflow.ru/account/2/applicants/1358872/log

"applicant_offer": {
                "id": 395,
                "account_applicant_offer": 10,
                "created": "2022-02-04 11:20:16"
            },
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2022-02-04T11:20:16+03:00"
            

GET https://rbru-api.huntflow.ru/account/2/applicants/1388074/log

"applicant_offer": {
                "id": 2230,
                "account_applicant_offer": 5,
                "created": "2021-02-09 21:37:20"
            },
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2021-02-09T21:37:20+03:00"
