### ISSUE TITLE
Неправильно определяется Источник привлечения кандидата

### ISSUE THREAD

**Issue by Amirna55** [huntflow/api#464]
Добрый день!
Из Huntflow по некоторым кандидатам через Api приходит источник привлечения NATIVE, хотя в Huntflow источники указаны (например, HH, LI).
Пример, где возвращается NATIVE вместо LI:
GET:
api.huntflow.ru/account/69791/applicants/14532035

"id": 14532035,
    "photo": 14863687,
    "first_name": "Андрей",
    "last_name": "Беляев",
    "middle_name": null,
    "birthday": null,
    "position": "главный аналитик",
    "company": "\"Почтатех\"",
    "money": null,
    "phone": "",
    "email": "",
    "skype": null,
    "created": "2018-05-15T17:43:26+03:00",
    "links": [
        {
            "id": 17017548,
            "vacancy": 2676507,
            "status": 114835,
            "changed": "2021-10-14T12:12:06+03:00",
            "updated": "2021-10-14T12:12:06+03:00",
            "rejection_reason": null
        },
        {
            "id": 12641967,
            "vacancy": 2670838,
            "status": 111442,
            "changed": "2020-06-25T11:00:10+03:00",
            "updated": "2020-06-25T11:00:10+03:00",
            "rejection_reason": null
        }
    ],
    "photo_url": "https://store.huntflow.ru/uploads2/6/f/2/6f2f7d983e868b11a2ce31996bbe20c9.jpeg?s=8FfvZBc_bCjx8ATsuZ05bQ&e=1643662800",
    "external": [
        {
            "id": 14100712,
            "applicant": 14532035,
            "auth_type": "NATIVE",
            "updated": "2018-05-15T17:43:26+03:00",
            "account_source": 316743
        }
    ],

**Comment by glibin** [comment]
Добрый день!

Источник резюме указывается в поле account_source.

**Comment by Amirna55** [comment]
Спасибо! 
А как получить расшифровку для account_source? Где это хранится?

**Comment by glibin** [comment]
Метод доступен тут: https://github.com/huntflow/api/blob/master/ru/dicts.md#applicant_sources

**Comment by Amirna55** [comment]
Спасибо!
