### ISSUE TITLE
Получение всех событий (собеседований) по кандидатам на определенную дату

### ISSUE THREAD

**Issue by solar-wind** [huntflow/api#465]
Добрый вечер. 

Мы у себя в Mindbox каждый день отправляем в специальный Slack канал информацию о всех собеседованиях на день. Каждое собеседование – это отдельное сообщение. В тредах потом идет обсуждение кандидатов / решаются орг. вопросы. 
Сейчас за это отвечает сложная автоматизация. 

Нам было бы гораздо проще, если бы появился метод API, который позволяет получить данные обо всех событиях (собеседованиях) за определенный день. Это сильно поможет сделать нашу автоматизацию более надежной и простой.

**Comment by glibin** [comment]
Добрый день!

К сожалению, такого метода пока нет в API, я добавлю вашу идею в список пожеланий.
