### ISSUE TITLE
method OPTION. response status: 401 Unauthorized

### ISSUE THREAD

**Issue by Evgenij00** [huntflow/api#466]
Добрый день!
Пытаюсь отправить запрос https://api.huntflow.ru/me, чтобы получить данные об учетной записи пользователя.
Предварительный запрос падает с ошибкой, хотя я все перепроверил, авторизационный токен отправляю верный. См. во вложении.

![Screenshot_1](https://user-images.githubusercontent.com/49844107/150107500-37b60137-0a3d-4e65-bff4-ad6d593a5667.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/49844107/150107508-ab88859a-2ec4-42ca-b738-664527b03bcf.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/49844107/150107511-8933940d-50d9-4db6-a861-571f08974341.jpg)

**Comment by glibin** [comment]
Добрый день!

На данный момент, API не поддерживает CORS. 
Рекомендуем обращаться к API Хантфлоу с серверной стороны.

**Comment by vberesnev** [comment]
Добрый день
Под "обращаться с серверной стороны", вы имеете ввиду поднять свой Web server, через который отправлять вам запросы?

**Comment by glibin** [comment]
Добрый день!

Верно. Более того, размещая токен на стороне клиента (в клиентском JS) вы делаете его общедоступным и каждый сможет получить доступ к вашей базе кандидатов со всей историей и комментариями.
