### ISSUE TITLE
Есть ли возможность получить перечень писем отправленных кандидату?

### ISSUE THREAD

**Issue by MeldunKitty** [huntflow/api#467]
Здравствуйте!

Есть необходимость реализовать определённые тригеры в нашей интеграции, которые бы срабатывали на отправку кандидатам определённых шаблонов писем в huntflow.

На данный момент подобное действие сопровождается прилётом на хуку сообщения указанного ниже.

Но в нём, к сожалению, пуст ключ `event.applicant_log.comment`, хотя в личном кабинете коментарий отображается некое содержание этого комента.

Помимо хуки, могли бы и просто опрашивать профили кандидатов, но в таком случае необходим доступ к полному перечню писем. 

В целом, я считаю, что можно просто в ключ  `event.applicant_log.comment` отправлять какой нибудь простенький текстовый признак того, что коммент относится к конкретному отправленному письму.

`{
  "changes": {},
  "event": {
    "applicant_log": {
      "id": 0,
      "type": "COMMENT",
      "vacancy": {
        "id": 0,
        "applicants_to_hire": 3,
        "position": "position_name",
        "company": null,
        "money": null,
        "state": "OPEN",
        "hidden": false,
        "priority": 0,
        "deadline": null,
        "account_division": {
          "id": 0,
          "name": "company_name"
        },
        "account_region": null,
        "created": "created",
        "multiple": false,
        "parent": null,
        "values": {
          "work_conditions": null,
          "reason": "reason",
          "replacement_other": "replacement_other",
          "employee_section": "employee_section",
          "description": "description"
        },
        "fill_quotas": [
          {
            "id": 0,
            "applicants_to_hire": 3,
            "deadline": null,
            "vacancy_request": null,
            "created": "created",
            "closed": null
          }
        ],
        "frame_id": 0
      },
      "status": {
        "id": 0,
        "name": "status_name"
      },
      "rejection_reason": null,
      "comment": "",
      "calendar_event": null,
      "files": [],
      "survey_answer_of_type_a": null,
      "employment_date": null,
      "created": "created",
      "removed": null,
      "vacancy_group_action": null,
      "source": null
    },
    "applicant": {
      "photo": null,
      "first_name": "first_name",
      "last_name": "last_name",
      "middle_name": "middle_name",
      "birthday": null,
      "position": null,
      "company": null,
      "money": null,
      "phone": "+7",
      "email": "email@email.email",
      "skype": null,
      "questionary": null,
      "id": 0,
      "values": {},
      "social": [
        {
          "id": 0,
          "social_type": "TELEGRAM",
          "value": "tg_nick",
          "verification_date": null,
          "verified": false
        }
      ],
      "pd_agreement": null
    }
  },
  "meta": {
    "event_type": "APPLICANT",
    "account": {
      "id": 0,
      "name": "Company",
      "nick": "company_name"
    },
    "author": {
      "id": 0,
      "name": "author",
      "email": "email@email.email",
      "meta": null
    },
    "version": "2.0",
    "retry": 0,
    "webhook_action": "ADD",
    "event_id": "0"
  }
}
`

**Comment by glibin** [comment]
Добрый день!

К сожалению, пока информация о письмах не отправляется в вебхуках, но у нас есть задача на доработку этого функционала в ближайшем будущем. Точные сроки, к сожалению, пока не смогу назвать.
