### ISSUE TITLE
Расхождение данных о вакансиях с тем, что на портале и запросе через API

### ISSUE THREAD

**Issue by PaulTmatik** [huntflow/api#468]
Добрый день

возникает проблема при попытке получить список вакансий, в этом списке отсутствуют некоторые вакансии, которые отображаются в хантфлоу, а также статусы вакансий не соответствуют со статусами вакансий на хантфлоу.

Для проверки делали такие манипуляции:
1. попытались запросить вакансию по идентификатору: `{{HOST}}/account/{{account_id}}/vacancies/11225` причём для разных account_id. ответ:
``` json
{
    "errors": [
        {
            "type": "common",
            "value": [
                "not found"
            ]
        }
    ]
}
```
2. посмотрев информацию о пользователе через `{{HOST}}/me`, добавили этого пользователя к самой вакансии, далее запросили все вакансии которые есть на этом пользователе `{{HOST}}/account/{{account_id}}/vacancies?mine=true`, ответ:
``` json
{
    "items": [],
    "page": 1,
    "count": 30,
    "total": 1
}
```

так же есть проблемы со статусами, например при запросе всех вакансий с фильтром только открытые, в выборку попали вакансии, которые в хантфлоу отмечены как закрытые (имеют соответствующий бэйдж)

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, последние 6 цифр токена, а также идентификаторы вакансий, которые вы должны видеть, но не видите.

**Comment by PaulTmatik** [comment]
44250c

вакансия: 11225

**Comment by glibin** [comment]
Добрый день!

Ваш токен имеет доступ к двум организациям, поэтому могу предположить, что вы делаете запрос для одной организации, а ожидаете получить данные для другой (или для всех).

Получить список доступных организаций можно тут: https://github.com/huntflow/api/blob/master/ru/user.md#organizations

Далее, при запросах нужно для каждой организации учитывать в пути запроса ее идентификатор `/account/<account_id>`.

**Comment by PaulTmatik** [comment]
Этот кейс мы проверили, нет ни в одной ни в другой, может быть такое что нам просто не тот хост API указали? Используем такой `https://evraz-api-mirror.huntflow.ru`

**Comment by glibin** [comment]
Да, похоже на то. Обратитесь в службу поддержки для получения более подробной информации.

**Comment by PaulTmatik** [comment]
Да, точно, 2 сервера, зеркало и рабочий
