### ISSUE TITLE
Добавление комментариев

### ISSUE THREAD

**Issue by GrayAn** [huntflow/api#47]
Добрый день!

Интересует возможность добавления комментариев к кандидату через API. Имеются в виду комментарии, которые можно получить через метод "Получение истории работы с кандидатом" с типом type=COMMENT. Насколько тяжело это будет реализовать?

И ещё вопрос. Часто попадаются пустые комментарии, у которых стоит тип COMMENT, но comment=None. Что это может означать? Пример запроса:
```
https://api.huntflow.ru/account/16653/applicants/5143712/log
```

**Comment by glibin** [comment]
Добрый день!

Добавить комментарий можно следующим образом:

POST /account/16653/applicants/5143712/log

```
{
"comment": "Комментарий"
"applicant": 5143712,
"vacancy": <vacancy_id>
}
```

Если не передать `vacancy`, то комментарий будет добавлен в личные заметки.

Также, обращаю внимание, что данный функционал пока в стадии бета-тестирования и может измениться в будущем.

По поводу пустых комментариев: пользователь может вместе с комментарием производить дополнительные действия (отправка письма, смс, оффера и т.п.), при этом сам текстовый комментарий будет необязателен.

**Comment by GrayAn** [comment]
Спасибо! К сожалению, запрос возвращает 500 ошибку. Были опробованы варианты:
```
{
  "comment": "Комментарий",
  "applicant": 3523439,
}
```
и
```
{
  "comment": "Комментарий",
  "applicant": 3523439,
  "vacancy": None,
}
```

**Comment by glibin** [comment]
Пришлите, пожалуйста, заголовки и тело запроса сюда или на glibin@huntflow.ru

**Comment by GrayAn** [comment]
Пока собирал информацию, нашёл проблему: я отправлял данные с Content-Type="application/x-www-form-urlencoded", при указании "application/json" сервер ответил 200 OK.

Спасибо!
