### ISSUE TITLE
Загрузка и распознавание файлов

### ISSUE THREAD

**Issue by Evgenij00** [huntflow/api#470]
Добрый вечер!
Пытаюсь загрузить файл через API в Postman
получаю в ответ {"errors": [{"type": "server_error", "value": ["FORBIDDEN"]}]}
не могу понять, что я делаю не так
помогите разобраться, пожалуйста
![image](https://user-images.githubusercontent.com/49844107/150543230-215db380-e39d-47f8-acd8-fa489e83a5d6.png)
![image](https://user-images.githubusercontent.com/49844107/150543369-ee58a35b-2c9e-4866-be06-8d66b6f319d5.png)

**Comment by Evgenij00** [comment]
account id - 110690

**Comment by aleks-v-k** [comment]
Запросы в API (почти все) выполняются в контексте организации, это account_id в пути вида `/account/{account_id}/...`. Список организаций в которые входит пользователь API можно получить через `GET /accounts`. 403 скорее всего потому что вы используете идентификатор пользователя в пути, а не идентификатор организации.
