### ISSUE TITLE
Не получается назначить пользователя на вакансию

### ISSUE THREAD

**Issue by altimar** [huntflow/api#471]
Я использую метод PUT /account/{account_id}/vacancies/{vacancy_id} и передаю массив coworkers с 2 пользователями. Получаю ответ с кодом 200, однако на сайте ничего не меняется.

**Comment by glibin** [comment]
Добрый день!

А вы назначаете рекрутеров или заказчиков? Если заказчиков, то необходимо также передать список доступных этапов подбора.

**Comment by altimar** [comment]
Пытаюсь назначить рекрутеров

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, заголовки и тело запроса, а также тело ответа.
