### ISSUE TITLE
all_divisions возвращает все подразделения как активные, хотя на сайте некоторые уже не отображаются

### ISSUE THREAD

**Issue by altimar** [huntflow/api#472]
После изменения структуры отделов в аккаунте на сайте изменения отображаются нормально, однако в API приходят как новые, так и удаленные позиции и отличить их нет никакой возможности.

**Comment by glibin** [comment]
Добрый день!

Наличие неактивных подразделений определяется параметром active (для неактивных должно возвращаться в виде active=false)

**Comment by altimar** [comment]
Спасибо, я так и подумал, но у всех пунктов стоит active=true (

**Comment by glibin** [comment]
А пришлите пример подразделения (его id), который должен быть неактивен? А также ваш account_id
