### ISSUE TITLE
Каким методом можно получить историю изменений всех вакансий?

### ISSUE THREAD

**Issue by tanyalu18** [huntflow/api#473]
Здравствуйте, нашла в issues не задокументированный еще метод https://api.huntflow.ru/account/<account_id>/vacancy/<vacancy_id>/logs 
но есть необходимость выгружать историю всех изменений по вакансиям, данный метод не совсем для этого пригоден. Есть ли еще варианты?
И так же по всем кандидатам, а не по конкретному.

**Comment by glibin** [comment]
Добрый день!

К сожалению, метода получения истории по всем кандидам или вакансиям нет, но вы можете использовать вебхуки (https://github.com/huntflow/api/blob/master/ru/webhooks.md) для получения всех событий.
