### ISSUE TITLE
Получить ссылку на вакансию

### ISSUE THREAD

**Issue by gromdron** [huntflow/api#475]
Мы хотим на внутреннем портале разместить перечень вакансий, который мы будем получать по API.
Ключевая особенность в том чтобы получать лишь список, а отклики формировать на сайте huntflow.

Получить список вакансий мы можем через API, но как сформировать ссылку на вакансию?
У нас есть 2 вакансии (отдельные), с названием "Head of Aftersales development and parts sales support Dept" и вот в одном случае, ссылка получается при транслитерации, а во втором добавляется постфикс "-1". Как в таком случае получить корректную ссылку на страниу вакансии?

Можно ли расширить модель вакансии URL?

**Comment by glibin** [comment]
Добрый день! Вас интересует ссылка на вакансию в Хантфлоу?

Если да, то она формируется следующим образом: 

https://huntflow.ru/my/<nick>#vacancy/<идентификатор вакансии>

nick можно получить здесь: https://github.com/huntflow/api/blob/master/ru/user.md#organizations

**Comment by gromdron** [comment]
Извините что задержался с ответом.

>Добрый день! Вас интересует ссылка на вакансию в Хантфлоу?

Нет, именно публичная ссылка.
Есть некоторый портал <some_name>.huntflow.io, на которой отображаются вакансии, каждая вакансия имеет свой URL https://<some_name>.huntflow.io/vacancy/<some_slug>

Если есть 2 вакансии Бухгалтер, то ссылка у одной будет "https://<some_name>.huntflow.io/vacancy/bukhgalter", а у второй "https://<some_name>.huntflow.io/vacancy/bukhgalter_v1" и вот эту ссылку на публичный портал мне и нужно получить.

**Comment by gromdron** [comment]
@glibin можете прокомментировать ситуацию?

**Comment by glibin** [comment]
@gromdron к сожалению, в API пока нет возможности получить список опубликованных на внешних сайтах (в том числе на .huntflow.io) вакансий (вместе с перечнем полей и ссылкой на публичную страницу). Я передам пожелание в отдел разработки на добавление такого функционала.
