### ISSUE TITLE
Not Found на логи, при существующей информации о пользователе

### ISSUE THREAD

**Issue by romutchio** [huntflow/api#476]
Добрый день. Появилась странная проблема. 
Запросить информацию по пользователе удается успешно, данные возвращаются 
```
curl -H "Authorization: Bearer SECRET_KEY" https://api.huntflow.ru/account/23115/applicants/21729756
```
Однако запрос логов 
```
curl -H "Authorization: Bearer SECRET_KEY" https://api.huntflow.ru/account/23115/applicants/21729756/log
```
возвращает
```
{"errors": [{"type": "common", "value": ["not found"]}]}
```

Логи должны присутствовать, так как в анкете есть движения (смены статусов и прочее)

**Comment by glibin** [comment]
Добрый день!

Такая ситуация возможна, если кандидат был объединен в дубликат.

Проверьте какой id возвращается в запросе `/account/23115/applicants/21729756` и используйте его для дальнейших запросов.
