### ISSUE TITLE
подразделение в вакансиях

### ISSUE THREAD

**Issue by nexter83** [huntflow/api#477]
Метод для получения информации о вакансии (https://github.com/huntflow/api/blob/master/ru/vacancies.md#vacancy) отдает информацию о компании в которую осуществляется подбор кандидата. Нам бы хотелось дополнительно получить и информацию о подразделении куда осуществляется подбор. Но этой информации в ответе API мы не нашли.
Есть ли возможность получить эту информацию?

**Comment by glibin** [comment]
Добрый день!

Идентификатор подразделения находится в поле account_division.

Получить этот справочник можно так: GET /account/{account_id}/divisions

**Comment by nexter83** [comment]
нужен не справочник подразделений, а в какое подразделение ищется вакансия

**Comment by glibin** [comment]
> Идентификатор подразделения в вакансии находится в поле account_division.

**Comment by nexter83** [comment]
Полнял. Спасибо
