### ISSUE TITLE
ошибка при передаче параметра отличного от дефолтного значения

### ISSUE THREAD

**Issue by nexter83** [huntflow/api#479]
в методе получения списка кандидатов https://github.com/huntflow/api/blob/master/ru/applicants.md#applicants
если передавать значение параметра count больше значения по умолчанию - возвращает ошибку 400 - неправильный запрос

**Comment by glibin** [comment]
Добрый день!

А какое значение вы передаете?

**Comment by nexter83** [comment]
пробовал 100, потом 50. в идеале конечно не меньше 1000 хотелось бы

**Comment by glibin** [comment]
Добрый день!

К сожалению, возможности получать более 30 кандидатов за раз через API нет.

**Comment by nexter83** [comment]
![image](https://user-images.githubusercontent.com/31773558/152549181-542b1d50-f5bf-488c-bb64-f1182d0eec10.png)
тянуть 6935 страниц - по 30 штук - это жестко. зачем вообще параметр если его не изменить по факту
