### ISSUE TITLE
Получение rejection_reason

### ISSUE THREAD

**Issue by Nurzilya** [huntflow/api#48]
Добрый день! 
Как можно посмотреть справочник Причины отказа (rejection_reason)?

**Comment by glibin** [comment]
Добрый день!

`GET /account/<account_id>/rejection_reasons`

**Comment by Nurzilya** [comment]
Благодарю!

**Comment by dKosarevsky** [comment]
Привет.

`GET /account/<account_id>/rejection_reasons` отдаёт 404, почему?

**Comment by glibin** [comment]
Добрый день!

https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/rejection_reasons
