### ISSUE TITLE
Вебхук по заявкам

### ISSUE THREAD

**Issue by NikitaMesn** [huntflow/api#482]
Добрый день! Хотел уточнить что будет содержать post response с событием по заявкам? В описании нет такого события.
![изображение](https://user-images.githubusercontent.com/68643690/151934390-bb2314b8-c4e3-4253-8e4c-92d4e7ae48d3.png)
И вопрос по работе с вакансиями, есть ли возможность создать дополнительное текстовое поле в вакансии? Нужно для того чтобы в этом поле хранилась информация в webhook для другой системы

**Comment by glibin** [comment]
Добрый день!

Описание вебхуов находится ниже https://github.com/huntflow/api/blob/master/ru/webhooks.md#тело-вебхука

> есть ли возможность создать дополнительное текстовое поле в вакансии?

да есть, управляющему рекрутеру Хантфлоу необходимо обратиться в поддержку через встроенный чат или на почту support@huntflow.ru

**Comment by NikitaMesn** [comment]
Это новое поле будет отображаться в вебхуке?

**Comment by glibin** [comment]
Добрый день!

Добавить поля в заявку или вакансию можно через группу поддержки (встроенный в Хантфлоу чат или support@huntflow.ru). После внедрения они появятся в вебхуках.
