### ISSUE TITLE
Проблема при загрузке резюме

### ISSUE THREAD

**Issue by AAlekseevich** [huntflow/api#483]
Отправляем резюме в pdf формате и иногда получаем ошибку в ответе с Вашего апи {"errors": [{"type": "server_error"}]} 

Эндпоинт: https://api.huntflow.ru/account/{id}/upload
Заголовки: 
'Content-Type' => 'multipart/form-data',
'X-File-Parse' => 'true',

Основная часть запросов проходит, но время от времени получаем в логах такую ошибку

**Comment by Shtaket** [comment]
При загрузке файла резюме в метод /upload та же получаем ошибку:
```{"errors": [{"type": "server_error", "value": ["FORBIDDEN"]}]}```

**Comment by AAlekseevich** [comment]
Так же сегодня тоже получали {"errors": [{"type": "server_error", "value": ["FORBIDDEN"]}]}, хотя раньше таких ошибок не наблюдал

**Comment by devdammit** [comment]
Подписываюсь! Господа, авиасейлс страдает — я тоже

**Comment by glibin** [comment]
Добрый день!

Была временная проблема в связи с большим релизом, который произошел вечером 1 февраля. 
На 3 февраля она уже была исправлена.

Уточните, пожалуйста, повторяется ли сейчас проблема?

**Comment by AAlekseevich** [comment]
У нас такая ошибка была последний раз 5 февраля, пока по логам не наблюдаю проблем
