### ISSUE TITLE
Проблема с запросом 

### ISSUE THREAD

**Issue by Yana-Kraynova** [huntflow/api#484]
Добрый день!

По запросу POST или PATCH https://rbru-api.huntflow.ru/account/2/applicants/1383554/questionary

с телом запроса

{
    "personnel_number": abc
}

Появляется 400 ошибка 
{
    "errors": [
        {
            "type": "common"
        }
    ]
}

Если передавать число, то запрос отрабатывает. 

При это в интерфейсе в Хантфлоу удается ввести буквенное значение в этом поле. Поле Card_id кандидата (если кандидат уже заполнил анкету СБ)

Из-за чего возникает ошибка?

**Comment by glibin** [comment]
Добрый день!

Выглядит неверным форматом JSON (не хватает кавычек):

```
{
"personnel_number": "abc"
}
```
