### ISSUE TITLE
Получение города и категории вакансии

### ISSUE THREAD

**Issue by jShox** [huntflow/api#485]
Добрый день, коллеги, отправили к вам. Прикладываю переписку по почте с менеджерами Huntflow.

Я: 
> Я включусь в беседу, со стороны команды разработки.
> Пишу по почте, а не в форму на гихабе, т.к. туда пишутся доработки по API, а мы не уверены, что дело в ней.
>  
> У нас есть ТЗ для вывода списка вакансий на сайте.
> Помимо просто вывода списка предусмотрен еще функционал фильтрации вакансий по Категории и по Городу.
> При реализации импорта данных через API столкнулись с несколькими проблемами:
> 
> 1) Город
> В данных, которые мы получаем через API, в принципе нет поля Город. Мы предполагаем, что у вакансий отсутствует поле Город в принципе, т.е. этих данных нет и быть не может.
> Однако название города присутствует в поле position (Название вакансии).
> Можно достать город из этого поля, но при заполнении город указан в слишком произвольном формате.
> Вот примеры: https://www.screenpresso.com/cloud/vwnSf/
> Варианты решения:
> а) Добавить поле город в ответе API. Если этот вариант в теории возможен, реализация займет не очень много времени, а для запуска в работу нужно создать тикет тут https://github.com/huntflow/api/issues, то мы сделаем.
> б) Привести в единый формат значения в поле position. Как пример: "{Название вакансии}, г. {Название города}"
>  
> 2) Категория
> Для заполнения Категории подходит поле API company
> Но это поле у части вакансий не заполнено. https://www.screenpresso.com/cloud/f8ijf/
> Варианты решения: Заполнить это поле у всех вакансий.
>  
> Также добавлю, что мы видим только то, что отдает API. Мы не знаем, кто, что и в каком виде заполняет, какие данные исходные. Поэтому мы не можем сравнить заполняемые исходные данные и получаемые через API.
> Решения, которые мы предлагаем, это более корректно заполнить текущие данные, не меняя текущий функционал API. Т.е. предполагаем, что проблема в заполнении данных, и нужно просто их откорректировать. Возможно, это неправильные решения.
>  
> Нужна помощь представителей Huntflow для анализа предлагаемых решений.
>  
> С уважением, Дмитрий

Менеджер Huntflow:

> Дмитрий, добрый день, приятно познакомиться.
> С нашими разработчиками связь возможна только через ссылку на гитхаб, так что попрошу вас смело направить их туда. 
> К сожалению, я им перенаправить не могу, разработчики реагируют только на сообщения с ресурса.

**Comment by glibin** [comment]
Добрый день!

Мы можем внедрить наш стандартный справочник регионов в вакансии или ваш собственный, рекрутеры смогут выбирать конкретный город вакансий, а вы получать эту информацию в нормализованном виде через API.

Тоже самое касается и Категорий – мы можем внедрить дополнительное поле с вашим справочником.

Если вас такой вариант устроит, напишите письмо на project@huntflow.ru со ссылкой на данный тикет.
