### ISSUE TITLE
Где взять account_id?

### ISSUE THREAD

**Issue by vberesnev** [huntflow/api#486]
Добрый день
На запрос **GET /me** от хоста https://dodobrands-api.huntflow.ru/  приходит ответ
```
{
    "id": 23,
    "name": "bla-bla",
    "position": "bla-bla",
    "email": "bla-bla",
    "phone": "bla-bla",
    "locale": "ru_RU"
}
```

Согласно [документации ](https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9)`GET /account/{account_id}/vacancies вернёт список вакансий компании.`

Но запрос вида **GET /account/23/vacancies** возвращает **Error Forbidden**
В то время как **GET /account/2/vacancies** возвращает корректный ответ. 

Что за 2, откуда взялась и как ее получить? 
И что за роковое число 23 в таком случае?

Спасибо

**Comment by glibin** [comment]
Добрый день!

https://github.com/huntflow/api/blob/master/ru/user.md#organizations
