### ISSUE TITLE
Создание событий

### ISSUE THREAD

**Issue by apahomov** [huntflow/api#487]
Добрый день! А возможно как-то через API создать собеседование с кандидатом и конкретным сотрудником?

**Comment by glibin** [comment]
Добрый день!

Пока такой возможности нет. Я добавлю ваше пожелание в список доработок по API.

**Comment by glibin** [comment]
Добрый день!

В методе создания записи по истории кандидата появилась возможность создать событие календаря (объект calendar_event): https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/applicants/-applicant_id-/logs
