### ISSUE TITLE
Список вакансий по рекрутерам

### ISSUE THREAD

**Issue by VladAlyushin** [huntflow/api#488]
Добрый день! Каким образом можно получить список вакансий в разрезе рекрутеров? На данный момент используем метод /account/{account_id}/vacancies, но он возвращает поля в которых нет hr-специалиста

**Comment by glibin** [comment]
Добрый день!

К сожалению, сейчас нет отдельного метода для выполнения вышей задачи, я добавлю ваш запрос в перечень доработок по API.

Как получить перечень работающих по вакансии рекрутеров можно здесь: https://github.com/huntflow/api/issues/155
