### ISSUE TITLE
Метод all_divisions изменил состав возвращаемых полей

### ISSUE THREAD

**Issue by tanyalu18** [huntflow/api#489]
Здравствуйте, столкнулась с ситуацией, что "/account/2/all_divisions" get запрос возвращал сначала один состав полей: id, lft, rgt, account, parent, name, foreign, created, removed, active, meta, deep, order; - теперь возвращает без lft, rgt, account, created

Почему так получилось? Это связано с настройками нашего huntflow или же из-за того, что метод не задокументирован его настройки могут меняться?

+ есть ли вероятность что задокументированные методы тоже будут меняться?

**Comment by glibin** [comment]
Добрый день!

Набор полей был уменьшен для экономии передаваемого трафика (уменьшение объема данных), так как содержал в большинстве служебные поля.

Подскажите, вы использовали данные поля? Повлияло ли это каким-то образом на ваши интеграции?

**Comment by tanyalu18** [comment]
Добрый день! 
Спасибо за ответ, на нынешнем этапе никак не повлияло на интеграции. Теперь интересует, насколько частая история с изменением набора полей для методов и касается ли это методов, которые уже представлены в документации?

**Comment by glibin** [comment]
Добрый день!

История крайне редкая, а какие-то изменения с потенциальным breaking changes мы анонсируем заранее. В данном случае, рисков проблем с обратной совместимостью мы не обнаружили, поэтому я и попросил уточнить, могло ли это как-то значимо повлиять на ваши интеграции.

Также мы готовим к релизу новую версию API с документацией по всем методам, которые ранее были недокументированы.

**Comment by tanyalu18** [comment]
Спасибо большое! 
Еще один вопрос: а в каком виде и где анонсируются изменения?

**Comment by glibin** [comment]
> Еще один вопрос: а в каком виде и где анонсируются изменения?

В рамках рассылки на почту управляющим рекрутерам.
