### ISSUE TITLE
Ограничение кол-ва запросов к api

### ISSUE THREAD

**Issue by Aqquila1** [huntflow/api#490]
Добрый день! Вы недавно как-то ограничивали допустимое количество запросов к API? При сборе логов кандидатов теперь появляется status code 429, раньше такого не было

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, адрес вашего Хантфлоу?

Об ограничении на количество запросов есть информация здесь: https://github.com/huntflow/api/blob/master/ru/general.md#ограничение-на-количество-единовременных-запросов

**Comment by Aqquila1** [comment]
https://skyeng.huntflow.ru/

**Comment by glibin** [comment]
Добрый день!

Ограничение может возникать в случае влияния на работу сервиса (деградация производительности), что и произошло в вашем случае. 

Если вам необходимо делать большое количество запросов в API, то было бы интересно узнать кейс такого использования, чтобы мы могли предложить более оптимальный вариант его использования. Напишите, пожалуйста, ваш кейс на project@huntflow.ru с копией glibin@huntflow.ru
