### ISSUE TITLE
Как сделать так, чтобы при изменении статуса кандидата происходил определённый вызов API Альткрафта

### ISSUE THREAD

**Issue by bluecafee** [huntflow/api#493]
Нужно, чтобы при изменении статуса кандидата в ХФ ему приходила соответствующая статусу почтовая отбивка через Альткрафт. АПИ только мейл. Ручки будут типа таких: 

Для новых заявок:

curl --location --request POST 'https://altcraft-sender.avs.io/api/trigger/advertising/fsk/sydney-city-apply' \
--header 'Authorization: Basic {login:password}' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "{email}"
}'

Для тех, кто подтвердился:

curl --location --request POST 'https://altcraft-sender.avs.io/api/trigger/advertising/fsk/sydney-city-confirm' \
--header 'Authorization: Basic {login:password}' \
--header 'Content-Type: application/json' \
--data-raw '{
  "email": "{email}"
}'

**Comment by glibin** [comment]
Добрый день! 

Вы можете добавить вебхук по кандидату и сделать обработчик, который отправит запрос в нужный сервис: https://github.com/huntflow/api/blob/master/ru/webhooks.md
