### ISSUE TITLE
Вывод статуса вакансии

### ISSUE THREAD

**Issue by alvlad** [huntflow/api#494]
Добрый день! в методе /account/{account_id}/vacancies есть поле status. Также есть метод /account/{account_id}/vacancy/statuses - как я понимаю это все этапы вакансии. Как то можно получить список вакансий по всем этапам процесса?

**Comment by glibin** [comment]
Добрый день!

> в методе /account/{account_id}/vacancies есть поле status. 

Это поле отвечает за статус вакансии. 

Метод `/account/{account_id}/vacancy/statuses` возвращает список этапов подбора по кандидатам на вакансии.
