### ISSUE TITLE
Загрузка результатов тестирования в этап подбора из внешней системы

### ISSUE THREAD

**Issue by KirillKVK** [huntflow/api#495]
Есть ли возможность через API Хантфлоу загрузить результаты тестирования (файл, текст) в этап подбора из внешней системы? Не нашел соответствующего метода в описании.

**Comment by glibin** [comment]
Добрый день!

По добавлению комментария можно почитать здесь: https://github.com/huntflow/api/issues/47

Для добавления файла, его нужно сначала загрузить (https://github.com/huntflow/api/blob/master/ru/upload.md#загрузка-и-распознавание-файлов), затем в объект на добавления комментария добавить поле `"file": [1]`, где 1 – идентификатор загруженного файла.
