### ISSUE TITLE
Отправка запросов со стороны фронта

### ISSUE THREAD

**Issue by bortmehannik** [huntflow/api#496]
Здравствуйте!
Необходимо делать запросы к хантфлоу через js (без дополнительных фреймворков), на данный момент получаю следующую ошибку в консоли:

Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Возможно ли на вашей стороне разрешить обращение с конкретного домена, чтобы запросы проходили?
Также отмечу, что доступа к файлу .htaccess у нас также нет и вносить какие-то изменения через него тоже не получится.

**Comment by glibin** [comment]
Добрый день!

На данный момент, API не поддерживает CORS.
Рекомендуем обращаться к API Хантфлоу с серверной стороны.

Более того, размещая токен на стороне клиента (в клиентском JS) вы делаете его общедоступным и каждый сможет получить доступ к вашей базе кандидатов со всей историей и комментариями.
