### ISSUE TITLE
Не работает API

### ISSUE THREAD

**Issue by AndreyMaryutin** [huntflow/api#497]
Добрый день, не работает https://api.huntflow.ru/account - отдает 404, прошу Вас разобрать в чем может быть дело и прислать мне ответ. С нашей стороны сервис работает.

**Comment by glibin** [comment]
Добрый день!

В Хантфлоу API нет метода `https://api.huntflow.ru/account`, но есть `https://api.huntflow.ru/accounts`

**Comment by AndreyMaryutin** [comment]
Мы допустили опечатку, но это не меняет результата.
При запросе аккаунтс мы получаем пустое поле. Как нам проверить работоспособность api и нашего ключ?
Get vacancies at: 2022-02-25 08:13:41.262544
accounts {'items': []}

**Comment by glibin** [comment]
Добрый день!

Уточните, пожалуйста, название вашей организации и адрес Хантфлоу?

**Comment by AndreyMaryutin** [comment]
[KamaGames Studio](https://huntflow.ru/settings/orgs/kamagameshr)

**Comment by AndreyMaryutin** [comment]
https://huntflow.ru/settings/orgs/kamagameshr

**Comment by glibin** [comment]
Добрый день!

Теперь вы можете управлять токенами из интерфейса: https://huntflow.ru/settings/orgs/kamagameshr/api 

Проверьте, что ваш токен есть там или сгенерируйте новый.
