### ISSUE TITLE
Апи выдает ошибку 429 при попытке обновить трех справочников

### ISSUE THREAD

**Issue by yurgen96** [huntflow/api#498]
Тема аналогично https://github.com/huntflow/api/issues/490

обновляем за раз 3 справочника (раз в сутки), на последнем стабильно валится ошибка

HTTP/1.1 429 Too Many Requests returned for "https://api.huntflow.ru/account/110578/dictionary/possible_project

нужно пофиксить асап или отписать четко какие правила по работе с апи

**Comment by glibin** [comment]
Добрый день!

Обновление справочников лучше выполнять последовательно, так как может сработать ограничение на одновременное обновление справочников.

**Comment by yurgen96** [comment]
мы так и делаем, но вроде у вас же внутри все асинхронно. какой нужен интервал между запросами чтобы апишка не ругалась?

**Comment by yurgen96** [comment]
ау, дайте инфу какой должен быть промежуток между запросами чтобы апишка НЕ выдавала такую ошибку?

**Comment by glibin** [comment]
Добрый день!

Механизм такой:

В ответе на создание справочника придет уникальный идентификатор задачи –– `payload.task_id`.
Нужно отследить завершение выполнения обновления справочника – [Как отслеживать статус задачи](https://github.com/huntflow/api/blob/master/ru/delayed_tasks.md).
После этого выполнять запрос на обновление следующего.

Я передам в команду пожелание упростить работу и загрузку справочников нескольких справочников одновременно.
