### ISSUE TITLE
Тестирование массовой загрузки базы кандидатов 

### ISSUE THREAD

**Issue by svetamelkina** [huntflow/api#499]
Добрый вечер!
Мне необходимо проверить загрузку базы кандидатов (несколько десятков тысяч) в тестовой песочнице Хантфлоу.
Подскажите, есть ли оптимальные способы это сделать? и как? 

нашла только метод для создания по одному кандидату в ХФ.

**Comment by glibin** [comment]
Добрый день!

Коллеги сообщили, что уже ответили на этот вопрос по другим каналам. Могу закрыть тикет?

**Comment by svetamelkina** [comment]
Добрый день! Да, по загрузке разобрались, закрывайте

Сб, 5 марта 2022 г. в 13:27, Vitaly Glibin ***@***.***>:
