### ISSUE TITLE
Получение данных об ответственном рекрутере по вакансии

### ISSUE THREAD

**Issue by svetamelkina** [huntflow/api#500]
Нам необходимо получать информацию об ответственном рекрутере при работе с вакансией (тот рекрутер, который работает над вакансией, он должен быть один). 
Желательно получать такую информацию по запросу и через вебхуки. 

Есть ли такая возможность? (просьба приложить примеры запросов на получение данных, ответов вебхуков - какой параметр смотреть)

**Comment by glibin** [comment]
Добрый день!

> Нам необходимо получать информацию об ответственном рекрутере при работе с вакансией (тот рекрутер, который работает над вакансией, он должен быть один).

Если вы имеете ввиду работающих по вакансии коллег, то можно воспользоваться информацией из тикета: https://github.com/huntflow/api/issues/155

Если вы имеете в виду дополнительные поля (справочники) в вакаснии, то их можно получить запросом на вакансию и также они приходят в вебхуках. Так как это поля настраиваемые под клиента, то вы сможете их увидеть самостоятельно в API. Однако, такие поля сначала должны быть внедрены.

**Comment by svetamelkina** [comment]
Добрый день!
уточните, а как из метода /account/<account_id>/members?vacancy=<vacancy_id> понять, кто именно работает над вакансией? 
на тестовой песочнице у меня всего один юзер - он же и создатель заявки, и вакансии, и работает над вакансией.
мне нужно понять, можно ли получить именно юзера, работающего над вакансией?
например, заявку создал user1, вакансию создал user2, а работает над вакансией на самом деле user3 (его нужно и получить)

**Comment by glibin** [comment]
> уточните, а как из метода /account/<account_id>/members?vacancy=<vacancy_id> понять, кто именно работает над вакансией?

В Хантфлоу работать над вакансией могут несколько рекрутеров (для этого рекрутер должен быть назначен на вакансию), указанный метод вернет именно назначенных на вакансию рекрутеров.
