### ISSUE TITLE
Получение данных по квотам

### ISSUE THREAD

**Issue by Fosly** [huntflow/api#501]
Добрый день.
Имеется ли возможность получать историю по квотам?
На некоторых вакансиях квоты замещаются, исторические не сохранятся, а на них есть люди.
Пример:
Аккаунт 71690
Вакансия 2777468, на ней сейчас квота 751463, нанятых нет. 
Но также к этой вакансии был нанят кандидат 21090258 (лог 122169261), но привязан он к другой квоте 670463, которая не возвращается по запросу vacancy/2777468/quotas.
Как найти данные по квоте 670463?

**Comment by glibin** [comment]
Добрый день!

В ближайшее время (в течение 1-2 недель) мы планируем релиз новой версии API, в которой информация по квотам будет доступна.

**Comment by Fosly** [comment]
@glibin поддержка текущего API останется? Если да, то на какой срок?
