### ISSUE TITLE
Получение статистики по заявкам (не вакансиям)

### ISSUE THREAD

**Issue by svetamelkina** [huntflow/api#503]
Требуется получать статистику по заявкам:
- количество заявок в разрезе статусов заявки/вакансии
- количество кандидатов по заявке в разрезе статусов заявки
- фильтрация по дате

На текущий момент такой воронки не существует. 
Уточните, есть ли возможность получать статистику по заявкам по API?

**Comment by svetamelkina** [comment]
добрый день! очень ждем обратной связи по вопросу

**Comment by glibin** [comment]
Добрый день!

Возможности получать аналитику именно по заявкам на вакансии сейчас нет. 

Потенциально, вы можете на базе вебхуков по заявкам отслеживать их состояние (взятие в работу или отказ), а также получать информацию о выходах кандидатов по конкретным заявкам на вакансии.
