### ISSUE TITLE
Инициализация account_division при создании заявки на вакансию

### ISSUE THREAD

**Issue by portretnyy** [huntflow/api#506]
Добрый день. Четыре дня назад возникла проблема с инициализацией атрибута account_division в системе Хантфлоу. 

// when
Отправляем заявку на вакансию через 

`https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E`

Также, ваши коллеги для нас в тело запроса добавляли атрибут account_division, в который мы отправляем название команды в виде string

// then

Заявка успешно создается. Однако на выходе через 

`https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D1%8F%D0%B2%D0%BA%D0%B8-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E`

мы получаем одно и то же значение account_division, не соответствующее тому, которое было отправлено при создании заявки.

Возможно, мы должны отправлять не название команды, а ее идентификатор? Если да, то какой - наш внешний (foreign из нашей системы) или же какой-то другой?

**Comment by portretnyy** [comment]
В целом, хотелось бы понять тип и вид данных для этого аттрибута при отправке в Хантфлоу. Благодарю

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, пример запроса.

О том, как передавать значения справочников (в тч системных) показано здесь: https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancy_requests

**Comment by portretnyy** [comment]
> Добрый день!
> 
> Пришлите, пожалуйста, пример запроса.
> 
> О том, как передавать значения справочников (в тч системных) показано здесь: https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancy_requests

POST /account/{account_id}/vacancy_request
тело запроса:
```
{
  "accountDivision": "Корп. портал",
  "accountVacancyRequest": "1",
  "clusterLeaderFullName": "Ивановский Иван Иванович",
  "comment": "Комментарий",
  "companyName": "Банк",
  "creatorFullName": "Сергеев Сергей Сергеевич",
  "description": "Описание",
  "direction": null,
  "externalAttribute": "ИТ",
  "externalId": "1",
  "fullName": "Васильев Василий Васильевич",
  "grade": "7",
  "leaderFullName": "Алексеев Алексей Алексеевич",
  "money": "10000000",
  "ownerFullName": "Игорев Игорь Игоревич",
  "position": "Разработчик",
  "productOwnerFullName": "Артемьев Артем Артемович",
  "skills": "Java"
}
```

**Comment by glibin** [comment]
Добрый день!

Вам необходимо получить схему заявки на вакансию: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/account_vacancy_requests

Затем по этой схеме передать необходимый набор параметров в Хантфлоу.

**Comment by glibin** [comment]
> Вопрос заключается именно в том, что это за тип данных - division? Насколько я понимаю, это не словарь потому, что тип словаря в схеме определен как dictionary

Это специальный системный словарь, можно посмотреть его содержимое в вашей организации: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/divisions или обновить https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/divisions/batch

Однако, для удобства передачи данных из внешних систем можно использовать идентификатор подразделения в вашей внутренней системе, тогда в запросе нужно будет передать параметр в виде:

```
{
...
"account_division": {"foreign": "идентификатор подразделения в вашей системе"}
...
}
```

**Comment by portretnyy** [comment]
> > Вопрос заключается именно в том, что это за тип данных - division? Насколько я понимаю, это не словарь потому, что тип словаря в схеме определен как dictionary
> 
> Это специальный системный словарь, можно посмотреть его содержимое в вашей организации: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/divisions или обновить https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/divisions/batch
> 
> Однако, для удобства передачи данных из внешних систем можно использовать идентификатор подразделения в вашей внутренней системе, тогда в запросе нужно будет передать параметр в виде:
> 
> ```
> {
> ...
> "account_division": {"foreign": "идентификатор подразделения в вашей системе"}
> ...
> }
> ```

Правильно ли я понимаю, что в качестве идентификатора используется именно целое число, но никак не название подразделения?

**Comment by portretnyy** [comment]
> > Правильно ли я понимаю, что в качестве идентификатора используется именно целое число, но никак не название подразделения?
> 
> Верно. Для передачи через foreign этот идентификатор нужно преобразовать в строку.

Прошу прощения за задержку. Тогда пробуем отправить запрос с подобным телом и я закрываю тикет. Благодарю за помощь.

```
{
  "accountDivision": {"foreign": "147"},
  "accountVacancyRequest": "1",
  "clusterLeaderFullName": "Ивановский Иван Иванович",
  "comment": "Комментарий",
  "companyName": "Банк",
  "creatorFullName": "Сергеев Сергей Сергеевич",
  "description": "Описание",
  "direction": null,
  "externalAttribute": "ИТ",
  "externalId": "1",
  "fullName": "Васильев Василий Васильевич",
  "grade": "7",
  "leaderFullName": "Алексеев Алексей Алексеевич",
  "money": "10000000",
  "ownerFullName": "Игорев Игорь Игоревич",
  "position": "Разработчик",
  "productOwnerFullName": "Артемьев Артем Артемович",
  "skills": "Java"
}
```
