### ISSUE TITLE
Загрузка нескольких резюме

### ISSUE THREAD

**Issue by arkhodakov** [huntflow/api#507]
Подскажите, можно ли реализовать загрузку множества вложений (резюме) для кандидата?
Никакие манипуляции с добавлением второго dict к files или добавление второго dict в массив extensions не работают.
Либо выбрасывает ошибку, либо на сайте отображается только один файл.
Спасибо.

**Comment by glibin** [comment]
Добрый день!

К сожалению, сейчас доступна только загрузка одного резюме по кандидату.

**Comment by arkhodakov** [comment]
Спасибо.
