### ISSUE TITLE
Новое API

### ISSUE THREAD

**Issue by Fosly** [huntflow/api#508]
Добрый день.
Подскажите, пожалуйста, ориентировочный срок выпуска нового API?
В течении какого времени будет сохранятся поддержка существующего API?

**Comment by glibin** [comment]
Добрый день!

Официальный анонс нового API будет в ближайшее время. Документация уже доступна: https://api.huntflow.ru/v2/docs#overview

Поддержку старого API мы прекратим 31 октября 2022.
