### ISSUE TITLE
Вопросы по загрузке файлов через API

### ISSUE THREAD

**Issue by EvgenyAstafurov** [huntflow/api#51]
Столкнулся с некоторыми проблемами, при использовании API, возможно, что-то делаю не так:
1. Сервер отвечает, что все успешно загружено, но обратная ссылка не работает, в название файла подставляется путь.
Ниже подробный лог, что и куда выгружается. :

Данные по файлу, полученные из формы:
Array
(
    [file] => Array
        (
            [name] => Тестеров Тестер Тестович.docx
            [type] => application/vnd.openxmlformats-officedocument.wordprocessingml.document
            [tmp_name] => /usr/local/var/sites/b2u.su/tmp/phpmC7Kcz
            [error] => 0
            [size] => 14815
        )

)
Данные отправляемые на API:
CURLFile Object
(
    [name] => /usr/local/var/sites/b2u.su/tmp/phpmC7Kcz
    [mime] => application/vnd.openxmlformats-officedocument.wordprocessingml.document
    [postname] => Тестеров Тестер Тестович.docx
)
Информация по соединению:
Array
(
    [url] => https://api.huntflow.ru/account/29071/upload
    [content_type] => application/json; charset=UTF-8
    [http_code] => 200
    [header_size] => 346
    [request_size] => 380
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.143342
    [namelookup_time] => 0.001851
    [connect_time] => 0.011532
    [pretransfer_time] => 0.049717
    [size_upload] => 15105
    [size_download] => 281
    [speed_download] => 1965
    [speed_upload] => 105629
    [download_content_length] => 281
    [upload_content_length] => 15105
    [starttransfer_time] => 0.059409
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 82.202.193.170
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 95.163.71.164
    [local_port] => 14317
)
Ответ от API:
stdClass Object
(
    [content_type] => application/octet-stream
    [url] => https://store.huntflow.ru/uploads/named/9/y/k/9ykin9rogxzo3t3qze0ale1vpuun8108//usr/local/var/sites/b2u.su/tmp/phpXWIYUV?s=yEe2swvioW7pfZG__utEAQ&e=1561071559
    [id] => 5473693
    [name] => /usr/local/var/sites/b2u.su/tmp/phpXWIYUV
)

2. Где в системе видны добавляемые файлы, как ими можно оперировать, или они остаются в системе навечно?
3. Собственно, возможно, из-за неправильной загрузки файла, он не прикрепляется к кандидату. Но это будем уже рассматривать, после 1-го вопроса.

**Comment by glibin** [comment]
Добрый день!

Разбираемся в проблеме, о результате сообщим.

**Comment by glibin** [comment]
Есть проблема с обработкой имен файлов со слешами на нашей стороне. Исправление в тестировании.

Также, вы можете обработать и передать имя файла в корректном виде, пример для Python:

```
import requests 

files = {'file': ('resume.pdf', open('./resume.pdf', 'rb'), 'application/pdf')}

headers = {
    'Authorization': 'Bearer <token>',
    'X-File-Parse': 'true'
}

print(requests.post('https://api.huntflow.ru/account/29071/upload', headers=headers, files=files).json())
```

**Comment by EvgenyAstafurov** [comment]
я понял, по сути, решение, которое Вы предлагаете, это кидать Вам не файл сразу из формы, из темповой папки, а обработать его, сохранить локально рядом со скриптом и послать Вам файл без пути, где путь будет соответствовать только названию... 
принято!
хотя, имхо, с Вашей стороны было бы проще обрабатывать одно доп.поле, если бы Вы ввели в API, это стандартные три поля: путь к файлу, тип файла, оригинальное имя файла

**Comment by glibin** [comment]
Я думаю, ваш вариант как-то возможно реализовать, но я не обладаю достаточными навыками в PHP, чтобы подсказать решение :)

**Comment by EvgenyAstafurov** [comment]
эмм... я про php вроде бы и не писал в последнем комменте :) все общими словами, на любых языках такое было бы логично, но это только имхо )))

**Comment by glibin** [comment]
Про PHP я рассудил по формату логов из первого сообщения :-) 

Я описывал вариант, когда возможно обработать входящий файл и передать его сразу в API без дополнительной обработки, отвечая на эту часть вашего сообщения:

> я понял, по сути, решение, которое Вы предлагаете, это кидать Вам не файл сразу из формы, из темповой папки, а обработать его, сохранить локально рядом со скриптом и послать Вам файл без пути, где путь будет соответствовать только названию...

**Comment by EvgenyAstafurov** [comment]
и так, вариант с передачей обработанного файла удался, файл загрузился и открывается по ссылке, которая приходит в ответ от сервера!

буду проверять дальше.

Спасибо!

**Comment by EvgenyAstafurov** [comment]
и так, прошу опять помощи! вполне возможно, что просто заработался и что-то делаю не так :)

дальнейшие пробы добавить файл в карточку кандидата, так и не увенчались успехом, пробовал и не по API делать с помощью объектов, и по описанию - с помощью массивов, результат один, ответ от сервера 500 ошибка...

Ответ от API при добавлении файла:
{"name": "\u0422\u0435\u0441\u0442\u0435\u0440 \u0422\u0435\u0441\u0442\u043e\u0432\u0438\u0447 .pdf", "content_type": "application/pdf", "url": "https://store.huntflow.ru/uploads/named/y/h/n/yhnvjfe6l3z1le67ii7kr6m1ltxygtve.pdf/%D0%A2%D0%B5%D1%81%D1%82%D0%B5%D1%80%20%D0%A2%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%B8%D1%87%20.pdf?s=Jbbm1uOat5x8_IcTXtfLGA&e=1561568311", "id": 5499745}

Добавление прошло успешно, ссылка на файл работает, id файла есть!

Дальше отправляем данные по добавлению кандидата в базу и в каком бы виде я не добавлял информацию по файлу в ключе "externals", ответ всегда одинаковый, стоит убрать данный ключ, кандидат успешно добавляется.
В виде массива отправляемые данные:
Array
(
    [last_name] => Тестер Тестович
    [first_name] => 
    [middle_name] => 
    [phone] => +7(123)456-78-90
    [email] => test@test.ru
    [externals] => Array
        (
            [files] => Array
                (
                    [id] => 5499745
                )

        )

)
В виде JSON формата:
{
    "last_name": "\u0422\u0435\u0441\u0442\u0435\u0440 \u0422\u0435\u0441\u0442\u043e\u0432\u0438\u0447",
    "first_name": "",
    "middle_name": "",
    "phone": "+7(123)456-78-90",
    "email": "test@test.ru",
    "externals": {
        "files": {
            "id": 5499745
        }
    }
}

Информация по соединению:
Array
(
    [url] => https://api.huntflow.ru/account/29071/applicants
    [content_type] => application/json; charset=UTF-8
    [http_code] => 500
    [header_size] => 339
    [request_size] => 527
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.101835
    [namelookup_time] => 0.001999
    [connect_time] => 0.013066
    [pretransfer_time] => 0.051935
    [size_upload] => 221
    [size_download] => 38
    [speed_download] => 376
    [speed_upload] => 2188
    [download_content_length] => 38
    [upload_content_length] => 221
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 82.202.193.170
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 95.163.71.164
    [local_port] => 11776
)

Ответ от API:
{"errors": [{"type": "server_error"}]}

**Comment by glibin** [comment]
Добрый день!

Похоже, что формат передаваемого JSON не совпадает с описанным в документации:

https://github.com/huntflow/api/blob/master/ru/applicants.md#add

Обратите внимание, что "externals" - это массив, а не объект.

**Comment by EvgenyAstafurov** [comment]
Итог, стандартными методами передать тот формат, который Вам нужен, не получается. В итоге было принято решение, просто текстом отправлять Вам этот формат :) Все работает, интеграция успешна, по сути все методы проверены )))
Задачу закрываем.
