### ISSUE TITLE
Справочник идентификаторов и доступных регионов

### ISSUE THREAD

**Issue by arkhodakov** [huntflow/api#510]
Где можно получить идентификаторы доступных регионов для поля с типом region в Questionary?
Если с типом dictionary всё понятно, то запроса на получение доступных полей для типа region в анкетах кандидата просто нет.

**Comment by glibin** [comment]
Добрый день!

https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/regions

**Comment by arkhodakov** [comment]
Спасибо!
