### ISSUE TITLE
Метод applicants

### ISSUE THREAD

**Issue by OpenDSIT** [huntflow/api#511]
Добрый день.

Метод applicants возвращает в т.ч. поле link, которое в свою очередь содержит поле rejection_reason, которое имеет цифровое значение, т.е. представляет собой справочник. Каким методом можно получить этот справочник? Вроде бы поддержка дала в меру очевидный ответ - GET /account/<accountid>/rejectionreasons, но такой вариант возвращает 404 ошибку

 

https://api.huntflow.ru/account/69759/applicants/21649970

 "links": [

        {

            "id": 21304070,

            "vacancy": 2825645,

            "status": 111420,

            "changed": "2022-03-10T15:25:28+03:00",

            "updated": "2022-03-10T15:25:28+03:00",

            "rejection_reason": 87082

        },

**Comment by OpenDSIT** [comment]
<img width="459" alt="image001" src="https://user-images.githubusercontent.com/77154222/159034078-24fdfc73-3897-4c0f-85e5-546ae592313b.png">

**Comment by glibin** [comment]
Добрый день!

https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/rejection_reasons
