### ISSUE TITLE
Загрузка данных в базу регионов

### ISSUE THREAD

**Issue by asobolev21** [huntflow/api#512]
Доброе время суток. Сейчас у нас появилась необходимость загружать новые регионы и города в базу Huntflow более оперативно. И она пала на меня:)  Я почитал инструкцию которой со мной поделились и само собой не понял нечего. Ранее мы создавал базу данных в exel и передавал ее человеку который загружал ее в Huntflow. Есть ли какая то возможность объяснить мне на пальцах как сделать это максимально просто и быстро? Может есть какая то подробная инструкция которая позволит быстро выполнять данный процесс?

**Comment by glibin** [comment]
Добрый день!

Есть метод обновления справочника с описанием необходимых полей для передачи: https://github.com/huntflow/api/blob/master/ru/dictionaries.md#edit
