### ISSUE TITLE
Ошибка при попытке создать токен в песочнице

### ISSUE THREAD

**Issue by FMajesty** [huntflow/api#515]
При попытке создать токен для доступа к API в песочнице при переходе по ссылке выдаёт ошибку.
Путь из логов: `http://127.0.0.1:7550/token_request/...`
Ошибка:
```
{
  "errors": {
    "common": [
      "error.production_calendar.not_found"
    ]
  }
}
```
Контакты: n.yudenkov@skipp.pro / @nyudenkov (TG)

**Comment by glibin** [comment]
Добрый день!

Проблема на данный момент должна быть устранена. Проверьте, пожалуйста.

**Comment by FMajesty** [comment]
Доброго дня. Нет, всё та же проблема.
