### ISSUE TITLE
Запрос кандидатов падает в ошибку

### ISSUE THREAD

**Issue by VladAlyushin** [huntflow/api#516]
Добрый день! Используем новое апи, при запросе списка всех кандидатов получаем ошибку 
![image](https://user-images.githubusercontent.com/99317690/161761550-75460931-47a0-454f-8051-2b076f280c30.png)
{
    "errors": [
        {
            "type": "not_found",
            "title": "Not Found"
        }
    ]
}
сам запрос https://api.huntflow.ru/v2/accounts/<account id>/applicants?page=

![image](https://user-images.githubusercontent.com/99317690/161761654-f87853f6-c113-44e2-969c-957c406e51da.png)

со старым api все работает

**Comment by glibin** [comment]
Добрый день!

Не смогли воспроизвести проблему. Подскажите, сохраняется ли он на данный момент?

**Comment by VladAlyushin** [comment]
Да. При этом на старом апи выдает без проблем

**Comment by glibin** [comment]
Пришлите, пожалуйста, на glibin@huntflow.ru полные заголовки запроса и полные заголовки и тело ответа (от токена API следует оставить только последние 6 символов).
