### ISSUE TITLE
мапинг APPLICANT и VACANCY

### ISSUE THREAD

**Issue by IvanZuzin** [huntflow/api#517]
Подскажите, пожалуйста, по какому ключу можно связать данный полученные от вебхуков APPLICANT и VACANCY.

**Comment by glibin** [comment]
Добрый день! 

О связке каких данных идет речь?

**Comment by IvanZuzin** [comment]
> Добрый день!
> 
> О связке каких данных идет речь?

Настроены вебхуки по действиям над кандидатом(APPLICANT) и действиям по вакансиям(VACANCY). Данные от вебхуков записываются в БД в виде таблице. Можно ли связать две полученные таблицы по какому-то ключу.

**Comment by glibin** [comment]
Если действие по кандидату происходит по вакансии, то в данных по кандидату будет передана соответствующая вакансия. По ней и можно сделать связку.
