### ISSUE TITLE
Метод get vacancies

### ISSUE THREAD

**Issue by Pavel-Qiwi** [huntflow/api#518]
Добрый день.
во второй версии api, при использовании метода получения списка вакансий в поле applicants to hire нет значений.
https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancies
![image](https://user-images.githubusercontent.com/80900126/162231128-87b2e75c-91f1-4205-831a-0779a7c30ad5.png)

в первой версии api эти данные были.
![image](https://user-images.githubusercontent.com/80900126/162231302-9d38ddda-796f-4924-a7fb-8ac4b6b1d637.png)

просьба помочь, т.к. это поле является критичным для массовых позиций.

**Comment by glibin** [comment]
Добрый день!

Данные поля являлись устаревшими в первой версии API и более не поддерживаются во второй.

Для получения значений необходимо использовать метод получения квот: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancies/-vacancy_id-/quotas
