### ISSUE TITLE
Проблема с токеном

### ISSUE THREAD

**Issue by Dzhalolov** [huntflow/api#519]
Пытаюсь достучаться до песочницы huntflow
header_params = {
'Authorization': 'Bearer token'
}
requests.get(url = 'https://api.huntflow.ru/v2/me', headers=header_params).text,
но получаю ошибку {"errors":[{"type":"authorization_error","title":"Authorization Error","detail":"Invalid access token"}]}
пытался также достучаться по апи через https://api.huntflow.ru/v2/docs#get-/me, но также какая-то проблема с токеном, но токен вроде бы правильно получен 
![image](https://user-images.githubusercontent.com/48567073/163136917-67767a08-973e-4206-9d31-8db9e065b755.png)

**Comment by glibin** [comment]
Добрый день! У песочницы отдельный адрес API: https://sandbox-api.huntflow.dev/v2/me

**Comment by khalpili** [comment]
Документация из этого репозитория не для работы с https://sandbox-api.huntflow.dev/v2/
