### ISSUE TITLE
Получение списка вакансий

### ISSUE THREAD

**Issue by pandamy619** [huntflow/api#52]
Если при запросе «/account/{account_id}/vacancies» поле company пустое.
Данные не добавлены со стороны компании ?

**Comment by glibin** [comment]
Добрый день!

Есть похожее обсуждение здесь: https://github.com/huntflow/api/issues/46

Подскажите, помогло ли оно вам?

**Comment by pandamy619** [comment]
День добрый! спасибо!
можно закрывать вопрос

**Comment by glibin** [comment]
👍
