### ISSUE TITLE
Добавление members через API

### ISSUE THREAD

**Issue by SikSpears** [huntflow/api#520]
Приветы!
Скажите, пожалуйста, можно-ли как-то через API добавить нового member? Например, с ролью watcher? Ну и другие роли тоже интересны.

**Comment by glibin** [comment]
Добрый день!

Такой возможности в API сейчас нет.

**Comment by SikSpears** [comment]
А планируется?

**Comment by glibin** [comment]
Да, в планах есть, но такой функционал будет доступен только клиентам на выделенных серверах и on-premise.

**Comment by SikSpears** [comment]
О, а еще и on-premise будет? Или уже есть?

**Comment by glibin** [comment]
Я не понял ваш вопрос :) 

Хантфлоу может размещаться в облаке (huntflow.ru), на выделенных серверах и серверах клиента (on-premise).

**Comment by SikSpears** [comment]
Ну вопрос как раз в том, что я думал, что только в облаке :) 
Спасибо! А куда идти за более подробной информации по размещению on-premise?

**Comment by glibin** [comment]
Напишите на sales@huntflow.ru

**Comment by SikSpears** [comment]
Спасибо!
