### ISSUE TITLE
запрос по id кандидату выдает Unknown applicant хотя такой iD точно есть в базе

### ISSUE THREAD

**Issue by Alexcrmdev** [huntflow/api#521]
Вопрос по работе апи, запрос по id кандидату выдает Unknown applicant хотя такой iD точно есть в базе. 

В чем может быть дело? 

![image](https://user-images.githubusercontent.com/103564454/163378504-dd295a6c-64db-4d6c-8dc9-ddfe142c48eb.png)

**Comment by glibin** [comment]
Добрый день!

Убедитесь, что используете корректные параметры и URL запроса.
