### ISSUE TITLE
Coworker id|member

### ISSUE THREAD

**Issue by Fosly** [huntflow/api#522]
Все запросы при наличии отсылки к сотруднику выдают ID (что является на самом деле полем member в запросах получения coworker). Соответственно использовать запрос на получение определенного сотрудника из вакансии или другого запроса зная его ID (member) по ответу сервера не является возможным.

**Comment by glibin** [comment]
Добрый день!

Уточните, в чем ваш вопрос?

**Comment by Fosly** [comment]
Можете ли вы в API возвращать ID, а не Member объекта Coworker, чтобы его можно было потом искать по соответствующему API?

**Comment by glibin** [comment]
Добрый день!

К сожалению, изменение контракта API с изменением обратной совместимости невозможен.
