### ISSUE TITLE
Часовой пояс временнЫх данных

### ISSUE THREAD

**Issue by tanyalu18** [huntflow/api#523]
Здравствуйте, 

Какой часовой пояс у полей с типом datetime, если он не указан в данных, которые приходят по ручке?
Более конкретно, какой часовой пояс у полей 
1) метод "/vacancy/statuses" поле "removed";
2) метод "/dictionary" поля "last_sync", "created"?

заранее спасибо :)

**Comment by glibin** [comment]
Добрый день!

Даты форматируются в соответствии с [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601): YYYY-MM-DDThh:mm:ss±hh:mm.

**Comment by tanyalu18** [comment]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/98325086/164049404-7429d90a-888b-492e-aab3-98fb82645b91.png">
подобный ответ, как на скриншоте, могу воспринимать как utc, верно?

**Comment by glibin** [comment]
Добрый день!

В старой версии API формат даты некорректен. Конкретно эту дату следует воспринимать как время по Москве.

В новой версии API дата отдается в ISO 8601 формате https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancies/statuses
