### ISSUE TITLE
Вопрос по методу причин отказов

### ISSUE THREAD

**Issue by antonpshenov** [huntflow/api#525]
Добрый день!
Используем метод - GET /account/<account_id>/rejection_reasons что бы получать причины отказов, все было ок
Но сегодня выходит ошибка - {'errors': [{'type': 'common', 'value': ['not found']}]}
Подскажите, пожалуйста в чем может быть причина?

**Comment by katerina-glushko** [comment]
Сегодня столкнулись с такой же проблемой. Тоже хотели бы понять причину.

**Comment by katerina-glushko** [comment]
@antonpshenov кажется, появилась новая версия API: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/rejection_reasons
вот статья с анонсом: https://huntflow.ru/blog/new-api/

правда, странно, что сломали этот метод в старой версии, а остальные методы работают.

**Comment by antonpshenov** [comment]
@katerina-glushko вы пробовали метод из вашей ссылки? у меня он все равно не работает :)
я посмотрел, на прошлые вопросы достаточно оперативно отвечали, думаю стоит подождать

**Comment by katerina-glushko** [comment]
@antonpshenov да, новые методы доступны по корневой ссылке:
`https://api.huntflow.ru/v2/accounts/{account_id}/`

**Comment by antonpshenov** [comment]
@katerina-glushko  у вас вернулись значения?
у меня по новому методу все равно {'errors': [{'type': 'not_found', 'title': 'Not Found'}]} выдает

**Comment by katerina-glushko** [comment]
@antonpshenov да, по ручке `ttps://api.huntflow.ru/v2/accounts/{account_id}/rejection_reasons` значения приходят

**Comment by glibin** [comment]
Добрый день!

Это ошибка, в данный момент мы занимаемся ее исправлением. Я отпишу, когда метод будет исправлен.

**Comment by glibin** [comment]
Добрый день!

Проблема на данный момент исправлена.
