### ISSUE TITLE
как внести изменения в карточку кандидата? изменить email, phone например

### ISSUE THREAD

**Issue by centerex** [huntflow/api#526]
не нашел в доксах

**Comment by codebridge-technology** [comment]
Аналогичный вопрос.

**Comment by glibin** [comment]
Добрый день!

Пока такой возможности нет, но мы добавим пожелание в роадмап по добавлению методов в API. 

Я отпишу в этом треде информацию, когда такая возможность появится.

**Comment by ivanredbread** [comment]
Наличие PUT/PATCH для applicant очень нужно =)

**Comment by glibin** [comment]
Добрый день!

Появился метод PATCH для обновление данных о кандидате: https://api.huntflow.ru/v2/docs#patch-/accounts/-account_id-/applicants/-applicant_id-

**Comment by glibin** [comment]
@ivanredbread да: https://sandbox-api.huntflow.dev/v2/docs#patch-/accounts/-account_id-/applicants/-applicant_id-
