### ISSUE TITLE
веб хуки не долетают до нашего сайта

### ISSUE THREAD

**Issue by maksim-zadubin-rtlabs** [huntflow/api#527]
Добрый день. 

Мы добавили хуки в настройках компании в ЛК.
Хук сохранился. 
Пробуем изменять вакансию, чтобы хук сработал, но на адрес хука ничего не прилетает. 

Обращались в первую линию поддержки huntflow но нам там сказали:
"Удаленный сервер должен ответить кодом 200 или 204 на запрос с типом PING. Скажите, пожалуйста, приходят ли запросы типа PING на указанные адреса от Хантфлоу?"

Не понимаю о чем идет речь. Что за запрос типа PING со статусом 200? 
В документации написано, что хуки работают, как HTTP POST. Проверяли с Postmana - запросы прилетают к  нам на адрес хука.

Более того, сегодня утром  в логах nginx видим, что были обращения от хантфлоу успешные:
zzzzzzz - - [20/Apr/2022:09:44:32 +0300 - 0.157] 200 "POST /applicant.php HTTP/1.0" 0 "-" "Mozilla/5.0 (compatible; pycurl)" "yyyyyy, xxxxx"
zzzzzzz - - [20/Apr/2022:09:44:42 +0300 - 0.118] 200 "POST /vacancy.php HTTP/1.0" 0 "-" "Mozilla/5.0 (compatible; pycurl)" "yyyyyy, xxxx"

Но при изменении вакансии, хуки так и не падают на нас.
Что делать?

**Comment by maksim-zadubin-rtlabs** [comment]
![error_huntflow](https://user-images.githubusercontent.com/104075870/164392802-558d5f38-8c49-4ff8-b537-8369d5b29b1a.jpg)
Кроме того при попытке обратоиться на сам Huntflow сейчас вылезает ошибка.

**Comment by glibin** [comment]
Добрый день!

Подскажите, вы общались с поддержкой в почте? Не могли бы добавить в переписку glibin@huntflow.ru и отправить туда адрес вебхука, на который должны приходить события + ваш account_id.
