### ISSUE TITLE
выгрузить список всех кандидатов по конкретной вакансии

### ISSUE THREAD

**Issue by QRFail** [huntflow/api#528]
по апи запрашиваю резюме, взятые в работу по вакансии методом https://skr.sh/sDYdG5ququY

передаю vacancy_id https://skr.sh/sDYc8UmB1Kk

В ответе получаю пустой массив items https://skr.sh/sDYn87YQnVF

Подскажите пожалуйста. корректно ли запрашиваю список кандидатов по вакансии или другой метод нужно использовать?

**Comment by glibin** [comment]
Добрый день! 

Нет, некорректно. Вы запрашиваете список заявок на вакансии.

Для выгрузки кандидатов по вакансии можно использовать метод поиска: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/search
