### ISSUE TITLE
applicants pagination

### ISSUE THREAD

**Issue by dKosarevsky** [huntflow/api#529]
Привет.

Пытаюсь забрать данные:
`https://api.huntflow.ru/v2/accounts/<account_id>/applicants`

на 23-й странице ловлю ошибку:

```json
  "errors": [
    {
      "type": "value_error.email",
      "title": "value is not a valid email address",
      "location": {
        "entity": "response",
        "variable": "/items/16/email"
      }
    }
  ]
```

В 1-й версии API работает корректно. Почему во 2-й не работает?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, ваш запрос на glibin@huntflow.ru с указанием вашего account_id.

**Comment by data-if** [comment]
Здравствуйте, отправил письмо.

**Comment by dKosarevsky** [comment]
Здравствуйте, отправил письмо.
