### ISSUE TITLE
Этап подбора

### ISSUE THREAD

**Issue by pandamy619** [huntflow/api#53]
Где могу посмотреть "Результат нахождения на этапе"?

**Comment by glibin** [comment]
Уточните, пожалуйста, что вы имеете ввиду?

**Comment by pandamy619** [comment]
В списке кандидатов в links могу посмотреть "этап подбора", но где я могу посмотреть результат нахождения на этапе (прим: Переведен на другой этап/Сейчас на этапе)?

**Comment by glibin** [comment]
в links – актуальный этап подбора, на котором сейчас находится кандидат

история переводов на этапы доступна здесь: https://github.com/huntflow/api/blob/master/ru/applicants.md#applicant_logs (записи type=STATUS)
