### ISSUE TITLE
Этапы подбора

### ISSUE THREAD

**Issue by Valeri37** [huntflow/api#530]
Добрый день. При прикреплении кандидата (отклик кандидата) к вакансии по API , можно указать конкретный этап, на который нужно прикреплять этот отклик?
При привязке вакансии к работным сайтам (например, HH) у вакансии появляется еще дополнительный первый этап "Отклик". 
Возможно ли прикреплять отклик с другого сайта на этот этап?

**Comment by glibin** [comment]
Добрый день!

Такой возможности нет. Данный механизм реализуется через платформу публикации и сбора откликов (https://github.com/huntflow/api/blob/master/ru/responses.md).

Если ваша компания хочет подключить свой карьерный сайт через этот механизм, напишите на project@huntflow.ru
