### ISSUE TITLE
Поле source в логе с кандидатами 

### ISSUE THREAD

**Issue by Asyaaaaaaa** [huntflow/api#531]
Подскажите, пожалуйста, что передается в поле  source в логе с кандидатами?
Думала, что там передается id  источника привлечения кандидата, но нет, поля account_source и source имеют разные значения

**Comment by glibin** [comment]
Добрый день!

Это вспомогательное служебное поле, которое используется при переносе данных  из других систем в Хантфлоу нашими силами.

Данные об источнике кандидата находятся в модели кандидата applicant.account_source + в резюме канидата.
