### ISSUE TITLE
Получение рекрутеров вакансии

### ISSUE THREAD

**Issue by OverLucker** [huntflow/api#533]
Добрый день! 

При создании вакансии возможно назначать рекрутеров, которые работают над вакансией.  Однако ни при получении 
[списка вакансий](https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9) , ни при получении [информации о вакансии ](https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B9) рекрутеры не возвращаются.

Возможно ли добавить поле coworkers в ответ запроса на список или конкретной вакансии?

**Comment by glibin** [comment]
Добрый день!

Я добавлю ваше пожелание в список возможных доработок.

Пока для получения рекрутеров, работающих по вакансии, можно использовать метод: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/coworkers

**Comment by shemetovilya** [comment]
Здравствуйте!

Присоединяюсь к данному пожеланию. 
Вдобавок к сказанному, хотелось бы получить возможность видеть назначенного на текущий момент рекрутера,

**Comment by shemetovilya** [comment]
Добрый день!

Подскажите, пожалуйста, данная опция все еще не была реализована?
