### ISSUE TITLE
404 по методу /account/{id}/rejection_reasons

### ISSUE THREAD

**Issue by gav26512** [huntflow/api#534]
Коллеги сегодня поймал вот такой ответ 
{
    "errors": [
        {
            "type": "common",
            "value": [
                "not found"
            ]
        }
    ]
}
вызывал GET  /account/{id}/rejection_reasons 
что случилось ?

**Comment by glibin** [comment]
Добрый день!

Проблема на данный момент должна быть исправлена. Проверьте, пожалуйста, повторно.
