### ISSUE TITLE
Обязательность заполнения полей в целом и при переходе на следующий этап

### ISSUE THREAD

**Issue by mrhappy9** [huntflow/api#535]
Добрый день!

Подскажите, пожалуйста, существует ли возможность сделать обязательным заполнение (кастомных/дополнительно добавленных) полей кандидата?

**Comment by glibin** [comment]
Добрый день!

Возможность сделать поля обязательными в дополнительной информации о кандидате – есть. Можно обратиться в поддержку для выставления нужных полей обязательным.
 
Возможности сделать обязательным заполнение полей доп. информации о кандидате при переходе на этап на данный момент нет и в ближайших планах такой доработки тоже нет.
