### ISSUE TITLE
Валидация DTO при создании заявки на вакансию

### ISSUE THREAD

**Issue by portretnyy** [huntflow/api#536]
Добрый день! При создании заявки на вакансию ловим 400-ую.

Судя по логам, несколько атрибутов неверно переданы и не прошли валидацию, но до недавнего времени все работало. Из чего делаю вывод - скорее всего какой-то один передан нами неправильно. Прошу помочь разобраться какой именно. Пример тела запроса ниже:

```
{
  "accountDivision": {"foreign": "147"},
  "accountVacancyRequest": "1",
  "clusterLeaderFullName": "Ивановский Иван Иванович",
  "comment": "Комментарий",
  "companyName": "Банк",
  "creatorFullName": "Сергеев Сергей Сергеевич",
  "description": "Описание",
  "direction": null,
  "externalAttribute": "ИТ",
  "externalId": "1",
  "fullName": "Васильев Василий Васильевич",
  "grade": "7",
  "leaderFullName": "Алексеев Алексей Алексеевич",
  "money": "10000000",
  "ownerFullName": "Игорев Игорь Игоревич",
  "position": "Разработчик",
  "productOwnerFullName": "Артемьев Артем Артемович",
  "skills": "Java"
}
```

Логи:

`400 {"errors": [{"type": "validation.account_division", "value": ["field 'account_division' cannot be coerced: int() argument must be a string, a bytes-like object or a number, not 'dict'", "must be of integer type"]}, {"type": "validation.company_name", "value": ["must be of ['integer', 'list'] type"]}, {"type": "validation.direction", "value": ["must be of ['integer', 'list'] type"]}, {"type": "validation.external_attribute", "value": ["must be of ['integer', 'list'] type"]}, {"type": "validation.grade", "value": ["must be of ['integer', 'list'] type"]}]}`

**Comment by glibin** [comment]
Добрый день!

Приношу извинения за возникшие трудности, была ошибка на стороне Хантфлоу. На данный момент она уже исправлена.
