### ISSUE TITLE
Недостаток данных в таблицах Huntflow

### ISSUE THREAD

**Issue by kylindil** [huntflow/api#538]
В таблицах huntflow не хватает данных по 
1. среднему времени на этапе статусы
2. разделению на преподавателей и офис
3. датам закрытия вакансии
4. фамилиям и именам рекрутеров, работающим по вакансиям

**Comment by glibin** [comment]
Добрый день!

Весь набор возможнных получаемых данных из API Хантфлоу представлен в документации: https://api.huntflow.ru/v2/docs#overview
