### ISSUE TITLE
Ошибка при запросе "Get all applicants"

### ISSUE THREAD

**Issue by s-novikov-evotor** [huntflow/api#539]
Всем, привет!

Подскажите, получаем ошибку при запросе: **https://api.huntflow.ru/v2/accounts/17192/applicants?status=44763&page=1&vacancy=2863798**

Ответ:
`{
  "errors": [
    {
      "type": "value_error.email",
      "title": "value is not a valid email address",
      "location": {
        "entity": "response",
        "variable": "/items/2/email"
      }
    }
  ]
}`

Как ее исправить?

Данные по запросу:
`connection: keep-alive
content-length: 147
content-type: application/json
date: Fri, 13 May 2022 09:57:18 GMT
x-request-id: c2e0769a-97ea-422c-8246-4668b0e307f8
`

**Comment by sSlideR** [comment]
Наблюдаю такую же ошибку при запросе списка всех кандидатов хоть постранично пачками, хоть с count=1 
Запрос: GET /accounts/{account_id}/applicants

Если в запрашиваемой странице (page) есть хоть одна запись с ошибкой е-мейла - не отдаёт все записи со страницы с данной ошибкой.
`{
  "errors": [
    {
      "type": "value_error.email",
      "title": "value is not a valid email address",
      "location": {
        "entity": "response",
        "variable": "/items/0/email"
      }
    }
  ]
}`

**Comment by glibin** [comment]
Добрый день!

Проблема находится на исправлении, я отпишу в этом тикете, когда она будет исправлена.

**Comment by glibin** [comment]
Добрый день!

Проблема исправлена.
