### ISSUE TITLE
(log, COMMENT) нужен корректный пример на создания интервью-встречи через АПИ

### ISSUE THREAD

**Issue by LitvinDaria** [huntflow/api#540]
Добрый день, подскажите пожалуйста. При создания интервью столкнулись с проблемой, 
Используя документацию с сайта (https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/applicants/-applicant_id-/logs) делаем обращение по адресу 
Пример запроса: POST https://api.huntflow.ru/account/23158/applicants/111111/log
```
{
            "applicant":111111,
            "account":22222,
            "vacancy":333333,
            "status": 119432,
            "rejection_reason": null,
            "**calendar_event**": {
                "foreign": ",
                "status": "confirmed",
                "event_type": "interview",
                "name": "Интервью: Тестов Тест ",
                "description": "Testing now",
                "location": null,
                "created": "2022-05-12T08:20:59+03:00",
                "all_day": false,
                "transparency": "busy",
                "start": "2022-05-12T15:00:50+03:00",
                "end": "2022-05-12T16:00:50+03:00",
                "timezone": "Europe/Moscow",
                "etag": null,
                "creator": {
                    "self": true,
                    "displayName": null,
                    "email": "email"
                },
                "attendees": [
                    {
                        "displayName": "FIO",
                        "name": " FIO ",
                        "responseStatus": "needsAction",
                        "contact_id": 888888,
                        "order": 1,
                        "member": 77777,
                        "resource": false,
                        "email": "@mail"
                    }
                ],
                "recurrence": [],
                "reminders": [
                    {
                        "minutes": 15,
                        "method": "popup"
                    }
                ]
            },
            "applicant_offer": null,
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2022-05-12T08:20:59+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id":,
                "name": ""
            }
        }
```
В ответе получаем создание Comment с "`calendar_event": null,`
Хотя его указываем.
Если его меняем поле calendar_event на event, выдает ошибку: {
```
    "errors": [
        {
            "type": "common",
            "value": [
                "required field"
            ]
        }
    ]
```
ID - берем существующие. 
Если создаем через веб-приложение, все создается нормально.
В чем может быть причина, можно корректный пример на создания интервью-встречи через АПИ, так как тот, который указан на сайте -  не корректный.

**Comment by glibin** [comment]
Добрый день!

Не хватает параметра calendar, его можно получить тут: https://api.huntflow.ru/v2/docs#get-/calendar_accounts (внутри блока calendars).

Рабочий пример тела запроса:

```
{
  "comment": "Example comment",
  "vacancy": 2701673,
  "calendar_event": {
    "private": false,
    "name": "Example event",
    "reminders": [
      {
        "multiplier": "hours",
        "value": 1,
        "method": "popup"
      }
    ],
    "location": "Washington street 121",
    "event_type": "other",
    "description": "Interview with applicant",
    "calendar": 320621,
    "attendees": [
      {
        "displayName": "John Doe",
        "email": "hello@huntflow.ru"
      }
    ],
    "start": "2022-05-20T09:00:00",
    "end": "2022-05-20T10:00:00",
    "timezone": "Europe/Moscow",
    "transparency": "busy"
  }
}
```

**Comment by LitvinDaria** [comment]
Добрый день,
использую ваш пример, отправляю по адресу:  https://api.huntflow.ru/account/23158/applicants/12345678/log
вставила существующие vacancy
сначала запрос выдал ошибку:
{
    "errors": [
        {
            "type": "validation.applicant",
            "value": [
                "required field"
            ]
        }
    ]
}
добавила еще код аппликанта   
"applicant": 12345678 (взяла существующего), выполняю запрос:
{
    "applicant": 12345678 ,
    "comment": "Example comment this POstmen",
    "vacancy": 87654321,
    "calendar_event": {
        "vacancy": 87654321,
        "private": false,
        "name": "Example event",
        "reminders": [
            {
                "multiplier": "hours",
                "value": 1,
                "method": "popup"
            }
        ],
        "location": "Washington street 121",
        "event_type": "other",
        "description": "Interview with applicant",
        "calendar": 156664,
        "attendees": [
            {
                "displayName": "John Doe",
                "email": "glibin@huntflow.ru"
            }
        ],
        "start": "2022-05-20T09:00:00",
        "end": "2022-05-20T10:00:00",
        "timezone": "Europe/Moscow",
        "transparency": "busy"
    }
}

В итоге, я получаю создание **COMMENT** комментария, а не **события**
{
    "id": 146710671,
    "applicant": 12345678,
    "type": "COMMENT",
    "account": 32387,
    "vacancy": 87654321,
    "vacancy_frame": 631458,
    "status": 54971,
    "rejection_reason": null,
    **"calendar_event": null,**
    "email": null,
    "sms": null,
    "phone_call": null,
    "applicant_offer": null,
    "survey_answer_of_type_a": null,
    "recruitment_evaluation": null,
    "group_action": null,
    "comment": "Example comment this POstmen",
    "source": null,
    "employment_date": null,
    "data": null,
    "created": "2022-05-23 05:21:03",
    "hired_in_fill_quota": null,
    "work_days_in_work": null,
    "work_days_after_deadline": null,
    "workdays_until_employment_date": null,
    "workdays_after_deadline_for_employment_date": null,
    "removed": null,
    "files": [],
    "im": []
}



**Как сделать чтобы создавало событие, а не комментарий?**
пробовала сменить 
event_type: "interview",
 "interview_type": 17066,
Не помогло(((

**Comment by LitvinDaria** [comment]
Я поменяла:
- название поле calendar_event на event,
- добавила в свой старый запрос calendar: idcalendar (тот что отправляла в начале)
и запрос сработал)))))

Спасибо, за обратную связь)
