### ISSUE TITLE
Как работать с дублями аппликантов?

### ISSUE THREAD

**Issue by golovansergey** [huntflow/api#541]
Правильно ли я понимаю, что в вебхуке APPLICANT типа DOUBLE
Поле source - это id оригинального кандидата, который был изначально
А поле applicant.id - это id дубля для оригинального?

Как правильно с этим работать? А именно на какое id смотреть для информации по кандидату, на оригинальное или на последний дубль? Или надо как-то их смерджить?

**Comment by glibin** [comment]
Добрый день!

applicant.id – это кандидат, в которого происходит мердж информации от объединения кандидатов (на выходе будет только он).
Поле source содержит идентификатор кандидата, который был замерджен. После мерджа данный кандидат удаляется.

**Comment by golovansergey** [comment]
Чтобы больше вопросов не возникало
Был кандидат 1, по нему была какая-то информация
Появился кандидат 2, который является дублем 1
Прилетел вебхук double - applicant.if = 2, source = 1
И чтобы собрать информацию, отражающую работу с физическим кандидатом, мне надо сначала отобразить работу с кандидатом 1, а потом с кандидатом 2
1 инфо
1 инфо
1 инфо
2 инфо
2 инфо

**Comment by glibin** [comment]
Уточните, пожалуйста, а в чем вопрос?

**Comment by golovansergey** [comment]
Правильно ли я расписал работу с физическим кандидатом, у которого есть дубли?

**Comment by glibin** [comment]
Я пока не очень понял задачу. Вам нужно объединить работу по кандидату после объединения?

**Comment by golovansergey** [comment]
Да, именно

**Comment by glibin** [comment]
Объединять нужно по времени (все события кандидата source = 1 попадут в историю по кандидату 2).
Вы можете это сделать самостоятельно или перезапросить историю работы по кандидату 2 из API.
