### ISSUE TITLE
Ошибка 401 при попытке запросить историю по апликанту

### ISSUE THREAD

**Issue by skarpushin** [huntflow/api#544]
Добрый день

При использовании Bearer токена запрос
`https://api.huntflow.ru/v2/accounts/55771/applicants?page=1&vacancy=2815543`
проходит нормально.

Далее при попытке запросить историю комментариев и изменений статусов по одному из апликантов
`https://api.huntflow.ru/v2/accounts/55771/applicants/25066738/logs?count=30&page=1&personal=false&vacancy=2815543`
приходит ошибка
`{"errors":[{"type":"authorization_error","title":"Authorization Error"}]}`

Подскажите пожалуйста, что делать в такой ситуации?

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, полные заголовки запроса и ответа, удалив авторизационные данные (за исключением последних 6 символов токена).

**Comment by skarpushin** [comment]
Пока собирал заголовки понял, что по какой-то причине пропал токен. Всё работает ок. Закрываю.
