### ISSUE TITLE
Не понимаю, как работать с токеном

### ISSUE THREAD

**Issue by pavzagor** [huntflow/api#547]
[В документации написано](https://github.com/huntflow/api/blob/master/ru/token.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0), что access token протухает через 7 дней, а refresh token — через 14.

Это получается, что мне надо руками пересоздавать токен каждые 14 дней?

**Comment by pavzagor** [comment]
Увидел, что refresh token обновляется вместе с access token

Есть какие-то примеры готовых решений как нормально реализовать обновление токена?
И можно ли получить токен, который не будет протухать просто?

Я очень хочу заставить это работать в интегромате без ручных замен токена, но пока не до конца понимаю, как это сделать без костылей(

**Comment by Fosly** [comment]
Я каждый день при обновлении всех данных шлю запрос на обновление токена.
API возвращает либо:
`[{'type': 'access_denied', 'title': 'error.robot_token.refresh_too_early'}]`
Либо пару токен+рефреш. В первом случае ничего не делаю, во втором случае перезаписываю в файл оба токена.

**Comment by pavzagor** [comment]
Ну то есть холостой лишний запрос просто получается, верно?

Это логично, но дизайн авторизационной механики кажется неоптимальным 😄

**Comment by Fosly** [comment]
> Ну то есть холостой лишний запрос просто получается, верно?
> 
> 
> 
> Это логично, но дизайн авторизационной механики кажется неоптимальным 😄

Если токен живет неделю, рефреш токен 14 дней -> вы можете отрабатывать скрипт и при первом запросе проверять ответ. Если токен истёк -> обновлять токен. Раз в неделю будет выполняться и без лишних прогонов.

**Comment by artegok** [comment]
тоже не понимаю как работает. есть пример решения обновления токена?

**Comment by glibin** [comment]
Добрый день!

Описание работы с токенами доступно здесь: https://github.com/huntflow/api/issues/562
