### ISSUE TITLE
Получение полной информации по вакансии

### ISSUE THREAD

**Issue by mixvlad** [huntflow/api#55]
Как можно получить информацию, которая есть в интерфейсе:
- дата закрытия вакансии;
- количество людей сколько нужно набрать/уже набрали;
- сколько кандидатов было на каждом этапе (сводная информация по вакансии).

**Comment by alshru** [comment]
Присоединяюсь к вопросу.
Очень хочется в ответе на метод "vacancies" (Список вакансий) видеть атрибут - "дата закрытия вакансии". Дата открытия есть (created), а даты закрытия нет. Ее остро не хватает для аналитики.

**Comment by glibin** [comment]
Добрый день!

Сколько нужно кандидатов нанять хранится в атрибуте applicants_to_hire

> количество людей сколько нужно уже набрали;
> дата закрытия вакансии;

Данных методов пока нет в API. Мы планируем их добавить в обозримом будущем.

**Comment by glibin** [comment]
На данный момент можно использовать функционал вебхуков для получения информации о закрытии вакансии: https://github.com/huntflow/api/blob/master/ru/webhooks.md#vacancy
