### ISSUE TITLE
Расшифровка грейдов

### ISSUE THREAD

**Issue by flatout2022** [huntflow/api#550]
Добрый день!
Подскажите, пожалуйста, где можно найти расшифровку грейдов для вакансии?

**Comment by aleks-v-k** [comment]
Здравствуйте. Не очень понятно о каких грейдах идет речь, предполагаю, что это внедренный справочник. Значения справочников можно получить по коду справочника, см. https://github.com/huntflow/api/blob/master/ru/dictionaries.md
