### ISSUE TITLE
Отправка сопроводительного письма со стороннего сайта

### ISSUE THREAD

**Issue by Jendozz** [huntflow/api#553]
Приветствую! Существует ли api  для  того, чтобы добавить сопроводительное письмо кандидата  в отдельную вкладку, в такой же зеленый блок как на скриншоте?

![photo_2022-06-16_14-30-02](https://user-images.githubusercontent.com/78259970/174052365-c5c47030-0f6a-4cad-845b-33e707865cb2.jpg)

**Comment by aleks-v-k** [comment]
Здравствуйте. Непонятен ваш сценарий. Если вы интегрируетесь с API публикации вакансий и сбора откликов, то сопроводительные письма нужно отдавать вот этим методом https://github.com/huntflow/api/blob/master/ru/responses.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%BF%D0%B8%D1%81%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D1%83

**Comment by Jendozz** [comment]
Сценарий - это интеграция корпоративного сайта с вакансиями huntflow. Хотелось чтобы отклик и сопроводительное письмо приходило c нашего сайта. Возможно это как то реализовать через ваше API?

**Comment by Jendozz** [comment]
Сценарий - это интеграция корпоративного сайта с вакансиями huntflow. Хотелось чтобы отклик и сопроводительное письмо приходило c нашего сайта. Возможно это как то реализовать через ваше API?

**Comment by Jendozz** [comment]
> Здравствуйте. Непонятен ваш сценарий. Если вы интегрируетесь с API публикации вакансий и сбора откликов, то сопроводительные письма нужно отдавать вот этим методом https://github.com/huntflow/api/blob/master/ru/responses.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D1%85-%D0%BF%D0%B8%D1%81%D0%B5%D0%BC-%D0%BF%D0%BE-%D0%BE%D1%82%D0%BA%D0%BB%D0%B8%D0%BA%D1%83

Сценарий - это интеграция корпоративного сайта с вакансиями huntflow. Хотелось чтобы отклик и сопроводительное письмо приходило c нашего сайта. Возможно это как то реализовать через ваше API?
