### ISSUE TITLE
Управление пользователям пространства через API

### ISSUE THREAD

**Issue by enb-f** [huntflow/api#554]
Добрый день!
Подскажите пожалуйста, возможно ли как-то получать список «Заказчиков» по API, и есть ли возможность удаления\откл их из спейса так же через API?

Спасибо!

**Comment by aleks-v-k** [comment]
Здравствуйте. Для получения списка "заказчиков" можно воспользоваться этим методом https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/coworkers
указав в `type` значение `watcher`
Возможности управления пользователями на данный момент в API нет.
