### ISSUE TITLE
Получить список разрешений по всем вакансиям заказчика

### ISSUE THREAD

**Issue by Semargl92** [huntflow/api#555]
Добрый день! 

Подскажите, пожалуйста, есть ли возможность получить по апи сведения по всем вакансиям конкретного заказчика включая набор этапов, по которым у него есть туда доступ?

**Comment by aleks-v-k** [comment]
Здравствуйте. Для получения вакансий/этапов к которым у заказчика есть доступ нужно использовать метод https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/coworkers/-coworker_id-

**Comment by Semargl92** [comment]
Спасибо за ответ. Есть нюанс - вышеприведенный метода не отображает пермишены для пользователя по id. Получить все пермишены пользователей получается только через https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/coworkers

**Comment by aleks-v-k** [comment]
Да, вы правы, невнимательно посмотрел. Действительно, поведение не выглядит консистентным. Мы обсудим что с этим можно сделать и я вернусь с ответом на следующей неделе. А пока получается, что только из запроса списка пользователей можно достать.

**Comment by Semargl92** [comment]
Спасибо, будем ждать ответа
!

**Comment by aleks-v-k** [comment]
Немного запоздало информирую - решили добавить поддержку флага fetch_permissions для получения пермишенов пользователя по аналогии с тем, как это работает для списка пользователей. По времени точно сориентировать не могу, но думаю, что до конца этого месяца будет сделано.

**Comment by Semargl92** [comment]
Спасибо за информацию! А можно ли попросить Вас написать в этот тред, когда все же добавят эту функциональность?

**Comment by glibin** [comment]
Добрый день!

В методе https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/coworkers/-coworker_id- в объекте permissions  теперь возвращается и список доступных заказчику вакансий (permission = "vacancy")
