### ISSUE TITLE
Вечный токен

### ISSUE THREAD

**Issue by etmee** [huntflow/api#556]
Здравствуйте! 
Можно ли каким-то образом получить вечный токен? У нас создано несколько веб-хуков в системе, из которой отправляем оповещения в Huntflow. Очень неудобно обновлять вручную токены каждую неделю

**Comment by aleks-v-k** [comment]
Здравствуйте. Штатной возможности нет. А зачем обновлять токен вручную? Почему нельзя программно?

**Comment by artegok** [comment]
@aleks-v-k привет. научите обновлять программно. обычно все работают через oath, тут какая-то пытка с refresh token. может я что-то делаю не так

**Comment by glibin** [comment]
Пример работы с токенами приведен в тикете: https://github.com/huntflow/api/issues/562
