### ISSUE TITLE
Загруженные файлы скачиваются с неправильной кодировкой

### ISSUE THREAD

**Issue by IgorDeinekin** [huntflow/api#558]
Здравствуйте, у нашей компании есть интеграция с вашим сервисом. Через эту интеграцию мы осуществляем помимо прочего загрузку файлов.

Пример:
POST запрос на адрес https://sandbox-api.huntflow.dev/account/10/upload
Содержание файла: "Вопросы и ответы кандидата :P"

Итоговая ссылка: https://sandbox-store.huntflow.dev/uploads/named/a/5/1/a51b04986567d44bd5ae04944cdafb28.txt/Candidate_Answers.txt?s=PnKfiDK10v6xe0SIOjzW6g&e=1657324124

Проблема заключается в следующем:
При отправке файла для его содержимого мы указываем Content-Type = "text/plain". Сам текст передается в кодировке UTF-8. В таком виде при попытке открыть загруженный файл в браузере, его содержимое выглядит так:

![image](https://user-images.githubusercontent.com/8201612/178003389-4cf7cd1a-b939-40ca-8a72-848758536dd0.png)

Для исправления данной проблемы мы попробовали задать для содержимого Content-Type = "text/plain; charset=utf-8", но при этом мы получаем Bad Request:

![image](https://user-images.githubusercontent.com/8201612/178003427-e0fea541-8d23-4eb4-8e10-f048a01ed5cc.png)

Подскажите пожалуйста, нормальное ли это поведение сервера, что он возвращает такой ответ, и как в таком случае нам получить больше контроля над тем, чтобы файл правильно отображался у клиента в браузере.

**Comment by glibin** [comment]
Добрый день!

Можете прислать пример файла на glibin@huntflow.ru со ссылкой на данный тикет?

**Comment by IgorDeinekin** [comment]
> Добрый день!
> 
> Можете прислать пример файла на [glibin@huntflow.ru](mailto:glibin@huntflow.ru) со ссылкой на данный тикет?

Добрый день!

Выслал файл на указанный email.

**Comment by glibin** [comment]
Добрый день!

К сожалению, пока возможности управлять кодировкой программно нет и в ближайших планах не будет.

Однако, файл из примера на почте после загрузки открылся корректно, что говорит о том, что можно настроить поведение браузера на работу с utf-8 по умолчанию:


<img width="747" alt="Screenshot 2022-07-27 at 11 16 41" src="https://user-images.githubusercontent.com/463881/181197533-7e6078ae-4f81-454a-81ba-b5e05a383891.png">

**Comment by IgorDeinekin** [comment]
Здравствуйте, @glibin !

Благодарю за прояснение ситуации!
