### ISSUE TITLE
Id кандидата постоянно меняется

### ISSUE THREAD

**Issue by AleksanderZverev** [huntflow/api#559]
Здравствуйте. Последнее время много страдаем от проблемы смены id кандидата после влития дубликатов. Насколько реально завязаться на каком-то конкретном id? Например, было бы в разы удобнее, если бы id сохранялся старый всегда, тогда поведение бы было предсказуемым и интеграция стала бы удобней.

**Comment by glibin** [comment]
Добрый день!

Спасибо за обратную связь, я передал пожелание в отдел разработки, мы обсудим в команде о возможности реализации вашего предложения.
