### ISSUE TITLE
Подсчет воронок и указание на кого подсчитывать

### ISSUE THREAD

**Issue by AleksanderZverev** [huntflow/api#561]
Здравствуйте. Хотим автоматизировать перевод этапов наших HR-в. Возникает проблема со статистикой, ведь все переводы от имени демона происходят, соответственно воронки считается по нему. Реально ли добавить фичу, чтобы можно было указывать аккаунт человека, на который надо назначить этот перевод? Или может указать аккаунт, который должен считаться в статистике?

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности нет.

**Comment by AleksanderZverev** [comment]
Как идея может быть добавить возможность подсчета статистики по тегам. Например, пользователь создает свой тег и помечает им удобные для себя этапы. 

Issue можно закрывать, идею вам подкинул :)
