### ISSUE TITLE
Как работать с токеном?

### ISSUE THREAD

**Issue by artegok** [huntflow/api#562]
Добрый день. 
Объясните, как можно настроить автоматическое обновление токена? Впервые столкнулся с таким странным подходом.

**Comment by glibin** [comment]
Добрый день!

Работа с токенами имеет стандартный для OAuth2 механизм работы с двумя токенами: access_token и refresh_token.

В момент, когда срок жизни access_token закончится (это можно будет понять по ошибке 401 и телу ответа `{"errors": [{"type": "oauth", "value": ["token_expired"]}]}`вам необходимо сделать запрос на обновление пары токенов с refresh_token: https://api.huntflow.ru/v2/docs#post-/token/refresh
