### ISSUE TITLE
Изменение статуса и полей заявки на вакансии

### ISSUE THREAD

**Issue by alex-l-morozov** [huntflow/api#563]
Возможно с помощью API изменить статус или какое-то поле заявки на вакансии и каким способом?

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности в API сейчас нет, но я передам ваше пожелание в отдел разработки.

Подскажите, для каких сценариев вам это необходимо?

**Comment by alex-l-morozov** [comment]
Добрый день!

По процессу требуется согласование заявок на вакансии + добавление к ним комментариев.

**Comment by glibin** [comment]
Добрый день!

Из нашего опыта клиенты организуют процесс согласования заявок на своей стороне (во внутренней системе, например, Интранете), а уже согласованную заявку передают в Хантфлоу для дальнейшей работы над ней рекрутерами.

Также, при передаче списка согласующих в заявке, процесс согласования будет запущен автоматически и согласующие по порядку будут получать уведомления от Хантфлоу с необходимостью согласовать заявку. После подтверждения последним согласующим заявка попадет в рекрутмент.

**Comment by katherine-pashchina** [comment]
Добрый день! Нашла этот тикет, хотела уточнить, изменилось ли что-то за месяц?
Возможно ли с помощью API изменить этап подбора по вакансии?
