### ISSUE TITLE
Изменение статуса кандидата и дополнительных полей

### ISSUE THREAD

**Issue by alex-l-morozov** [huntflow/api#564]
Возможно ли изменение дополнительных полей у кандидата и статуса через api и каким способом?

**Comment by alexreznikoff** [comment]
Здравствуйте, вы можете менять значения доп.полей кандидата используя данный метод 
https://api.huntflow.ru/v2/docs#patch-/accounts/-account_id-/applicants/-applicant_id-/questionary

Тело запроса зависит от схемы доп.полей, которую можно получить тут https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/questionary
Простой пример:
```
{
  "region": 9,
  "category_developer": 100500
}
```

Смена статуса кандидата описана тут
https://api.huntflow.ru/v2/docs#put-/accounts/-account_id-/applicants/-applicant_id-/vacancy
