### ISSUE TITLE
Get an applicant's worklog 400 bad request

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#565]
При построении запроса к API:

curl -X GET https://api.huntflow.ru/v2/accounts/208/applicants/1812954/logs?type=STATUS&count=30&page=1  \
-H "Accept: application/json" \
-H "Authorization: Bearer xxxxxx_4f137b" \

Получаю такой ответ:
{
  "errors": [
    {
      "type": "value_error.missing",
      "title": "field required",
      "location": {
        "entity": "response",
        "variable": "/items/0/calendar_event/creator/self"
      }
    }
  ]
}

Суть ответа не ясна, не удается найти ответ в документации к API.
Прошу помочь разобраться, в чем проблема.

При обращении с теми же параметрами к другому applicant, все работает корректно

P.S. оставил последние 6 символов токена

**Comment by alexreznikoff** [comment]
@shemetovilya здравствуйте, баг взяли в работу, напишу как пофиксим

**Comment by alexreznikoff** [comment]
@shemetovilya исправлено

**Comment by shemetovilya** [comment]
@alexreznikoff , доброго дня.
Спасибо, помогло, проблема решена!
