### ISSUE TITLE
Создание заявки на вакансию

### ISSUE THREAD

**Issue by artegok** [huntflow/api#566]
Не понимаю как создавать заявки на вакансию. Что такое схема заявки? Нигде нет определения.
Также не понимаю можно ли по id вакансии прикидывать заявку в нужную.
Все инструкции читал, но не понятно. Объясните, пожалуйста. Возможно есть пример реального запроса

**Comment by alexreznikoff** [comment]
@artegok Здравствуйте.
Схема заявки - это схема, описывающая набор полей, их обязательность и тип, установленная в настройках организации для работы с заявками.
[Получить все схемы заявок в организации](https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/account_vacancy_requests)
[Получить конкретную схему заявки](https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/account_vacancy_requests/-account_vacancy_request_id-)

Пример схемы
```
{
  "id": 1,
  "account": 11,
  "name": "IT Developers",
  "attendee_required": false,
  "attendee_hint": "Send for approval",
  "active": true,
  "schema": {
    "position": {
      "id": 130,
      "type": "string",
      "title": "Position",
      "required": true,
      "order": 1,
      "pass_to_report": true,
      "account": 11,
      "key": "position"
    },
    "category": {
      "id": 132,
      "type": "dictionary",
      "title": "Category",
      "required": true,
      "order": 3,
      "pass_to_report": true,
      "account": 11,
      "dictionary": "category",
      "vacancy_field": "category"
    }
  }
}
```
Исходя из этой схемы нужно при создании заявки передать два обязательных поля - position (строка) и category (идентификатор значения из справочника category)
[Создание заявки](https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancy_requests) - пример POST запроса:
```
{
  "account_vacancy_request": 1,
  "position": "Developer",
  "category": 100
}
```

При [создании вакансии](https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancies), можно указать заявку, на основе которой создается вакансия в поле `fill_quotas.vacancy_request`
