### ISSUE TITLE
Перестал работать метод /token/refresh

### ISSUE THREAD

**Issue by alex-l-morozov** [huntflow/api#567]
Ошибка:
stdClass Object ( [errors] => Array ( [0] => stdClass Object ( [type] => not_found [title] => error.robot_token.not_found ) ) )

**Comment by glibin** [comment]
Добрый день!

Метод работает корректно. Проблема, скорее всего, связана с некорректной логикой работы вашего приложения.

Если проблему не удается решить, напишите, пожалуйста, на support@huntflow.ru

**Comment by alex-l-morozov** [comment]
Не работает метод корректно, все остальные нормально. А с этим проблема.

Есть подобное обращение - https://github.com/huntflow/api/issues/574
