### ISSUE TITLE
Получение всех записей в системе

### ISSUE THREAD

**Issue by pgoncharov-ea** [huntflow/api#57]
Добрый день! Пробуем построить аналитику на базе Power BI. 

let
    source = Web.Contents("https://api.huntflow.ru/account/*ACCOUNT_ID*/vacancies", [Headers=[Authorization="Bearer "&"********TOKEN********",ContentType="application/json"]]),    
    Result = Json.Document(source)
in
    Result

Возвращает только вакансии менеджера, как получить все вакансии в базе?

**Comment by glibin** [comment]
Добрый день!

Подскажите свой account_id?

**Comment by pgoncharov-ea** [comment]
23158

**Comment by glibin** [comment]
Добрый вечер!

Проверили, что возвращается полный набор вакансий. Не могли бы вы прислать полные параметры запроса и ответа на hello@huntflow.ru со ссылкой на данный issue на github

**Comment by pgoncharov-ea** [comment]
Спасибо за помощь и блогу https://medium.com/@marktiedemann/how-to-do-pagination-in-power-query-430460c17c78 

Запрос на выдачу всех записей
let 
    
    AccountId       = "**ACCOUNT_ID**",
    Token           = "**TOKEN**",
    BaseUrl         = "https://api.huntflow.ru/account/" & AccountId & "/vacancies?",
    EntitiesPerPage = 100,
 
    GetJson = (Url) =>
        let Options = [Headers=[ #"Authorization" = "Bearer " & Token,ContentType="application/json"]],
            RawData = Web.Contents(Url, Options),
            Json    = Json.Document(RawData)
        in  Json,
 
    GetPageCount = () =>
        let Url   = BaseUrl,
            Json  = GetJson(Url),
            Count = Json[#"total"]
        in  Count,
    
   GetPage = (Index) =>
        let 
            Page = "page=" & Text.From(Index),
            Top   = "count=" & Text.From(EntitiesPerPage),
            Url   = BaseUrl & Page & "&" & Top,
            Json  = GetJson(Url),
            Value = Json[#"items"]
        in  Value, 
    PageCount   = GetPageCount(),
    PageIndices = {1 .. PageCount},
    Pages       = List.Transform(PageIndices, each GetPage(_)),
    Entities    = List.Union(Pages),
    Table       = Table.FromList(Entities, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    ExpandedData = Table.ExpandRecordColumn(Table, "Column1", {"company", "priority", "money", "state", "multiple", "applicants_to_hire", "vacancy_request", "position", "parent", "id", "created", "account_division", "hidden", "deadline"}, {"company", "priority", "money", "state", "multiple", "applicants_to_hire", "vacancy_request", "position", "parent", "id", "created", "account_division", "hidden", "deadline"})
in
    ExpandedData
