### ISSUE TITLE
Rate limiter

### ISSUE THREAD

**Issue by Yurovskikh** [huntflow/api#572]
Добрый день, коллеги с поддержки отправили сюда с вопросом.

Хотелось бы узнать какие у rate limiter'a лимиты и можно ли их по необходимости будет увеличить. Не так давно столкнулись с проблемой что в api rate limiter отпинывает, хотя кол-во запросов едва ли превышало 100 rpm, вот и хотелось бы знать на какие лимиты расчитывать

**Comment by glibin** [comment]
Добрый день!

Информация по лимитам доступна здесь: https://github.com/huntflow/api/blob/master/ru/general.md#ограничение-на-количество-единовременных-запросов
