### ISSUE TITLE
Какие типы авторизации возможны помимо токена http bearer? Можно ли реализовать авторизацию по SLL сертификату? 

### ISSUE THREAD

**Issue by abramovks** [huntflow/api#573]
Коллеги, добрый день,
В рамках обеспечения защиты персональных данных служба СБ в настоящее время рассматривает дополнительные меры по защите корпоративной информации при интеграциях.

Не могли бы вы нам помочь и сориентировать нас по наличию альтернативных механизмов аутентификации в ваших API.
При подаче заявки на подбор, передачи откликов и информации о кандидатах из/в Хантфлоу из/в другие внутренние системы нашей компании требуются дополнительные меры защиты при интеграционном взаимодействии.

Какие типы авторизации возможны помимо токена http bearer? Можно ли реализовать авторизацию по SLL сертификату? Как в сторону huntflow, так и при передачи хуков в нашу сторону.

Возможно такие решения уже обрабатывались для других клиентов? Ранее написали запрос на help@huntflow, но нас направили сюда, хотя возможно такое решение предоставляется персонализировано.

**Comment by glibin** [comment]
Добрый день!

Не могли бы вы добавить в переписку с запросом на help@huntflow.ru адрес glibin@huntflow.ru со ссылкой на данный тикет?
