### ISSUE TITLE
404 при обновлении токена

### ISSUE THREAD

**Issue by step24** [huntflow/api#574]
При отправлении запроса на обновление токена (response = requests.post('https://lanit-api.huntflow.ru/v2/token/refresh', json={"refresh_token": "ТОКЕН_ОБНОВЛЕНИЯ"}, headers=my_headers)) возвращает ошибку: <Response [404]> {'errors': [{'type': 'not_found', 'title': 'error.robot_token.not_found'}]}.
Давно использовал скрипт, проблем раньше не было. Ошибку стало выдавать после попытки обновления после очередного истечения срока годности access_token.

**Comment by glibin** [comment]
Добрый день!

Возможные причины такого поведения:

- передаётся некорректное значение refresh_token
- refresh_token уже был ранее использован для обновления access_token

Решение проблемы:

- зайти в настройки ХФ и сгенерировать новый токен
