### ISSUE TITLE
Поиск вакансии по названию

### ISSUE THREAD

**Issue by katherine-pashchina** [huntflow/api#576]
Добрый день!
Увидела этот тикет https://github.com/huntflow/api/issues/336, сейчас столкнулась с такой же необходимостью - нужно фильтровать вакансии по названию и получать их id. Подскажите, такой метод все еще не добавили?

**Comment by glibin** [comment]
Добрый день!

Пока такой возможности не появилось, но я передам пожелание в отдел разработки на добавление этой возможности. Отпишу в этом тикете, когда возможность появится.
