### ISSUE TITLE
Получение ссылки на резюме тип LI (LinkedIn)

### ISSUE THREAD

**Issue by denkarusev** [huntflow/api#578]
Добрый день!

Для получения детальной информации по резюме использую метод [Получение резюме кандидата](https://github.com/huntflow/api/blob/master/ru/externals.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0). Но в ответе нет полей, содержащих ссылку на резюме. Каким образом я могу получить ссылку на резюме из LinkedIn?

**Comment by glibin** [comment]
Добрый день!

Пока такая информация не возвращается в API, но я передам ваше пожелание в отдел разработки и напишу в этом тикете, когда такая возможность появится.

Обращу внимание, что обновление будет доступно только в новой версии API: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/-applicant_id-/externals/-external_id-
