### ISSUE TITLE
logs/type=MAIL письмо прикрепленное к комментарию

### ISSUE THREAD

**Issue by LitvinDaria** [huntflow/api#579]
здравствуйте!
Подскажите как мне вернуть письмо прикрепленное к комментарию
пример:
              
![image](https://user-images.githubusercontent.com/62325850/188370064-8dc0dd9a-587d-4559-9d20-b0bfe2bcb378.png)

когда я запрашиваю через : https://api.huntflow.ru/account/XXXXX/applicants/XXXXXX/log?vacancy_id= XXXXXXX
мне приходит ответ:
 {
            "id": 13131313131,
            "type": "COMMENT",
            "account": 77777,
            "status": 54971,
            "rejection_reason": null,
            "calendar_event": null,
            "applicant_offer": null,
            "comment": "",
            "source": null,
            "employment_date": null,
            "created": "2022-07-21T11:11:46+03:00",
            "hired_in_fill_quota": null,
            "files": [],
            "account_info": {
                "id": 77777,
                "name": "fio"
            },
            "vacancy": XXXXXX
        }

Это именно этот комментарий, в вебе ответ формируется такой:
{
            "id": 6466,
            "applicant": 546,
            "type": "COMMENT",
            "account": 71589,
            "vacancy_frame": hgh,
            "status": 54971,
            "rejection_reason": null,
            "calendar_event": null,
            "email": {
                "id": 7667676,
                "account_email": 767676,
                "email_thread": 1232456,
                "type": "mail",
                "foreign": "<380A5378158Ah2.mnv.ru>",
                "replyto": null,
                "references": null,
                "replyto_md5": [],
                "references_md5": [],
                "to": [
                    {
                        "displayName": "",
                        "email": "hgjgs@ya.ru",
                        "type": "to"
                    }
                ],
                "from_email": "eпп@mnv.ru",
                "from_name": "fdgdgdfgdfg ",
                "html": "<div><p style=\"margin: 0; line-height: normal;\"><span style=\"font-size: 10.0pt;\">\u0414\u043e\u0431\u0440\u044b\u0439 \u0434\u0435\u043d\u044c!<\/span><\/p><p style=\"margin: 0; line-height: normal;\"><span style=\"font-size: 10.0pt;\">\u00a0<\/span><\/p><p style=\"margin: 0; line-height: normal;\"><span style=\"font-size: 10.0pt;\"743401<\/p><\/div>",
                "meta": {
                    "id": "fgdgd="
                },
                "me": true,
                "hash": "59b32a8da1c1133",
                "send_at": null,
                "timezone": "Europe/Moscow",
                "state": "SENT",
                "state_reason": null,
                "state_comment": null,
                "read_by_recipient": false,
                "is_replied": false,
                "outgoing": true,
                "created": "2022-07-21 11:11:46",
                "multivacancy_meta": {
                    "28080159": {
                        "frame_id": 56565656
                    }
                },
                "removed": null,
                "version": 8
            },
            "sms": null,
            "phone_call": null,
            "applicant_offer": null,
            "survey_answer_of_type_a": null,
            "recruitment_evaluation": null,
            "group_action": null,
            "comment": "",
            "source": null,
            "employment_date": null,
            "data": null,
            "created": "2022-07-21 11:11:46",
            "hired_in_fill_quota": null,
            "work_days_in_work": null,
            "work_days_after_deadline": null,
            "workdays_until_employment_date": null,
            "workdays_after_deadline_for_employment_date": null,
            "removed": null,
            "vacancy_id": 555555,
            "files": [],
            "im": [],
            "account_info": {
                "id": 00000,
                "name": "\gfhgfjhgjsfgjfgjj"
            },
            "fill_quota": null
        }

Скажите какой метод вызвать чтобы получить письмо или другой обьект(файл прикрепленный например)?

**Comment by glibin** [comment]
Добрый день!

Сейчас такой возможности нет, но уже взяли задачу на доработку в работу. Напишу в этом тикете, когда возможность появится.

**Comment by glibin** [comment]
Добрый день!

Доработка вышла: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/-applicant_id-/logs
