### ISSUE TITLE
Должность по штатке

### ISSUE THREAD

**Issue by pandamy619** [huntflow/api#58]
не увидел в описании поля: "Должность по штатке".
Можно ли через api вытягивать это поле? 
Спасибо!
<img width="404" alt="Снимок экрана 2019-07-07 в 23 10 19" src="https://user-images.githubusercontent.com/28829785/60773325-6f454180-a10c-11e9-8ed8-d2d949977387.png">

**Comment by glibin** [comment]
Добрый день!

Это поле в вакансии? Вам нужно получить его значение и/или список возможных вариантов?

**Comment by pandamy619** [comment]
Получить значение.

**Comment by glibin** [comment]
Пришлите, пожалуйста, ваш account_id

**Comment by pandamy619** [comment]
2

**Comment by glibin** [comment]
Список возможных значений можно получить запросом:

`/account/<account_id>/dictionary/position_shtat`

Само поле должно отдаваться как в списке вакансий, так и в запросе самой вакансии в поле (значение поле должно быть похоже на position_shtat)

Вероятно, у вас выделенная установка Хантфлоу, поэтому для более детальной помощи напишите на hello@huntflow.ru с адресом вашего API endpoint и ссылкой на этот тикет.
