### ISSUE TITLE
Настройка webhook

### ISSUE THREAD

**Issue by katherine-pashchina** [huntflow/api#580]
Добрый день!
Столкнулись с проблемой - нужно принимать вебхуки из HF по кандидатам в нашу платформу, но при настройке url выдает ошибку Webhook can't be reached. Вероятно это связано с тем, что нужна отправка определенных параметров в теле отправляемого вебхука. Подскажите, это как-то можно настроить на стороне HF?

**Comment by glibin** [comment]
Добрый день!

К сожалению, настройка дополнительных параметров запроса невозможно. Ваш endpoint должен быть доступен (отвечать кодами 200 или 201), чтобы он мог быть добавлен в Хантфлоу.
