### ISSUE TITLE
Перестал работать метод /token/refresh

### ISSUE THREAD

**Issue by alex-l-morozov** [huntflow/api#581]
Переоткрываю данное обращение, так как метод перестал корректно работать
https://github.com/huntflow/api/issues/567 

Есть еще подобное https://github.com/huntflow/api/issues/574

**Comment by glibin** [comment]
Добрый день!

Возможные причины такого поведения:

- передаётся некорректное значение refresh_token
- refresh_token уже был ранее использован для обновления access_token

Решение проблемы:

- зайти в настройки ХФ и сгенерировать новый токен, который в дальнейшем использовать для корректного обновления пары (при обновлении приходит новая пара access_token/refresh_token)

**Comment by glibin** [comment]
> А возможно ли получить постоянный токен для администратора проекта?

К сожалению, такой возможности нет.
