### ISSUE TITLE
400 Bad Request: URL invalid, extra characters found after valid URL

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#582]
Добрый день!
При построении запроса к API:
GET /v2/accounts/208/applicants/27513049/logs?page=2 HTTP/1.1
Host: api.huntflow.ru
Authorization: Bearer 6ebffa
Получаю ответ:
{
    "errors": [
        {
            "type": "value_error.url.extra",
            "title": "URL invalid, extra characters found after valid URL: ' 1/%25D0%25A8%25D0%25B8%25D1%2580%25D0%25BE%25D0%25BA%25D0%25BE%25D0%25B2%2B%25D0%2594.%2B1?s=Sw7kDChLn8powVI7N2_dyA&e=1662770073'",
            "location": {
                "entity": "response",
                "variable": "/items/0/files/1/url"
            }
        }
    ]
}

При том, что если строить с параметром page=1, то все ок.
Посмотрите, пожалуйста.

P.S. оставил последние 6 символов токена

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ. Передали задачу в разработку и уже разбираемся с проблемой. 
Отпишем по результатам в этот тикет.

**Comment by shemetovilya** [comment]
Здравствуйте!
Спасибо, что взяли в работу. Уточните, пожалуйста, текущий статус по данной проблеме.

**Comment by glibin** [comment]
Добрый день!

Задача находится на этапе тестирования, исправление выйдет на этой неделе. Я отпишу в этом тикете по результату.

**Comment by glibin** [comment]
Добрый день! 

Исправление вышло.
