### ISSUE TITLE
Получение всех календарей сотрудников

### ISSUE THREAD

**Issue by Gut0wski** [huntflow/api#585]
В интерфейсе вижу два календаря:
![3](https://user-images.githubusercontent.com/12109780/189827097-2c93a08f-258f-4ec3-804d-818f4ae42edb.png)

Однако запрос возвращает только один:
![4](https://user-images.githubusercontent.com/12109780/189827175-d45c2b1a-6789-4f65-9f52-dc5d54dc963b.png)

Как получить их все?

**Comment by glibin** [comment]
Добрый день!


Такой возможности нет. Метод отдает лишь календари, которые принадлежат пользователю, ассоциированному с токеном.
