### ISSUE TITLE
Adding query param filters to entities

### ISSUE THREAD

**Issue by sanederchik** [huntflow/api#586]
I don't know whether it was asked before, but this moment looks very critical to me.

According to [`API docs`](https://api.huntflow.ru/v2/docs#overview) there is no approach to get list of updated `vacancy_requests`, `vacancies`, and `applicants` by either directly pointing some paramaters in `query params` or somewhere else. This problem is essentially crucial for `applicants` methods because in my company there are **hundreds of thousands** of these entities and regular method without search allows to fetch a maximum of 30 records per request. Hence, time spent for getting all data synchronously would take dozens of hours each day, while asynchronous requests create a risk of pushing the backend down.

It would be very nice of you if you add such query params in the nearest future.

**Comment by glibin** [comment]
Hello,

currently we don't have any cursor based (or updates related) methods. 

But you can use a strategy of one time syncing everything and then catching updates via webhooks. In that case you will sync only objects that have been changed.
