### ISSUE TITLE
Дата в логах кандидата

### ISSUE THREAD

**Issue by katherine-pashchina** [huntflow/api#587]
Добрый день!
Возник вопрос - почему-то парсим от HF по методу GET https://cdek.huntflow.ru/account/2/applicants/<applicant_id>/log время интервью, ставим событие по часовому поясу UTC+7, а приходит UTC+3 вместо него. На скринах событие, которое создано в HF и полученное по API:
<img width="1097" alt="Снимок экрана 2022-09-19 в 16 26 42" src="https://user-images.githubusercontent.com/112069655/191004449-dac10f38-b9b8-47bf-a672-1ceb9c942bf5.png">
<img width="266" alt="Снимок экрана 2022-09-19 в 16 27 15" src="https://user-images.githubusercontent.com/112069655/191004453-ede3ebaf-b645-4f1e-99d7-3200c7e4a229.png"
Либо это передается не часовой пояс, указанный в событии? В таком случае можно сделать так, чтобы в событии он передавался?

**Comment by glibin** [comment]
Добрый день!

В API отдается время по Москве. Актуальную таймзону события можно получить по полю timezone и, при необходимости, сконвертировать в нее.
