### ISSUE TITLE
Добавление кандидата на вакансию

### ISSUE THREAD

**Issue by artegok** [huntflow/api#588]
Добрый день. 2 вопроса: 
1) При добавлении кандидата в базу, поле externals[].files.id не обязательное. При "Добавление кандидата на вакансию" files id обязательное. Почему и зачем?

2) Пытаюсь добавить кандидата на вакансию, получаю ошибку. Не понимаю что не так
```
 {
  "message": "400 - {\"errors\":[{\"type\":\"server_error\"}]}",
  "name": "Error",
  "stack": "Error: Request failed with status code 400\n    at createError (/data/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/data/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
} 
```

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, примеры запросов и ответов. Без них в проблеме разобраться невозможно,

**Comment by artegok** [comment]
Запрос:
https://api.huntflow.ru/account/105367/applicants/127166
```
{
    "vacancy": 3163182,
    "status": 127166,
    "files": [
        {
            "id": 1111111
        }
    ]
}
```

Ответ:
```
{
  "message": "400 - {\"errors\":[{\"type\":\"server_error\"}]}",
  "name": "Error",
  "stack": "Error: Request failed with status code 400\n    at createError (/data/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/data/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:525:35)\n    at IncomingMessage.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
} 
```

**Comment by glibin** [comment]
Добрый день!

> При "Добавление кандидата на вакансию" files id обязательное. Почему и зачем?

Оно необязательное. Это поле можно не передавать. 

Подскажите, удалось решить проблему?

**Comment by artegok** [comment]
> Добрый день!
> 
> > При "Добавление кандидата на вакансию" files id обязательное. Почему и зачем?
> 
> Оно необязательное. Это поле можно не передавать.
> 
> Подскажите, удалось решить проблему?

Добрый день. 
Проблему решить не удалось. Выше пример запроса и ответа.

В документации указано что поле files id бязательное.
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/107918717/193529828-5bca348a-c55f-423e-bd79-54f000519b21.png">

**Comment by glibin** [comment]
Сам объект `files` является необязательным (на вашем скрине на пункт выше от красной рамки). Если массив передается, то идентификатор является обязательным.

**Comment by artegok** [comment]
> Сам объект `files` является необязательным (на вашем скрине на пункт выше от красной рамки). Если массив передается, то идентификатор является обязательным.

с этим разобрались, спасибо) остально понять почему 400 получаю(

**Comment by glibin** [comment]
Кажется, что у вас некорректный урл на добавление кандидата на вакансию. 

Корректный POST /account/{account_id}/applicants/{applicant_id}/vacancy

В APIv2: https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/applicants/-applicant_id-/vacancy

**Comment by artegok** [comment]
спасибо
