### ISSUE TITLE
Ошибка при добавлении кандидата в базу

### ISSUE THREAD

**Issue by maddoxdev** [huntflow/api#59]
Добрый день.

Получаю ошибку при добавлении кандидата в базу, но только в случае, если укажу externals[].account_source

Что имеем: 

- справочник [ApplicantSources](https://github.com/huntflow/api/blob/master/ru/dicts.md#applicant_sources)
- [метод добавления кандидата](https://github.com/huntflow/api/blob/master/ru/applicants.md#add)

В документации метода добавления кандидата указано:

externals[].account_source | number | Нет | Идентификатор источника резюме ([справочник](https://github.com/huntflow/api/blob/master/ru/dicts.md#applicant_sources))
-- | -- | -- | --

Что делаю я.

1. Обращаюсь по адресу https://api.huntflow.ru/account/{ID}/applicant/sources
![image](https://user-images.githubusercontent.com/10694484/62213544-d53f8480-b3ab-11e9-969a-e745991918ec.png)
2. Отправляю запрос на добавление нового кандидата и указываю account_source и списка выше и получаю ошибку (PS: без указания externals[].account_source ошибки не будет)
![image](https://user-images.githubusercontent.com/10694484/62213922-b392cd00-b3ac-11e9-9a34-8256dc458b13.png)

Все ли верно я делаю? В чем может быть ошибка?

**Comment by glibin** [comment]
Добрый день!

Передаваемый объект резюме должен иметь минимальный формат:

```
            "data": {
                "body": ""
            },
            "auth_type": "NATIVE",
            "account_source": 131679
```
