### ISSUE TITLE
Получение вакансии (400 - str type expected)

### ISSUE THREAD

**Issue by AlexeySumin** [huntflow/api#590]
Проблема возникает в песочнице(sandbox) при получении вакансии по ее id в песочнице:
https://github.com/huntflow/api/blob/master/ru/vacancies.md#%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D0%B8

Пытаюсь получить данные через вторую версию апи:
https://sandbox-api.huntflow.dev/v2/accounts/188/vacancies/48

Ожидаю получить вакансию с id 48, но в ответ получаю: 
```
{
    "errors": [
        {
            "type": "type_error.str",
            "title": "str type expected",
            "location": {
                "entity": "response",
                "variable": "/source"
            }
        }
    ]
}
```

**Comment by julyl2gen** [comment]
Добрый день!

Причина была на нашей стороне, у двух полей было одинаковое название "source"

Исправили схему вакансии, теперь должно работать.
