### ISSUE TITLE
Запрос логов апликанта возвращает 400 и непонятную ошибку про email

### ISSUE THREAD

**Issue by skarpushin** [huntflow/api#591]
**REQUEST**:
 `GET https://api.huntflow.ru/v2/accounts/55771/applicants/20497793/logs?page=1&count=30&vacancy=2962498`

HEADERS:
```
Accept: [application/json, application/*+json]
Content-Length: [0]
Authorization: Bearer ***d2e0e9
User-Agent: [App/1.0 ([sergey.karpushin@auriga.com](mailto:sergey.karpushin@auriga.com))]
```

**RESPONSE**: HTTP 400 Bad Request
HEADERS:
```
Date: [Fri, 07 Oct 2022 09:42:53 GMT]
Content-Type: [application/json]
Content-Length: [304]
Connection: [keep-alive]
x-request-id: [cba80c84-3235-4f7a-8848-5f1785ffb2f0]
```
BODY:
`{"errors":[{"type":"[value_error.email](http://value_error.email/)","title":"value is not a valid email address","location":{"entity":"response","variable":"/items/0/email/to/0/email"}},{"type":"[value_error.email](http://value_error.email/)","title":"value is not a valid email address","location":{"entity":"response","variable":"/items/3/email/from_email"}}]}`

При этом если открыть страницу https://huntflow.ru/my/aurigahr#vacancy/2962498/filter/workon/id/20497793 то там есть какая-то ошибка про персональные данные, которая видимо как-то связана с ошибкой выше 
![image](https://user-images.githubusercontent.com/4069181/194531701-366b9ffb-2a38-4fe5-938f-191676224026.png)

Ну ок, если мне через API нельзя видеть email человека - не возвращайте просто этот самый email. В данном случай мне нужен не email, а история событий по апликанту, чтобы посчитать специфические внутренние KPI в нашей компании. 

Как получить историю событий по такому апликанту?

**Comment by katerina-glushko** [comment]
аналогично. очень хотелось бы понять, как обойти ошибку.

**Comment by aleks-v-k** [comment]
Проблема в том, что в базе лежат email, не проходящие валидацию. Это на нашей стороне проблема, вернее две: вместо 500 мы отдаем 400 (впрочем это не поможет вам получить ваши данные); мы допускаем кривые имейлы в базе, но при этом строго валидируем их в исходящих данных API. На обе проблемы завел тикеты, будем решать, по срокам сообщу позднее.

**Comment by aleks-v-k** [comment]
Одну из проблем решили - теперь логи должны возвращаться. Другую (про то, что возвращается 400 вместо 500) пока нет, но она сейчас не должна вам мешать.

**Comment by katerina-glushko** [comment]
@skarpushin , мы продолжаем получать ошибку на часть запросов. подскажите, что нужно сделать, чтобы для них ошибки не возникало, и мы смогли получить эти логи?

**Comment by skarpushin** [comment]
@aleks-v-k спасибо.
