### ISSUE TITLE
Одинаковые типы ошибок для удаленных обьектов и несуществующих путей.

### ISSUE THREAD

**Issue by georgy72** [huntflow/api#592]
Идентичные ошибки на не существующий или удаленный объект https://api.huntflow.ru/v2/accounts/12345/applicants/1234
и не существуйющий ресурс https://api.huntflow.ru/v2/accounts/12345/applicantssssssss/1234

<img width="313" alt="image" src="https://user-images.githubusercontent.com/16348574/194757023-52d60d1d-453a-4bf1-a947-db5aaed48789.png">

Сделайте например разный тип ошибки.

**Comment by aleks-v-k** [comment]
Добавил задачу на доработку, по срокам пока не могу сориентировать
