### ISSUE TITLE
ID статусов

### ISSUE THREAD

**Issue by nadezhda-krasichkova-lamoda** [huntflow/api#593]
Добрый день! Коллеги, мы при загрузке данных увидели, что у одного из статусов ID стоит NULL и мы не можем его забрать.
![image](https://user-images.githubusercontent.com/115457606/194827983-289131e3-5fca-4661-abdf-c1507fbf9ff4.png)
Пожалуйста, подскажите, можно ли поменять ID на числовое значение? И является ли ID ключевым полем?

--

Nadezhda Krasichkova

IT Support specialist of corp apps

Mobile: +7 (909) 340-21-32

Russia | Moscow | prosp. Marshala Zhukova, 1, bld.1

[www.lamoda.ru](http://www.lamoda.ru/)

**Comment by aleks-v-k** [comment]
Насколько я понял речь о причинах отказа, а не о статусах. Элемент с id = null - "виртуальный", его нет БД, означает, что никакой причины не проставлено. Поменять, соответственно, его нельзя. Можете игнорировать, если куда-то хотите записать и отсуствие идентификатора не позволяет это сделать.
