### ISSUE TITLE
400 Error. value is not a valid email address

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#594]
Добрый день!
При построении запроса к API:
GET /v2/accounts/208/applicants/27189902/logs?page=1 HTTP/1.1
Host: api.huntflow.ru
Authorization: Bearer dae40d
Получаю ответ:
{
    "errors": [
        {
            "type": "value_error.email",
            "title": "value is not a valid email address",
            "location": {
                "entity": "response",
                "variable": "/items/1/email/from_email"
            }
        },
        {
            "type": "value_error.email",
            "title": "value is not a valid email address",
            "location": {
                "entity": "response",
                "variable": "/items/3/email/from_email"
            }
        },
        {
            "type": "value_error.email",
            "title": "value is not a valid email address",
            "location": {
                "entity": "response",
                "variable": "/items/5/email/from_email"
            }
        }
    ]
}

Посмотрите, пожалуйста.

P.S. оставил последние 6 символов токена

**Comment by aleks-v-k** [comment]
Исправлено, можете проверять.

**Comment by shemetovilya** [comment]
Подтверждаю, спасибо!
