### ISSUE TITLE
400 Error. none is not an allowed value

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#595]
Добрый день!
При построении запроса к API:
GET /v2/accounts/208/applicants/7024761/logs?page=1 HTTP/1.1
Host: api.huntflow.ru
Authorization: Bearer dae40d
Получаю ответ:
{
    "errors": [
        {
            "type": "type_error.none.not_allowed",
            "title": "none is not an allowed value",
            "location": {
                "entity": "response",
                "variable": "/items/15/calendar_event/name"
            }
        }
    ]
}

Посмотрите, пожалуйста.

P.S. оставил последние 6 символов токена

**Comment by aleks-v-k** [comment]
Ошибка на нашей стороне. Исправлено, можете проверять.

**Comment by shemetovilya** [comment]
На всякий случай добавлю, вдруг тут чем-то отличается: 
Аналогичная проблема по кандидату 28317435

{'errors': [{'type': 'type_error.none.not_allowed', 'title': 'none is not an allowed value', 'location': {'entity': 'response', 'variable': '/items/7/email/subject'}}]}

**Comment by aleks-v-k** [comment]
Спасибо за подробные ошибки. Да, это тоже на нашей стороне проблемы, будем исправлять.

**Comment by shemetovilya** [comment]
Коллеги, добрый день! Уточните, пожалуйста, какой сейчас статус по данным проблемам?

**Comment by alexreznikoff** [comment]
Добрый день, все ошибки были исправлены
