### ISSUE TITLE
404 ошибка метода /account/{account_id}/all_divisions

### ISSUE THREAD

**Issue by uwlebedev** [huntflow/api#596]
Хочу выгрузить структуру подразделений в песочницу.
Делаю POST запрос к URL https://sandbox-api.huntflow.dev/accounts/190/all_divisions
Возвращается 404: Not Found

Так же вопрос: в github выполнение этой операции описывается методом `/accounts/{account_id}/all_divisions`, а в Huntflow API Reference v2 через `/accounts/{account_id}/divisions/batch`
Какой метод правильно использовать?
Спасибо.

**Comment by skarpushin** [comment]
@uwlebedev я не работаю в ХФ, но рискну предположить, что вы используете старый API, который был отключён. 
Попробуйте использовать другой API: https://sandbox-api.huntflow.ru/v2/accounts/190/divisions

**Comment by uwlebedev** [comment]
Попробовал различные варианты, в итоге
https://sandbox-api.huntflow.dev/v2/accounts/190/divisions/batch
