### ISSUE TITLE
Вопрос по документации

### ISSUE THREAD

**Issue by hia-itsolution** [huntflow/api#598]
Как получить события календаря? Есть  методы на производственный календарь, но это не то. Я знаю, что с помощью /calendar_accounts можно получить ID календаря. Как по нему получить список событий?

**Comment by hia-itsolution** [comment]
Подскажите, хотя бы, как вытащить список событий (интервью и т.д.)? Цель - синхронизировать "календарь" вашего сервиса и другого. В событии нужны детали, аля участники, дата, и тд

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности в API сейчас нет.

Я передам ваше пожелание в отдел разработки на добавление такой возможности в будущем.
