### ISSUE TITLE
ошибка value_error.email value is not a valid email address

### ISSUE THREAD

**Issue by kimrbv** [huntflow/api#599]
Делаем запрос кандидатов в новой версии API 2.0
/accounts/{account_id}/applicants

выдается ошибка
{"errors":[{"type":"value_error.email","title":"value is not a valid email address","location":{"entity":"response","variable":"/items/0/email"}}]}

При аналогичном запросе в старой работающей версии API 
такой проблемы не возникает

Что происходит и как с этим бороться?

**Comment by glibin** [comment]
Добрый день! Подскажите, пожалуйста, используемый вами endpoint API, а также account_id

**Comment by glibin** [comment]
Мои коллеги должны были уже связаться с вами по этому вопросу (в том числе срокам исправления). 

Подскажите, вопрос еще актуален?

**Comment by kimrbv** [comment]
спасибо. ждем исправлений

**Comment by glibin** [comment]
Добрый день! Подскажите, коллеги вам уже сообщили об исправлении?
