### ISSUE TITLE
Explain how work with coworkers field

### ISSUE THREAD

**Issue by ShuFFel** [huntflow/api#6]
https://github.com/huntflow/api/blob/master/ru/vacancies.md 
Если возможно пояснить, какие объекты должны находиться в массиве для поля «coworkers»?
(If possible, explain which objects should be in the array for the "colleague" field?)

**Comment by glibin** [comment]
По примеру, там передается список идентификаторов (чисел) аккаунтов рекрутеров

**Comment by glibin** [comment]
> А идентификаторы это поле "id" или "member"?

если имеются ввиду данные из запроса /account/<account_id>/coworkers, то "id"

**Comment by ShuFFel** [comment]
/account/<account_id>/coworkers выдает 404

**Comment by glibin** [comment]
Прошу прощения, 

`/account/<account_id>/members`

который вернет всех работающих в организации рекрутеров, также возможен фильтр для вакансии (кто работает на вакансии):

`/account/<account_id>/members?vacancy=<vacancy_id>`

а также добавить в ответ заказчиков:

`/account/<account_id>/members?show_watchers=true`

Метода пока нет в документации – исправим в ближайшее время.

**Comment by ShuFFel** [comment]
Попробовал, вакансия создается, но из назначенных людей только тот, от чьего имени создавалась вакансия

**Comment by glibin** [comment]
Пришлите запрос, который отправляете?

**Comment by glibin** [comment]
Уточните у управляющего вашей организации, что у пользователя API Robot стоит право "Назначать коллег на вакансии".

**Comment by ShuFFel** [comment]
Права есть

**Comment by ShuFFel** [comment]
Переназначил права, проверл - без изменений. Есть еще варианты по поводу того, что я могу делать не так?
Нашел метод POST https://api.huntflow.ru/account/11657/members?vacancy=<vacancyId> выдает 403  Forbidden (права на назначение коллег на вакнсии есть)
