### ISSUE TITLE
Не работает загрузка подразделений

### ISSUE THREAD

**Issue by DimaDodger** [huntflow/api#60]
```
POST https://api.huntflow.ru/account/23115/all_divisions

HTTP/1.1 403 Forbidden
Date: Thu, 08 Aug 2019 11:24:54 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 38
Connection: keep-alive
Server: TornadoServer/5.1.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: x-requested-with, content-type

{
  "errors": [
    {
      "type": "server_error"
    }
  ]
}

Response code: 403 (Forbidden); Time: 415ms; Content length: 38 bytes
```
Необходимо обновлять структуру компании, возникает ошибка. Метод работает? Почему у нас нет прав (403)?

**Comment by glibin** [comment]
У технической учетной записи вашего API проставлена роль "Рекрутер". Управления подразделениями возможно только с ролью "Управляющий". 

Вы можете запросить смену роли для технической учетной записи через клиентскую поддержку со ссылкой на данный тикет.
