### ISSUE TITLE
Не удается загрузить pdf-файл, сервер отвечает ошибкой 504 (Превышен лимит ожидания)

### ISSUE THREAD

**Issue by oddmdma** [huntflow/api#601]
Любые другие запросы к апи работают нормально. Загрузка файлов, кажется, перестала работать с начала октября.
Делаю запрос к `https://api.huntflow.ru/v2/accounts/23064/upload`, но не получаю ответ от сервера.

**Comment by glibin** [comment]
Добрый день!


Подскажите, проблема еще актуальна?

**Comment by oddmdma** [comment]
Добрый день!
Да, ничего не изменилось.

**Comment by glibin** [comment]
Ситуация повторяется для всех файлов или только для конкретного? Можете прислать проблемный файл на glibin@huntflow.ru со ссылкой на данный тикет?
