### ISSUE TITLE
Не работает загрузка файлов в sandbox

### ISSUE THREAD

**Issue by bluebird04** [huntflow/api#602]
Сначала пробовал на .net написать как-то так:
```
var contentData = new MultipartFormDataContent("541707001333896955513675");
contentData.Headers.ContentType.MediaType = "multipart/form-data";
contentData.Add(new ByteArrayContent(request.File, 0, request.File.Length), "file", request.OriginalName);
var resp = await _httpClient.PostAsync($"/account/{_accountID}/upload", contentData);
```
Получаю в ответ:
{"errors": [{"type": "server_error", "value": ["BAD_REQUEST"]}]}
Запросы на /me отрабатывает корректно.

Потом пробовал нативным curl:
```
curl -X POST -H "Content-Type: multipart/form-data" -H "X-File-Parse: false" -H "Authorization: Bearer TOKEN" -F "file=@PATH_TO_FILE" https://sandbox-api.huntflow.dev/account/ACCOUNT_ID/upload
```
В ответ получил:
{"errors": [{"type": "server_error", "value": ["FORBIDDEN"]}]}

Что мы делаем не так? Есть ли какие-то мысли почему на .Net Core запрос работает некорректно? 
Спасибо.

**Comment by glibin** [comment]
Добрый день!

К сожалению, мы не сможем подсказать с использованием конкретных языков программирования.

Подскажите, удалось разобраться с проблемой?

**Comment by bluebird04** [comment]
Добрый день,

Нет к сожалению ошибка та же при попытки загрузить файл в песочнице.
{"errors": [{"type": "server_error", "value": ["FORBIDDEN"]}]}

**Comment by glibin** [comment]
Есть подозрение, что у вас неверно указан ACCOUNT_ID, сделайте запрос на получение списка доступных организаций (https://sandbox-api.huntflow.dev/accounts) и используйте для запросов идентификатор из него 

Также, обращу внимание на то, что мы прекращаем поддержку первой версии API 26 ноября. Необходимо перейти на вторую версию API: https://api.huntflow.ru/v2/docs#overview
