### ISSUE TITLE
Перестали создаваться вакансии через API v2 Create a vacancy request

### ISSUE THREAD

**Issue by rekunovVV** [huntflow/api#603]
Отправляем запрос на создание вакансии вот в таком виде:
{"account_vacancy_request":000,"position":"Onboarding manager (Growing advisors community","company":"BU - Univibes","money":"1108.94","body":"- searching, hiring and onboarding new education abroad consultants","requirements":"Supervisor: Irina Ivanova<br>Reasons for opening the job position: Replacement<br>Experience requirements (skills, software proficiency, etc.): 1-3 years<br>Remote option available: Yes<br>Preferable office: Moscow<br>Responsibilities: - searching, hiring and onboarding new education abroad consultants<br>"}

Получаем ответ:

{"errors":[{"type":"there_was_an_error_parsing_the_body","title":"There was an error parsing the body"}]}

Ответ на запрос схемы:

{"items":[{"id":158,"account":188,"name":"","attendee_required":null,"attendee_hint":"","active":true,"schema":{"position":{"id":1705,"type":"string","title":"Должность / Position","required":true,"order":1,"value":null,"key":"position","account":188},"company":{"id":1706,"type":"string","title":"Подразделение / Department","required":true,"order":2,"value":null,"key":"company","account":188},"money":{"id":1707,"type":"string","title":"Зарплата / Compensation","required":true,"order":3,"value":null,"delimiter":true,"key":"money","account":188},"body":{"id":1708,"type":"html","title":"Обязанности  / Responsibilities","required":true,"order":4,"value":null,"vacancy_field":"body","key":null,"account":188},"requirements":{"id":1709,"type":"html","title":"Требования / Requirements","required":true,"order":5,"value":null,"vacancy_field":"requirements","key":null,"account":188},"comment":{"id":1710,"type":"text","title":"Комментарии / Comments","required":false,"order":6,"value":null,"key":null,"account":188}}}]}

Помогите пожалуйста понять в чем ошибка.

Ошибка возникла спустя некоторое время после перехода на API v2

**Comment by rekunovVV** [comment]
Запрос отправляем на: https://sandbox-api.huntflow.dev/v2/accounts/XXX/vacancy_requests

**Comment by glibin** [comment]
Добрый день!

Судя по запросу и ответа, у вас сформировано неверное тело запроса. 

Строка:

```
{"account_vacancy_request":000,"position":"Onboarding manager (Growing advisors community","company":"BU - Univibes","money":"1108.94","body":"- searching, hiring and onboarding new education abroad consultants","requirements":"Supervisor: Irina Ivanova
Reasons for opening the job position: Replacement
Experience requirements (skills, software proficiency, etc.): 1-3 years
Remote option available: Yes
Preferable office: Moscow
Responsibilities: - searching, hiring and onboarding new education abroad consultants
"}
```

Не является валидным JSON. Вероятно, вам необходимо использовать библиотеки сериализации данных в JSON формат.

**Comment by rekunovVV** [comment]
Прошу прощения при копировании  заменил account_vacancy_request на 000.
Актуальное тело запроса ниже:
{"account_vacancy_request":158,"position":"Onboarding manager (Growing advisors community","company":"BU - Univibes","money":"1108.94","body":"- searching, hiring and onboarding new education abroad consultants","requirements":"Supervisor: Irina Golotova<br>Reasons for opening the job position: Replacement<br>Experience requirements (skills, software proficiency, etc.): 1-3 years<br>Remote option available: Yes<br>Preferable office: Moscow<br>Responsibilities: - searching, hiring and onboarding new education abroad consultants<br>"}

**Comment by glibin** [comment]
Добрый день!

Повторю свой ответ:

Судя по запросу и ответа, у вас сформировано неверное тело запроса.

```
{"account_vacancy_request":158,"position":"Onboarding manager (Growing advisors community","company":"BU - Univibes","money":"1108.94","body":"- searching, hiring and onboarding new education abroad consultants","requirements":"Supervisor: Irina Golotova
Reasons for opening the job position: Replacement
Experience requirements (skills, software proficiency, etc.): 1-3 years
Remote option available: Yes
Preferable office: Moscow
Responsibilities: - searching, hiring and onboarding new education abroad consultants
"}
```

Не является валидным JSON. Вероятно, вам необходимо использовать библиотеки сериализации данных в JSON формат.

**Comment by alexreznikoff** [comment]
Добрый день, подобная ошибка будет возникать, если данные отправлять как форму, а не как json

**Comment by rekunovVV** [comment]
Проблема была в том, что cURL отправлял POST запрос с заголовком Content-Type: application/x-www-form-urlencoded и телом запроса в формате JSON.
После исправления заголовков интеграция заработала.
На первой версии АПИ почему то не возникала такая ошибка.
Тикет можно закрывать. Спасибо.
