### ISSUE TITLE
Создание вакансии, не добавляет coworkers

### ISSUE THREAD

**Issue by LitvinDaria** [huntflow/api#604]
Добрый день, пытаюсь создать новую вакансию, в новой версии обязательным полем стоит coworkers(раньше создавалась вакансия и с пустым значением)
Выпадаем ошибка:
{
    "errors": [
        {
            "type": "type_error.list",
            "title": "value is not a valid list",
            "location": {
                "entity": "body",
                "variable": "/coworkers"
            }
        }
    ]
}

я добавляю значение coworkers:[id_coworkers]
id_coworkers - данное значение беру из списка  https://api.huntflow.ru/v2/accounts/XXXXX/coworkers?count=100&page=4

Вакансия создается, НО в ответе получаю:
  **"coworkers": null,**

Как решить эту проблему?

**Comment by glibin** [comment]
Добрый день!

Можете прислать полное тело запроса (чувствительные текстовые данные можно заменить) и ответа?

**Comment by LitvinDaria** [comment]
Добрый день, да конечно, вот мой запрос 
POST, по адресу: https://api.huntflow.ru/v2/accounts/22222/vacancies
{
    "fill_quotas": [
        {
            "applicants_to_hire": 1,
            "deadline": null
        }
    ],
    "coworkers": [
        555555
    ],
    "parent": null,
    "account_division": "888888",
    "account_vacancy_status_group": null,
    "account_region": null,
    "position": "Специалист по кадрам и работе с общественностью (жен.)",
    "company": null,
    "money": ".",
    "state": "OPEN",
    "created": "2022-10-21T15:15:13.466+08:00",
    "source": null,
    "hidden": false,
    "priority": 0,
    "body": "Основные задачи: ",
    "requirements": "Образование: ; \\u003cp\\u003e Опыт:  \\u003cp\\u003e Знание ПК: ; Специальность по образованию: ",
    "conditions": "Командировки: ; \\u003cp\\u003e Метод работы: Вахта [36-часов (вахта)];",
    "deadline": "2022-11-20",
    "applicants_to_hire": 1,
    "multiple": false,
    "category": 423443,
    "work_format": 45454,
    "company_name": 67676,
    "location": 45409,
    "directorate": 78787,
    "public_career_site": null,
    "accepted_offer": 55555,
    "actual_status": 444444,
    "work_status": 444487,
    "schedule": "Вахта",
    "work_time": "",
    "reason": "Новая позиция",
    "reason_name": "-",
    "type_searching": 44444,
    "type_contract": "Срочный",
    "reason_type_contract": "Обоснование срочности договора (вид срочности)",
    "period_contract": null,
    "purpose_work": "Специалист по связям с общественностью",
    "tasks": "",
    "trips": "",
    "education": "",
    "special_education": "",
    "english": "",
    "software_knowledge": "",
    "position_experience": null,
    "experience": "",
    "direction_search": null,
    "company_search": null,
    "skills": "",
    "soft_skills": "",
    "interview": null,
    "solution_member": "",
    "salary_office": ".",
    "salary_watch": ".",
    "bonus": "Бонус",
    "files": [],
    "vacancy_request": null,
    "comments": null
}

**Comment by glibin** [comment]
Добрый день!

Проблема исправлена.
