### ISSUE TITLE
Не удается получить новую пару токенов 

### ISSUE THREAD

**Issue by AntonGrushkin** [huntflow/api#608]
В ходе работы с токенами возникла проблема с их обновлением. Ниже опишу шаги которые я выполнил для воспроизведения проблемы. 
1. Получил пару токенов: `access_token` и `refresh_token` в разделе - Настройки API
2. Дождался истечения срока работы для `access_token`
3. Выполнил `POST` запрос на URL: `https://api.huntflow.ru/v2/token/refresh`, в теле запрос передал `refresh_token`
4. В ответе `POST` запроса мне вернулось:
```
{
    "errors": [
        {
            "type": "not_found",
            "title": "error.robot_token.not_found"
        }
    ]
}
``` 

P.S срок жизни `refresh_token` на момент выполнения запроса ещё не истек.

**Comment by AntonGrushkin** [comment]
Пример запроса в Postman:
![image](https://user-images.githubusercontent.com/41586313/200488536-97609eaa-905f-4492-b7cc-cc59747f97a4.png)

**Comment by glibin** [comment]
Добрый день!


Возможные причины такого поведения:

- передаётся некорректное значение refresh_token
- refresh_token уже был ранее использован для обновления access_token

Пришлите, пожалуйста, account_id и последние 6 цифр refresh_token, попробуем разобраться в причинах.

**Comment by AntonGrushkin** [comment]
Добрый день, куда вам прислать информацию ? У вас есть почта? Как-то не хочется скидывать эти данные в общий доступ.

**Comment by glibin** [comment]
Добрый день!

glibin@huntflow.ru

**Comment by AntonGrushkin** [comment]
Добрый день, сегодня протестировал обновление токена ещё раз, все заработало. Закрываю этот issue.
