### ISSUE TITLE
Вакансия присутствует в логе кандидатов, но отсутствует среди перечня вакансий

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#609]
Здравствуйте!

Обнаружили следующую несогласованность в данных. В логе кандидатов имеется ссылка на вакансию 3155891, а в endpoint-е по вакансиям таковая отсутствует. 
Пример запросов:

GET /v2/accounts/208/applicants/27691832/logs?page=1 HTTP/1.1
Host: api.huntflow.ru
User-Agent: SelectelDWH (shemetov.i@selectel.ru)
Authorization: Bearer 9380c8

GET /v2/accounts/208/vacancies/3155891?page=1 HTTP/1.1
Host: api.huntflow.ru
User-Agent: SelectelDWH (shemetov.i@selectel.ru)
Authorization: Bearer 9380c8

Посмотрите, пожалуйста.

**Comment by glibin** [comment]
Добрый день!

Вакансия 3155891 удалена, однако позже подтянулись ответы кандидатов на письма. Я завел задачу на исправление данной проблемы.

**Comment by shemetovilya** [comment]
Добрый день! Проблема еще наблюдается. Уточните, пожалуйста, когда получится поправить проблему?
Заранее благодарю.

**Comment by aleks-v-k** [comment]
@shemetovilya можете проверить? Данные поправили в поденедельник вечером

**Comment by shemetovilya** [comment]
@aleks-v-k , здравствуйте.
Да, проблема не наблюдается, спасибо!
