### ISSUE TITLE
Не могу передать отклик

### ISSUE THREAD

**Issue by artzavod** [huntflow/api#61]
Добрый день! Пытаюсь сделать передачу отклика для бургеркинга из посадочной страницы в huntflow. Мне выдали образец JSON, токен и ендпоинт.

Отправляю вот такой JSON:

{

    "f":"Пупкин",
    "i":"Вася",
    "o":"Саныч",
    "tel":"7 (911) 111-11-11",
    "vacancy":"Повар-Кассир",
    "city":"Москва",
    "metro":"Тульская",
    "restaurant":"МСК, ул Большая Тульская 2",
    "restaurant_num":"0135",
    "citizenship":"РФ",
    "email":"smil_e@bk.ru",
    "from_rest":"0",
    "site":"nophone",
    "b_day":"1",
    "b_month":"1",
    "b_year":"2001"

}

Вот на этот URL: https://burgerking.huntflow.ru/bk/multivacancy/add
Для авторизации использую дополнительный header ( Authorization: Bearer <personal_token> )

И получаю вот такой ответ:

   [0] => HTTP/1.1 400 Bad Request
   [1] => Server: nginx
   [2] => Date: Fri, 09 Aug 2019 14:20:15 GMT
   [3] => Content-Type: application/json; charset=UTF-8
   [4] => Content-Length: 66
   [5] => Connection: close
   [6] => X-Frame-Options: SAMEORIGIN
   [7] => Strict-Transport-Security: max-age=31536000

Подскажите что не так?

**Comment by glibin** [comment]
Доброе утро!

Подскажите, какие данные возвращаются в теле ответа от сервера?

**Comment by artzavod** [comment]
{"errors": [{"value": "unsupported_position", "type": "request"}]}

**Comment by glibin** [comment]
Неверно передано название вакансии. Доступные значения:

– Менеджер
– Повар-кассир
– Тренер-наставник

**Comment by artzavod** [comment]
А что не так с названием? Оно идентично вашему примеру:

"vacancy":"Повар-Кассир",

**Comment by glibin** [comment]
регистром?

**Comment by artzavod** [comment]
Да, с вашим названием нормально прошло, Но ведь это не правильно? Если уж вы делаете сверку по названию, то надо перед сверкой провети различные манипуляции (trim, strtolower, etc...)

**Comment by glibin** [comment]
Предполагается, что на данный URL приходят подготовленные данные от подрядчика, который подготовить и приведет данные к нужному формату.
