### ISSUE TITLE
Отсутствует источник резюме

### ISSUE THREAD

**Issue by shemetovilya** [huntflow/api#610]
Добрый день!
У кандидата 17997574 указан источник "external"."account_source": 36881. Однако такой источник отсутствует в /accounts/208/applicants/sources

GET /v2/accounts/208/applicants/17997574?page=1 HTTP/1.1
Host: api.huntflow.ru
User-Agent: SelectelDWH (shemetov.i@selectel.ru)
Authorization: Bearer 9380c8

GET /v2/accounts/208/applicants/sources?page=1 HTTP/1.1
Host: api.huntflow.ru
User-Agent: SelectelDWH (shemetov.i@selectel.ru)
Authorization: Bearer 9380c8

Посмотрите, пожалуйста.
P.S. оставил 6 последних символов токена.

**Comment by shemetovilya** [comment]
Случай не единичный, ниже привожу перечень кандидатов, которые ссылаются на несуществующие резюме:
16231329
16485382
16512775
16705946
17401722
17716734
17997574
18057919
18265667
19452570
19751021
20212790
21507192
22674207
22712080
22978138
23468800
26585692
27023845


Перечень отсутствующих идентификаторов резюме:
36881
306273
330341
330345
386996

**Comment by glibin** [comment]
Добрый день!

Указанные источники резюме удалены, поэтому нужно считать, что у кандидатов/резюме на таких источниках источника нет. Мы со своей стороны сделаем доработку, чтобы удаленные источники не отображались в выводе API.
