### ISSUE TITLE
Hunflow api v2, создание вакансии

### ISSUE THREAD

**Issue by ShamVlad** [huntflow/api#612]
Доброго дня!

Вылетают ошибки валидации параметров, при создании заявки через новый API /accounts/2/vacancy_requests
![image](https://user-images.githubusercontent.com/29889223/201882692-77faca64-0359-4661-b85a-699b633c279d.png)
В данном случае, поле date_hiring необязателен для заполнения, поэтому в теле запроса ее значение пустое (пустая строка), но API все равно ругается на это поле.
Если в качестве date_hiring отправить null, то запрос будет успешен. 
Такое же поведение с полями, у которых есть параметр availableOn, то есть с такими полями, которые необходимо передавать при определенных условиях. 

На старом API, вакансия создается успешно.

**Comment by glibin** [comment]
Добрый день!

Да, валидация в APIv2 стала более жесткой. Пустая строка не является валидной датой. Для передачи необязательного поля, как вы правильно написали, необходимо передавать или значение `null`, или вовсе не передавать указанное поле.
