### ISSUE TITLE
Можно ли упростить выгрузку логов?

### ISSUE THREAD

**Issue by qqdqx** [huntflow/api#615]
Уважаемые партнеры, добрый день.

Мы пользуемся API для выгрузок данных в наш DWH для аналитических целей и сталкиваемся с проблемой выгрузки логов событий.
Единственным предусмотренным способом является GET /accounts/{account_id}/applicants/{applicant_id}/logs с указанием id кандидата, что для нас означает ~200k запросов без учета пагинации.
Нам решение кажется не самым оптимальным, пробовали определять пул активных кандидатов 
•	через поля created у кандидата, ставя границы по периоду
•	поля updated\changed у связки кандидата c вакансией (поле links у кандидата)
Эти способы всё равно не помогут «отловить» кандидатов, который был давно заведен в систему и в связке с вакансией у него не происходили изменения.
По этой причине хочу узнать у вас, есть ли другой способ забирать логи, например, с выгрузкой всех логов за выбираемый период без привязки к кандидатам, - который еще не задокументирован в api v2.

Заранее благодарю за ответ.

**Comment by glibin** [comment]
Добрый день!

Самый эффективный способ отслеживать движения по кандидатам – подписываться на вебхуки (https://github.com/huntflow/api/blob/master/ru/webhooks.md) и по ним синхронизировать изменения по кандидатам.

Метода для выгрузки всех логов без привязки к кандидату в API пока нет.
