### ISSUE TITLE
Адрес отправки вебхуков

### ISSUE THREAD

**Issue by vmaevskaya** [huntflow/api#616]
Добрый день.
Подскажите, пожалуйста, с какого адреса (IP или имя) отправляются вебхуки HF?

**Comment by glibin** [comment]
Добрый день!

Для облачной версии Хантфлоу у нас есть специальный адрес ([cloud.huntflow.ru](http://cloud.huntflow.ru/)), который при DNS-запросе возвращает все публичные IP-адреса Хантфлоу, с которых может идти отправка вебхуков.

На данный момент список такой, но может меняться в будущем:

```
% nslookup
> cloud.huntflowru

Address: 188.246.235.227
Address: 188.246.235.236
Address: 82.202.193.172
Address: 5.189.235.109
Address: 82.202.193.170
```

Если вы используете выделенное размещение Хантфлоу, то лучше обратиться в поддержку (help@huntflow.ru) для уточнения адреса вашего Хантфлоу.
