### ISSUE TITLE
Проблема с фильтрацией кандидатов

### ISSUE THREAD

**Issue by StarForser** [huntflow/api#617]
`https://sandbox-api.huntflow.dev/v2/accounts/181/applicants?vacancy=13&status=891`

Добрый день, такой запрос возвращает всегда всех кандидатов, даже если они не на этой вакансии и этапе.

**Comment by glibin** [comment]
Добрый день!

Не смогли воспроизвести проблему. Пришлите, пожалуйста, полный заголовки запроса (исключая токен) и полные заголовки и тело ответа.
