### ISSUE TITLE
Пояснения по Мультивакансии

### ISSUE THREAD

**Issue by Pavel-Qiwi** [huntflow/api#618]
Добрый день!
Проясните, пожалуйста детали мультивакансии.
пример:
создана мультивакансия, она отражается 2мя строками, при этом в методе vacancies по вакансии 3261367 не выгружаются, например, поля account division, reason и тд. Они все остаются на вакансии 3261368.
Какая из них является основной?
и с какими заполненными атрибутами будет выгружаться вакансия, если одна вакансия из набора будет закрыта?
вакансия с id 3261368 обновится на новую дату открытия и сохранит уже ранее заполненные поля или как?

![image](https://user-images.githubusercontent.com/80900126/203775379-9b174806-e4c8-4125-b738-efc9cdf703eb.png)

**Comment by glibin** [comment]
Добрый день!

Вакансия 3261367 является объединяющей вакансией (мультивакансией). Вакансия 3261368 является дочерней, таких вакансий у мультивакансии может быть несколько. 

Вакансию 3261368 можно закрывать и переоткрывать, она никак не отразится на мультивакансии.
