### ISSUE TITLE
Видимо, ошибка в документации по API

### ISSUE THREAD

**Issue by ostelenkov** [huntflow/api#620]
В документации, по адресу: https://api.huntflow.ru/v2/docs#overview по поводу устаревания токена авторизации написано следующее:
The lifetime of the access_token is 7 days. Upon expiring you will start receiving a 401 HTTP response code for the requests to API with a body {"errors": [{"type": "oauth", "value": ["token_expired"]}]}.

На самом деле приходит это вот:
{"errors":[{"type":"authorization_error","title":"Authorization Error","detail":"token_expired"}]}

**Comment by ostelenkov** [comment]
Вопрос по описанному несоответствию:

Я могу уверенно использовать ответ {"errors":[{"type":"authorization_error","title":"Authorization Error","detail":"token_expired"}]} в своих кодах, или что-то может измениться?

И еще один вопрос по ошибке при попытке смены токена раньше срока его устаревания:
{"errors":[{"type":"access_denied","title":"error.robot_token.refresh_too_early"}]} - это можно использовать?

**Comment by ostelenkov** [comment]
??

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ.
Была допущена ошибка в описании поведения и будет исправлена в ближайшем времени.

Корректный ответ при устаревшем токене:

`{"errors":[{"type":"authorization_error","title":"Authorization Error","detail":"token_expired"}]}`

(ориентироваться необходимо на detail→token_exired)


> И еще один вопрос по ошибке при попытке смены токена раньше срока его устаревания:
{"errors":[{"type":"access_denied","title":"error.robot_token.refresh_too_early"}]} - это можно использовать?

да, можно

**Comment by ostelenkov** [comment]
Спасибо!

**Comment by glibin** [comment]
Ошибка исправлена. Спасибо!
