### ISSUE TITLE
Получение дополнительной информации

### ISSUE THREAD

**Issue by dwhus** [huntflow/api#621]
Добрый день, подскажите пожалуйста как получить дополнительную информацию по сотруднику. Не смог понять по документации.
[Скриншот](https://skr.sh/sHIdHGnUvnS)

И если можно, подскажите пожалуйста как этот запрос посылать в песочницу(некоторые запросы просят acсount_id и не понятно какой указывать для песочнцы)

**Comment by vmaevskaya** [comment]
@glibin Добрый день. Обратите внимание на вопрос, пожалуйста, очень ждем ответ.

**Comment by glibin** [comment]
Добрый день!

Получение доп. информации о кандидате: https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/-applicant_id-/questionary

Адрес API песочницы, а также документация находятся тут: https://sandbox-api.huntflow.dev/v2/docs#overview
Получить список доступных организаций (account_id): https://sandbox-api.huntflow.dev/v2/docs#get-/accounts
