### ISSUE TITLE
Отключение проверки доставки

### ISSUE THREAD

**Issue by moredain** [huntflow/api#623]
Добрый день! 

```
Для повышения надежности и устойчивости системы отправки вебхуков, мы внесли изменения в условия их доставки.

Теперь, если вебхук не был успешно доставлен, Хантфлоу сделает три дополнительные попытки доставки:

Через 10 секунд после последней попытки.
Через 100 секунд после последней попытки.
Через 1000 секунд после последней попытки.

Если все попытки доставки будут неуспешны, то вебхук деактивируется, а управляющие рекрутеры получат об этом уведомление на почту.

Чтобы снова активировать вебхук, нужно будет перейти в настройки (например, из письма-уведомления) и включить его вручную.
```
Как то можно отключить эту проверку? 
Каждый раз нужно лазить в хантфлоу и включать хук - не очень удобно при частом отключении приемщика хуков
Ну или на крайний случай  - увеличить интервал отправки?

**Comment by alexreznikoff** [comment]
@moredain добрый день, возможности отключения данного алгоритма не планируется. Могу только порекомендовать сделать приемщик вебхуков легким, и не затрагивающим бизнес-логики приложением, который лишь получает вебхук, складывает его в очередь/базу данных для дальнейшей обработки и возвращает нам корректный ответ (200, 204)
