### ISSUE TITLE
Некорректно отрабатывает запрос applicants

### ISSUE THREAD

**Issue by OlegFedorovich** [huntflow/api#624]
Добрый день! 
Столкнулись с проблемой, запрос не выдает всех кандидатов, у которых текущий статус 53750, делаем вот такой запрос (страницы перещелкиваем, ответы в файликах стр1 и стр2):

https://api.huntflow.ru/v2/accounts/22417/applicants?&status=53750&only_current_status=true&page=1

Не получаем в ответ сотрудников с ИД:
29486805
29812850

Хотя, если делать запрос(ответ в файлике 29812850):

https://api.huntflow.ru/v2/accounts/22417/applicants/29812850, то

Указано, что текущий статус сотрудника 53750, но его нет в общей выборке.

**Comment by alexreznikoff** [comment]
@OlegFedorovich добрый день, ваш вопрос взяли в работу.
Огромная просьба, удалите, пожалуйста, приложенные файлы, они содержат персональные данные людей

**Comment by alexreznikoff** [comment]
@OlegFedorovich 
Кандидаты 29486805 и 29812850 находятся на вакансии, которая уже закрыта. Исторически так сложилось, что если в запросе на получение списка кандидатов не указана конкретная вакансия, то возвращаются только кандидаты, которые находятся на открытых вакансиях. Заняться этим вопросом сможем только в следующем году.

**Comment by OlegFedorovich** [comment]
Уточните, пожалуйста, есть ли какие-то приблизительные даты по решению или проблема низкоприоритетная и будет решена как дойдут руки?

**Comment by alexreznikoff** [comment]
Задача не приоритетная, к сожалению, по срокам пока не могу Вас сориентировать
