### ISSUE TITLE
Не создаёт кандидата при пустом после email

### ISSUE THREAD

**Issue by Suvmsh** [huntflow/api#625]
Не создаёт кандидата при пустом после email, ошибка "value is not a valid email address".
С остальными полями проблем нет, например если пустое поле - телефон. 

[Фото 1](https://sun9-27.userapi.com/impg/0Rlm-5r6SGkAMgMtb31ls5opNLy6B-hTsR0VxA/6kvi_2VTT3o.jpg?size=1876x926&quality=96&sign=b3810003313153838979116edf184b7d&type=album) | [Фото 2](https://sun9-23.userapi.com/impg/kijmQAyIAcW6qvSB3bBNJFEAuNxv_CB3mviM3Q/b7sw2QZMm5I.jpg?size=1025x715&quality=96&sign=70f49a0baed8b61a576dd5d6864dd288&type=album)

**Comment by alexreznikoff** [comment]
@Suvmsh добрый день, если у кандидита нет email, нужно или вообще не прописывать поле `email` при создании, или установить ему значение `null`

**Comment by Suvmsh** [comment]
> @Suvmsh добрый день, если у кандидата нет email, нужно или вообще не прописывать поле `email` при создании, или установить ему значение `null`

1. Подскажите, почему этого момента нет в документации?
2. Почему в прошлой версии API - таких проблем с этим полем не было?
3. В чем разница между полем "Телефон" или любым другим необязательным, которые успешно создаются без `null` и полем Email?

**Comment by alexreznikoff** [comment]
1. В документации указаны все типы полей и их обязательность, например поле `phone` имеет тип `string` и для него значение пустой строки валидно, а вот поле `email` имеет тип `email` и для него значение пустой строки недопустимо
2. В старой версии АПИ не было многих проверок типов
3. ответ из пункта 1
