### ISSUE TITLE
Ограничение на количество запросов в секунду и день

### ISSUE THREAD

**Issue by dsboff** [huntflow/api#627]
Добрый день! У меня большой проект по сбору большого количества данных из huntflow. Необходимо точно знать сколько запросов в секунду по api можно осуществлять, а так же есть ли ограничение на количество запросов в день (если да, то сколько)?

С Уважением, Дмитрий

**Comment by glibin** [comment]
Добрый день!

Для каждого токена установлен лимит в 10 запросов в секунду (лимит может не действовать при on-premise размещении и размещении на выделенных серверах).

При превышении лимита будет возвращен ответ 429 Too Many Requests.
