### ISSUE TITLE
Большая задержка при отправке хука

### ISSUE THREAD

**Issue by Sebastyan1** [huntflow/api#628]
ID организации - 135809
ID вакансии - 3138260
ID этапа - 139659
ID кандидата - 31238029

В 23.01.2023 17:44:41+03:00 кандидат был передвинут на этап 139659
В это же время на URL в настройках API упал хук.
URL - https://webhook.site/66e5d54b...

НО, по другой ссылке хук свалился с большим опозданием, аж в 18:33:40
URL - https://h.albato.com/wh/38/1lfo2ng/NmJSth...

Подскажите, пожалуйста, почему в Альбато хук упал с задержкой почти в час и можно ли как-то ускорить процесс отправки хуков?
Если на вашей стороне, всё-таки, хук ушел в 17:44 могли бы отправить лог чтобы было с чем идти в Albato?)

**Comment by glibin** [comment]
Добрый день!

Все вебхуки отправляются с одинаковой скоростью, но время доставки может значительным образом зависеть от принимающей стороны. На текущий момент у вас активно два обработчика хуков и очередь вебхуков на Альбато обрабатывается гораздо медленнее второго обработчика.

Если у вас остались какие-либо вопросы, то лучше обратиться в поддержку help@huntflow.ru
