### ISSUE TITLE
Вопрос по методу /accounts/{account_id}/upload

### ISSUE THREAD

**Issue by petrof85** [huntflow/api#629]
Не грузит файлы форматов jpeg, также файлы презентаций.
Есть какие-то ограничения на форматы файлов?

Текст ошибки:
{"errors":[{"type":"validation_error","title":"Cannot parse a file with content_type = 'application/vnd.openxmlformats-officedocument.presentationml.presentation'"}]}

**Comment by glibin** [comment]
Добрый день!

Ограничения есть, но указанные форматы поддерживаются. Пришлите, пожалуйста, заголовки и тело запроса + заголовки и тело ответа (исключив данные авторизационного токена).
