### ISSUE TITLE
Не работают веб хуки

### ISSUE THREAD

**Issue by hodev** [huntflow/api#63]
Добрый день
Зарегистрировал веб хуки у вас в админке.
Запрос PING увидел у себя.
После этого не вижу чтобы к нам бэк попадали изменения по Вакансиям и Кандидатам
Интеграцию настраивал на https://apps-emb.lmru.adeo.com/huntflow-integration/api/v1/webhook

**Comment by glibin** [comment]
Проверили логи, по данному URL отдается невалидный SSL сертификат.
