### ISSUE TITLE
При декодировании ответа в апи Get a vacancy "error":"invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by StepalevaM** [huntflow/api#631]
код на go

**Comment by StepalevaM** [comment]
https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/vacancies/-vacancy_id-

**Comment by glibin** [comment]
Добрый день!

Пришлите, пожалуйста, заголовки и тело ответа от API для уточнения деталей возможной проблемы.
