### ISSUE TITLE
Не удается получить список пользователей с помощью метода /email_accounts

### ISSUE THREAD

**Issue by a1exCross** [huntflow/api#632]
При попытке обращения к методу /email_accounts и указании токена авторизации в ответ приходит пустой массив items.

{
  "items": [ ]
}

При обращении к другим методам с тем же токеном данные подтягиваются корректно. 

Подскажите в чем может быть проблема при работе с методом /email_accounts? Есть ли какие то разграничения прав доступа для данного метода?

**Comment by glibin** [comment]
Добрый день!

Да, разграничение прав, действительно, есть. Данный метод возвращает только список подключенных акаунтов почты пользователя-владельца токена. 

Если вам необходимо организовать автоматизированную отправку писем через Хантфлоу, то обратитесь на help@huntflow.ru с описанием желаемой интеграции.

**Comment by a1exCross** [comment]
Спасибо за информацию!
