### ISSUE TITLE
Есть ли возможность получить "Resume data in unified format" в песочнице

### ISSUE THREAD

**Issue by sergauriga** [huntflow/api#634]
Согласно документации
https://api.huntflow.ru/v2/docs#tag--Applicant's-resumes
и
https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/-applicant_id-/externals/-external_id-

в ответ на запрос можно получить структурированные данные резюме в поле 'resume', а именно "Resume data in unified format"

Правильно ли я понимаю что
- эта структура не создается для резюме с auth_type=NATIVE
- создать резюме другого типа можно с помощью "Волшебной" кнопки
- "Волшебная" кнопка не работает для песочницы

Можете ли вы подсказать способ создать/получить эту структуру в песочнице?
В настоящий момент я не вижу этой возможности.

**Comment by glibin** [comment]
Добрый день!

Прощу прощения за длительное ожидание.

> эта структура не создается для резюме с auth_type=NATIVE

верно

**Comment by glibin** [comment]
> создать резюме другого типа можно с помощью "Волшебной" кнопки

верно

> "Волшебная" кнопка не работает для песочницы

Работает. Достаточно зайти в интерфейс песочницы и нажать на Волшебную кнопку (установить можно из маркетплейса браузера, например), чтобы она активировалась для песочницы.

**Comment by sergauriga** [comment]
> Достаточно зайти в интерфейс песочницы и нажать на Волшебную кнопку
До этого я не допер ))
Спасибо Виталий. попробую - (видимо уже завтра)

**Comment by sergauriga** [comment]
Благодарю! Все работает.
