### ISSUE TITLE
Некорректно работает API метод [Get an applicant's worklog] not_found

### ISSUE THREAD

**Issue by abramovks** [huntflow/api#635]
Некорректно работает API метод

https://api.huntflow.ru/v2/accounts/23158/applicants/31123192/logs?count=100&page=1

ответ
{
"errors": [
{
"type": "not_found",
"title": "Not Found"
}
]
}

Не возвращает лог кандидата. По другим кандидатам отрабатывает нормально.

**Comment by glibin** [comment]
Попробуйте получить информацию о кандидате запросом [https://api.huntflow.ru/v2/accounts/23158/applicants/31123192](https://api.huntflow.ru/v2/accounts/23158/applicants/31123192)

Если возвращается другой идентификатор кандидата, то это значит, что кандидат был объединен как дубликат. Требуется перезапросить логи с новым идентификатором.
