### ISSUE TITLE
Возможность изменять кастомные поля

### ISSUE THREAD

**Issue by alexx17** [huntflow/api#637]
Добрый день.
В заявке на вакансию у нас есть наше поле external_id.
Нам необходимо поменять значение этого поля. 
В описании api как его менять я не нашел.
Подскажите пожалуйста, есть ли возможность его изменять?

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за длительный ответ. Подскажите, что вы имеете ввиду?

Если нужно поменять тип поля или перечень возможных параметров, вы можете обратиться в поддержку help@huntflow.ru
