### ISSUE TITLE
CURL на  api.huntflow.ru

### ISSUE THREAD

**Issue by hangmana** [huntflow/api#64]
Пытаемся отправить запрос CURL но получаем отказ.
Подскажите что мы делаем не так.
CURL
`
curl -i -X GET -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "User-Agent: App/1.0 (mail@mail.ru)" -H "Accept: */*"  https://api.huntflow.ru/me
`
отбивка
`
HTTP/1.1 401 Unauthorized
Date: Wed, 14 Aug 2019 09:51:02 GMT
Content-Type: application/json; charset=UTF-8
Content-Length: 100
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: TornadoServer/5.1.1
Access-Control-Allow-Methods: POST, GET, OPTIONS
Access-Control-Allow-Headers: x-requested-with, content-type
{"description": "Invalid access token", "errors": [{"value": "bad_authorization", "type": "oauth"}]}
`

**Comment by hangmana** [comment]
Токен мы получили после того как написали в поддержку.
feedback8@huntflow.ru

**Comment by glibin** [comment]
Добрый день!

Можете прислать сюда или на hello@huntflow.ru (со ссылкой на этот тикет) название вашей организации, попробуем разобраться с токеном.

**Comment by hangmana** [comment]
ООО Криптонит

**Comment by hangmana** [comment]
закрывайте заявку.
проверил все на постмене.
там все работает.
Буду уже cURL ковырять сам.
