### ISSUE TITLE
Происходит отключение вебхука

### ISSUE THREAD

**Issue by tianaserver** [huntflow/api#642]
Добрый день помогите разобраться. Немогу найти причину.
Происходит отключение вебхука в меню: Настройки -> API, постоянно в процессе работы отключается вебхук, то есть снимается галочка (Активен) отключается только на событии ( Кандидат ). Измерял работу скрипра выполняется быстро.
Подскажите, какие могут быть причины такого отключения. Компания VSN Realty

**Comment by glibin** [comment]
Добрый день!

Такое возможно в случае, если несколько попыток доставить вебхук провалятся. В этом случаем мы шлем уведомление управляющему рекрутеру о том, что вебхук октключен.

Проверьте, пожалуйста, на свой стороне, что вы корректно обрабатываете вебхуки и возвращаете ответ с 2хх кодами.

**Comment by glibin** [comment]
Информация по логике работы переотправки описана тут: https://github.com/huntflow/api/blob/master/ru/webhooks.md#отправка-и-получение-событий
