### ISSUE TITLE
Проблема с хуками

### ISSUE THREAD

**Issue by krinroman** [huntflow/api#643]
Во время тестирования хуков на изменения кандидатов и вакансий в песочнице. Была выявлена проблема, что хуки об изменениях не всегда доходят до сервера, примерно в 6 из 10 случаев. Объясните пожалуйста в чем может быть проблема.

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за длительный ответ.

Подскажите, проблема актуальна на данный момент?
