### ISSUE TITLE
400 Ошибка при добавлении вакансии POST https://api.huntflow.ru/v2/accounts/11657/vacancies

### ISSUE THREAD

**Issue by alexsokolovby2019** [huntflow/api#644]
response:

{
    "errors": [
        {
            "type": "value_error.missing",
            "title": "field required",
            "location": {
                "entity": "body",
                "variable": "/position"
            }
        },
        {
            "type": "value_error.missing",
            "title": "field required",
            "location": {
                "entity": "body",
                "variable": "/fill_quotas"
            }
        }
    ]
}

Body

{"issue":   
    {"key": "HR-1001", 
    "fields":   
        {"summary": "Тестовая вакансия HR-1001", "customfield_13437": {"value": "departmentName"}, "customfield_10214": "projectDescription", "customfield_11810": "candidateDuties", "customfield_11802": "clientSphere",  "customfield_11813": "trips",    "customfield_11815": "personal_quolities",    "customfield_11812": "unformalDetails",    "customfield_11817": "workExpirience",    "customfield_11809": "ourTeamSize",    "customfield_11808": "clientTeamSize",    "customfield_10217": "1",    "customfield_11803": "projectStatus",    "customfield_11801": "clientCountry",    "customfield_11807": "technologyStack",    "customfield_11804": "projectDuration",    "customfield_11811": "advantag",   "customfield_10224": {"value": "englishLevel"},   "customfield_11814": "requirementsCnd",  "customfield_11816": "asPlus",        "customfield_12600": {"value": "Гродно"},    "customfield_12900": {"value": "Trainee"},      "customfield_12906": {"value": "Node.js"},       "customfield_10001": {"requestType": {"name": "Вакансия на проект"}}
        }
    }
}

**Comment by alexsokolovby2019** [comment]
I look forward to your answer.
I added a few details. 

My request:
POST https://api.huntflow.ru/v2/accounts/11657/vacancies
Body:
{"issue":
{"key": "HR-1001",
"fields":
{"summary": "Тестовая вакансия HR-1001", "customfield_13437": {"value": "departmentName"}, "customfield_10214": "projectDescription", "customfield_11810": "candidateDuties", "customfield_11802": "clientSphere", "customfield_11813": "trips", "customfield_11815": "personal_quolities", "customfield_11812": "unformalDetails", "customfield_11817": "workExpirience", "customfield_11809": "ourTeamSize", "customfield_11808": "clientTeamSize", "customfield_10217": "1", "customfield_11803": "projectStatus", "customfield_11801": "clientCountry", "customfield_11807": "technologyStack", "customfield_11804": "projectDuration", "customfield_11811": "advantag", "customfield_10224": {"value": "englishLevel"}, "customfield_11814": "requirementsCnd", "customfield_11816": "asPlus", "customfield_12600": {"value": "Гродно"}, "customfield_12900": {"value": "Trainee"}, "customfield_12906": {"value": "Node.js"}, "customfield_10001": {"requestType": {"name": "Вакансия на проект"}}
}
}
}

I get responce:
Code 400 with body:
{
"errors": [
{
"type": "value_error.missing",
"title": "field required",
"location": {
"entity": "body",
"variable": "/position"
}
},
{
"type": "value_error.missing",
"title": "field required",
"location": {
"entity": "body",
"variable": "/fill_quotas"
}
}
]
}

**Comment by glibin** [comment]
Добрый день!

Формат запроса не соответствует документации: https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancies

**Comment by alexsokolovby2019** [comment]
Изменил боди, но результат тот же. В чем же ошибка?

Боди:

{
    "account_division": null,
    "account_region": null,
    "position": "Account Executive / Sales Manager",
    "company": "BD Account Executives Unit",
    "money": null,
    "priority": 0,
    "hidden": false,
    "state": "OPEN",
    "id": 3332692,
    "created": "2023-03-15T17:04:36+03:00",
    "additional_fields_list": [
        "vacancy_priority",
        "country",
        "sphere",
        "description",
        "stage",
        "duration",
        "technologies",
        "size_client",
        "size_our",
        "capability",
        "details",
        "trips",
        "personal_qualities",
        "plus",
        "experience",
        "language"
    ],
    "multiple": false,
    "parent": null,
    "account_vacancy_status_group": null,
    "updated": "2023-03-15T17:04:36+03:00",
    "body": "<p>+ Communicating with clients and gathering information about a project’s scope, budgets and timelines\r\n+ Meeting with other executives to discuss clients’ project goals, progress and outcomes\r\n+ Developing budgets and timelines for clients and the company they work for\r\n+ Coordinating teams to meet project milestones\r\n+ Assembling new teams to meet clients’ or businesses’ goals\r\n+ Reporting and recording all sales activities in a web-based CRM system\r\n+ Qualifying inbound leads and prospects via phone and email\r\n+ Organizing regular client meetings to ensure excellent customer service\r\n+ Prospecting new sales\r\n+ Holding virtual demonstrations with an end goal of earning a prospect’s business\r\n+ Preparing and presenting proposals and bids\r\n+ Negotiating terms and conditions with clients\r\n+ Collaborating with key decision makers to identify opportunities and develop ideas that deliver sales results\r\n+ Uncovering and understanding a company’s needs\r\n+ Attending trade shows and hosting customer events\r\n</p>",
    "requirements": "<p>null</p>",
    "conditions": null,
    "files": [],
    "source": null,
    "blocks": [],
    "language": "Advanced",
    "experience": "3-5",
    "details": "{\"location\":[\"Минск\"],\"techLevel\":[\"Middle\",\"Senior\"],\"specialization\":\"Sales\",\"sd\":\"HR-13442\",\"sdURL\":\"https://servicedesk.instinctools.com/browse/HR-13442\",\"leadRecruiter\":\"katsiaryna.navitskaya@instinctools.com\",\"priorityDetail\":\"Low\",\"requestType\":\"Open vacancy in company / Вакансии в компанию\",\"typeOfCooperation\":\"office/remote\"}",
    "personal_qualities": "+ Communication skills to regularly discuss project deadlines, responsibilities and goals with clients and employees on the phone, in-person and over email\r\n+ Organizational and time management abilities to stay ahead of regular deadlines and to organize projects, clients’ files and other important tasks \r\n+ Problem-solving and critical thinking skills to quickly find creative solutions to any client issues that may arise \r\n+ Presentation skills to build strategies and report them clearly and professionally to both clients and employees\r\n",
    "size_our": null,
    "description": null,
    "technologies": null,
    "stage": null,
    "capability": null,
    "trips": null,
    "sphere": null,
    "plus": null,
    "duration": null,
    "size_client": null,
    "vacancy_priority": 67860,
    "country": null
}

Responce: 400
{
    "errors": [
        {
            "type": "value_error.missing",
            "title": "field required",
            "location": {
                "entity": "body",
                "variable": "/fill_quotas"
            }
        }
    ]
}


Пожалуйста, прокомментируйте, о чем говорит текст ошибки?

**Comment by glibin** [comment]
Добрый день!

Ответ в ошибке говорит о том, что не передан объект fill_quotas . Еще раз прошу подробнее ознакомиться с документацией по методу: https://api.huntflow.ru/v2/docs#post-/accounts/-account_id-/vacancies

**Comment by alexsokolovby2019** [comment]
Спасибо, да ошибка найдена
