### ISSUE TITLE
Получение информации в разрезе кандидата - вакансии - заявки на вакансию

### ISSUE THREAD

**Issue by a1exCross** [huntflow/api#645]
Добрый день! 
Настраиваем интеграцию с Huntflow (ХФ) в разрезе работы с кандидатами и вакансиями. Опишем небольшую предысторию для понимания контекста, а затем сам вопрос. 

Предыстория:

Система Х хранит в себе некоторое количество заявок, которые в определенный момент по API передаются в ХФ. На стороне ХФ также создаются заявки на вакансию, которые преобразовываются в вакансию вручную пользователями. Одна вакансия может объединить собой несколько заявок на вакансию. Отметим, что в контексте решаемой задачи каждая заявка на вакансию предполагает некоторые различия во входной информации (например, существует вакансия "Тестировщик" и к ней привязано 3 заявки на вакансию Тестировщика, но в различные проектные команды).
Далее, в ХФ создаются кандидаты, которые связываются с вакансией. И в некоторый момент времени нам необходимо направить по API в систему Х кандидатов в привязке к вакансии, а также к одной из связанных с вакансией заявок. 

Вопрос: возможно ли получать информацию о кандидате, вакансии и единственной из нескольких заявок на эту вакансию?

**Comment by a1exCross** [comment]
Добрый день! 

Мы пытаемся привязать вебхуки к системе, которая поддерживает авторизацию с помощью токена Bearer. Но запрос приходит в нашу систему как не авторизованный. Как мы можем авторизовать запрос для подключения вебхуков с помощью Bearer token`а? В обсуждениях я нашел подобную тему и там сказано, что нужно внести ваши адреса в список доступных, но я не уверен, что те адреса уже актуальны.

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ. Коллеги подсказали, что ответ на первый вопрос уже дали. Отвечу на второй.

> В обсуждениях я нашел подобную тему и там сказано, что нужно внести ваши адреса в список доступных, но я не уверен, что те адреса уже актуальны.

Информацию о списке адресов можно получить тут: https://github.com/huntflow/api/issues/616

Механизм аутентификации реализован через подпись запроса, описание доступно здесь: https://github.com/huntflow/api/blob/master/ru/webhooks.md#заголовки-вебхука (заголовок X-Huntflow-Signature)
Других вариантов на данный момент нет.
