### ISSUE TITLE
ERROR: Create a vacancy request {  ...,  "dictionary_field": {"foreign": "field_foreign_value"},  ... }

### ISSUE THREAD

**Issue by alexsokolovby2019** [huntflow/api#649]
Речь о связи реквизитов в запросе на новый справочник Подразделения.
Запрос:
https://sandbox-api.huntflow.dev/v2/accounts/51/vacancies

так работает
"account_division": 33237

так "account_division": {"foreign": "000000001"} ругается, value is not a valid integer

Полный тестовый боди:
{
  "title": "Тестовая вакансия HR-1001",
  "position": "Тестовая вакансия HR-1001",
  "location": 1,
  "description": "projectDescription",
  "size_our": "ourTeamSize",
  "size_client": "clientTeamSize",
  "applicants_to_hire": "1",
  "sphere": "clientSphere",
  "duration": "projectDuration",
  "stage": "projectStatus",
  "capability": "advantag",
  "personal_qualities": "personal_quolities",
  "language": "englishLevel",
  "experience": "",
  "plus": "asPlus",
  "country": "clientCountry",
  "trips": "trips",
  "body": "<p>candidateDuties</p>",
  "requirements": "<p>requirementsCnd</p>",
  "priority": 1,
  "vacancy_priority": 26914,
  "account_division": {"foreign": 1}, 
  "hidden": false,
  "fill_quotas": [
    {
      "applicants_to_hire": "1",
      "vacancy_request": null
    }
  ]
}

**Comment by alexsokolovby2019** [comment]
responce 400:
{
    "errors": [
        {
            "type": "type_error.integer",
            "title": "value is not a valid integer",
            "location": {
                "entity": "body",
                "variable": "/account_division"
            }
        }
    ]
}

**Comment by glibin** [comment]
Добрый день!

Возможность передачи подразделения в виде объекта с внешним идентификатором доступно только для заявок на вакансии. 

Подскажите, вы работаете с вакансиями напрямую, без создания заявки на вакансию?
