### ISSUE TITLE
Загрузка подразделений с уровнем вложенности более 5.

### ISSUE THREAD

**Issue by eugenyProchan** [huntflow/api#65]
Добрый день, как загружать подразделения если уровень вложенности > 5 ? В описание метода для загрузки это прописано как ограничение.

**Comment by glibin** [comment]
Евгений, вы можете обратиться в поддержку и для вашей выделенной инсталляции число может быть увеличено.

**Comment by prochanEV** [comment]
Ок, спасибо!

**Comment by eugenyProchan** [comment]
Ок, спасибо!
