### ISSUE TITLE
Пропадают нанятые кандидаты 

### ISSUE THREAD

**Issue by Pavel-Qiwi** [huntflow/api#650]
Суть проблемы: если по кандидату был проставлен статус приема на работу, а затем был проставлен отказ (увольнение после приема), то поле hired_applicants не возвращает id таких кандидатов в методе /accounts/{account_id}/vacancies/{vacancy_id}/frames

Пошагово задача решалась таким образом:

Шаг 1: получаем все вакансии 
GET /accounts/{account_id}/vacancies

Шаг 2: получаем все фреймы по каждой вакансии
GET /accounts/{account_id}/vacancies/{vacancy_id}/frames

Шаг 3: разворачиваем поле “hired_applicants”

**Comment by Pavel-Qiwi** [comment]
Коллеги, поможете с вопросом?

**Comment by alexreznikoff** [comment]
@Pavel-Qiwi добрый день!
Прошу прощения за длительный ответ.
`hired_applicants` - отображает только тех кандидатов, которые реально находятся на этапе `hired`, если кандидат был отправлен в отказ, то из данного списка он удаляется

**Comment by Pavel-Qiwi** [comment]
@alexreznikoff спасибо за ответ!
а какой тогда метод использовать корректнее, чтобы видеть нанятых без учета проставленного статуса "отказ"?
мы некоторые вакансии переоткрываем на новый поиск и хочется видеть тех, кто был нанят ранее

**Comment by alexreznikoff** [comment]
Вы можете использовать поиск кандидатов для этого https://api.huntflow.ru/v2/docs#get-/accounts/-account_id-/applicants/search_by_cursor
