### ISSUE TITLE
Ошибка при регистрации webhook

### ISSUE THREAD

**Issue by subtronic** [huntflow/api#652]
Делаю по инструкции. 

Отправляю запрос на регистрацию webhook, для получения изменений по вакансиям.
В ответ получаю:
`{'errors': [{'type': 'internal_server_error', 'title': 'Internal Server Error'}]}`

Запрос типа PING доходит до бекенда от huntflow, в ответ отдаю 200.

Подскажите, в чем может быть проблема?

**Comment by alexreznikoff** [comment]
@subtronic добрый день, разбираемся с проблемой

**Comment by alexreznikoff** [comment]
@subtronic повторите, пожалуйста, запрос регистрации вебхука

**Comment by subtronic** [comment]
@alexreznikoff повторил, ничего не изменилось. 

1. Отправляю запрос на регистрацию
2. ловлю запрос PING от hf в переданный endpoint, переданный в п.1
3. endpoint регистрации webhook возвращает ту же ошибку `{'errors': [{'type': 'internal_server_error', 'title': 'Internal Server Error'}]}`

**Comment by alexreznikoff** [comment]
@subtronic в поле `secret` вы передаете слишком длинную строку, должно быть не больше 64 символов, мы в ближайшее время поправим валидацию, чтобы такой ошибки не возникало больше
