### ISSUE TITLE
API для изменения статуса кандидата.

### ISSUE THREAD

**Issue by DH-Yaroslav** [huntflow/api#66]
Здравствуйте!
Этим вызовом можно получить кандидатов на определенном этапе подбора:
GET /account/{account_id}/applicants вернёт список кандидатов компании.
Принимаемые параметры:
status — этап подбора. 

А каким вызовом можно задать/установить кандидату новый/другой этап подбора?

**Comment by glibin** [comment]
Добрый день!

> А каким вызовом можно задать/установить кандидату новый/другой этап подбора?

Изменение этапа подбора у кандидата возможно методом PUT, формат данных аналогичен добавлению на этап: 

https://github.com/huntflow/api/blob/master/ru/applicants.md#vacancy_applicant

**Comment by DH-Yaroslav** [comment]
Спасибо за быстрый ответ!
