### ISSUE TITLE
Передача данных выполняется в последнюю секунду жизни token

### ISSUE THREAD

**Issue by Xlorik0** [huntflow/api#660]
Добрый день.
У нас получилась следующая ситуация по запросам к сервису huntflow:
Когда запрос на передачу данных выполнялся в последнюю секунду жизни token, мы получили ответ
{"errors":[{"type":"authorization_error","title":"Authorization Error","detail":"token_expired"}]}
Мы сместили алгоритм на 1 секунду, и когда осталась последняя секунда жизни токена, мы отправили запрос на перевыпуск и получили ответ
КодОтвета : 403
{"errors":[{"type":"access_denied","title":"error.robot_token.refresh_too_early"}]}
Видимо все зависит от доли секунд внутри секунды.
Подскажите пожалуйста какая имеется практика по решению сложившейся у нас ситуации?

**Comment by alexsokolovby2019** [comment]
Присоединяюсь к вопросу.
Вообще не понятно, как можно отладить код, который получает новый аксес токен в последнюю секунду его жизни?Текущим апи получить новый токен программно не возможно. Можно убрать это ограничение?

**Comment by alexreznikoff** [comment]
Добрый день, логика работы подразумевается следующая
Используете созданный `access_token` до тех пор пока не получаете ошибку 401 с телом:
```json
{
  "errors": [
    {
      "type": "authorization_error",
      "title": "Authorization Error",
      "detail": "token_expired"
    }
  ]
}
```
После этого необходимо обновить токен и дальше использовать новый полученный `access_token`
