### ISSUE TITLE
Не приходит Webhook c типом событий APPLICANT

### ISSUE THREAD

**Issue by subtronic** [huntflow/api#663]
Здравствуйте, делаем все по инструкции:

1. Регистрируем webhook через API, PING приходит, webhook успешно ригстрируется
2. Ждем получения событий, но больше ни одного запроса до нас не доходит
3. Со временем регистрация webhook на стороне huntflow отваливается

**Comment by alexreznikoff** [comment]
@subtronic Добрый день, подскажите ID организации в которой регистрируете вебхук

**Comment by alexreznikoff** [comment]
А что за организация?

**Comment by subtronic** [comment]
в смысле? Она у нас одна с id 6

**Comment by alexreznikoff** [comment]
Я ведь не знаю из какой вы организации, и на каком инстансе Хантфлоу расположены. 
Поэтому мне нужно или название Вашей организации, и желательно еще полный URL точки АПИ через который Вы создаете вебхук
