### ISSUE TITLE
Фильтрация applicant_logs по дате

### ISSUE THREAD

**Issue by ADIKANT** [huntflow/api#664]
Добрый день!

Настроил python скрипты для подключения по api и в частности для получения логов по кандидатам, но т.к. кандидатов много, то и логов на каждого приходится прилично. В связи с этим добавил в код условие, чтобы забирались данные только за определенный месяц. Однако это не сработало, т.к. сначала идет получение данных по api и проверка поля created на соответствие условию, а не изначальная фильтрация api запроса по дате - в документации не нашел описания возможности отправить запрос сразу же с определенным условием по полю created. Подскажите, возможно ли это сделать? Если да, то поделитесь, пжл, примером. Если нельзя, то какие могут быть варианты решения проблемы? Сейчас код бегает в цикле 80 минут, а данные у нас только в марте начали поступать, соответственно чем дальше, тем дольше будет забег.

во вложении rtf файл с текущим кодом

[applicants_logs.zip](https://github.com/huntflow/api/files/12287199/applicants_logs.zip)

**Comment by glibin** [comment]
Добрый день!

Пока такой возможности нет в API.

Для обновления и загрузки актуальных данных можно использовать вебхуки с типом APPLICANT (https://github.com/huntflow/api/blob/master/ru/webhooks.md)
