### ISSUE TITLE
Подключение API через python

### ISSUE THREAD

**Issue by Dr-Alex110** [huntflow/api#665]
Добрый день.
Просьба оказать содействие в решении следующей проблемы – при попытке подключения к API через python возникает ошибка 404. Вот мой код:

```
import requests 
headers={'user-agent': 'App/1.0',
         'Accept':'application/json',
         'Authorization': 'Bearer Token'
        }
response = requests.get('https://sandbox-api.huntflow.dev/v2/me', headers)
print(response)
```

Полагаю, проблема заключается в авторизации. Что именно я делаю не так?

**Comment by Dr-Alex110** [comment]
> 
В строке `'Authorization': 'Bearer Token'` разумеется вместо Token у меня в коде написан реально сгенерированный токен в тестовой среде Sandbox.

**Comment by alexreznikoff** [comment]
@Dr-Alex110 Добрый день, Вы передаете `headers` как query-параметры запроса, а не хидеры. 
Вот так правильно
```python
import requests 
headers={
    'user-agent': 'App/1.0',
    'Accept':'application/json',
    'Authorization': 'Bearer Token',
}
response = requests.get('https://sandbox-api.huntflow.dev/v2/me', headers=headers)
print(response)
```

**Comment by Dr-Alex110** [comment]
Получилось. Спасибо)
