### ISSUE TITLE
Регистрация webhook - поле webhook_events типа enum

### ISSUE THREAD

**Issue by ravaitov** [huntflow/api#666]
Поле enum вызывает проблемы, нет примера json с таким полем.

Пытаюсь зарегистрировать webhook  таким запросом (body json):
{ 
 "secret": "kjhituy",
 "url": "https://app.company.ru/huntflow/applicant",
 "active": 1,
 "webhook_events": ["APPLICANT"] 
 }

Получаю ошибку (500):
{
    "errors": [
        {
            "type": "internal_server_error",
            "title": "Internal Server Error"
        }
    ]
}

Покажите пожалуйста правильный пример запроса Create webhook

**Comment by glibin** [comment]
Добрый день!

Проблема актуальна? Если да, то отправьте, пожалуйста, информацию о проблеме на help@huntflow.ru
