### ISSUE TITLE
Отображение резюме у "Заказчика"

### ISSUE THREAD

**Issue by VitalikMM** [huntflow/api#667]
При создании заказчика с включенной функцией "Скрывать зарплату кандидатов" у заказчика не отображается оригинал резюме кандидата. Есть ли возможность указать параметр/флаг (при создании кандидата или в другом месте), который позволит отображать оригинал резюме кандидата при этих настройках?

**Comment by glibin** [comment]
Добрый день!

Здесь мы отвечаем только на вопросы по использованию Хантфлоу API.

Отправьте ваш запрос на help@huntflow.ru

**Comment by VitalikMM** [comment]
Так в этом и вопрос. Как это сделать через API и возможно ли такое. Ответа в документации я не нашел
