### ISSUE TITLE
Вакансии с местоположением

### ISSUE THREAD

**Issue by garyanikin** [huntflow/api#68]
Добрый вечер! 
У нас на странице есть такой блок с вакансиями:
<img width="729" alt="Screenshot 2019-08-29 at 18 31 51" src="https://user-images.githubusercontent.com/8394041/63954843-6ded2100-ca8c-11e9-9565-04cb25471175.png">

Вакансии разделены по командам (company в вашем API), так же у вакансий есть местоположение (Moscow, London)
Как записать местоположение в вакансию(на сайте) и получить его из API?

**Comment by glibin** [comment]
Добрый день!

Подскажите, внедрялись в вашу форму вакансии в Хантфлоу дополнительные поля? 
Это можно сделать через них. Самое простое: внедрить поле со справочником для команд (это будет удобнее, чем использовать текстовое поле) и поле со справочником для локаций.

Для внедрения полей можно обратиться к персональному менеджеру.
