### ISSUE TITLE
Не получается загрузить файл

### ISSUE THREAD

**Issue by garyanikin** [huntflow/api#71]
Добрый день. Пытаюсь загрузить файл, но сервер возращает `{"errors": [{"type": "server_error"}]}`

Помогите, пожалуйста, разобраться в чем проблема.
Файлы отправлял примерно в 12:00 (по мск)
User-Agent: App/1.0 (info@sweatco.in)

**Comment by glibin** [comment]
Добрый день!

Пришлите полный набор данных, который отправляете (без заголовка Authorization) сюда или на hello@huntflow.ru

**Comment by garyanikin** [comment]
Headers:
Content-Type - multipart/form-data
User-Agent - App/1.0 (i.anikin@sweatco.in)

Body(form-data): 
file - картинка
description - '' (пустая строка)

У меня получается сохранить файл с помощью Postman, но не получается когда я сохраняю его через сервер.
Возможно вы можете подсказать почему не получается сохранить файл? Например по логам

**Comment by maddoxdev** [comment]
@garyanikin 
> Headers:
> Content-Type - multipart/form-data
> User-Agent - App/1.0 ([i.anikin@sweatco.in](mailto:i.anikin@sweatco.in))
> 
> Body(form-data):
> file - картинка
> description - '' (пустая строка)

Попробуйте добавить в заголовки Content-Length
