### ISSUE TITLE
Максимальный размер загружаемого файла

### ISSUE THREAD

**Issue by maddoxdev** [huntflow/api#72]
Пожалуйста опишите в [документации по загрузке файлов](https://github.com/huntflow/api/blob/master/ru/upload.md) максимальный размер загружаемого файла. Дело в том, что все процессы взаимодействия с этим API проходят в фоне и пользователь не может хоть как-то отреагировать на эту ситуацию ->

> <body bgcolor="white">
> <center><h1>413 Request Entity Too Large</h1></center>
> <hr><center>nginx</center>

 А так, хотя бы ограничения установим.

**Comment by glibin** [comment]
Максимальный размер файла 15 Мб. В документацию добавим, спасибо.
