### ISSUE TITLE
Инкрементальная загрузка

### ISSUE THREAD

**Issue by aleksey1928** [huntflow/api#75]
Добрый день.
1) Есть возможность инкрементальной загрузки логов работы с кандидатом?
GET /account/{account_id}/applicants/{applicant_id}/log
Перед нами стоит задача забирать к себе историю работы с кандидатами. Забирать каждый день всю историю по всем кандидатам не вариант, т.к. кандидатов слишком много. Было бы хорошо, если бы была возможность забирать только новые записи в истории (например, передавать в запросе фильтр на дату).
1.1. В методе GET /account/{account_id}/applicants нашёл поля links[].updated, links[].changed. Они всегда обновляются, когда с кандидатом происходит новое событие? Если да, то, наверно, можно было бы на них завязаться. Или есть какой-то вариант проще?
2) Аналогичный вопрос про инкрементальную загрузку для следующих методов:
GET /account/{account_id}/vacancies
GET /account/{account_id}/applicants
Есть возможность как-то забирать каждый день не всё, а только изменившиеся записи?

Заранее спасибо за ответ :)

**Comment by glibin** [comment]
Добрый день!

К сожалению, такой возможности пока нет. Как альтернативу можно использовать вебхуки (https://github.com/huntflow/api/blob/master/ru/webhooks.md) для получения обновлений в реальном времени.

**Comment by aleksey1928** [comment]
А можно узнать, что за база, в которой лежат все данные? Может быть, есть возможность создать учётку, с доступом к необходимым данным, из-под которой мы будем ходить своим ETL средством?

**Comment by glibin** [comment]
Такой возможности нет.

**Comment by aleksey1928** [comment]
Понятно, спасибо за ответ.
Ещё вопрос - можно ли для метода GET /account/{account_id}/applicants увеличить число итемов на страницу? Например, до 100, как у GET /account/{account_id}/vacancies

**Comment by glibin** [comment]
К сожалению, пока такой возможности нет.
