### ISSUE TITLE
Как получить дополнительные поля?

### ISSUE THREAD

**Issue by garyanikin** [huntflow/api#76]
Добрый день. Нам добавили два справочника City и Teams.
Мы указали их в вакансии, но я не могу получить эти данные ни в общем списке вакансии, ни в детальной информации о вакансии.
<img width="266" alt="Screenshot 2019-09-16 at 17 39 45" src="https://user-images.githubusercontent.com/8394041/64967447-2b5b7f00-d8a9-11e9-9a46-6382a2222455.png">
В детальной информации присутствуют только названия полей, без их значений

**Comment by glibin** [comment]
Добрый день!

Подскажите ваш account_id? А также пример того, как отдается в запросе детальной информации по вакансии?

**Comment by garyanikin** [comment]
account_id 23064
```
'2400000': {
        teams: 2754,
        source: null,
        applicants_to_hire: 2,
        multiple: false,
        body: '',
        priority: 1,
        deadline: null,
        city: 2749,
        position: 'Product',
        files: [],
        account_division: null,
        created: '2019-08-07T16:05:32+03:00',
        hidden: false,
        money: '',
        state: 'OPEN',
        id: 2400000,
        requirements: null,
        additional_fields_list: [
          'city',
          'teams'
        ],
        conditions: null,
        parent: null,
        company: 'Product',
        vacancy_request: null
      }
```

Как из id `teams: 2754` и `city: 2749` получить названия?

**Comment by garyanikin** [comment]
Account_id 23064

в запросе детальной информации по вакансии 
```
'2400006': {
        teams: 2754,
        source: null,
        applicants_to_hire: 2,
        multiple: false,
        body: '',
        priority: 1,
        deadline: null,
        city: 2749,
        position: 'Product',
        files: [],
        account_division: null,
        created: '2019-08-07T16:05:32+03:00',
        hidden: false,
        money: '',
        state: 'OPEN',
        id: 2400006,
        requirements: null,
        additional_fields_list: [
          'city',
          'teams'
        ],
        conditions: null,
        parent: null,
        company: 'Product',
        vacancy_request: null
      }
```

как из id `teams: 2754` и `city: 2749` получить названия?

**Comment by glibin** [comment]
Города: GET `/account/23064/dictionary/city_sweatcoin`
Команды: GET `/account/23064/dictionary/team_sweatcoin`

**Comment by garyanikin** [comment]
Спасибо
