### ISSUE TITLE
Чат-бот для корпоративного мессенджера Dialog

### ISSUE THREAD

**Issue by adovgopolova** [huntflow/api#77]
Здравствуйте, мы являемся вашими клиентами и с учетом возможностей наших API, хотели бы реализовать чат-бота (Dialog-Хантфлоу) для улучшения рекрутингового процесса. На данном этапе хотелось бы уточнить про авторизацию, в документации у Вас написано: 
Для использования сервисов, требующих авторизацию пользователя, вам необходимо зарегистрировать приложение. Для этого Управляющий рекрутер должен отправить заявку на hello@huntflow.ru. После этого вы сможете настроить процесс авторизации.

Не могли бы Вы, пожалуйста, более подробно мне рассказать, какие шаги мне необходимо предпринять для того, чтобы пользователям Dialog (заказчикам и рекрутерам) при открытие ссылок на вакансии кандидатов не приходилось каждый раз вводить логин и пароль. 

Также в документации я не нашла информации, как мы можем из системы передавать информацию по статистике закрытия вакансий. Возможно ли получение из Хантфлоу статистики по закрытию вакансий? 

Заранее спасибо.

__

**Comment by glibin** [comment]
Доброе утро!

> Для использования сервисов, требующих авторизацию пользователя, вам необходимо зарегистрировать приложение. Для этого Управляющий рекрутер должен отправить заявку на hello@huntflow.ru. После этого вы сможете настроить процесс авторизации.

Для большинства случаев достаточно наличия персонального токена, который позволяет организовать интеграцию с сервисами, похожими на ваш (например, Slack). Подробнее о персональных токенах: https://github.com/huntflow/api/blob/master/ru/personal_token.md

> Не могли бы Вы, пожалуйста, более подробно мне рассказать, какие шаги мне необходимо предпринять для того, чтобы пользователям Dialog (заказчикам и рекрутерам) при открытие ссылок на вакансии кандидатов не приходилось каждый раз вводить логин и пароль.

К сожалению, такого типа интеграции по API нет (если только вы не будете присылать всю нужную для заказчиков информацию по API прямо в чат). Для отправки событий по кандидатам в чат отлично подойдут вебхуки: https://github.com/huntflow/api/blob/master/ru/webhooks.md 

Также, при инсталляции Хантфлоу на выделенных серверах есть возможность использовать дополнительные средства аутентификации (с корпоративной учетной записью или сертификатами типа X590), что упростит вход нанимающим менеджерам.

> Возможно ли получение из Хантфлоу статистики по закрытию вакансий?

На данный момент выгружать отчеты через API нельзя, но вы можете через методы API получать информацию, агрегировать ее и готовить отчет по своим потребностям.
