### ISSUE TITLE
Неверная ссылка

### ISSUE THREAD

**Issue by eugenyProchan** [huntflow/api#78]
Поправьте ссылку вот на этой странице 
https://github.com/huntflow/api/blob/master/ru/account_divisions.md
в самом низу "Как отслеживать статус задачи."

Сейчас там во такая ссылка https://github.com/huntflow/api/blob/master/ru/delayed_tasks.py
и 404.

**Comment by chistyakov** [comment]
@eugenyProchan , спасибо!

Исправил.

Верная ссылка:
https://github.com/huntflow/api/blob/master/ru/delayed_tasks.md
