### ISSUE TITLE
Проблемы с отправкой post запроса

### ISSUE THREAD

**Issue by denisoed** [huntflow/api#81]
1. Пытаюсь отправить post запрос на урл https://api.huntflow.ru/account/account_id/vacancy_request, чтобы отправить заявку на вакансию

2. В **headers** передаю 
Authorization: "Bearer token api"
User-Agent: "App/1.0 (incaseoffire@example.com)" 

![image](https://user-images.githubusercontent.com/17797700/65605422-e16e4980-dfca-11e9-86d5-dbcbe0214109.png)

3. В тело запроса
```
{
    "account_vacancy_request": 7396,
    "position": "Фронтендер",
    "money": "25000",
    "hard_skills": "Опыт руководства производством не менее 80 лет",
    "soft_skills": "Коммуникабельность, целеустремленность, стрессоустойчивость",
    "comment": "ASAP"
}
```

3. Фактический результат 
```
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}
```
![image](https://user-images.githubusercontent.com/17797700/65605639-41fd8680-dfcb-11e9-81a6-d9da4a519773.png)

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за долгий ответ.

Уточните, пожалуйста, вы отправляете запрос на https://api.huntflow.ru/account/account_id/vacancy_request ?

Дело в том, что вместо account_id должен быть идентификатор вашей организации, который можно получить здесь: https://github.com/huntflow/api/blob/master/ru/user.md#получение-информации-о-доступных-организациях

**Comment by denisoed** [comment]
Да, я указываю **account_id**(из пяти чисел) https://api.huntflow.ru/account/*****/vacancy_request

- После указываю хедеры(прикрепил в первом комментарии, во 2ом шаге) 
- Получаю id схемы https://api.huntflow.ru/account/*****/account_vacancy_request
- Беру тестовые данные из документации, при этом указав id схемы в поле **account_vacancy_request**(в моем случае это 7396)
```
{
    "account_vacancy_request": 7396
    "position": "Директор",
    "money": "25000",
    "hard_skills": "Опыт руководства производством не менее 80 лет",
    "soft_skills": "Коммуникабельность, целеустремленность, стрессоустойчивость",
    "comment": "ASAP"
}
```
- Отправляю POST запрос и в ответе получаю вот такую беду
```
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
} 
```
GET запросы проходят нормально.
Может быть у нашего аккаунта нет доступа для отправки POST запросов(хотя это мало вероятно)?

При создании [меток](https://github.com/huntflow/api/blob/master/ru/tags.md#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B5%D1%82%D0%BA%D0%B8-%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8) тоже самое - **server_error**

**Comment by glibin** [comment]
Добрый день!

Прошу прощения за задержку с ответом.

При получении ответа по запросу https://api.huntflow.ru/account/36479/account_vacancy_request будут получены поля для передачи в качестве параметров.

В вашем случае есть обязательные поля body, requirements, которые вы не передаете. Мы завели задачу на улучшение отдачи ошибок добавления заявок.

Еще раз приношу извинения за долгий ответ.

**Comment by denisoed** [comment]
@glibin Спасибо!
