### ISSUE TITLE
Не получается создать вакансию

### ISSUE THREAD

**Issue by SoHardKI** [huntflow/api#82]
Добрый день при попытке создать вакансию возвращается следующий ответ
![image](https://user-images.githubusercontent.com/47571224/65885770-dd17a700-e3a3-11e9-800a-5f14f8f9ea31.png)
Хотелось бы объяснений что значит эта ошибка

**Comment by glibin** [comment]
Добрый вечер!

Эта ошибка значит, что для создания вакансии в КА требуется передача заявки на вакансию из модуля кадровых агентств. 
Пожалуйста, свяжитесь с вашим менеджером для уточнения вопросов доработки API.
