### ISSUE TITLE
Проблемы по работе с вакансиями

### ISSUE THREAD

**Issue by SoHardKI** [huntflow/api#84]
В документации описан метод создания вакансии (https://github.com/huntflow/api/blob/master/ru/vacancies.md#add), при тестировании выяснилось что обязательным параметром является id заявки на вакансию. Далее был рассмотрен метод создания заявки на вакансию (https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#vacancy-request-new). В этом методе обязательным параметром является id схемы заявки на вакансию. При использовании метода получения всех схем заявок на вакансии (https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#account-vacancy-request-list), возвращается пустой массив, в свою очередь метода создания схемы заявки на вакансию найдено не было. Вопрос как нам быть в данном случае? Или мы что-то не так делаем?

**Comment by glibin** [comment]
Добрый день!

Описанные ссылки касаются работы с заявками для компании внутренного подбора. 

У кадровых агентств заявки на вакансию инициируются от клиентов (своими сущностями), поэтому и передаваться должны именно они. 

Свяжитесь с коллегами из поддержки для уточнения доработок API для КА.
