### ISSUE TITLE
Поиск кандидатов по email, телефону, ФИО

### ISSUE THREAD

**Issue by aakolzin** [huntflow/api#85]
Добрый день, хотелось бы иметь возможность найти кандидата в системе по email, телефону, ФИО. Сейчас я вижу только вариант с тем, чтобы постранично запросить всех кандидатов и проверить на своей стороне, какие еще есть варианты?

**Comment by glibin** [comment]
Мы планируем расширить работу данного метода после чего он станет документированным

**Comment by Alien88183** [comment]
Коллеги, подскажите /account/<account_id>/applicants/search?q= были ли внесены изменения?сегодня перестало работать.
