### ISSUE TITLE
Обновление подразделений

### ISSUE THREAD

**Issue by maddoxdev** [huntflow/api#86]
Добрый день!

В документации API подразделений задокументирован только один метод: **POST /account/{account_id}/all_divisions (Метод для загрузки подразделений)**

Раз нет методов типа Create/Update/Delete, то мне следует предполагать, что этот метод выполняет все эти операции. То есть если в вашей базе сохранено 500 наших подразделений и я этот метод оправляю JSON такого вида:
`{
   "items":[
      {
         "name":"Подразделение 1",
         "foreign":"d1"
      }
   ]
}`

то 500 записей полностью удалятся или будут помечены "active" = false и будет активна только 1 (отправленная) запись?

-----------------------------------------------------------------

Примерно такой же вопрос по обновлениям записей.

У вас в базе 500 строк наших подразделений. Каждый из них имеет свой ID, который потом привязывается в вакансиям и прочее.. Как происходит обновление записей? Идет проверка ваш ID <==> Foreing (наш ID)?

Так же, что на счет вложенности? В нашем случае, при обновлении 5 уровней - мало.

**Comment by glibin** [comment]
Добрый вечер!

> этот метод выполняет все эти операции

Да

> то 500 записей полностью удалятся или будут помечены "active" = false и будет активна только 1 (отправленная) запись?

500 будут помечены `"active" = false`, а активной будет одна загруженная

> Идет проверка ваш ID <==> Foreing (наш ID)?

Мы сверяем дубликаты записей по "foreign", чтобы вам не было необходимости знать про идентификаторы внутри Хантфлоу для обновления структуры.

> Так же, что на счет вложенности? В нашем случае, при обновлении 5 уровней - мало.

Уточните уровень вложенности у вас?

**Comment by maddoxdev** [comment]
> Уточните уровень вложенности у вас?

11

**Comment by maddoxdev** [comment]
@glibin @chistyakov 
Здравствуйте коллеги!

Пытаюсь загрузить подразделения - выдает ошибку:
`HTTP 403 Forbidden
{
    "errors": [
        {
            "type": "server_error"
        }
    ]
}`

JSON:
`{
  "items": [
    {
      "name": "Уровень 1",
      "foreign": "2615",
      "meta": {
        "parentId": null,
        "id": "2aafa7a5-0676-480a-8097-4fdf80e2fa1b",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2623",
      "meta": {
        "parentId": null,
        "id": "e254c2e1-e41f-11e0-b4ed-001ec9d552b1",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2626",
      "meta": {
        "parentId": null,
        "id": "74d16179-39f8-44b7-946a-40334a7ea91c",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2636",
      "meta": {
        "parentId": null,
        "id": "028019dc-6592-47d8-963d-3d5274c9a47b",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2638",
      "meta": {
        "parentId": null,
        "id": "6bbcc81c-f67d-424c-9ace-3683602df490",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2644",
      "meta": {
        "parentId": null,
        "id": "79ac18bd-e283-41e5-94fa-12f0eeff4217",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2646",
      "meta": {
        "parentId": null,
        "id": "175ad7a1-f6ab-4841-8f20-01ce31d3e554",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "2657",
      "meta": {
        "parentId": null,
        "id": "50a47d36-9334-4c56-8287-cf5173bcab3e",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "3220",
      "meta": {
        "parentId": null,
        "id": "8d36d70e-bbfc-4a68-839a-078f113bbbee",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "3222",
      "meta": {
        "parentId": null,
        "id": "bab3ced2-7c9e-4556-beda-3e205226bc19",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "4480",
      "meta": {
        "parentId": null,
        "id": "4276370d-4d98-404a-bc4b-41e657f615f2",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "4586",
      "meta": {
        "parentId": null,
        "id": "5e06610f-f889-4801-9ad4-7063729aab5f",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "4773",
      "meta": {
        "parentId": null,
        "id": "7628f2f2-fa06-11e7-b1f7-001ec9d8cb21",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "7725",
      "meta": {
        "parentId": null,
        "id": "2a27a8e8-b577-11e3-ac92-001ec9d8cb21",
        "deep": 1
      }
    },
    {
      "name": "Уровень 1",
      "foreign": "8113",
      "meta": {
        "parentId": null,
        "id": "1fcff596-eb48-4017-92a5-af3fb09a1f65",
        "deep": 1
      }
    }
  ]
}`

**Comment by glibin** [comment]
Добрый день!

Для обновления подразделений пользователь API должен быть с правами управляющего. Изменить роль можно через запрос в службу поддержки.
