### ISSUE TITLE
Не возвращается список кандидатов по статусу

### ISSUE THREAD

**Issue by aakolzin** [huntflow/api#87]
Проблема аналогичная https://github.com/huntflow/api/issues/39

На запрос
requests.get('https://api.huntflow.ru/account/35448/applicants', headers=headers, params={'status':'74183'}).json()

Возвращается пустой список кандидатов
{'links': [], 'external': []}

Если убрать статус или добавить вакансию, то все работает, просьба пофиксить.

**Comment by chistyakov** [comment]
@aakolzin , простите за задержку с ответом!

Мы исправили настройки доступа для технической учетной записи вашей организации.

Проверьте, пожалуйста, что возвращается корректный список кандидатов.

**Comment by aakolzin** [comment]
Возвращается корректный
