### ISSUE TITLE
Установка вебхука

### ISSUE THREAD

**Issue by eugenyProchan** [huntflow/api#88]
Добрый день!

1. Протокол для установки вебхука должен быть https?
2. Если ХФ установлен на серверах компании, то адрес вебхука должен быть во внутренней сети или нужен внешний IP?

**Comment by mullakhmetov** [comment]
>Протокол для установки вебхука должен быть https?

`http` или `https` на ваше усмотрение

>Если ХФ установлен на серверах компании, то адрес вебхука должен быть во внутренней сети или нужен внешний IP?

Адрес вебхука должен быть доступен с сервера, где запущен Хантфлоу. Надежнее всего, когда это внешний адрес или домен. Еще это может быть домен, который резолвится внутри вашей сети, либо внутренний ip адрес, за исключением `127.0.0.1` и всех его алиасов.
