### ISSUE TITLE
Сортировка анкет и резюме

### ISSUE THREAD

**Issue by BeardedVage** [huntflow/api#89]
Добрый день.
Предусмотрена ли сортировка в запросах на получение списка кандидатов и резюме? И как она реализована (по какому принципу она работает)?

**Comment by glibin** [comment]
Добрый день!

В списке кандидатов по умолчанию сортируется по дате добавления кандидата в базу (по убыванию).

При запросе по этапам подбора сортируется по дате последнего действия (по убыванию).

Управлять сортировкой при запросе данных возможности нет.
