### ISSUE TITLE
Ограничения на загрузку файлов

### ISSUE THREAD

**Issue by osotov** [huntflow/api#90]
Добрый день!
При переносе базы кандидатов столкнулись с 2-мя ограничениями на загрузку файлов.

1. Ограничение на тип загружаемых файлов. Перечислю список расширений, с которыми возникли проблемы: 7z, zip, psd, cs, rar2, html, c, pas, otf, php, rar1, odt, gz, css, tar, zip1, swift, testProject_iOS, vsdx, cpp, mmap, mpp, docx, m3d, fbx, FBX, docm, mp. Возможно ли добавить данные расширения в список разрешенных?
2. Ограничение на размер загружаемых файлов. Возможно ли увеличить допустимый размер файла до 50 Мб?

**Comment by glibin** [comment]
Добрый день!

1. Не могли бы вы прислать перечень mime-types, думаю, что сможем добавить?

2. К сожалению, увеличить лимит до 50 Мб мы не сможем. Изменение возможно только в случае размещения Хантфлоу на выделенных серверах.

**Comment by osotov** [comment]
Mime-types:
application/x-7z-compressed, application/x-zip-compressed, image/vnd.adobe.photoshop, text/plain, text/html, text/x-c, text/x-pascal, application/x-font-opentype, text/x-php, application/vnd.oasis.opendocument.text, application/x-gzip, text/css, application/x-tar, text/php, application/x-photoshop, application/pdf, application/vnd.ms-visio.drawing, application/vnd.ms-project, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-word.document.macroEnabled.12, application/msword, text/x-csharp

**Comment by glibin** [comment]
Уже поддерживаются:

application/x-zip-compressed
image/vnd.adobe.photoshop
text/plain
application/vnd.oasis.opendocument.text
application/x-tar
application/pdf
application/vnd.ms-project
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.ms-word.document.macroEnabled.12
application/msword

Пока не можем добавить из соображений безопасности:

text/html
text/css

Остальные добавим и появятся в одном из ближайших релизов. Напишем в этом тикете.

**Comment by osotov** [comment]
Спасибо

**Comment by glibin** [comment]
Добрый день!

Добавили.

**Comment by osotov** [comment]
Отлично. Спасибо!
