### ISSUE TITLE
Синхронизация базы Хантфлоу с HRM Personio

### ISSUE THREAD

**Issue by InnaRasko** [huntflow/api#91]
Добрый день!
Я хочу настроить синхронизацию базы кандидатов (и вакансий) Хантфлоу и системой Personio. 
Personio не предоставляет поддержки по API, но прислали следующую информацию: https://support.personio.de/hc/en-us/articles/360000314338-The-Personio-Recruiting-API
https://developer.personio.de/docs/applications-endpoint
https://support.personio.de/hc/en-us/articles/115003421529-Transmitting-Applicant-Data-to-Your-Personio-Account
Наш менеджер сразу направил нас на гитхаб =) Можно что-то с этим сделать и как много времени вообще занимает эта процедура?) 
Буду благодарна за помощь

**Comment by glibin** [comment]
Добрый день!

К сожалению, мы не можем вас проконсультировать по этому вопросу. Здесь разработчики отвечают только на вопросы о работы с API Хантфлоу. 

Уточните, пожалуйста, какой менеджер Хантфлоу вас направил сюда?

**Comment by InnaRasko** [comment]
Здравствуйте,Артём (@huntflowsupport8) и Яна (@huntflowsupport5)И насколько я поняла из общении моей коллеги (Natalya.kassich@gmail.com) с саппортом: «Михаил обещал, что можно подключить Виталия»Что-нибудь можно сделать, чтобы перенести часть базы из Хантфлоу в систему? С уважением,Инна Расько --Отправлено из мобильной Яндекс.Почты25.11.2019, 17:06, "Vitaly Glibin" <notifications@github.com>:Добрый день!
К сожалению, мы не можем вас проконсультировать по этому вопросу. Здесь разработчики отвечают только на вопросы о работы с API Хантфлоу.
Уточните, пожалуйста, какой менеджер Хантфлоу вас направил сюда?

**Comment by glibin** [comment]
Коллеги сообщили, что поговорили с вами лично.
