### ISSUE TITLE
Проблема с выгрузкой списка кандидатов (параметр page игнорируется)

### ISSUE THREAD

**Issue by annieckat** [huntflow/api#92]
При отправке запроса  'https://api.huntflow.ru/account/<accountid>/applicants?page=1' при изменении значения параметра page, ответ не меняется: приходит список одних и тех же 30 кандидатов. 
Ранее такой проблемы не было. При этом, похоже, проблема возникает только при выгрузке кандидатов. При выгрузке списка вакансий всё работает по прежнему.

**Comment by glibin** [comment]
Добрый день!

Действительно, есть проблема с корректной работой аргументов. Мы сейчас готовим исправление. Как только оно выйдет, мы дадим знать в этом тикете.

**Comment by annieckat** [comment]
Спасибо!

**Comment by glibin** [comment]
Доброе утро!

Исправление выпущено, спасибо, что сообщили об ошибке.
