### ISSUE TITLE
создание Заявки на вакансию

### ISSUE THREAD

**Issue by AlekseyRiv** [huntflow/api#93]
Ошибка при создании Заявки на вакансию
POST: https://evraz-api-mirror.huntflow.ru/account/3/vacancy_request

заголовки запроса
User-Agent: [{"key":"User-Agent","value":"App/1.0 (Alexey.Kim@evraz.com)","description":"","type":"text","enabled":true}]
Accept: */*

тело запроса
account_vacancy_request: 1
position: Директор
money: 25000
hard_skills: Опыт руководства производством
soft_skills: Коммуникабельность
comment: ASAP

тело ответа
{"errors": [{"type": "server_error"}]}

Вопросы:
	Правильно ли указан account_id (3)? по get запросам ответ возвращается
	account_vacancy_request – какой идентификатор формы заявки на вакансию необходимо указать? Ссылка на github не рабочая

 
	При запросе https://evraz-api-mirror.huntflow.ru/me не возвращается Идентификатор пользователя
    "name": "Системная учетная запись",
    "position": "Системная учетная запись",
    "email": "evraz@huntflow.ru",
    "phone": "+111111111",
    "locale": "ru_RU"

**Comment by glibin** [comment]
>  Правильно ли указан account_id (3)? по get запросам ответ возвращается

Список доступных организаций можно получить здесь https://github.com/huntflow/api/blob/master/ru/user.md#organizations

>  account_vacancy_request – какой идентификатор формы заявки на вакансию необходимо указать?

Получить список схем можно здесь: https://github.com/huntflow/api/blob/master/ru/vacancy_requests.md#account-vacancy-request-list
