### ISSUE TITLE
Проблема выбора кандидата по статусу

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#94]
при запросе applicants выдает список кандидатов, в том числе со статусом "59":
       "middle_name": "Тестович",
         "photo": null,
         "id": 22298,
         "birthday": "1977-05-15",
         "links": [         {
            "vacancy": 37,
            "status": 59,
            "rejection_reason": null,
            "updated": "2019-11-29T11:00:54+03:00",
            "id": 188,
            "changed": "2019-11-29T11:00:54+03:00"
         }],
но, если добавить параметр ?status=59 не выбирает никого:
{
   "links": [],
   "external": []
}
при этом по параметру ?status=1 выбирает одного кандидата, хотя точно знаю, что их больше:
  "links": [      {
         "changed": "2019-11-06T15:58:44+03:00",
         "status": 1,
         "rejection_reason": null,
         "vacancy": 5,
         "updated": "2019-11-06T15:58:44+03:00",
         "id": 2
      }],

**Comment by glibin** [comment]
Добрый день!

Данный метод выбирает кандидатов по этапу на открытых вакансиях, на которых добавлен технический пользователь (API Robot). Если нужно получать кандидатов по всем открытым вакансиям, то пришлите информацию о вашей организации в Хантфлоу на hello@huntflow.ru со ссылкой на данный тикет.
