### ISSUE TITLE
Обновление справочников

### ISSUE THREAD

**Issue by RA13** [huntflow/api#95]
как обновить (изменить/удалить) значение в справочнике, чтобы при этом значение изменилось во всех вакансиях, где оно было указано?

**Comment by glibin** [comment]
Добрый день!

Если речь идет о названии элементов справочника, то необходимо обновить значение в справочнике через методы управления справочниками https://github.com/huntflow/api/blob/master/ru/dictionaries.md . Во всех вакансиях новое значение будет применено автоматически.
