### ISSUE TITLE
Создание отклика

### ISSUE THREAD

**Issue by RA13** [huntflow/api#96]
в документации не нашел, как через api создать отклик на вакансию?

**Comment by glibin** [comment]
Подскажите, какую задачу вы хотите решить?

**Comment by RA13** [comment]
Задачу по интеграции карьерного сайта компании с хантфлоу. Отклики будут приходить с карьерного сайта компании.

**Comment by glibin** [comment]
Есть несколько вариантов:
1. использовать нашу платформу откликов https://github.com/huntflow/api/blob/master/ru/responses.md 

2. использовать стандартные методы API: добавление кандидата в базу: https://github.com/huntflow/api/blob/master/ru/applicants.md#add и на вакансию: https://github.com/huntflow/api/blob/master/ru/applicants.md#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D0%BD%D0%B4%D0%B8%D0%B4%D0%B0%D1%82%D0%B0-%D0%BD%D0%B0-%D0%B2%D0%B0%D0%BA%D0%B0%D0%BD%D1%81%D0%B8%D1%8E

**Comment by RA13** [comment]
первая ссылка - это api на получение откликов.
вторая ссылка - добавление кандидатов на вакансию, это не отклики

как мы можем создать отклик используя api? судя по документации такой возможности сейчас не, планируется ли ее доработка в ближайшее время?

**Comment by glibin** [comment]
Добрый день!

Создать отклик непосредственно из API нельзя. Доработка не планируется.

Единственный способ: интеграция через платформу откликов (пункт 1).

**Comment by RA13** [comment]
это не способ.
через этот способ я не смогу создать отклик.
