### ISSUE TITLE
Как заполнить дату выхода на работу?

### ISSUE THREAD

**Issue by Nikolay1791** [huntflow/api#99]
Добрый день!

с помощью https://github.com/huntflow/api/blob/master/ru/applicants.md можно изменить статус кандидата в HuntFlow, например на "Вышел на работу". В запросе указывается ИД кандидата, ИД вакансии, а  теле запроса указывается новый статус. Но как заполнить дату выхода на работу?

**Comment by glibin** [comment]
Добрый день!

Нужно передать параметр employment_date в формате `%Y-%m-%d`
